- README.md
> :page_facing_up: docs: add install docs & headings

- README.md
- install_for_anaconda_users.sh
All of them are required for installation of gmpy2
** This fix is for anaconda users**
> Corrected Issue of missing math libraries: mpc, mpfr, gmp

- notebooks/Syft - Testing - Benchmark Tests.ipynb
- syft/test/benchmark.py
- test-requirements.txt
- Added Test-Requirements (so-called development requirements) to add any testing frameworks
- Added Test Module with Benchmarking Class
- Added Jupyter Notebook on Benchmark Testing
> added basic benchmark testing suite and corresponding notebook

- requirements.txt
So that we can run `jupyter notebook` in the `notebooks` directory.
> Add jupyter to requirements

- install_for_anaconda_users.sh
Because latest is better.
Unless there is a reason to use that specific version.
> Update to use Python 3.6

- bin/syft_cmd
- setup.py
Should allow us to just install the git repository and have the command available.
> :construction_worker: build: create binary `syft_cmd` during install

- bin/syft_cmd
Another minor fix. Just calling `syft` resulted in an error because `args.all` didn't have any elements to index
> :ant: fix: no command shows help

- Dockerfile
We can use this Dockerfile as a base image to extend other projects off of.
> A simple Dockerfile for Syft

- README.md
I really like how the links are organized here in one neat place. While doing research I kept coming back to this page as a reference to see if I was duplicating Trasks's research. It's hard to tell what the links are though just by glancing at them so I thought labeling might help, esp if someone wants to find something specific or just read 2-3 items that are of particular interest. If that's helpful I'll go ahead and do the rest of the links too :)
> Adding Descriptions to Links

- notebooks/Syft - Paillier Homomorphic Encryption Example.ipynb
There were errors in the output of the previous version of the notebook, besides imports were not working and were also not consistent with the linear classification notebook. This PR fixes this issue.
> Fix imports in encryption example notebook

- syft/tensor.py
`if x` is a concise way of saying `if x is True` (when x is a bool)
> Remove redundant boolean checks

- tests/test_math.py
- tests/test_tensor.py
Since we are invoking `pytest` which will use it's own test runner, we don't
need these declarations.
> Remove redundant calls to `unittest.main`

- Makefile
- README.md
I find it convenient to jump into any repo and use `make test` and `make run`,
this makes it easy for new contributors as well.
Only caveat is that I don't know the Windows OS situation for using `make`.
> Add Makefile for ease of use

- .circleci/config.yml
- Dockerfile
- setup.py
Fixes #119
Next steps:
- You'll need to go to https://circleci.com/vcs-authorize/ and sign in with an GitHub account that is admin on the PySyft repository, and follow instruction in the UI to enable CI for the PySyft project.
- Once done, you need to store the dockerhub environment variables into the circleci UI under the project settings.
- You can see a preview of what the result look like [here.](https://circleci.com/gh/cypherai/PySyft/9?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). Tests are currently failing because of the indentation error (see PR #149).
> CI setup: automated docker build, tests, and docker image hosting (issue #119)

- syft/tensor.py
- tests/test_tensor.py
Tests were failing:
```
$ git clone -b develop https://github.com/OpenMined/PySyft.git PySyftclean && cd PySyftclean && pytest
Cloning into 'PySyftclean'...
remote: Counting objects: 792, done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 792 (delta 48), reused 61 (delta 25), pack-reused 707
Receiving objects: 100% (792/792), 756.57 KiB | 1.04 MiB/s, done.
Resolving deltas: 100% (429/429), done.
===================================================================== test session starts =====================================================================
platform darwin -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/swaroop/personal/openmined/PySyftclean, inifile:
collected 0 items / 2 errors …
```
> Fix indentation & name

- syft/tensor.py
- tests/test_tensor.py
1. added rsqrt() and rsqrt_() in syft/tensor.py
2. added class rsqrtTests() in tests/test_tensor.py
> Implemented default rsqrt functionality for BaseTensor object#90

- syft/__init__.py
- syft/math.py
- syft/tensor.py
- tests/test_math.py
- tests/test_tensor.py
1. `unsqueeze` function in `math.py`
2. `unsqueeze` function for `TensorBase`
3. `unsqueeze_` Function for `TensorBase`
4. Respective unit tests
> :sparkles: Implemented unsqueeze functionality

- bin/syft_cmd
The `syft.he.Pallier` class seems to be renamed but this reference is not.
> :ant: fix: Paillier -> paillier

- notebooks/Functional Encryption Prototype.ipynb
- syft/he/paillier/basic.py
- syft/tensor.py
- tests/test_paillier.py
This fixes the issue with mine.js that caused the following error found by @anoff :
mine_1     | Traceback (most recent call last):
mine_1     |   File "/usr/bin/syft_cmd", line 4, in <module>
mine_1     |     __import__('pkg_resources').run_script('syft==0.1.0', 'syft_cmd')
mine_1     |   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 743, in run_script
mine_1     |     self.require(requires)[0].run_script(script_name, ns)
mine_1     |   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1505, in run_script
mine_1     |     exec(script_code, namespace, namespace)
mine_1     |   File "/usr/lib/python3.6/site-packages/syft-0.1.0-py3.6.egg/EGG-INFO/scripts/syft_cmd", line 141, in <module>
mine_1     |   File …
> Paillier division

- syft/tensor.py
- tests/test_tensor.py
Added implementation of split, squeeze and expand_as functions for TensorBase along with tests.
> Added split, squeeze and expand_as functions for TensorBase #97, #99 and #42

- syft/tensor.py
- tests/test_tensor.py
This PR fixes #39.
It has the same structure than the already implemented gt()/gt_() operation.
> Implement TensorBase eq()/eq_() functionality with tests

- syft/he/paillier/basic.py
Changed `__sub__` analogically to `__add__` to avoid 
```
AttributeError: 'EncryptedNumber' object has no attribute 'data'.
```
If previous behaviour is intended - please feel free to reject the PR.
> Changed PaillierTensor `__sub__` to avoid 'AttributeError'

- Makefile
While #270 is being reviewed I think it's important/urgent to have a `make test` consistent with Travis.
> add PEP8 style pytest in Makefile

- syft/he/paillier/keys.py
- tests/test_paillier.py
**Added Serialization to Public and Secret keys.** 
**serialize()** in **PublicKey** class creates a dictionary taking n value of the key and pickles the dictionary.
**deserialize()** in **PublicKey** class loads the pickled dictionary taking n value out of it and create a new phe.PaillierPublicKey using the n value.
**serialize()** in **SecretKey** class creates a dictionary taking p, q value of the key and n value of the public key and pickles the dictionary.
**deserialize()** in **SecretKey** class loads the pickled dictionary taking the p, q, and n value out of it and create a new phe.PaillierPrivateKey as follows:
`k = paillier.PaillierPrivateKey(
public_key=paillier.PaillierPublicKey(n=int(sk_record['n'])),
p=sk_record['p'],
q=sk_record['q'])
`
PS: This is my first PR on any …
> Serialize Public key Secret key with pickle

- tests/test_tensor.py
Current implementations of `normal` and `normal_` were missing unit tests.
> Add unit tests for normal and normal_

- README.md
While #270 is reviewed the readme should contain Capsule dependency as it is required for tests
> Add capsule dependency for running tests

- README.md
I was trying to setup development environment for myself, found that pip install -r test-requirements.txt was missing. So I edited it and created a pull request.
> add instructions to install test-requirements before running tests in README.md

- .gitignore
- syft/tensor.py
- tests/test_tensor.py
After communicating with @bharathgs about `tensor.py`, I fixed a bug in `sqrt()` method which should return a `TensorBase` but is returning Numpy `np.sqrt(self.data)`.
Going through `tensor.py`, I also found out that some in-place methods do not return anything. The corresponding methods in PyTorch usually return `self`, therefore I adjusted the documentation for some methods and added `return self` when appropriate. The corresponding unit tests in `test_tensor.py` are also fixed when necessary.
Please let me know if these adjustments are appropriate or not and I can keep improving the pull request. Thank you for your time and help!
List of methods adjusted:
`sqrt`: return `Tensor` instead of Numpy
`sqrt_`: return `self`
`abs`: return `Tensor`
`abs_`: return `self`
`zero_`: return `self` …
> Request: Fixing Some Methods in Tensor.py

- Makefile
If I run tests locally then inside the container (or other way around) I get the following error. 
```
tests/test_integrations_locally.py _____________________________________________________________
import file mismatch:                                                                                                                                                         
imported module 'PySyft.tests.test_integrations_locally' has this __file__ attribute:                                                                                         
/src/PySyft/tests/test_integrations_locally.py                                                                                                                              
which is not the same as the test file we want to collect: …
```
> remove cached pyc files before running tests

- syft/tensor.py
Using shortcircuit logic prevents a call to np.allclose which would be unnecessary when the shapes don't match.
This also prevents a ValueError: operands could not be broadcast together with shapes when comparing tensors with different shapes.
> Use shortcircuit logic to optimize function call

- tests/test_tensor.py
Added a couple of tests in which we check tensors of different shapes for inequality.
The test should return the correct result and not throw ValueError from np.allclose.
> Add shape mismatch tests

- syft/tensor.py
The Last formatting style was Python 3.6 based which broke things in Python 3.5. So reverted it to Python 3.5 style formatting.
**From**
`if not isinstance(dim, int) or not isinstance(start, int) or not isinstance(length, int):
raise TypeError(("narrow received an invalid combination of arguments:\n"
f"  got ({dim.__class__.__name__} dim, "
f"{start.__class__.__name__} start, "
f"{length.__class__.__name__} length), "
"but expected (int dim, int start, int length)"))`
**to this**
`if not isinstance(dim, int) or not isinstance(start, int) or not isinstance(length, int):
raise TypeError(("narrow received an invalid combination of arguments:\n" 
"    got ({} dim, {} start, {} length), " 
" but expected (int dim, int start, int length)"
.format(dim.__class__.__name__, …
> Revert string formatting for TensorBase narrow TypeError

- syft/math.py
- syft/tensor.py
- tests/test_math.py
- tests/test_tensor.py
This fixes #383 
This add split functionality to default tensor type.
In syft.math it add a split function which uses numpy.array_split() for splitting the array into given axis into `split size` size of each chunk. The function returns a list containing divided sub-arrays. I had to some initial calculations to match the numpy api.
> Split tensor

- syft/__init__.py
- syft/math.py
- syft/tensor.py
- tests/test_math.py
- tests/test_tensor.py
- Fixes #382
Adds default cross functionality for base tensor type
> Add cross functionality for Base Tensor Type

- notebooks/Syft - Paillier Encrypted Linear Classification.ipynb
- notebooks/Syft - Paillier Homographic Encrypted Linear Classification example .ipynb
- Addresses #384 
- Removes capsule dependencies from the following notebooks
- [Syft - Paillier Homographic Encrypted Linear Classification example ](https://github.com/OpenMined/PySyft/blob/master/notebooks/Syft%20-%20Paillier%20Homographic%20Encrypted%20Linear%20Classification%20example%20.ipynb)
- [Syft - Paillier Encrypted Linear Classification](https://github.com/OpenMined/PySyft/blob/master/notebooks/Syft%20-%20Paillier%20Encrypted%20Linear%20Classification.ipynb)
Use `syft.he.keys.Paillier` instead of capsule to get the keys
> Remove capsule dependency from notebooks

- notebooks/Syft - Paillier Encrypted Linear Classification.ipynb
- notebooks/Syft - Paillier Homographic Encrypted Linear Classification example .ipynb
- syft/__init__.py
- syft/he/paillier/__init__.py
- syft/he/paillier/basic.py
- syft/he/paillier/keys.py
- syft/math.py
- syft/tensor.py
- tests/test_math.py
- tests/test_tensor.py
Implements #274 
Implements dense to sparse matrix conversion
Implement sparse function in math.py
implemented function uses scipy sompressed sparse row matrix format to create sparse matrix
function returns TensorBase object
Implement spars functions in tensor.py
sparse() returns TensorBase object same as sparse() in math.py
sparse_() operates inline
Add unit tests for both sparse() functions and for sparse_() 
A few days ago I created original pull request (#376), but I got a bit confused trying to push my changes after rebase and changes according to comments from reviewer so I accidentally deleted branch from my fork which automatically closed that pull request.
> Dense to sparse matrix

- syft/tensor.py
We should not use hard coded type sizes in the library. This fix uses the host architecture type size.
> do not use hard coded type sizes

- syft/syft.py
As per https://github.com/OpenMined/PySyft/issues/586
`size()` returns a FloatTensor that basically contains `int`s (note that Pytorch has a SizeTensor for this). For the moment, I guess using FloatTensor is sufficient, and it leverages the messaging mechanism with Unity.
The corresponding PR in OpenMined is https://github.com/OpenMined/OpenMined/pull/128
Acceptance criteria:
> add `size()`

- README.md
Changed filename for installing PySyft via Anaconda into: `install_for_anaconda.sh`
> Corrected filename installation for anaconda users

- syft/tensor.py
This is the completed PR of Inline Documentation.
NumPy Style on inline documentation. http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html same as the Deprecated-PySyft. #273 has been followed.
For future Documentation and Function implementations, same pattern could be followed.
Most of the definitions were picked up from PyTorch and modified.
PS
Some functions including autograd(),no_params_func() and arithmetic_operation() have not been documented as it would be best for someone more experienced to document them due to their extensive use case.
> Inline Documentation - 2

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
We are creating loads of Issue and PRs, manually sorting through would be a hassle in the future! I have added some templates, which use github's embeedded markdown thingy to magically fill in the PR and Issue body with their respective templates, giving a cleaner look to our Repos. 
But, Due to the way GitHub works I doubt if it would be possible 
1. To move these files to https://github.com/OpenMined/Docs.
2. Test if the templates actually work, without creating a new branch or merging them to master.
Templates and instructions to create more can be found at [here](https://github.com/embeddedartistry/embedded-resources).
And as always, I am open to any suggestions and improvements. 😅
> Added PR and Issue Templates, which magically fill into all new bodies!

- issue_template.md
1. _.github_ folder already contains an *issue_template.md* ([here](https://github.com/OpenMined/PySyft/blob/master/.github/ISSUE_TEMPLATE.md)). this one is redundant.
> remove redundant file

- syft/interfaces/__init__.py
- syft/interfaces/torch/actual_torch.py
torch module is being imported alongside syft.
This is not convenient because if a user doesn't have torch module on the system should be able to import syft and just not use the PyTorch capabilities.
With this PR if torch module can be imported is imported but if it's not available just a warning message is shown to the user.
Fixes not being able to use Syft to user that doesn't have PyTorch
> Manage pytorch import

- syft/optim.py
1e-8  = 0.00000001 which is too many digits for a float so the value of epsilon becomes 0
which can result in nan errors with RMSProp and Adam.
Not sure if there's an easy way to use doubles in this scenario so setting epsilon to 1e-6 for now
> Reducing default epsilon for RMSProp and Adam to fit in float

- syft/optim.py
- syft/tensor.py
I found out that the hyperparameters weren't correctly parsed by Unity causing a hyperparameter lr=0.1 to be parsed as 100000 causing `nan` errors. This was easily fixed by sending the hyperparameters as a string.
Tested running the optimizer notebooks and they worked now. Also logged the hyperparameters and the correct values were being parsed in Unity.
> Fix hyperparameters parsing

- syft/interfaces/keras/models/sequential.py
- syft/interfaces/keras/optimizers/sgd.py
Implemented hyperparameter forwarding Keras
I noticed it wasn't possible to forward any hyperparameters like lr, momentum and decay to the optimizer in Keras. So I added keyword arguments to the optimizer and unpack them when calling the syft function.
Tested in the Keras notebook.
> Implemented hyperparameter forwarding Keras

- syft/controller.py
- syft/nn.py
- syft/tensor.py
Implemented a function that deletes a tensor in Unity when the FloatTensor python object is deleted. Also added n argument "delete_after_usage" parameter to the FloatTensor object to make sure certain tensors related to the model are not deleted.
- Not a very clean implementation, maybe someone has a better idea to reduce the overhead of unused tensors.
Ran several demo notebooks that still seem to work, the necessary tensors are not deleted. Also tried creating tensors and then overwriting the variable in which case the tensor was deleted.
> Delete tensor after usage

- syft/tensor.py
Fixes a bug: for inline arithmetic operations, no new python FloatTensor should be created. Otherwise, the first version of the tensor in python will be deleted, causing the Tensor in C# to be deleted aswell.
- Bug fix 
Tested in Syft Tensor Example Notebook.ipynb
> bugfix: do not delete results for inline aritmetic operations

- syft/tensor.py
When doing a certain operation twice, Unity will automatically re-use the tensor (saving memory). However since we remove tensors that are not being used anymore in Python this can cause problems. Example:
```
a = FloatTensor(data)
b = a.max()
c = a.max()
```
Now b and c both refer to the same tensor and if we delete variable b: `del b`, the tensor that b refers to will be removed as well and running: `print(c)` will result in an error as the tensor c refers to doesn't exist anymore.
To fix this I propose setting `delete_after_use` to `False` by default and setting this to `True` whenever possible.
> set default of delete_after_use to False

- syft/tensor.py
Issue #760 
Moved all the `arithmetic_operation` methods into `BaseTensor` class and tested that `FloatTensor` is still working fine. Only `add` is done for `IntTensor` on the Unity side so far.
> Create a BaseTensor class

- syft/interfaces/keras/layers/dense.py
- syft/interfaces/keras/models/sequential.py
Hello,
This PR add the following features to the Keras interface:
- Add activation functions Sigmoid and Tanh to Dense layer
- In the predict function, if the input is an np.array, it will be transformed to FloatTensor (forward function expect a FLoatTensor) 
* CPU:
* GPU:
> Keras: Add activation functions to Dense Layer

- README.md
The Markdown formatting for the link to the Unity app install instructions was not displaying correctly.
Fixes # (NA)
- [x ] Bug fix (non-breaking change which fixes an issue)
- [NA] Test A
- [NA] Test B
**Test Configuration**: NA
* CPU: NA
* GPU: NA
* PySyft Version: NA
* Unity Version: NA
* OpenMined Unity App Version: NA
> Quick docs fix

- syft/grid/grid.py
now, you can submit a job, disconnect from jupyter, and check on the
result a year later.
Example usage can be found in `notebooks/grid/Grid Example.ipynb` in
> store jobs so you can come back later

- syft/interfaces/keras/models/sequential.py
Hello,
Sorry for the small PR.  For the Keras interface, the predict function returns now a numpy array like in the Keras library, instead of a FloatTensor. 
* CPU:
* GPU:
- x ] My changes generate no new warnings
> feat: keras interface predict function update

- syft/grid/grid.py
Added `__getitem__` to the grid class that can be used to retrieve the address of an experiment either by using the name `g['experiment1']` or by using the number in the list of experiments `g[0]`.
Tested in the grid example notebook by creating an experiment with a certain name and then trying to retrieve the address using `g['experiment_name']` and then also by trying `g[0]` which returns the same address.
> implement __getitem__ for grid class to retrieve experiments

- syft/tensor/float_tensor.py
Previously, `random_` was ported from PyTorch as sampling from a uniform distribution over `[0,1)`.  This is incorrect, as PyTorch's `uniform_` method accomplishes this, while `random_` samples integers from the range `[start, end)`.  Additionally, `random_` was incorrectly using `no_params_function`, while the backend was expecting parameters for `start` and `end`.
I've fixed `random_`, and also added a Python equivalent of `uniform_`.
Accompanies OpenMined/OpenMined#405.
* CPU: Mac OS X -- 2.8 GHz Intel Core i7
* GPU: AMD Radeon R9 M370X 2 GB & Intel …
> Fixing random sampling

- syft/tensor/int_tensor.py
This pull request resolves issue #830 . This pull request is the PySyft portion of the implementation. See the pull request https://github.com/OpenMined/OpenMined/pull/411 for the unity portion.
* CPU: Macbook Pro (intel core i7)
* GPU: AMD Radeon R9 M370X
* Unity Version: 2017.2.0f3
* OpenMined Unity App Version: Latest
> Implement the Acos function for IntTensor on the CPU #830

- README.md
I just added the command for installing for anaconda in windows.
**Motivation:** people unfamiliar with linux commands like bash might get confused about installing using anaconda.
It's a small addition to prevent possible further confusion for someone.
Documentation
> [Docs] include install command for windows in ReadMe.md 

- syft/tensor/int_tensor.py
- tests/test_inttensor.py
This PR solves issue #1266 in Openmined/PySyft
Fixes #1266 
##
* CPU: Intel Code i7 (4th Gen), Jupyter Notebook, Python 3.6
* GPU: n/a
* PySyft Version: 0.1.0
* Unity Version: 2017.2.0f3 Personal
> Add python interface and unit test for unfold function 

- syft/tensor/int_tensor.py
Adds the Reciprocal Square Root functionality to int tensors
Addresses # (issue) 1162 in PySyft
```
I added tests in  IntTensorTest.cs
int[] data1 = {1, 2, 3, 4};
int[] shape1 = {2, 2};
int[] data2 = {1, 1, 1, 0};
int[] shape2 = {2, 2};
```
Link to Issue:
https://github.com/OpenMined/PySyft/issues/1162
Confusion/Problem:
```
What is the expected behaviour for IntTensor Rsqrt
`x => 1 / (int) Math.Sqrt(x)`
or
`x => (int)(1 /  Math.Sqrt(x))` 
```
Link to OpenMined PR: https://github.com/OpenMined/OpenMined/pull/427
> Adresses #1162 add rsqrt functionality

- syft/tensor/int_tensor.py
- tests/test_inttensor.py
This PR solves issue #1267 in Openmined/PySyft
Fixes #1267 
* CPU: Intel Code i7 (4th Gen), Jupyter Notebook, Python 3.6
* GPU: n/a
* PySyft Version: 0.1.0
* Unity Version: 2017.2.0f3 Personal
> Add interface and unittest for IntTensor inline unfold function

- syft/tensor/int_tensor.py
currently, rsqrt(int version) returns an Int instead of floattensor but the expected output is a floattensor in this case and this fixes it.
> fix/returns FloatTensor instead of IntTensor

- README.md
- binder/environment.yml
Add the links and code to make Binder (http://repo2docker.readthedocs.io) work with the repo. Basically, it has the dependencies in a conda standard environment. It makes running and testing the code as easy as clicking on a link (https://mybinder.org/v2/gh/kmader/PySyft/patch-2?filepath=examples%2FFederated%20Learning%20Example.ipynb) to run and start the Federated Learning Example
> Adding binder support for repository

- examples/SocketWorker Client.ipynb
- examples/SocketWorker Server.ipynb
"SockerWorker Server.ipynb" and "SockerWorker Client.ipynb" notebooks contains broken links to "Basic Virtual Worker Tutorial" notebook.
> Fix broken links to Virtual Worker Tutorial notebook

- syft/core/workers.py
Fix bug with double decoding the input byte stream (in _process_buffer & receive_msg). This generates an error in Python 3 as `str.decode()` was deprecated. Resolves #1358 
* CPU:
* GPU:
> Fix bug with double decoding the input byte stream

- syft/core/workers/socket.py
This pull request just replace the hardcoded 'localhost' host in socket connections with the object's attribute.
It allows to connect to remote computers (not only localhost)
> Allow socket connection to remote machines

- syft/core/hooks/torch/hook.py
- syft/core/workers/base.py
- test/torch_test.py
Fixes Issue #1382
Pysyft test pass.
(See Issue #1382)
> Fixes Issue #1382 : Call of torch functions on remote Variable (ex: torch.matmul(x,y))

- syft/core/hooks/torch/hook.py
- syft/core/utils.py
- syft/core/workers/base.py
- test/torch_test.py
The goal is to provide a fully working demo of federated learning on MNIST.
As for now, it is not possible to handle convolution (`F.conv2d`, `nn.conv2d`), because the args and kwargs required get lost during the hook.
Hence, we provide a stronger handling of arks and kwargs in the transmission process of commands to workers, with a special focus on the conservation of the types not natively supported in JSON.
See the **working example on MNIST** : https://colab.research.google.com/drive/1DxjiUjLUenFaVBrz3QMuJ665Z2HsfmgA
Unit tests added on convolution
Colab config
> Handling more sophisticated args and kwargs when calling torch func

- examples/experimental/Forward or Move tensors.ipynb
- syft/core/frameworks/torch/hook.py
- syft/core/frameworks/torch/tensor.py
- syft/core/workers/base.py
I added the previously discussed move() function which moves the end chain Tensor to another worker: `self->alice->obj [worker] => self->alice->worker->obj`
This functionality differs of send() which would perform: `self->alice->obj [worker] => self->worker->alice->obj`
However there is still an issue with undesired Tensors being created  (see `Forward or Move tensors.ipynb`), which is due to the ability of `self.child` to create arbitrarily tensors, I don't know how we could handle this at the moment.
No tests so far, just use `Forward or Move tensors.ipynb`
> [pointers_are_tensors] Add move function (with pb of extra registering..)

- syft/core/frameworks/torch/hook.py
- syft/core/frameworks/torch/tensor.py
- syft/core/utils.py
- syft/core/workers/base.py
Add handling of nested args/kwargs (incl. _SyftTensor) on methods only
This allows to call methods on Tensors (eg `x.add(y)`), with the following limitations:
- with single output
- chains of pointers in args must be identical
Not tested except on notebooks
> [pointers_are_tensors] Handling of nested args/kwargs (incl. _SyftTensor) on methods

- syft/core/frameworks/torch/hook.py
- syft/core/frameworks/torch/tensor.py
- syft/core/utils.py
- syft/core/workers/base.py
- test/torch_test.py
Fix send/get in chain Tensors and partial fix of torch func
- All functionalities claimed have unit tests
- torch func with args=FloatTensor and output=FloatTensor work remotely
- So, output=IntTensors or output=float fails so far
This can be merged directly (if to be reused direcly), or wait for additional bug fix (with unit tests!)
A code review on my `_execute_call()` (hook.py l.387) might be useful.
Unit tests
> [pointers_are_tensors] Fix send/get in chain Tensors and partial fix of torch func

- syft/core/frameworks/torch/__init__.py
- syft/core/frameworks/torch/hook.py
- syft/core/frameworks/torch/tensor.py
- syft/core/utils.py
- syft/core/workers/base.py
- test/tensor_serde_test.py
- test/torch_test.py
This PR provides so far ideas to refactor the code to use standardized processes which are less likely to be broken. It hasn't been tested so far on Variables, so... (but it will be!)
Refactor the code to provide a more compact framework (in progress)
- Merge all calls in a single calling function in the hook
- Use a single protocol to exchange between workers (PythonJSONEncoder/Decoder)
- Implement the following logic: workers communicate with _SyftTensors, and
communicate with the user/client and torch functions with Torch tensors
- Tensors can be send/get, and methods or torch functions work
TODO:
- Variables are not handled so far
- Part of the logic of the PythonJSONEncoder/Decoder could be put in the ser/deser
- Moving the calling function of the hook to workers could enable more …
> [tensors_are_pointers] [wip] Refactor the code to provide a more compact framework

- syft/core/frameworks/torch/tensor.py
- syft/core/utils.py
- syft/core/workers/base.py
- test/torch_test.py
One concern is that the get seems to be working (output the tensor,
etc.) but if after like x.get() (print(x) will be perfect), but if
you do x.dim() it returns 0, actually the good value is in x.child.child
* CPU:
* GPU:
> Post-merge fixes on sending and gettind tensor.

- syft/core/hooks/base.py
- syft/core/hooks/torch/hook.py
Previously, the `__enter__` and `__exit__` methods were deleted from TorchHook.  They're back, and they're better than ever!  In particular, they no longer assume that torch was unhooked before the TorchHook was initialized.  In addition, I wrapped all the various hooking logic from `__init__` into it's own function, preparing for an API change where you have to imperatively establish the hooks instead of having them happen whenever you instantiate TorchHook.
> Context manager for TorchHook is back!

- syft/core/frameworks/torch/hook.py
- syft/core/frameworks/torch/tensor.py
- syft/core/utils.py
- syft/core/workers/base.py
- test/torch_test.py
Add support of function and method on remote tensors EXCEPT weird output/input
Add support of send / get Variable BUT some registrations remain uncontrolled
Add support of SOME function and method on singly remote Variables (=One single send)
TODO: dispatch the parts of JSON Encode/Decode to the appropriate ser and deser
Unittests
> [pointers_are_tensors] Continue handling tensors and variables

- syft/core/frameworks/torch/__init__.py
- syft/core/frameworks/torch/hook.py
- syft/core/frameworks/torch/tensor.py
- syft/core/utils.py
- syft/core/workers/base.py
- test/tensor_serde_test.py
- test/torch_test.py
Working on chains: enable send/get tensors
Changing paradigm: Always send a chain with head=tensorvar and tail=_Local or _Pointer.
- When tail is _Local, head and tail loop with child and parent
- When tail is _Pointer, the loop is broken
Working on chains: enable send/get, func and methods on remote tensors
- The Python/JSON Encode/Decoder has been modified to include a 'mode'
parameter for decoding, to disambiguate the behaviors
- There is still an issue with converting tensors (run x.int() to see)
- Todo: decompose the parts of the Python/JSON Encode/Decoder in the
tensors methods
Unit tests
> [Pointers are tensors]  Working on chains: sanitizing the previous work

- syft/core/frameworks/torch/hook.py
- syft/core/frameworks/torch/tensor.py
- syft/core/workers/base.py
- test/torch_test.py
- Fix an issue with casting tensors (e.g. x.int()) but in a ugly way (see TODO hook.py l.82, which require to understand well namespace and packages) (Also related, understanding why the hook of sy.[Float|Int|...]Tensor doesn't work completely (`x.sy.FloatTensor([1], owner=..., id=...)` fails because we are not allowed to transmit unexpected keywords) would be very interesting to clean the code)
- Fix execution of functions with several output
- Unlock many unittests
- A bit a code cleaning
- An interesting new unittest to unlock: torch_test.py l.302 : can be have different pointers pointing at the same remote?
Fixes …
> [Pointers are tensors] Little fix and many TODO!

- syft/core/frameworks/torch/hook.py
- syft/core/frameworks/torch/tensor.py
- syft/core/utils.py
- syft/core/workers/base.py
- test/tensor_serde_test.py
- test/torch_test.py
Enable support on functions and methods on local and remote tensor non-trivial chains (ie including a PlusIsMinusTensor) 
The process chain is a bit changed:
The idea that we should always send a wrapper on even a partial chain is relativised: we still do this when sending commands / objects to another worker, because it is useful for a worker receiving an object for instance to have directly the wrapper available (just as it is convenient wor the local_worker, i.e. us); but within a local chain (ie Float > _PlusIsMinus > _Pointer), the intermediate nodes don't need the wrapper to execute correctly, and this enable to more easily overload methods as well, for the head element (of e.g. command['self']) is of the same type than the class in which handle_call is performed.
Please delete …
> [Pointers are tensors] Playing with PlusIsMinus Tensor : full support on Torch Tensors

- syft/__init__.py
- syft/core/frameworks/torch/hook.py
- syft/core/frameworks/torch/tensor.py
- syft/core/utils.py
- syft/core/workers/base.py
- test/torch_test.py
Improve handling of the grad attr for var.backward()
- Add a test of backprop which performs chain fixes itself
- Light code refactor to make _execute_call easy to read
- TODO:Because backward() modifies chains of variables not in args,
we need to understand if 1. we can prevent backward of breaking
the chains, or 2. we can retrieve the variables modified (just
as backward did it) and fix their chain, in an automatic fashion
Unittest
> [Pointers are tensors]   Improve handling of the grad attr for var.backward()

- syft/core/frameworks/torch/hook.py
- syft/core/frameworks/torch/tensor.py
- syft/core/utils.py
- syft/core/workers/base.py
- test/torch_test.py
**Add a hook on backward compatible with non-trivial chains**
- The backward hook retrieves the variables modified in the computational
graph and retablish the grad chains after backward is called, updating
only the gradient value
- There is an improved (but not complete) support of remote non-trivial
chain of which backward is performed, unittest use PlusIsMinusTensor
unittest
> [pointers_are_tensors] Add a hook on backward compatible with non-trivial chains

- Dockerfile
- syft/core/utils.py
- test/core/utils_test.py
I modify the custom_obj_hook method of PythonJSONDecoder in order to allow string id.
Fixes #
Before my change, remote operations on objects with string was throwing exception on server side and empty responses on client side.
Docker container of the project
> Strings id + Unittest 

- syft/core/frameworks/torch/hook.py
Added missing docstrings to hooking methods. Updated TorchHook docstring.
Fixes # 1443
Documentation Update
No specific test run or needed.
> Add missing docstrings in TorchHook #1443

- syft/core/frameworks/torch/tensor.py
- syft/core/frameworks/torch/utils.py
Previously if you ran 
x = sy.ByteTensor([1,2,3,4]).send(bob)[0].get()
x would end up being a FloatTensor, which is wrong (should be ByteTensor). This fixed it.
> Scalar return bug

- examples/torch/toy/Toy MPC Example.ipynb
- syft/core/frameworks/torch/tensor.py
Now if you haven't implemented something custom into MPCTensor, it will attempt to accomplish the method using the default PyTorch functionality.
Aka... you can do
slice_of_mpc_tensor = my_mpc_tensor[0]
> MPCTensor inheritance

- syft/core/frameworks/torch/tensor.py
When creating _MPCTensor we realized that we needed a new kind of tensor wrapping, one where the .child object remains a torch tensor. In this PR, I have added a new PlusIsMinusTensor example showing how to do this called _WrapTorchObjectPlusIsMinusTensor
> created another example plus is minus tensor

- syft/core/frameworks/torch/tensor.py
- test/torch_test.py
Regarding the following issue: 
https://github.com/OpenMined/PySyft/issues/1548
Adding method to return list of workers from GeneralizedPointerTensor.
Adds method `workers` to `syft/core/frameworks/torch/tensor.py` L:749  
Adding unittest in `test/torch_test.py` L:1121
* CPU: Mac
* GPU: None
* PySyft Version: master
* Unity Version: None
* OpenMined Unity App Version: None
> adds getting workers from gpt

- syft/core/workers/base.py
- syft/mpc/securenn.py
It has been previously agreed and confirmed with both the employee (Jason Mancuso - @jvmancuso ) and employer (Gavin Uhma - @gavinuhma) that all contributions are happening after hours and thus the inclusion of a copyright indicating that any contributions are copyright DropoutLabs is extraneous because it is referring to no actual code contained within any files in OpenMined. Thus, I am removing the copyright.
> removed extraneous copyright for out-of-work-hours contribution

- README.md
For Windows, Pytorch version 0.3.1 for CPU can be installed using conda as below- 
conda install -c peterjc123 pytorch-cpu
Since PySyftOn requires Pytorch version 0.3.1, hence on Windows the CPU version can be installed using conda as mentioned in the embedded URL
Pytorch 0.3.1 for CPU can be installed on Windows
This change requires a documentation update in README.md
By running "setup.py test" on Windows after installing pytorch 0.3.1
* CPU: Yes
* GPU: None
* PySyft Version: 0.3.1
* Operating System: Windows 10
> Update README.md for Windows Pytorch Installation

- syft/core/frameworks/torch/hook.py
- syft/core/frameworks/torch/tensor.py
- syft/mpc/__init__.py
- test/torch_test.py
This PR does the following:
- Add the support of neg values
- Add multiplication (local and remote and compatible with spdz)
- Add matmul
What remains to be done for another PR:
- Address the issue of LongTensor being too small for "real" computations
Suggestions are welcome!
Unittests
> Fix Precision Tensor : support neg values, mul and matmul op

- Dockerfile
Issue: https://github.com/OpenMined/PySyft/issues/1590
Tested with Docket on this notebook: https://github.com/OpenMined/PySyft/blob/master/examples/torch/Boston_Housing_Federated_Training.ipynb
Workaround from: https://github.com/grpc/grpc/issues/6126#issuecomment-211863937
> Add libc6-compat library to Dockerfile

- syft/core/frameworks/torch/utils.py
While running the https://github.com/OpenMined/PySyft/blob/master/examples/numpy/Federated%20Learning.ipynb
got the following error-
File "D:\PySyft\PySyft_Project\syft\core\frameworks\numpy\ndarray.py", line 228, in method
attr=str(attr), args=args, kwargs=kwargs, has_self=True, self=self
File "D:\PySyft\PySyft_Project\syft\core\frameworks\torch\utils.py", line 386, in compile_command
locations = [pointers[0].location]
IndexError: list index out of range
The error was thrown from compile_command when len(pointers)=0. Fixed the same and verified by running the above Federated%20Learning.ipynb
Tested the fix with further tests. Tests passed.
\test\tensor_serde_test.py
\test\torch_test.py
(Syft) Denver_Boston_Federated_Training.ipynb
> fixed exception in compile_command when len(pointers)=0

- .travis.yml
- pyproject.toml
Whitespaces in regexp inside pyproject.toml shouldn't be there. Maybe now travis will build fine?
> Fix regexp for black exclude option in pyproject.toml

- examples/other/experimental/MNIST Example.ipynb
fix an import problem caused by TorchHook which has been moved into frameworks.torch
> Update MNIST Example.ipynb

- syft/core/workers/base.py
Now correctly deregistering all objects that belong to a torch.Variable.
Example Code is attached to issue #1645. I additionally fixed some typos within the comments as well.
> Fix for issue #1645. 

- syft/core/workers/websocket.py
- test/core/workers_test.py
I've created this pull request to bugfix branch, because I want to easily share code with Ogofo and Nivek92 who expressed interest in issue #1642. This code is not ready for master. Can someone create a separate branch for this maybe? I will then set it in this PR.
I believe the reason why there are so few tests is because this TorchHook solution (possibly combined with the way we write/run tests) makes adding new tests much harder for people. Running tests produce lots of  `Torch was already hooked... skipping hooking process` and `Replacing old worker which could cause unexpected behavior` warnings. In my case I'm adding a correctly failing test (TestWebSocketWorker) and when I run it with `python3 setup.py test` I see different error messages than when I test the same code manually (in …
> [WIP] Fix websocketworker

- syft/serde.py
- test/test_serde.py
Added serialization and deserialization of torch.Tensor objects. 
Changed the _simplifier to return a list instead of a tuple, as it looks like the `msgpack` is encoding a tuple as a list. This is throwing errors in the `_details` method. 
Renamed the methods `compress`  and `decompress` to `_compress` and `_decompress` as these are private methods.
> Issue #1666

- .travis.yml
- syft/serde.py
- test/test_serde.py
Added a test case for serialization and deserialization of a `bytearray`.  It seems to me that we don't need to add any additional logic, as `msgpack` can handle `bytearrays` quite well.
> Add serde logic for bytearray #1672

- syft/serde.py
- test/test_serde.py
Removed pickle and used numpy functions instead so we don't need to worry about code injection in pickle and because it's faster than pickle
> Replaced pickle for ndarray

- syft/core/frameworks/torch/tensor.py
- test/torch_test.py
Currently it's called on a `dict` object and calling `end_get` in tutorial 3 generates an error because `dict` does not have a `get()` method with no arguments.
Adds a test that demonstrates a scenario in which the code currently fails.
> In `handle_call` for the "end_get" case need to call get() on a _SyftTensor

- requirements.txt
- syft/serde.py
- test/test_serde.py
Change details-
1. Added support for 'zstd' compression algorithm in the library. Now both 'lz4' and 'zstd' algorithms can be used.
2. Handled the scenario when compression algorithm output is greater than the input stream in serialize\deserialize apis. Added a 1-byte header to the serialized output to indicate output is compressed or not.
3. Added 2 unit test cases for zstd algorithm for testing compression\decompression apis and serialize\deserialize apis.
4. Added zstd dependency in requirements.txt
5. Executed unit test cases using "python setup.py test". All tests passed including the newly added unit tests.
> Guarantee Lz4 Compressed binary is shorter than original #1704

- syft/frameworks/torch/hook.py
- syft/frameworks/torch/tensors/abstract.py
- syft/frameworks/torch/tensors/native.py
- syft/frameworks/torch/torch_attributes.py
- syft/serde.py
- syft/util.py
- test/test_serde.py
Fixes https://github.com/OpenMined/PySyft/issues/1694
This PR does a few things.
1) it adds a new .serialize() convenience function to all tensors (by adding it to AbstractTensor). I added 2 unit tests for this function.
2) it removed the STRING based configuration of compression - opting instead for an integer based one (a general design decision we're optimizing for in Torch 1.0 to make things faster and more compressed). I modified previous unit tests to adjust (also fixed a style issue where compress_scheme was camel-caps for some reason)
3) it added a bit of inline documentation as I was going.
4) a few minor style fixes (removed unused imports)
5) added a new error class CompressionNotFoundException if you try to use a compression
code that doesn't exist (previously if you didn't …
> Added AbstractTensor.serlialize() convenience function w/ tests; added inline documentation

- syft/__init__.py
- syft/codes.py
- syft/exceptions.py
- syft/frameworks/torch/hook.py
- syft/frameworks/torch/hook_args.py
- syft/frameworks/torch/tensors/native.py
- syft/frameworks/torch/tensors/pointer.py
- syft/frameworks/torch/torch_attributes.py
- syft/objects.py
- syft/serde.py
- syft/workers/base.py
- test/test_serde.py
- test/torch/tensors/test_native.py
- test/torch/tensors/test_tensor.py
- test/torch/test_hook.py
- test/workers/test_virtual.py
Continue addressing #1657
- Improve ownership on send / get tensors #1697 #1698
- Add GC from #1796* to solve #1701 (see also #1658)
- Add hooking for torch methods on pointers, following up on #1729
PR was first intended to explore chains without torch wrappers. This solution is simpler to write but makes PySyft less flexible for libraries using PyTorch. We're currently putting back the wrapper while keeping the features developed in the first setting.
```
import torch
import torch.nn.functional as F
hook = sy.TorchHook(torch)
me = hook.local_worker
alice = sy.VirtualWorker(hook, id="alice")
bob = sy.VirtualWorker(hook, id="bob")
```
**Fast remote op on pointers**
```
x = torch.Tensor([1, 2, 3, 4])
x2 = torch.Tensor([4, 3, 2, 1])
x_ptr = x.send(bob)
x2_ptr = …
```
> Torch 1 and (not) headless tensor chains - send/get - GC - ptr.method() - etc.

- syft/exceptions.py
- syft/frameworks/torch/__init__.py
- syft/frameworks/torch/hook.py
- syft/frameworks/torch/hook_args.py
- syft/frameworks/torch/tensors/__init__.py
- syft/frameworks/torch/tensors/abstract.py
- syft/frameworks/torch/tensors/log.py
- syft/frameworks/torch/tensors/native.py
- syft/frameworks/torch/tensors/pointer.py
- syft/serde.py
- syft/workers/base.py
- test/torch/tensors/test_log.py
- test/torch/test_hook.py
Add a LogTensor and change the way commands are handled:
Add a handle_command method in syft/torch tensor classes for methods:
Move the call handling from the hook to each tensor class to allow for specific behaviour depending of the class.
Add a symmetric architecture to rebuild the chain on top of the response once the chain has been completely un-wrapped (like a forward and backward logic)
Add a LogTensor
```
wrapper = torch.Tensor()
wrapper.child = LogTensor().on(torch.Tensor([1, 2, 3]))
x = wrapper
print(x)
y = x.add(x)
print(y)
```
TODO:
- resolve some todos on imports
> LogTensor and decentralized handling of commands

- syft/core/frameworks/torch/tensor.py
- syft/spdz/spdz.py
- test/torch_test.py
Usecase: when sharing a scalar with mpc, you cast your float in a 1D tensor
then `mul` sees two tensors fo different shapes:
```
[a] x [[b, b], = [[ab, ab],
[b, b]]    [ab, ab]]
```
> Add support of product scalar x tensor when scalar is of type tensor

- syft/frameworks/torch/hook.py
- syft/frameworks/torch/hook_args.py
- syft/frameworks/torch/tensors/__init__.py
- syft/frameworks/torch/tensors/log.py
- syft/frameworks/torch/tensors/native.py
- syft/frameworks/torch/tensors/pointer.py
- syft/frameworks/torch/tensors/utils.py
- syft/serde.py
- test/torch/tensors/test_log.py
Move hook method from online class routing to pre routing in the hook
Rename LogTensor -> LoggingTensor
Add a decorator to easily over-hook method for syft tensors  …
See add() exemple in LoggingTensor
> Move hook of methods

- examples/experimental/GC Experiment.ipynb
- syft/frameworks/torch/hook.py
- syft/workers/base.py
- test/torch/test_hook.py
ptr = torch.Tensor([1.0, -1.0, 3.0, 4.0]).send(bob)
print(ptr.child)
p = nn.Parameter(ptr)
p.data = ptr
print(p.data.child) # --> trigger attribute error
This used to fail but now it does not
> Parameter hooking

- README.md
- syft/frameworks/torch/hook.py
- syft/frameworks/torch/hook_args.py
As we'll dive into debug logs, let's have more explicit stack traces --> 
Change hook `overloaded_attr` to explicit names like `overloaded_pointer_method`, `overloaded_syft_method`  for stacktrace clarity
> Debugger help

- syft/exceptions.py
- syft/frameworks/torch/hook.py
- syft/frameworks/torch/hook_args.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/frameworks/torch/tensors/interpreters/pointer.py
- syft/serde.py
- syft/workers/base.py
- test/test_exceptions.py
- test/torch/tensors/test_logging.py
- test/torch/tensors/test_parameter.py
- test/torch/tensors/test_pointer.py
- test/torch/test_federated_learning.py
This PR tries to get this working:
```
import torch as th
hook = sy.TorchHook(th)
bob = sy.VirtualWorker(hook, "bob")
alice = sy.VirtualWorker(hook, "alice")
sy.local_worker.add_worker(bob)
data = th.nn.Parameter(th.tensor([[1.,1],[0,1],[1,0],[0,0]]))
data = data.send(bob).send(alice)
data = data.get().get()
```
Now this works (Garbage collection and wrapping issues fixed)
And additional fix on:
nn.model parameter send / get which must be inplace
Etc.
> Parameter attributes handling and remote usage

- syft/frameworks/torch/hook.py
- syft/frameworks/torch/hook_args.py
- syft/frameworks/torch/tensors/decorators/logging.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/frameworks/torch/tensors/interpreters/pointer.py
- syft/frameworks/torch/tensors/interpreters/precision.py
- syft/frameworks/torch/tensors/interpreters/utils.py
- syft/workers/base.py
Add support of passive kwargs hook: they are forwarded as is
This is sufficient for python numbers, str, tuple, etc.
removes the warning for cases like:
```
x = torch.tensor([1., 2])
F.log_softmax(x, dim=0)
```
> Add support of passive kwargs hook: they are forwarded as is

- examples/tutorials/Part 2 - Intro to Federated Learning.ipynb
I found two places to change while running the tutorial today. Please correct me if I am wrong.
+ It seems that `syft` does not have `optim`?
+ `opt.step` would not take `data.shape[0]` as input because `opt.step` should take some closure.
Doc: https://pytorch.org/docs/stable/optim.html#torch.optim.Optimizer.step
> Fix error in tutorial 2

- syft/workers/base.py
- syft/workers/virtual.py
This is my first contribution attempt ever to OpenMined's PySyft. So, I made it so concise with the issue #1456 
I annotated the 'message' type in _recv_msg and _send_msg (in virtual.py) as binary although they are marked as strings in the doc strings in base.py. I thought this might be a typo  since `send_msg` and `recv_msg` use binary message types. So please let me know if I am missing something here.
> Type annotation

- syft/serde.py
- test/test_serde.py
This PR enables different strategies to serialise/deserialise tensors.
Right now the serialisation of the tensors is delegated to Torch but the serialised objects are not compatible with other platforms
This PR includes a strategy to seder the tensors using npy format
> Serialization strategies

- syft/frameworks/torch/tensors/interpreters/abstract.py
- syft/serde.py
- test/test_serde.py
This PR will help to open the compression/decompression process to workers that do not have access to the configuration used during seder
The way of choosing a compression with this PR is by overriding the function `_apply_compress_scheme`
The function will default to `LZ4` compression.
If no compression is required then use `_apply_compress_scheme = apply_no_compression`
Other compression schemes, as SZTD, can be applied similarly: 
`_apply_compress_scheme = apply_zstd_compression`
* Replace flag determining compression by flag indicating possible compression schemes (including NO_COMPRESSION)
* Added hooks that can be overridden to set the compression scheme (or none)
> Replace hard-coded compression by strategy

- syft/frameworks/torch/crypto/securenn.py
- syft/frameworks/torch/crypto/spdz.py
- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- syft/workers/base.py
All is in the title :)
I aligned the spdz protocol syntax on the secure nn one: the objects used are AdditiveSharedTensors and MultiPointerTensors
Regarding the section in spdz_mul 
```
j1 = torch.ones(delta_epsilon.shape).long().send(locations[0])
j0 = torch.zeros(delta_epsilon.shape).long().send(*locations[1:])
if len(locations) == 2:
j = sy.MultiPointerTensor(children=[j1, j0])
else:
j = sy.MultiPointerTensor(children=[j1] + list(j0.child.child.values()))
```
It could be a method of the MultiPointerTensor (used in several cases including spdz and snn), if someone finds a fancy name, I'll add it as a native method for this tensor!
> Clean SPDZ mul and AdditiveSharingTensor methods

- syft/workers/base.py
- syft/workers/plan.py
- test/workers/test_plan.py
* Plans are no longer searchable :cry: . This is mainly due to the different behavior when "searching" for plans and searching for tensors.
* Now is possible to fetch a plan based on its id :smile: . This will get a plan from a worker's registry, create a copy of the plan and change the owner to whoever is fetching the plan.
This is the result of a [~~pair~~ triple programming section](https://github.com/OpenMined/PySyft/commit/66f5cc9688f5c74140772766420ba5d034d24c01) with @robert-wagner and @jlebensold.
> Create fetch_plan in base

- syft/__init__.py
- syft/frameworks/torch/hook.py
- syft/frameworks/torch/tensors/interpreters/abstract.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/workers/base.py
- syft/workers/plan.py
- test/torch/tensors/test_additive_shared.py
- test/torch/tensors/test_gc.py
- test/torch/tensors/test_logging.py
- test/torch/tensors/test_native.py
- test/torch/tensors/test_parameter.py
- test/torch/tensors/test_pointer.py
- test/torch/tensors/test_tensor.py
- test/torch/tensors/test_variable.py
- test/torch/test_federated_learning.py
- test/torch/test_hook.py
- test/workers/test_virtual.py
- test/workers/test_worker.py
fixes #2063
This pull request removes the duplicated code that generates the random ids. 
It does not improve on the way the random int is generated. But switching to a much larger hash is now easily possible as only one location needs to be changed.
> use IdProvider to provide random ids

- syft/workers/base.py
- test/conftest.py
The workers and hook were only initialized once for all unit tests. Therefore data accumulated and created unexpected behavior in the tests.
> Clear hook and workers before each pytest function

- syft/exceptions.py
- syft/generic/id_provider.py
- syft/workers/base.py
- test/generic/test_id_provider.py
IdProvider was not guaranteed to provide an id only once. Added tests.
> Provide unique ids by checking against already generated ids

- CONTRIBUTING.md
"ony" to "only"
"confidant" to "confident"
> fixed two typos in contributing.md

- examples/tutorials/Part 4 - Federated Learning via Trusted Aggregator.ipynb
This fixes the exception:
`RuntimeError: set_storage is not allowed on Tensor created from .data or .detach()`
that occurs when running tutorial 4 with `torch 1.1.0`.
Following the fix from [here](https://discuss.pytorch.org/t/api-change-for-tensor-data-set-in-torch-nightly/33310/2), we:
1. just remove the reference to `.data`,
2. wrap the code with `with torch.no_grad()`
> small fix so that the tutorial works with torch 1.1.0

- syft/serde.py
- test/test_serde.py
- test/workers/test_virtual.py
This pull request modifies the serde module to support serialization for torch.jit.ScriptModule instances. 
This covers both functions decorated with @torch.jit.script (torch.jit.ScriptModule) and models traced using torch.jit.trace() (torch.jit.TopLevelTracedModule).
> Add serialization support for torch.jit.ScriptModule instances

- syft/frameworks/keras/model/sequential.py
- syft/workers/tfe.py
- test/keras/test_sequential.py
Tests where previously running using a `tfe.RemoteConfig` but that is fragile due to process starting and concurrency. This patch changes the tests to use `tfe.LocalConfig` instead.
Closes https://github.com/OpenMined/PySyft/issues/2211.
> Run tests using tfe.LocalConfig

- requirements.txt
- syft/exceptions.py
- syft/serde.py
- syft/workers/base.py
- syft/workers/websocket_server.py
- test/federated/test_plan.py
- test/test_serde.py
- test/workers/test_websocket_worker.py
Provides an implementation to solve #2214
Version 1:
Keep all stack trace just like if the error was happening locally, but uses pickle c742c9b
Version 2:
Keep a serialized version of the stack trace which contains less information, but doesn't use pickle 8466e4f
> Add handling of ResponseSignatureError across socket workers

- syft/frameworks/torch/federated/utils.py
- test/torch/federated/test_utils.py
Bug fix and fix of compatibility issues with pytorch 1.1 for functions add_model and scale_model. These functions are used to calculate the federated average of models.
> Correct functions to add and scale models

- test/torch/pointers/test_pointer_tensor.py
An error will be raised if any instance of "PointerTensor" got accessed its method "item" with an error message telling to consider accessing "get" method instead so you can get the item you want safely.
> Raising error if PointerTensor got called with .item

- requirements.txt
- syft/frameworks/torch/hook/hook_args.py
Fix #2260 
Basically the error was for torchvision >0.2.2
We had a special case to handle
> Add special case for torch function which dont have tensors as input

- syft/frameworks/torch/hook/hook.py
- syft/frameworks/torch/hook/hook_args.py
- syft/frameworks/torch/torch_attributes.py
- test/torch/test_hook.py
I just propose a alternate way to the fix for #2260 which doesn't need to list functions specifically:
Function like `as_tensor` when not identified are correctly handled by hook_args thanks to a fallback mechanism, but can also be included in the list of function not to hook.
> Making hook_args more robust against functions without a tensor in args

- requirements_dev.txt
- syft/__init__.py
- syft/dependency_check.py
- syft/frameworks/__init__.py
- syft/workers/__init__.py
- test/conftest.py
- test/federated/test_federated_client.py
- test/keras/test_sequential.py
- test/test___init__.py
- test/test_dependency_check.py
Many applications of syft don't depend both on pytorch and tensorflow. This code makes it possible to run `import syft` without having tf_encrypted (and thereby tensorflow) installed. 
The goal is to reduce the resources needed for the library, especially for embedded devices.
> Allow syft to be imported without tf_encrypted being installed.

- syft/frameworks/torch/tensors/interpreters/native.py
- test/torch/tensors/test_large_precision.py
- test/torch/tensors/test_precision.py
Fixed issue when calculating whether to use LPT or FPT for LongTensor tensors.
Issue: https://github.com/OpenMined/PySyft/issues/2327
> Use NumPy to compute log2 as LongTensor does not support it

- syft/workers/base.py
- test/workers/test_base.py
The cause of this behavior is due to the way "_objects" dictionary is reset inside clear_objects() method using the statement "self._objects = {}"
When we create a worker with the same id as a pre-existing worker then its "__dict__" object is shared with the pre-existing worker using "self.__dict__.update(known_workers[self.id].__dict__)"
Due to this when we do "self._objects = {}" inside clear_object(), "__objects" now points to a new dictionary object and hence "known_workers" dictionary and "__object" dictionary are not in sync anymore.
To fix this we would need to call the clear() method rather than assigning {} inside clear_objects() method
self._objects.clear()
After the above change the sample code output is shown below-
```
import torch
hook = sy.TorchHook(torch) …
```
> Multiple workers with same id issues #2333

- syft/frameworks/torch/hook/hook.py
I encountered the issue
"AttributeError: 'Linear' object has no attribute 'fix_prec'"
while I replaced fix_precision with fix_prec as shown in this tutorial https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/Part%2012%20-%20Train%20an%20Encrypted%20Neural%20Network%20on%20Encrypted%20Data.ipynb
> Added fix_prec for Linear Object

- requirements.txt
Users are experiencing broken notebooks for the tf-encrypted sections, see here: https://github.com/tf-encrypted/tf-encrypted/issues/624
This is simply a hotfix until the next release of tf-encrypted.
> Patch tf-encrypted version

- syft/frameworks/keras/layers/constructor.py
This fixes the bug found in https://github.com/tf-encrypted/tf-encrypted/issues/624
For context, the most recent release of tf-encrypted (0.5.7) added functionality to help keep track of which layer constructor args had been switched from defaults, but when used in conjunction with the hooked version of tf.keras in PySyft, the signature for these constructors was changed to (self, *args, **kwargs), which would cause errors.  Fixed by using functools.wraps on the hooking decorator, which passes the original signature on to tho hooked function in Python 3.5+.
> Wrapping for keras constructor hook

- syft/__init__.py
Currently on running command 
```
syft.__doc__
```
gives output:
```
>>> Some syft imports...
```
which is correct in the context of syft/__init__.py  but it should be more likely to describe PySyft briefly like:
```
>>> PySyft is a Python library for secure, private Deep Learning. 
>>> PySyft decouples private data from model training, using Federated Learning,
>>> Differential Privacy, and Multi-Party Computation (MPC) within PyTorch.
```
> Syft DocString

- test/workers/test_websocket_worker.py
Sometimes, a ConnectionRefusedError was raised when trying to instantiate a WebsocketClientWorker in the tests for websocket workers.
The introduced helper function waits if the websocket client could not be instantiated before trying once more (5 tries max)
> Helper function to try websocket connection

- examples/tutorials/advanced/websockets-example-MNIST/run_websocket_server.py
While running examples/tutorials/advanced/websockets-example-MNIST/run_websocket_server.py the websocketserver could not be started on Windows due to pickling error while creating a separate process for websocketserver.
Modified the code to create the websocketserver within the current process context itself rather than creating a separate process for the same. After this change the websocketserver could be started on Windows using run_websocket_server.py. Currently I have made this change only for Windows. For non-Windows the logic remains the same as earlier.
> websocketserver startup issue on Windows for websockets-example-MNIST/run_websocket_server.py

- syft/serde/native_serde.py
- test/test_serde.py
This changes set and dict simplification to use tuple instead of list, as suggested in
https://github.com/OpenMined/PySyft/issues/2422
> Closes #2422: use tuple for dict and set simplification

- test/torch/tensors/test_additive_shared.py
.long() is needed. If .long() is removed the types don't match
> Remove unused TODO

- syft/workers/websocket_client.py
Fix TODO at websocket_client.py. No need to "get angry" arguments are mandatory.
> No need to "get angry" arguments are mandatory

- syft/frameworks/torch/tensors/interpreters/precision.py
- test/torch/tensors/test_precision.py
The result of comparisons between Torch tensors being of type uint8, when we were doing `result * self.base ** self.precision_fractional`, this was overflowing.
With a scaling of 1000 for the precision, we were having 232 (`1000 % 2**8`) instead of 1000 (for 1) in the result tensor when doing comparisons.
> Fix comp fpt

- syft/frameworks/torch/hook/hook_args.py
torch.split wasn't working correctly when changing the number of splits needed
> added split in ambiguous functions

- syft/frameworks/torch/crypto/beaver.py
- syft/frameworks/torch/crypto/spdz.py
- syft/workers/base.py
Closes #2475 .
Major changes:
- Removed generate_triple function from base.by
- Added syft/frameworks/torch/crypto/beaver.py 
- Made request_triple in beaver.py with generate_triple logic and additional crypto_provider argument
- Updated spdz.py usage of generate_triple to request_triple to pass failing tests
> Moved generate_triple code to request_triple

- syft/workers/websocket_client.py
This corrects a bug in the websocket client class. Messages are no longer (plain) tuples but instances of the Message class.
> Wrap message tuple in Message class

- syft/frameworks/attributes.py
- syft/frameworks/hook.py
- syft/frameworks/torch/hook/hook.py
- syft/frameworks/torch/torch_attributes.py
- syft/workers/base.py
- test/torch/test_hook.py
In line with OpenMined/rfcs#3, we need to generalize `TorchAttributes` in order for hooking to be fully general (since this is where the command guard lives for `torch.xx` functions, and where it will live for other functions as well).
Other changes:
- Introduces `FrameworkAttributes` to accomplish the above.
- Generalize `TorchHook.is_inplace_method` to an abstractmethod in `BaseHook`
- Renames `BaseHook` to `FrameworkHook` to be consistent with the new `FrameworkAttributes` naming convention.
> Generalize TorchAttributes to FrameworkAttributes

- syft/frameworks/torch/hook/hook.py
The example section in TorchHook class is shown wrongly at two points :
* hook = sy.TorchHook() is not working and giving error TypeError: __init__() missing 1 required positional argument: 'torch'
*  x = sy.Tensor([-2,-1,0,1,2,3]) is giving error as AttributeError: module 'syft' has no attribute 'Tensor'
> update example section of class TorchHook 

- syft/frameworks/torch/tensors/interpreters/large_precision.py
- test/torch/tensors/test_large_precision.py
When performing remainder operation with floats and a large field numpy was throwing a `TypeError` exception.
This issue explains how to fix it
numpy/numpy#6464
Closes #2604
> Fix TypeError when doing remainder

- examples/tutorials/Part 05 - Welcome to the Sandbox.ipynb
This PR should fix the non-working notebook (Part 05 under the `/examples` folder).  The reason for it is such:
`VirtualWorker.search()` requires a list (i.e. `VirtualWorker.search(['#boston', '#target'])`)
... while `VirtualGrid.search()` receives params as *args (i.e. `VirtualGrid.search('#boston', '#target')`)
I figure this may or may not be an intentional API change.  But it is a bit confusing.  Until the API standardizes between a list or *args, I've at least corrected the notebook.
> Currently virtualworker search requires a list

- syft/frameworks/tensorflow/__init__.py
- syft/frameworks/torch/hook/hook.py
- syft/frameworks/torch/torch_attributes.py
- syft/generic/frameworks/hook/hook.py
Accompanies https://github.com/OpenMined/PySyft-TensorFlow/pull/6 for hooking major TF modules.
- Move the inner function `perform_overloading` from `TorchHook._hook_torch_module` to the generic FrameworkHook
- Register PySyft-TF hook_args
- Make some TorchHook methods classmethods
> Support for OpenMined/PySyft-TensorFlow#6

- syft/frameworks/torch/hook/hook.py
- syft/generic/frameworks/hook/hook.py
Tensorflow uses swig to generate APIs and thus their module structure is
quite different than their public api.
in `_get_hooked_func` we would construct the command name to executed like so
```
cmd_name = f"{attr.__module__}.{attr.__name__}"
```
In torch, this was never a problem.  However, with Tensorflow, the attribute
module would often times not line up with the public API.  This uses the user supplied
API namespace for hooking so we can be more confident the API will be there.
> User name hook

- syft/generic/frameworks/types.py
Variables in TF are usually instantiated as some subclass of tf.Variable (see the [Variables RFC](https://github.com/tensorflow/community/blob/master/rfcs/20180817-variables-20.md) for details). This means the actual types of Variables will be some other class, most commonly ResourceVariable in Eager mode.  Thus, we need to add ResourceVariable to the list of FrameworkTensors we typecheck for.
> Add TF ResourceVariable to FrameworkTensor

- test/torch/linalg/test_lr.py
This PR fixes #2680 .
As mentioned in the [Encrypted Linear Regression Tutorial](https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/advanced/Encrypted%20Linear%20Regression.ipynb), the inputs to the Encrypted Linear Regression model should be standardized. The test I had implemented was simulating data where one of the covariates had a standard error of 10 which was causing overflow
> Fix errors / warnings with test of encrypted linear regression

- syft/exceptions.py
Missed f-string on ```"`pip install {pypi_alias}`."``` added. Without it, ``` `pip install {pypi_alias}`.``` would be printed instead.
> minor code fixes in exceptions.py

- pip-dep/requirements_dev.txt
- syft/messaging/plan/plan.py
- test/message/test_plan.py
Solves #2710 
Add a cache mechanism for the Plan class.
1-to-1 mapping between a location and a possible pointer plan that was sent to a worker.
Should reduce the bandwidth usage when the same plan might be sent multiple times to the same worker.
> Add cache for location2pointerplan

- examples/tutorials/advanced/websockets-example-MNIST-parallel/run_websocket_client.py
- syft/federated/federated_client.py
- syft/federated/train_config.py
- syft/frameworks/torch/hook/hook.py
- syft/frameworks/torch/tensors/interpreters/autograd.py
- syft/frameworks/torch/tensors/interpreters/precision.py
- test/federated/test_federated_client.py
- test/message/test_plan.py
- test/torch/federated/test_utils.py
- test/torch/hook/test_hook.py
- test/torch/pointers/test_pointer_plan.py
continued from #2690
Note that Travis is not testing the cuda part as cuda is (currently) not available.
> Enable CUDA processing in PySyft

- run_websocket_server.py
Tried to start a local websocket server using:
```python run_websocket_server.py --id="alice" --port=3000 --host="localhost"```
But got a call error since we were expanding the dictionary (and there is no ```id``` parameter for the ```start_proc``` function)
Solved the issue by removing the ```**``` from the ```kwargs``` variable since it will get expanded in ```start_proc```
Running
```python run_websocket_server.py --id="alice" --port=3000 --host="localhost"```
Should work fine
> Remove ** from kwargs when calling functiono function

- docker-images/pysyft-worker/worker-server.py
- examples/deploy_workers/deploy-and-connect.ipynb
WebsocketServerWorker should now be imported from syft directly instead of syft.workers.
> Fix import in worker Docker image

- syft/__init__.py
- syft/sandbox.py
I find it annoying to have to write hook=sy.TorchHook(th) all the time
and to create the same sample virtual workers over and over. So I short-
ened the .create_sandbox() to a shorter option called .hook(globals())
which hooks pytorch and creates a few virutal workers to play with
> Add .hook() convenience function

- CONTRIBUTING.md
Base branch switched from `dev` to `master`, this PR also change the contribution docs to this.
> Change contribution documentation from dev to master branch

- pip-dep/requirements.txt
When I try to `pip install -Ur pip-dep/requirements.txt` 
in Ubuntu 16.04 / python 3.6.9 / pip 19.3.1 / setuptools 41.6.0
I see following warning:
```
Collecting proto
Cloning git://github.com/OpenMined/proto (to revision master) to /tmp/pip-install-e_sft7x2/proto
Running command git clone -q git://github.com/OpenMined/proto /tmp/pip-install-e_sft7x2/proto
WARNING: Generating metadata for package proto produced metadata for project name pysyft-proto. Fix your #egg=proto fragments.
```
Then it fails to install it.
It seems egg value should match with package name which is `pysyft-proto` (as defined in proto's setup.py).
> Update egg name in proto git dependencity url

- syft/serde/torch_serde.py
- test/torch/tensors/test_additive_shared.py
Fixes #2768.
In ```syft/frameworks/torch/tensors/interpreters/native.py``` **tags** will first look at the tensor, to see if it has any child and if it does it will take the tags from the child.
```
@property
def tags(self):
if self.has_child():
return self.child.tags
else:
if not hasattr(self, "_tags"):
self._tags = None
return self._tags
```
The same behavior is for the **description**:
```
@property
def description(self):
if self.has_child():
return self.child.description
else:
if not hasattr(self, "_description"):
self._description = None
return self._description
```
The problem was the order in which we put the fields for a new tensor (when we call ```_detail_torch_tensor```):
```
if tags is not None:
tags = list(tags)
for i in range(len(tags)):
tag = tags[i]
if isinstance(tag, …
```
> Additive Sharing Tensor search tag and description

- .travis.yml
It seems there is problem when ```coverage``` tries to report for the ```preprocess``` file. The ```preprocess.py``` file was used in the ```SMS Spam prediction``` notebook - there might be a ```pyc``` file that can not be read.
Another solution would be to remove all the ```*.pyc``` files
Source: https://stackoverflow.com/questions/2386975/no-source-for-code-message-in-coverage-py
> Coverage ignore errors when reading files

- test/notebooks/test_notebooks.py
Currently we do not know why the FL Spam detection for SMS is failing.
Someone needs to investigate this issue.
For the moment skip the test such that dev is unblocked
> Skip notebook fl Spam SMS

- syft/messaging/plan/plan.py
- syft/serde/serde.py
This should make it easier to add additional strategies for other
serialization formats (e.g. Protobuf.)
> Refactor serialization and deserialization to use strategy pattern

- CONTRIBUTING.md
Suggested new workflow for syft-proto updates.
This is required after the recent change in requirements.txt where syft-proto package is not referenced as direct git url anymore.
Please also see corresponding PR in syft-proto: https://github.com/OpenMined/syft-proto/pull/16
> New syft-proto workflow in CONTRIBUTING.md

- syft/serde/__init__.py
- syft/serde/compression.py
- syft/serde/serde.py
- test/test_serde.py
This makes the compression and de-compression easier to use again in a
second serialization approach (e.g. Protobuf.) Resolves #2834.
> Extract compression module from serde to simplify re-use

- syft/messaging/protocol.py
Cleans-up `protocol.py` a little bit. In particular:
* Arrange imports to PEP8
* Add doc strings and Args, Returns, Raises where missing
* Adds a couple of inline comments
* Adds missing typehints / corrects some type hints
Overall, errors found when running `mypy syft` have decreased
This PR makes a small contribution to #2510
> Cleanup Protocol

- syft/messaging/message.py
- syft/workers/base.py
- test/test_serde_full.py
This change sacrifices some generality in order to make the actually-in-use contents more explicit and visible. It's a bit awkward in the current code, but should make it easier to construct Protobuf schemas with appropriate types for the parameters. Some of the awkwardness comes from maintaining backwards compatibility for msgpack serialization, some of it comes from the structure of the code that sends commands. It may still be possible to push these named arguments "farther out" into the code that sends commands, which could either be added to this PR or saved for a later one.
> Change `Operation` constructor to take named args (instead of tuple)

- syft/frameworks/torch/hook/hook.py
- syft/messaging/plan/plan.py
- syft/messaging/plan/state.py
- syft/workers/base.py
- test/message/test_plan.py
- test/test_serde_full.py
Solves #2707.
Building a plan that has already a built plan should directly call the function - take into consideration ```*args and **kwargs```.
For doing this, we keep in the owner a state, which would indicate if a plan is already building or not. If a plan is already building, then directly call the function.
Made this PR to support plans in plans - even if the inner plan is already built (with a state) - for that I had to add more information that is sent to the worker (the states for the first plans)
> Deactivate plans in plans

- syft/serde/msgpack/torch_serde.py
- syft/serde/protobuf/__init__.py
- syft/serde/protobuf/proto.py
- syft/serde/protobuf/serde.py
- syft/serde/protobuf/torch_serde.py
- syft/serde/torch/serde.py
- test/serde/protobuf/test_protobuf_serde.py
- test/serde/protobuf/test_protobuf_serde_full.py
This PR also extracts a Torch serde from the msgpack serialization and reuses it in the Protobuf serialization.
Depends on OpenMined/syft-proto#21.
> Add Protobuf serialization for `torch.Tensor` 

- syft/serde/protobuf/proto.py
- syft/serde/protobuf/serde.py
- syft/serde/protobuf/torch_serde.py
- test/serde/protobuf/test_protobuf_serde_full.py
This covers all the Torch types except `torch.Tensor`, which was added in a previous PR.
Depends on OpenMined/syft-proto#23 and #2869.
> Add Protobuf serialization for the remaining Torch types

- pip-dep/requirements.txt
The tests are failling because ```PILLOW_VERSION``` is removed in ```Pillow7.0```
We need to keep track of the [torchvision release](https://github.com/python-pillow/Pillow/releases) that has [this fix](https://github.com/pytorch/vision/pull/1501) in it.
**LE**: This should unblock travis :)
> Downgrade Pillow to <7

- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- syft/generic/pointers/pointer_tensor.py
- syft/messaging/message.py
- syft/serde/protobuf/proto.py
- syft/serde/protobuf/serde.py
- syft/serde/protobuf/torch_serde.py
- test/serde/protobuf/test_protobuf_serde_full.py
- test/serde/serde_helpers.py
This adds serialization for all the types required to make round-trip serialization of `AdditiveSharingTensor` work (at least to the extent that serialization tests pass.)
Depends on OpenMined/syft-proto#24 and #2876.
> Add Protobuf serialization for `Object` and `Operation` messages, `AST` tensor

- docker-images/pysyft-notebook/Dockerfile
[Tutorial 5](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/Part%2005%20-%20Welcome%20to%20the%20Sandbox.ipynb) and presumably some others require sk-learn in order to work correctly. This was causing some errors to run with the default notebook docker image.
This patch adds the `sandbox` option to installing syft for this the notebook docker image.
> Add sk-learn to notebook docker image

- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- test/torch/tensors/test_additive_shared.py
```python
bob, alice, james = (workers["bob"], workers["alice"], workers["james"])
x_sh = torch.tensor([[3, 4]]).share(alice, bob, crypto_provider=james)
if x_sh:
print('should fail')
```
> Add an exception when evaluating an Additive Sharing Tensor in an if statement

- syft/serde/torch/serde.py
- test/serde/msgpack/test_msgpack_serde.py
Using similar syntax as torch_tensor_serializer/desearializer. #2357
> Replace TemporaryFile() with io.BytesIO()

- test/notebooks/test_notebooks.py
The single translation test was taking more than 10m to execute, which was leading Travis CI to infer that our tests were frozen and terminate the builds.
> Split tutorial notebook translation test into separate tests per lang

- test/notebooks/test_notebooks.py
This will give us a better idea of which notebooks are failing when we have problems, and should resolve #2880 in a way that doesn't run afoul of the test coverage checker.
> Split notebook tests into separate tests per notebook

- syft/workers/websocket_client.py
The MNIST async websocket exampe fails because the workers cannot unpack an int. The message sent needs to be the tuple defined previously.
> ObjectRequestMessage for async example

- syft/frameworks/torch/nn/conv.py
- test/torch/nn/test_conv.py
Solves #2927 by changing the convolution implementation and disabling mkldnn while running the test. Test for handcrafted convolution also modified to check for exact match.
> Modify conv implementation and corresponding test to get exact match

- pip-dep/requirements.txt
- syft/frameworks/crypten/__init__.py
- syft/frameworks/crypten/context.py
- syft/messaging/message.py
- syft/serde/msgpack/serde.py
- syft/workers/base.py
- test/crypten/test_context.py
- test/serde/msgpack/test_msgpack_serde_full.py
- test/serde/serde_helpers.py
The new context of computation can run parties that are distributed across syft workers. The communication of crypten parties remains the same, however, syft workers handle initialization and the serialization of return values.
The crypten computation done for the moment is a toy function defined at worker level. The exchange of function isn't yet supported for security reasons.
This PR introduces:
- A new message type CryptenInit that lets workers exchange information such as rank of crypten party to run, number of parties involved, and ip and port of the master party.
- A new router for the CryptenInit message type that runs crypten party according to the information received.
- A function decorator (that doesn't distribute the function yet) to distribute the function and run it as …
> Context of computation for crypten

- syft/frameworks/torch/hook/hook.py
- syft/frameworks/torch/torch_attributes.py
Try to make our repo cleaner by removing a code fix for an old pytorch version
> Remove codefix for old pytorch version

- syft/frameworks/crypten/__init__.py
- syft/frameworks/crypten/context.py
- test/crypten/test_context.py
Added ```self``` such that we can reference the worker in the ```toy_func``` and use the tag to work with the specific data.
A possible fix for #2986
> Add tag for sending tensors to crypten

- README.md
Addition of the url to the Udacity Secure and Private AI course to the README markdown file.
> added link to Udacity course in Readme

- test/notebooks/test_notebooks.py
Some *"basic"* tutorials are ignored in [`test_notebooks.py`](https://github.com/OpenMined/PySyft/blob/master/test/notebooks/test_notebooks.py), namely part 10, 13b and 13c, for multiple reasons (e.g. numpy needs to be hooked for part 10 https://github.com/OpenMined/PySyft/pull/2990).
This PR excludes the translated versions of these *"basic"* tutorials so that the translations of these parts in all languages can be merged while the issues are resolved.  
See: 
- https://github.com/OpenMined/PySyft/pull/3031 
- https://github.com/OpenMined/PySyft/pull/2980
> Failing tutorial translations should be ignored

- .github/workflows/run-notebook-tests.yml
- test/notebooks/test_notebooks.py
Solves the same problem as https://github.com/OpenMined/PySyft/pull/3059 but only tests the notebooks if they have actually been changed.
> Only test translation notebooks if they have been changed

- examples/tutorials/Part 10 - Federated Learning with Secure Aggregation.ipynb
Hi,
I have seen a lot of questions in the community forum about errors when using Part 10 notebook because numpy is not hooked "yet". 
I thought it made sense to put a small disclaimer at the top so people are aware. It can be removed once the issue is fixed.
> Tutorial Notebook 10 note on numpy hook

- .github/workflows/run-notebook-tests.yml
- test/notebooks/test_notebooks.py
> Revert "Only test translation notebooks if they have been changed"

- .github/workflows/update-docker-image.yml
Automatically update Docker Hub image at [https://hub.docker.com/r/openmined/pysyft-notebook](https://hub.docker.com/r/openmined/pysyft-notebook) on push to Master (using GitHub Actions).
Addresses https://github.com/OpenMined/PySyft/issues/2528
Requires:
Questions:
- not sure how to explicitly test that this works, so I'm not sure if there is a way and I'm missing that test...
- Python version set to '3.x', is this okay? 
- In the test workflows, both 3.6 and 3.7 are specifically tested
- in the publish to pypi, 3.x is used
- Did not include publishing to GitHub Packages as per [the example](https://github.com/arkhn/fhir-pipe/blob/master/.github/workflows/main.yml) listed in https://github.com/OpenMined/PySyft/issues/2528. Do you want this feature?
> Automatically update Docker Hub using GitHub Actions (on push to master)

- syft/generic/pointers/pointer_tensor.py
Tags and descriptions are no longer received as binary values during the `pointer_tensor.detail` method.
Therefore, we can remove the decoding instructions.
These changes solve  the [PyGrid issue](https://github.com/OpenMined/PyGrid/issues/473)
> Remove decode instruction from tags/description

- pip-dep/requirements.txt
This is a follow-up to #3067. The changes in that PR broke compatibility with `msgpack<1.0.0`, requirements should reflect that.
> Update msgpack version requirement

- syft/workers/websocket_client.py
This is making CI tests hang ~forever. I think 278 hours is a bit
excessive, don't you? :)
> Reduce websocket timeout to one minute

- .github/workflows/translated-tutorials.yml
Failing changes here: https://github.com/OpenMined/PySyft/pull/3082 
Potential solution [here](https://github.community/t5/GitHub-Actions/GitHub-actions-does-not-print-git-diff/td-p/43755)
> Change GHA checkout version in translation tests

- .github/workflows/translated-tutorials.yml
Looks like what really works is this: https://github.com/actions/checkout/issues/160 regarding the problem with https://github.com/OpenMined/PySyft/pull/3084. Hopefully this will set the right track to solve at least problem 2 of this issue: https://github.com/OpenMined/PySyft/issues/2917
> Use v2 and fetch all in checkout during build for translations

- test/torch/nn/test_rnn.py
Addressing the issue for https://github.com/OpenMined/PySyft/issues/2926. Commit test_rnn.py for https://github.com/OpenMined/PySyft/blob/master/syft/frameworks/torch/nn/rnn.py
> Commit test_rnn

- test/federated/test_train_config.py
- test/torch/test_hook.py
RNG state coupling between tests still needs a more thorough fix, but
this will make the tests pass for now.
> Fix failing tests on master

- INSTALLATION.md
- examples/tutorials/Part 01 - The Basic Tools of Private Deep Learning.ipynb
Since the pytorch version was bumped to 1.4 (#2916) , some of the docs still mentioned pytorch1.3 , I changed that to pytorch 1.4
> Update pytorch version to 1.4 in docs

- README.md
Since python 3.8 is incompatible with Tensorflow, a note in the README would be helpful to beginners installing PySyft.
> Update regarding incompatible python versions

- examples/tutorials/Part 05 - Welcome to the Sandbox.ipynb
Just a small change, removed an unnecessary line :)
> Minor Tutorial Change

- CONTRIBUTING.md
- README.md
- pip-dep/requirements.txt
- syft/serde/compression.py
- test/serde/msgpack/test_msgpack_serde.py
In files:   CONTRIBUTING.md, README.md
all documentation referring to ZSTD were removed.
In file:   pip-dep/requirements.txt
dependency on ZSTD removed
In files:   syft/serde/compression.py, test/serde/msgpack/test_msgpack_serde.py
all codes referring to ZSTD were removed
> Remove ZSTD and all references to it: closes #3134

- README.md
As of now, `conda create -n pysyft python=3` will create an environment with python 3.8, which will not be able to run PySift, due to its Tensorflow dependencies. By specifying `python=3.7`, we solve this issue.
> README.md update: specify python=3.7

- syft/common/util.py
- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- syft/frameworks/torch/tensors/interpreters/precision.py
- syft/generic/frameworks/hook/hook.py
- syft/generic/frameworks/overload.py
- syft/workers/base.py
- test/torch/tensors/test_precision.py
Added the reference for the paper where the polynomial approximations are discussed.
[Here](http://tygert.com/realcrypt.pdf) is the paper (it is also added as a comment)
They talk about more functions and how to approximate those - maybe it is worth to have approximations for more functions?
Added tests and the possibility to choose between Chebyshev or Sigmoid for computing the hyperbolic tangent.
> Chebyshev or Sigmoid for tanh

- .pre-commit-config.yaml
- examples/tutorials/advanced/websockets-example-MNIST-parallel/run_websocket_client.py
- examples/tutorials/advanced/websockets-example-MNIST/run_websocket_client.py
- syft/execution/plan.py
- syft/execution/state.py
- syft/federated/federated_client.py
- syft/frameworks/keras/model/sequential.py
- syft/frameworks/torch/fl/dataset.py
- syft/frameworks/torch/hook/hook.py
- syft/frameworks/torch/linalg/lr.py
- syft/frameworks/torch/nn/rnn.py
- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- syft/generic/frameworks/hook/hook_args.py
- syft/generic/id_provider.py
- syft/generic/pointers/object_pointer.py
- syft/serde/msgpack/proto.py
- syft/workers/tfe.py
- test/execution/test_plan.py
- test/federated/test_federated_client.py
- test/federated/test_train_config.py
- test/serde/msgpack/test_msgpack_serde_full.py
- test/serde/protobuf/test_protobuf_serde_full.py
- test/torch/federated/test_dataloader.py
- test/workers/test_websocket_worker.py
**This PR**:
- Ran a linter, [`flynt`](https://github.com/ikamensh/flynt), to turn formatted strings which already exist in the codebase to f-strings
- Adds `flynt` to pre-commit
f-strings are quicker than other types of formatting strings.
I can remove the pre-commit addition if needed. It may not be worth the additional overhead of running pre-commit so long as non-f strings in new PRs are caught in review.
There is no existing issue relating to this PR.
**To test**:
1. Check  than the converted strings have been formatted correctly
2. Check pre-commit compiles and works as expected
> Turn existing formatted strings into f-strings

- syft/execution/plan.py
- test/execution/test_plan.py
This PR fixes #3184 
Solved:
* added support when input tensor is also output tensor.
* added a test case when input tensor is also output tensor.
To do:
* check for the number of parameters
* create support for nested structures
> Improve Plans flexibility

- pip-dep/requirements.txt
- syft/generic/pointers/pointer_tensor.py
- syft/messaging/message.py
- syft/serde/msgpack/serde.py
- syft/serde/protobuf/proto.py
- syft/serde/protobuf/serde.py
- syft/workers/base.py
- syft/workers/websocket_client.py
- test/message/test_message.py
- test/serde/msgpack/test_msgpack_serde_full.py
- test/serde/protobuf/test_protobuf_serde_full.py
- test/serde/serde_helpers.py
- test/workers/test_base.py
Depends on OpenMined/syft-proto#53.
> Standardize the names of tensor, plan, and worker command messages

- examples/experimental/FL Training Plan/Create Plan.ipynb
- pip-dep/requirements.txt
- syft/__init__.py
- syft/execution/computation.py
- syft/execution/placeholder.py
- syft/execution/plan.py
- syft/frameworks/torch/hook/hook.py
- syft/messaging/message.py
- syft/serde/msgpack/serde.py
- syft/serde/protobuf/proto.py
- syft/serde/protobuf/serde.py
- test/serde/msgpack/test_msgpack_serde_full.py
- test/serde/protobuf/test_protobuf_serde_full.py
- test/serde/serde_helpers.py
It's not actually specific to PyTorch and is most closely related to
the other classes in `execution` (e.g. `Plans`, `Protocols`.)
> Move `Placeholder` class to `execution` package

- syft/frameworks/torch/tensors/interpreters/precision.py
- test/conftest.py
- test/torch/tensors/test_precision.py
Fixes #3131 
Also adds the approximation for sigmoid using the tanh.
> Sigmoid aprox with tanh + fix sigmoid

- syft/execution/placeholder.py
- test/execution/test_plan.py
Fixes #3214. 
The problem was that when reconstructing the network placeholders, the is_wrapper parameter from tensor was ignored.
The apparent issue with parameter serialization was due to the fact that when fetching a plan the wrapper parameter was incorrectly reconstructed as a plain parameter. This is actually done inside the placeholder deserialization function, where the "is_wrapper" field is stripped from the parameter tensors inside the instantiate method, hence the missing "Wrapper" when printing the deserialized network's parameters.
> Fix the placeholder serialization.

- syft/frameworks/torch/tensors/interpreters/native.py
- test/torch/tensors/test_native.py
- test/torch/tensors/test_paillier.py
Fixes [#3212](https://github.com/OpenMined/PySyft/issues/3212)
> Modify .encrypt() to add a kwarg and be used not only for Paillier encryption but only MPC (default should be MPC, and it should call for mpc .fix_prec(...).share(...) under the hood)
> Add a `protocol` kwarg to `encrypt()` method to select between MPC and Paillier HE

- setup.cfg
Required for testing coverage of #3269
> Update Coverage path

- syft/frameworks/torch/tensors/interpreters/paillier.py
On the creation of a `PaillierTensor`, a message gets printed (a debug log I guess)
That is removed
<details>
<summary>The Message</summary>
`creating paillier tensor 2`
</details>
A Micro Change :smile:
> Remove Debug Log on Instantiation of a PaillierTensor

- docker-images/pysyft-notebook/Dockerfile
Error coming up:
``` ERROR: syft 0.2.4 has requirement tornado==4.5.3, but you'll have tornado 5.1.1 which is incompatible.```
> Target correct notebook version

- syft/execution/plan.py
The worker that has the "original" plan will use ```forward``` and the other workers (which received the plan) will use the stored actions.
If the plan is not built, it can not be built on a remote worker since it does not have the ```forward```.
If my understanding is correct, then we should remove the specified lines.
> Remove redundant check

- syft/execution/role.py
- syft/generic/frameworks/__init__.py
- syft/generic/frameworks/types.py
This creates a global registry of the available framework packages,
which can be used when executing `Actions` in `Plans`. This removes the
last remaining `eval` in the code base, and removes the need for `Role`
to import framework packages referenced in `Plans` (like `torch` or
`crypten`.)
> Remove `eval` & `import torch` from `Role` using framework package store

- syft/workers/websocket_client.py
This is to enable training on GPU optionally using async_fit function on the worker by passing the device in the async_fit function
> Add device option to async_fit

- .github/workflows/tests.yml
- .github/workflows/translated-tutorials.yml
- .github/workflows/tutorials.yml
The test suite includes some flaky tests, which are hampering our ability
to merge translation PRs that don't touch the main code of the library.
This updates the paths that trigger the test suite so that it only runs
when `.py` requirements files are changed. The tutorials tests will only
run when `.py`, `.ipynb`, or requirements files are changed. The
translation tests will only run when there are changes to the translation
notebooks.
> Update path triggers for automated test workflows

- pip-dep/requirements_notebooks.txt
As per #3272 , there is a dependency missing issue while running Tutorial 5 notebook.
> Add Scikit-Learn to Notebook requirements.txt

- test/federated/test_federated_client.py
This test was failing unexpectedly in the automated test suite, which
appears to be due to randomization sometimes leading the `loss` to
increase instead of decrease. In that circumstance, the test would try
to train the model further until the loss decreased, but the line that
trains the model again was missing the `device` param, causing the test
to fail intermittently.
> Fix missing `device` param in `test_federated_client.py::test_fit`

- .github/workflows/tests.yml
- .github/workflows/translated-tutorials.yml
As #3339 takes care of scikit-learn installation through `pip-dep/requirements_notebook.txt` , no need to use `pip install scikit-learn` separately.
@karlhigley
> Removing scikit-learn from workflow ymls

- .github/workflows/tests.yml
- .github/workflows/translated-tutorials.yml
- .github/workflows/tutorials.yml
- pip-dep/requirements.txt
- syft/__init__.py
- syft/dependency_check.py
- syft/execution/placeholder.py
- syft/execution/plan.py
- syft/execution/role.py
- syft/frameworks/crypten/__init__.py
- syft/frameworks/crypten/context.py
- syft/frameworks/crypten/hook/hook.py
- syft/frameworks/torch/hook/hook.py
- syft/frameworks/torch/tensors/crypten/syft_crypten.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/generic/frameworks/hook/trace.py
- syft/generic/frameworks/types.py
- syft/messaging/message.py
- syft/sandbox.py
- syft/serde/msgpack/serde.py
- syft/workers/base.py
- test/crypten/test_context.py
- test/serde/msgpack/test_msgpack_serde_full.py
- test/serde/serde_helpers.py
**Attention** Those changes are not meant to go into master, I will change the PR to target a different branch.
Rebased with master Crypten using Plans (also integrated with SyftCrypTensor).
* Added the initial implementation (context setup with ```run_multiparty_computation``` and test file) from Ayoub
* ```SyftCrypTensor``` will be a shell for the operations that will be done on the MPCTensor -- Integrated changes from Ajay
* Traced the ```add``` and ```get_plain_text``` methods
How the tested function looks:
```
@run_multiworkers([alice, bob], master_addr="127.0.0.1")
@sy.func2plan()
def plan_func():
alice_tensor = crypten.load("crypten_data", 1)
bob_tensor = crypten.load("crypten_data", 2)
crypt = alice_tensor + bob_tensor
result = crypt.get_plain_text()
return result
```
How the plan …
> Init Crypten Plan + Rebased

- test/torch/differential_privacy/test_pate.py
Tested Pysyft with torch nightly and found this problem.
The PR can be checked out [here](https://github.com/OpenMined/PySyft/pull/3315).
The problem I had is:
```
def test_torch_ref_match():
num_teachers, num_examples, num_labels = (100, 50, 10)
preds = (np.random.rand(num_teachers, num_examples) * num_labels).astype(int)  # fake preds
indices = (np.random.rand(num_examples) * num_labels).astype(int)  # true answers
preds[:, 0:10] *= 0
data_dep_eps, data_ind_eps = pate.perform_analysis_torch(
preds, indices, noise_eps=0.1, delta=1e-5
)
data_dep_eps_ref, data_ind_eps_ref = pate.perform_analysis(
preds, indices, noise_eps=0.1, delta=1e-5
)
>       assert torch.isclose(data_dep_eps, torch.tensor(data_dep_eps_ref))
E       RuntimeError: Float did not match Double
```
> Pate test specify type

- test/torch/test_hook.py
This test was implicitly relying on `torch.Tensor's` approximate `eq`
when comparing a tensor with a float. Instead, let's compare floats
directly, which makes this test always fail.
> Fix flakiness in `test_local_remote_gradient_clipping`

- test/keras/test_sequential.py
This test has a known issue with sampling from a normal distribution
that might land close to zero, making small absolute errors result in
large relative errors. This bumps the relative tolerance and adds an
absolute tolerance to prevent the test from accepting large absolute
errors on large values that result in small relative errors.
More on this in [Issue #3344](https://github.com/OpenMined/PySyft/issues/3344#issuecomment-612652546).
> Adjust comparison thresholds in `test_instantiate_tfe_layer`

- pip-dep/requirements_dev.txt
`pytest-randomly 3.3.0` adds support for `pytest-xdist` but does so in a
way that requires `pytest-xdist` to be installed, which we don't need.
It's probably an accidental change, but until it's resolved we'll just
avoid that version (which breaks our builds.)
> Restrict `pytest-randomly` version to avoid `3.3.0`

- syft/execution/role.py
- syft/execution/translation/torchscript.py
In https://github.com/OpenMined/PySyft/pull/3263, plan with state was traced to torchscript with extra arg that passes state inside the plan. The last arg was handled in Role.
However, adding this extra argument interferes with #3296 by @tudorcebere
This PR moves handling of the last arg from Role into wrapper func in torchscript translator class, so the Role itself is not affected and gets correct number of arguments.
> Handle torchscript state arg outside of Role

- syft/frameworks/torch/tensors/interpreters/native.py
Current call of a `.encrypt()` defaults to `requires_grad` and `no_wrap` to be `False` and has no provision of choice. 
This adds that functionality while preserving the default values from the `.share()` method.
> Accomodate `no_wrap` and `requires_grad` kwargs in `.encrypt()` Method

- examples/tutorials/advanced/split_neural_network/Tutorial 1 - SplitNN Introduction.ipynb
- examples/tutorials/advanced/split_neural_network/Tutorial 2 - MultiLayer Split Neural Network.ipynb
- examples/tutorials/advanced/split_neural_network/Tutorial 3 - Folded Split Neural Network.ipynb
This PR is requested by @H4LL in #3166, just fix my previous mistakes. Ready to be merged directly.
> Remove unnecessary name off tutorials

- test/notebooks/test_notebooks.py
The black box model inversion notebook is downloading EMNIST and using
up all the space in the automated test environments.
> Skip the privacy attack notebooks during notebook tests

- syft/workers/base.py
That assumption makes it possible to have a case where `known_workers`
is empty, which leads `len(frameworks) == 1` to be `False`, which
defaults to the wrong serialization strategy when `self.framework` is
`torch`.
Fixes #3359
> Don't assume `self` is in `known_workers` in `BaseWorker.serializer`

- syft/execution/translation/torchscript.py
Resolve Conficts, merge with master
>It turns out `jit.trace()` strips `Parameters` out of the tensor chain,
which causes issues with `fix_precision`. Don't fully understand why
`jit.trace()` does that, but operating on a copy of the original Plan
avoid mutating the original State tensors, which fixes the issue.
@karlhigley #3375
> Rework `PlanTranslatorTorchscript` so it doesn't strip `Parameters`

- codecov.yml
Makes the codecov actions always pass. This is okay, because we have other test coverage checks in the normal test suite.
> Make codecov statuses informational (always pass)

- syft/codes.py
- syft/workers/node_client.py
One of the most common errors reported by PyGrid users is the Syft version mismatch between the grid nodes and the user environment. The purpose of this PR is to provide a debugging mechanism for this error.
> Add Syft version checking

- syft/frameworks/torch/hook/hook.py
- test/crypten/test_hook.py
In a parallel PR #3365 , I was wrapping the crypten model and adding functionalities such as sending and sharing crypten models. In this PR, I add the same features by hooking into `crypten.nn.Module` instead of wrapping it.
> Hooking crypten.nn.Module

- syft/frameworks/torch/tensors/interpreters/autograd.py
- syft/frameworks/torch/tensors/interpreters/gradients.py
- syft/frameworks/torch/tensors/interpreters/gradients_core.py
- syft/workers/base.py
- test/torch/tensors/test_autograd.py
Issue addressed: https://www.diffchecker.com/7jVaQe96
Code for testing
```python
import torch as th
import torch.optim as optim
import pprint
hook = sy.TorchHook(th) #, verbose=True)
bob = sy.VirtualWorker(hook, id="bob") #, verbose=True)
alice = sy.VirtualWorker(hook, id="alice") #, verbose=True)
crypto_provider = sy.VirtualWorker(hook, id="james") #, verbose=True)
torch = th
syft = sy
a = torch.ones(1, 5)
b = torch.ones(1, 5)
a = a.encrypt(workers=[alice, bob], crypto_provider=crypto_provider, requires_grad=True)
b = b.encrypt(workers=[alice, bob], crypto_provider=crypto_provider, requires_grad=True)
class Classifier(torch.nn.Module):
def __init__(self, in_features, out_features):
super(Classifier, self).__init__()
self.fc = torch.nn.Linear(in_features, out_features) …
```
> Garbage Collection for `AutoGradTensor`

- syft/__init__.py
- syft/execution/placeholder.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/generic/frameworks/hook/trace.py
- syft/sandbox.py
- test/execution/test_placeholder.py
Update master with the core changes made on the crypten branch
> Add Crypten changes to master

- syft/frameworks/torch/nn/__init__.py
- syft/frameworks/torch/nn/functional.py
- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- test/torch/nn/test_functional.py
resolves issue #2573 
overloading torch.nn.F.max_pool2d and avg_pool2d in order to use it in architectures like ResNet
> Avg & Maxpooling with SMPC

- README.md
Make the link to API doc explicit in the `README.md` so new users could easily find the doc.
> make the link to API doc explicit in the readme

- MANIFEST.in
`pip-dep` does not get included when building sdist, and creates issues such as #3413.
I have added a MANIFEST.in file so that the requirement files can be referenced at setup.py without breaking.
> create manifest file to include pip-dep directory

- .github/pull_request_template.md
- syft/execution/plan.py
- syft/generic/frameworks/hook/hook_args.py
Got an inspect warning while running some tests
```
/plan.py:199: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0,
use inspect.signature() or inspect.getfullargspec()
forward_args = inspect.getargspec(self.forward).args
```
Also, I fixed some typos.
> Fix typo and inspect warning

- test/torch/tensors/test_precision.py
The ```sigmoid_exp``` test is failing (sometimes).
This PR increases the tolerance such that the test will pass.
Fixes #3345
* Have seen this failure [here](https://github.com/OpenMined/PySyft/pull/3422/checks?check_run_id=632038986)
* Tested with the values from the issue and from the above test run:
* 0.0605 / (0.065 * 0.9885) = 0.94 (bellow threshold) (how it failed in the PR)
* 0.0605 / (0.065 * 0.9890) = 0.94 (bellow threshold) (how it failed in the issue description)
> Increase sigmoid exp tol

- syft/execution/tracing.py
- test/execution/test_plan.py
There was a bug that actions were duplicated when tracing a torch function on Placeholders.
> Fix double tracing bug

- syft/frameworks/torch/nn/rnn.py
This pull request simplifies the code in RNNBase. A significant amount of complexity was caused by using the same code to deal handling 2 different data structures of hidden state (LSTMCell has hidden+cell, GRUCell and RNNCell have only hidden). This was simplified by converting these 2 structures into 1 compatible structure internally in the forward method.
I have not added tests. If you think I should add tests for this change, could you point me to an example of how I might do this?
I followed the existing comment structure when making comments.
Fixes #3431 
> cleanup rnn.py

- syft/workers/base.py
This bypasses some issues where serialization/deserialization changes
the state or type of the objects passed to the serdes. That also needs
to be fixed, but this is a smaller and still sensible change in the mean
time.
> Store the message log in `BaseWorker` in an unserialized format

- syft/execution/communication.py
- syft/execution/computation.py
- syft/messaging/message.py
- test/serde/serde_helpers.py
Gets rid of a few stray `contents` methods, which are no longer needed due to changes to the way messages are routed and processed in #3175.
> Remove `contents` methods (previously deprecated, partially removed)

- syft/workers/base.py
- syft/workers/node_client.py
- syft/workers/websocket_client.py
- syft/workers/websocket_server.py
**:warning: Is needed for https://github.com/OpenMined/PySyft/pull/3337**
Improves async support for grid nodes, by allowing to send async commands simultaneously to several remote servers.
Waiting for a global strategy to add tests, as tests require setting up a grid network.
```python
import asyncio
import torch as th
from syft.workers.node_client import NodeClient
hook = sy.TorchHook(th)
alice = NodeClient(hook, "ws://localhost:7600")
bob = NodeClient(hook, "ws://localhost:7601")
charlie = NodeClient(hook, "ws://localhost:7602")
crypto_provider = charlie
me = sy.local_worker
my_grid = sy.PrivateGridNetwork(alice,bob,charlie)
x = th.tensor([-1., 2])
p_alice = x.send(alice)
p_bob = x.send(bob)
p = asyncio.run(
alice.async_send_command(
message=('abs', p_alice.child, (), …
```
> Add async send_command to websocket client

- syft/frameworks/crypten/context.py
- syft/frameworks/crypten/jail.py
- syft/frameworks/torch/hook/hook.py
- syft/workers/base.py
After introducing Jails and the mechanisms for sending Crypten models across workers, we needed a way to send those models while initializing a Crypten computation using our `@run_multiworkers` decorator. 
With this PR, a function decorated with `@run_multiworkers([ALICE, BOB], master_addr="127.0.0.1", model=model, dummy_input=dummy_input)` where `model` is a `torch.nn.Module` and dummy input is a `torch.Tensor` that can be evaluated using the `model`, every party running on different workers will have access to the `model` inside their functions, which then should be an equivalent Crypten model.
> Send models with @run_multiworkers

- .github/workflows/tests.yml
The verbose output makes it harder to see where the problems are, because it includes files that already have the correct formatting. That makes it a needle/haystack problem trying to figure out what to change in order for the linting to pass.
> Remove `verbose` flag from code formatting check

- syft/frameworks/torch/hook/hook.py
- syft/frameworks/torch/mpc/fss.py
- syft/generic/frameworks/hook/hook.py
- syft/generic/pointers/callable_pointer.py
- syft/generic/pointers/object_pointer.py
- syft/generic/pointers/pointer_dataset.py
- syft/generic/pointers/pointer_plan.py
- syft/generic/pointers/pointer_tensor.py
- syft/workers/base.py
refactor BaseWorker.send_command to accept explicit arguments.
Refactor the send_command method of BaseWorker class to accept explicit arguments. The message tuple argument is replaced with arguments in the message tuple.
Refactor: Issue #3481, [Link to issue.](https://github.com/OpenMined/PySyft/issues/3481)
> refactor BaseWorker.send_command to accept explicit arguments.

- syft/generic/pointers/pointer_tensor.py
- test/torch/pointers/test_pointer_tensor.py
> the move() method intended to throw an error, when trying to move an object to a virtual worker that already possesses the object
Fixes #3435 
> Fix `move` PT to its own location

- syft/grid/abstract_grid.py
This shows up as a `flake` linting error on several PRs after recent changes to the linting rules.
> Add a missing `NodeClient` import to `AbstractGrid`

- syft/workers/abstract.py
- syft/workers/base.py
`AbstractWorker` is currently empty, while `BaseWorker` contains abstract methods. This consolidates the abstract definition of workers into one place.
> Move abstract methods from `BaseWorker` to `AbstractWorker`

- syft/frameworks/crypten/context.py
- syft/frameworks/crypten/worker_support.py
- syft/workers/base.py
- syft/workers/worker_support.py
- test/crypten/test_context.py
- test/workers/test_virtual.py
Fixes #3363 
Some initial changes to add the mechanism to add/remove methods from a base worker such that it will be able to support the implemented CrypTen operations.
Currently, there is added only CrypTen support, but I choose to implement it in this way (is only an initial draft) such that we could easily add more frameworks in the future.
WIP: Need to add tests to make sure the add/remove mechanism work as intended.
> Add method to add/remove operations from base worker

- syft/workers/base.py
- test/torch/nn/test_nn.py
- test/torch/pointers/test_pointer_tensor.py
- test/torch/tensors/test_additive_shared.py
- test/torch/tensors/test_autograd.py
The extra objects initialized on every worker for FSS cause weird behavior in tests and very non-obvious object counts in unrelated parts of the code.
Resolves #3464
> Fix stray objects from FSS `Worker/Plan` initialization

- syft/grid/webrtc_connection.py
Apparently, the jupyter notebook has some limitations for running code asynchronously using the asyncio lib _(more details below)_. This PR aims to replace `asyncio.run()` calls to solve event loop issues during async calls inside of a notebook environment.
Issue details:
_"Unlike terminal IPython, all code runs on asyncio eventloop, so creating a loop by hand will not work, including with magics like %run or other frameworks that create the eventloop themselves."_ , [IPython Docs](https://ipython.readthedocs.io/en/stable/interactive/autoawait.html?highlight=nest#using-autoawait-in-a-notebook-ipykernel)
Related issues on jupyter notebook repository:
[Can't invoke asyncio event_loop after tornado 5.0 update](https://github.com/jupyter/notebook/issues/3397)
[asyncio.run() fails in the …
> Solve webrtc notebook async calls

- syft/generic/frameworks/hook/hook.py
- syft/generic/frameworks/hook/pointers.py
- syft/generic/frameworks/hook/string.py
- syft/generic/frameworks/hook/tensors.py
This splits `FrameworkHook` into `TensorHook`, `PointerHook`, and `StringHook` in order to make it easier to figure out which parts can be replaced with the new style of tensor hooking in #3559.
> Split `FrameworkHook` into multiple parts

- syft/grid/__init__.py
This PR aims to disable the ability to set the peer ID manually.
Resolves #3574
> Disable register peer ID's manually

- syft/frameworks/torch/tensors/interpreters/native.py
- test/serde/serde_helpers.py
- test/torch/tensors/test_private.py
According to what was required by issue #3569 , we must change the data structure used to store the allowed users in private tensors. Doing its conversion to tuples internally.
Resolves #3569 
> Change PrivateTensor parameter type

- syft/workers/base.py
- test/workers/test_base.py
Added method to return support for framework in BaseWorker.
Issue: #3523
Resolves #3523 
* [x ] I have run [the pre-commit hooks](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md#setting-up-pre-commit-hook) to format and check my code for style issues.
* [ x] I have commented my code following [Google style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
> Added method to return support for framework in BaseWorker

- test/workers/test_virtual.py
Time based tests are inherently flaky based off of hardware. The original idea
of this test was to make sure that virtual workers were created quickly since
we were concerned about virtual workers taking too long to be created (since
data had to be copied) and wanted to make sure that we didn't regress to a point
where they were so slow that they caused timeout errors. The timings and amount
of data used to test were arbitrary. By removing this test we can reduce test
flakiness and add allow for more freedom to add something similar back when the
requirements are better understood.
Resolves #3503 
(This change deletes a test so i guess?)
Actually completely forgot to set these up since I wrote this pr on a fresh fork. That being said, the change I made should not break formatting so I'm …
> Remove test_spinup_time

- examples/experimental/FL Training Plan/Create Plan.ipynb
- syft/execution/placeholder.py
- syft/execution/plan.py
- syft/execution/role.py
- syft/execution/translation/torchscript.py
- syft/frameworks/torch/tensors/interpreters/autograd.py
- syft/frameworks/torch/tensors/interpreters/gradients.py
- syft/frameworks/torch/tensors/interpreters/gradients_core.py
- test/execution/test_translation.py
Attempt to use autograd tracing (in its existing form) to trace MNIST example for static FL.
Initially, there's unit test that should pass.
Next, notebooks should be updated.
> FL MNIST example with autograd tracing

- syft/frameworks/torch/hook/hook.py
- test/crypten/test_context.py
Remove the hooking for the MPCTensor since currently the PlaceHolder class is used to track the operations on an MPCTensor (in a plan)
> Remove the hook from Crypten MPC Tensor

- test/conftest.py
This mark is used in the test suite to designate tests that should only
run during the translation tests and not as part of the regular notebook
tests. It works fine now, but results in warnings from PyTest at the end
of the test suite output about an unregistered mark. This change makes
the warnings go away, but otherwise doesn't change anything about the
functionality of the test suite.
> Register the `translation` mark with PyTest to suppress warnings

- pip-dep/requirements.txt
There was a version conflict with the installation of jupyter notebook with tornado version.
In order to overcome the problem, the requirements.txt is updated with a notebook <6 version so that it is compatible tornado version <5
Resolves # (issue)
3546
> requirements.txt updated with tornado compatible notebook version

- syft/generic/abstract/hookable.py
- test/generic/test_hookable.py
Adds utilities for inserting optional `_before_method()`/`_after_method()` hooks on a method decorated with `@hookable`, which allows custom tensor types to insert any functionality they individually require before or after a generic tensor method like `send`. This should help clean up the copious `if isinstance(self, TensorClass)` code in `AbstractTensor` and beyond.
In order to make sure that all custom functionality for types in the tensor chain gets called, this also creates a `chain_call()` function, which accepts a method name with args/kwargs, and calls that method (if it exists) on every tensor in the chain from outermost to innermost, returning the results in an ordered list.
> Add utilities for hooking and chaining methods calls along tensor chains

- syft/frameworks/torch/tensors/interpreters/native.py
- syft/frameworks/torch/tensors/interpreters/private.py
- syft/generic/abstract/hookable.py
- syft/workers/base.py
This extracts permission checking into a `_before_send()` hook on the relevant class (`PrivateTensor`), so that `TorchTensor` doesn't have to know as much about the functionality of custom types. This is the first of many similar refactors to move knowledge of custom tensor types out of `TorchTensor`.
> Move permissions from `TorchTensor.send()` to `PrivateTensor._before_send()` hook

- pip-dep/requirements.txt
Update to pull in Protobuf support for `BaseDataset`, `FixedPrecisionTensor`, and a fix for integer `Action` arguments.
> Update `syft-proto` to 0.4.7

- examples/experimental/Federated Learning Experiment/FL Experiment.ipynb
- examples/experimental/Federated Learning Experiment/server.py
- syft/generic/abstract/sendable.py
- syft/generic/abstract/tensor.py
- test/serde/msgpack/test_msgpack_serde.py
This removes a few rarely used serialization methods and moves some methods that turn out to only make sense on tensors into `AbstractTensor`.
> Clean up `AbstractSendable` to remove extraneous methods

- syft/generic/abstract/hookable.py
- syft/workers/base.py
- test/generic/test_hookable.py
This renames `chain_call` to `map_chain_call` and introduces a method
called `reduce_chain_call`. `map_chain_call` still gathers the values
returned from each hook method that's called on a tensor chain, resulting
in a list of values. `reduce_chain_call` passes the output value from
each hook method into the next one, resulting in a single value.
> Improve `@hookable` decorator to allow modifying return values after

- syft/generic/frameworks/hook/hook_args.py
- syft/generic/object_storage.py
- syft/generic/pointers/pointer_tensor.py
- test/generic/pointers/test_pointer_tensor.py
Fixes #3543
Add the possibility to do:
```
for tensor in ptr:
print(tensor) # should return a new pointer tensor
```
- Test if the number of tensors alice has 
Add a new method to the storage object such that we can call ```len(alice.object_store``` and will return the number of objects from the worker.
> Add iterable behavior for PointerTensor

- examples/experimental/Training an Encrypted Neural Network across Workers using Crypten.ipynb
- syft/frameworks/crypten/context.py
- syft/frameworks/crypten/jail.py
- syft/frameworks/torch/hook/hook.py
- test/crypten/test_context.py
- test/crypten/test_hook.py
- test/crypten/test_jail.py
This PR add an experimental notebook showing how to train an encrypted neural network using crypten, it's based on [Tutorial7 of CrypTen](https://github.com/facebookresearch/CrypTen/blob/master/tutorials/Tutorial_7_Training_an_Encrypted_Neural_Network.ipynb).
Two issues were also solved to implement the demo correctly. First an issue regarding how the crypten computation is initiated in the syft context, and a second regarding how virtual workers are used.
CrypTen computation is started from a master worker that will be responsible of running the master party which needs to bind and listen to a port for synchronizing between distributed parties, our initial design start a party (rank 0) on the local worker to be the master that will do the previous job, this introduced some complication …
> Full Demo: Training an Encrypted Neural Network across Workers using Crypten (with jails)

- examples/tutorials/Part 10 - Federated Learning with Secure Aggregation.ipynb
In [Part 10 - Federated Learning with Secure Aggregation.ipynb](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/Part%2010%20-%20Federated%20Learning%20with%20Secure%20Aggregation.ipynb), the first step of "encrypted aggregation" is that copying the selected parameter.
Since the **Fixed Precision** and **Encrypt** are not in-place operations.
Without copying the parameters, we can still keep the plain parameters in the local.
Therefore, in my opinion, this step can be omitted.
No
No
> Simplify encrypted aggregation in the tutorials

- syft/frameworks/torch/he/fv/decryptor.py
- test/torch/tensors/test_fv.py
Closes #3671 
Added tests for checking encryption-decryption of the same ciphertext without changing parameters (3 times)
> Fix: Copy issue with ciphertext in FV scheme.

- test/workers/test_base.py
- test/workers/test_virtual.py
- test/workers/test_websocket_worker.py
Swaps out `whitelist` for a better term.
> Change `whitelist` to `allow_list`

- syft/frameworks/torch/he/fv/util/operations.py
- test/torch/tensors/test_fv.py
Closes #3683
Non-same size polynomials are shifted so that the Numpy can perform operations correctly. 
Added tests with operations on non same size polynomials.
> Update polynomial operations

- syft/frameworks/crypten/context.py
- test/crypten/test_context.py
To refer to crypten parties running on specific workers, we can do whether with the rank (int) of the party or the id (str) of the worker running the party, thus we needed a kind of translation mechanism between worker id and rank, but when workers involved in the computation happen to have duplicate ids, ranks get translated badly and the computation will fail badly. This PR raise an error when a computation is about to start with duplicates ids.
> Detecting duplicate worker IDs in crypten computation

- syft/workers/message_handler.py
in `syft/workers/message_handlers:respond_to_search()`, all pointers are wrapped before being returned. This should be the case only on `PointerTensor` objects, not only all pointers.
This causes a fail in SyferText where we need to exchange object pointers that are not tensors.
None
All existing tests
> Removed `wrap()` on non-tensor pointers in `respond_to_search()`

- syft/frameworks/crypten/__init__.py
- syft/frameworks/crypten/context.py
- syft/frameworks/crypten/message_handler.py
- test/crypten/test_context.py
Each CrypTen computation is identified using a CID (computation id), it might be different in different workers. Translation tables are indexed using CIDs. Global table and the CID of the running computation are stored under `syft.frameworks.crypten`, we assume that parties are separate processes and that CID is overwritten after process creation, which means that even if parties are running in the same machine, they won't manipulate the global CID concurrently.
`get_worker_from_rank` was also updated and I assumed that `syft.local_worker` is able to find all other workers using their id, please correct me if that's not the case.
Fixes #3516 
Fixes #3687
> New strategy for storing rank to id translation tables

- examples/experimental/FL Training Plan/Create Plan.ipynb
Fixes #3780 
```python
def set_model_params(module, params_list, start_param_idx=0):
""" Set params list into model recursively
"""
param_idx = start_param_idx
for name, param in module._parameters.items():
print('\t','name:', name, '\tparam_idx:', param_idx)
module._parameters[name] = params_list[param_idx]
param_idx += 1
for name, child in module._modules.items():
print(child, param_idx)
if child is not None:
param_idx = set_model_params(child, params_list, param_idx)
return param_idx
class Net(nn.Module):
def __init__(self):
super(Net, self).__init__()
self.fc1 = nn.Linear(784, 392)
self.fc2 = nn.Linear(392, 64)
self.fc3 = nn.Linear(64, 10)
def forward(self, x):
x = nn.functional.relu(self.fc1(x))
x = nn.functional.relu(self.fc2(x))
x = self.fc3(x)
return x
model = Net()
model_params = …
```
> Fixed bug in set_model_params() in Create Plan

- syft/workers/node_client.py
- syft/workers/websocket_client.py
Related to #3714 , we needed a mechanism to use a larger timeout when we know how much the computation will take. This PR gives the ability for experienced users to use a different timeout rather than the default which is 60 seconds.
> Customizable timeout in workers

- syft/frameworks/torch/he/fv/evaluator.py
- test/torch/tensors/test_fv.py
closes #3701  
Implemented negation operation of the FV scheme.
Accepts Ciphertext and returns negated value Ciphertext.
None
- Added tests which check the negated values from the operation.
> Negate operation of FV scheme

- pip-dep/requirements.txt
- syft/workers/node_client.py
Due to the need to support uploads for large models **_(>=200MB)_**, the approach used by the `serve_model` method has been modified. We changed the use of standard WebSockets messages to a well-known solution used for uploading large files on HTTP servers.
Fix [#23](https://github.com/OpenMined/PyGridNode/issues/23) 
- **requests_toolbelt**
```
import torch as th
from syft.workers.node_client import NodeClient
hook = sy.TorchHook(th)
node = NodeClient("ws://<node_address>")
traced_model = th.jit.load('large_traced_model.jit')
node.serve_model(traced_model,
model_id="myCustomModel",
allow_download=True,
allow_remote_inference=True)
```
> Fix grid model hosting for large models

- syft/frameworks/torch/he/fv/evaluator.py
- syft/frameworks/torch/he/fv/util/operations.py
- test/torch/tensors/test_fv.py
closes #3702
Implemented Subtraction operation of the FV scheme.
Can Subtract two ciphertexts or a plaintext from a ciphertext.
None
- Added tests which check the subtracted values from the operation.
> Implemented Subtraction operation of FV Scheme

- test/execution/test_translation.py
Fixed bug in implementation of `set_model_params()` in `test/exection/test_translation.py`. See #3780
> Fixed bug in set_model_params() in test_translation.py

- README.md
Fixes #3508.
When you install the ```jupyter notebook``` it will install the latest version, but there are some issues regarding this that are detailed [here](https://github.com/jupyter/notebook/issues/3397)
- Check the #3508 and validate that the notebook can be seen.
This PR should solve the problem with the notebooks.
> Update notebook/tornado versions

- syft/frameworks/torch/torch_attributes.py
- syft/generic/frameworks/attributes.py
- syft/generic/frameworks/hook/hook_args.py
- syft/generic/utils.py
- syft/test/__init__.py
- syft/workers/base.py
- test/generic/frameworks/test_attributes.py
This is an experimental tool which really helps reducing communication rounds. It doesn't use Plans and is only compatible with Python workers, which is a limitation for PySyft.
However it is very useful for the moment for crypto protocols, as it highly reduces the number of communication and doesn't require to contain only pytorch operations (for example I can make a call to a custom library or use numpy code)
> Introduce an experimental mechanism for remote exec on Python workers

- syft/exceptions.py
The method route_method_exception was previously having a much higher complexity of conditional statements. Hence, when checking it with Flake8 it was showing a C901 error. To resolve the problem I have simply reduced the use of the conditional statements. Closes #3429 
- Flake8 tests and PyTest were giving positive results for the changes.
> Reduced complexity for route_method_exception

- pip-dep/requirements.txt
- syft/frameworks/crypten/__init__.py
- syft/frameworks/crypten/hook/hook.py
- syft/frameworks/crypten/model.py
- test/crypten/test_context.py
- test/serde/msgpack/test_msgpack_serde_full.py
- test/serde/protobuf/test_protobuf_serde_full.py
- test/serde/serde_helpers.py
Define and use ```OnnxModels``` serialized models.
The parties know the model architecture and one of the parties has data that should be run through the model.
The local party does not have any idea about the architecture or the data.
The local party would only receive the result for the inference step.
- Added test to check the functionality
> Use OnnxModels for private inference

- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- syft/frameworks/torch/tensors/interpreters/autograd.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/frameworks/torch/tensors/interpreters/precision.py
This cleans code in handle_func_command and fix bugs due to variable overwriting for syft tensors, and to overloading functions in native.py
> Fix issues in handle_func_command in syft tensors

- syft/grid/clients/dynamic_fl_client.py
Namespace dynamic FL client routes. Added url prefix `dynamic` to the Dynamic FL client url.
Fixes https://github.com/OpenMined/PyGrid/issues/600
- Existing tests.
> Namespace dynamic_fl_client route

- pip-dep/requirements.txt
- syft/__init__.py
- syft/generic/object_storage.py
- syft/generic/pointers/object_pointer.py
- syft/messaging/message.py
- syft/workers/base.py
- syft/workers/message_handler.py
- test/generic/test_gc.py
- test/serde/serde_helpers.py
This will help reducing messages to remotely GC values.
> Add a parameter to batch all garbage collection calls every n seconds

- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- syft/frameworks/torch/tensors/interpreters/precision.py
- test/torch/tensors/test_additive_shared.py
This is a small cleaning PR
None
> Improve public mul and div for AST

- syft/frameworks/torch/mpc/securenn.py
- syft/frameworks/torch/nn/__init__.py
- syft/frameworks/torch/nn/functional.py
- test/torch/nn/test_functional.py
- test/torch/nn/test_nn.py
- test/torch/tensors/test_additive_shared.py
This is an optimisation of pooling and convolution layers which uses #3689. Basically it consists of decomposing conv & pool in 3 phases: a "pre" phase where all workers compute local stuff, a phase with communication, and a "post" phase where all workers compute local stuff.
> Add optimized versions of AvgPool, MaxPool and adaptive pooling

- src/syft/common/id.py
None
Notebook, create a VirtualMachine, and let it print the id of the newly created machine.
Previously it would print a random int, now it would print a UUID.
> use python uuid instead of random int for object ids

- syft/frameworks/torch/tensors/interpreters/autograd.py
- test/generic/test_autograd.py
`return self` in AutogradTensor's `+=` and `-=`.
Otherwise the tensor would be `None` and not usable afterwards.
Ran test_autograd.py
> autograd: return self for += and -=.

- syft/grid/clients/static_fl_client.py
PyGrid route is updated:
https://github.com/OpenMined/PyGrid/pull/668
Client is updated accordingly.
n/a
E2e run of static FL notebooks.
> Update static FL get-model route to retrieve-model

- syft/frameworks/torch/nn/__init__.py
- syft/frameworks/torch/nn/functional.py
- syft/frameworks/torch/tensors/interpreters/precision.py
- test/torch/tensors/test_additive_shared.py
Add Batchnorm and tests
Fix a bug in .var() for  evaluation on a specific dim
**NOTE** This implem will be improved with the current work on FALCON
> Add BatchNorm to AdditiveSharingTensor

- examples/tutorials/Part 09 - Intro to Encrypted Programs.ipynb
- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/frameworks/torch/tensors/interpreters/precision.py
- test/torch/tensors/test_additive_shared.py
This improves implementation of max and argmax, tests are improved as well
> Improve implementation of max and argmax

- pip-dep/requirements.txt
**4 Pillow vulnerabilities found in pip-dep/requirements.txt 2 days ago**
Remediation
Upgrade Pillow to version 7.1.0 or later. For example:
```
Pillow>=7.1.0
```
Always verify the validity and compatibility of suggestions with your codebase.
Details
CVE-2020-11538
moderate severity
Vulnerable versions: < 7.1.0
Patched version: 7.1.0
In libImaging/SgiRleDecode.c in Pillow through 7.0.0, a number of out-of-bounds reads exist in the parsing of SGI image files, a different issue than CVE-2020-5311.
CVE-2020-10177
moderate severity
Vulnerable versions: < 7.1.0
Patched version: 7.1.0
Pillow before 6.2.3 and 7.x before 7.0.1 has multiple out-of-bounds reads in libImaging/FliDecode.c.
CVE-2020-10379
moderate severity
Vulnerable versions: < 7.1.0
Patched version: 7.1.0
In Pillow before 6.2.3 and …
> Bump Pillow version in requirements.txt

- syft/frameworks/torch/he/fv/evaluator.py
- syft/frameworks/torch/he/fv/util/base_converter.py
- syft/frameworks/torch/he/fv/util/operations.py
- syft/frameworks/torch/he/fv/util/rns_tool.py
- test/torch/tensors/test_fv.py
Multiplication operation for FV scheme using RNS variant. The current implementation of a multiplication operation is not performing well during relinearization operation. So updating the operation with the RNS variant.
None
Tests already present for multiplication operation but added tests for internal methods.
> RNS variant multiplication operation for FV scheme.

- .github/workflows/tests.yml
- requirements.txt
- setup.cfg
- src/syft/core/common/uid.py
- src/syft/core/io/address.py
- src/syft/core/io/connection.py
- src/syft/core/io/virtual.py
- src/syft/core/node/common/node.py
- src/syft/core/node/common/service/child_node_lifecycle_service.py
- src/syft/core/node/common/service/heritage_update_service.py
- src/syft/core/node/common/service/msg_forwarding_service.py
- src/syft/core/node/common/service/node_service.py
- src/syft/core/node/common/service/obj_action_service.py
- src/syft/core/node/common/service/repr_service.py
- src/syft/core/node/device/client.py
- src/syft/core/node/device/device.py
- src/syft/core/node/network/client.py
- src/syft/core/node/vm/client.py
- src/syft/core/node/vm/vm.py
- src/syft/core/store/store_disk.py
- src/syft/decorators/syft_decorator_impl.py
This PR fixes some minor flake8 issues re-introduced allowing CI to pass, and adds support for both Python 3.7 and Python 3.6 with minimal changes.
The issue was discussed here:
https://github.com/OpenMined/PySyft/issues/3826
Changes required for each version are separated into their own commits.
None
This has been tested on MacOS with Python 3.8.5, Python 3.7.8 and Python 3.6.11, and additionally GitHub Actions CI.
> Support Python <3.8 #3826

- syft/grid/utils/autoscale/README.md
- syft/grid/utils/autoscale/gcloud.py
- syft/grid/utils/autoscale/test.ipynb
- syft/grid/utils/autoscale/test.py
- syft/grid/utils/autoscale/utils/tutorials/mnist/Fed.Learning MNIST [ Part-1 ] - Populate a Grid Network ( Dataset ).ipynb
- syft/grid/utils/autoscale/utils/tutorials/mnist/Fed.Learning MNIST [ Part-2 ] - Train a Model.ipynb
I have added startup-scripts and other necessary changes which will enable the autoscale API to automatically launch PyGrid servers(network and nodes). Now using the autoscale API can launch PyGird cluster(1 network + N nodes) with one function call or create a PyGrid network and add PyGrid nodes to it one at a time as per the requirement.
I have also added tests and an example tutorial training script for the demonstration of the same.
@hericlesme 
Issue #3099
None (New Feature)
- I have created test.py script and test.ipynb notebook to test the functionality of the features implemented 
- I have also modified the README.md with examples on how to use the functionality. 
- I have also modified a PyGrid tutorial to use this API for demonstration.
> Added functionality to launch PyGrid network and nodes upon creation of a cluster

- syft/__init__.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/frameworks/torch/tensors/interpreters/replicated_shared.py
- syft/frameworks/torch/tensors/interpreters/replicative_shared.py
- test/torch/tensors/test_replicated_shared.py
- test/torch/tensors/test_replicative_shared.py
This PR will implement the basic operations of the replicative secret sharing scheme in order to be able to implement falcon protocol
for more details: #3852 
Milestones:
> Replicated Sharing Tensor (RST): secret sharing, reconstruction, and linear operations

- syft/generic/utils.py
- syft/serde/compression.py
- syft/workers/base.py
- syft/workers/virtual.py
- test/generic/test_autograd.py
- test/workers/test_virtual.py
These are remaining few fixes and updates
> Refacto various little thing

- syft/grid/rtc/network.py
The `__repr__` method only generated a string and did not return it. I fixed it 😄 
Thank You!
> The `__repr__` on the `Network` class must return a `repr_str`

- syft/execution/placeholder.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/generic/abstract/object.py
- syft/generic/abstract/tensor.py
Classes that inherit `TensorObject` often use `hasattr(self, "child")`. So, I think it's good to abstract this.
Thank You!
> Create `has_child` method

- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- syft/frameworks/torch/tensors/interpreters/precision.py
- test/torch/tensors/test_additive_shared.py
> Add `argmin` and `min` method in AST

- syft/frameworks/torch/he/fv/ciphertext.py
- syft/frameworks/torch/he/fv/context.py
- syft/frameworks/torch/he/fv/decryptor.py
- syft/frameworks/torch/he/fv/encryption_params.py
- syft/frameworks/torch/he/fv/encryptor.py
- syft/frameworks/torch/he/fv/evaluator.py
- syft/frameworks/torch/he/fv/integer_encoder.py
- syft/frameworks/torch/he/fv/key_generator.py
- syft/frameworks/torch/he/fv/util/operations.py
- syft/frameworks/torch/he/fv/util/rlwe.py
- syft/frameworks/torch/he/fv/util/rns_tool.py
- test/torch/tensors/test_fv.py
For Relinearization operation, we need to perform modulus switching which requires the context chain to have context object with different coefficient modulus value.
None
All tests for components passing
> Update FV scheme to use context chain instead of single context object

- syft/frameworks/torch/tensors/interpreters/precision.py
- test/torch/tensors/test_precision.py
As pointed out in https://github.com/OpenMined/PySyft/issues/3958 modular operations over fixed precision tensors are broken. This PR overloads the mod operation over fixed precision tensors in [`syft/frameworks/torch/tensors/interpreters/precision.py`](https://github.com/arturomf94/PySyft/blob/d75a2ba0d4542faf1e5d019c00a9d77868f4d723/syft/frameworks/torch/tensors/interpreters/precision.py#L76) and adds a corresponding test in [`test/torch/tensors/test_precision.py`](https://github.com/arturomf94/PySyft/blob/d75a2ba0d4542faf1e5d019c00a9d77868f4d723/test/torch/tensors/test_precision.py#L40)
Closes: https://github.com/OpenMined/PySyft/issues/3958
> Overload mod operator for the fixed precision tensor

- examples/experimental/trask/Duet Experiments.ipynb
- examples/mock_apis/duet/Data Scientist Mock.ipynb
- src/syft/core/node/common/action/get_object_action.py
- tests/syft/grid/duet_test.py
In this PR I fixed a small bug which was preventing .get() serde to work correctly.
> tensor.send(duet) and ptr.get() both work with duet (with tests)

- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- syft/frameworks/torch/tensors/interpreters/precision.py
RuntimeError raised when a negative interger is entered in the `pow` as in pytorch.
> Raise RuntimeError when negative integers is entered in the `pow`

- examples/tutorials/Part 05 - Welcome to the Sandbox.ipynb
- Added a code cell to display the populated datasets on a worker
- Changed the initial search from boston housing tags to custom tags
- Added the boston housing dataset search at a later stage
Tested the code by running the entire code as a separate notebook.
> Make Sandbox Tutorial more Intuitive

- test/workers/test_websocket_worker.py
Key-size value is changed to 2048 to deal with issues raised by [tighter default security values in openssl configuration](https://wiki.debian.org/ContinuousIntegration/TriagingTips/openssl-1.1.1).
Closes https://github.com/OpenMined/PySyft/issues/3787
`test_websocket_worker.py` run OK with `CipherString = DEFAULT@SECLEVEL=2`.
> Increase key-size to 2048-bit keys in test_websocket_worker.py

- test/torch/tensors/test_fv.py
Just updated the BFV tests with smaller params for quicker results. 
reduced time on my machine from 329sec to 77sec.
None
> Refractor bfv tests for faster results

- syft/__init__.py
- syft/frameworks/torch/mpc/__init__.py
- syft/frameworks/torch/mpc/primitives.py
- syft/frameworks/torch/mpc/przs.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/frameworks/torch/torch_attributes.py
- syft/workers/base.py
- test/torch/mpc/test_crypto_store.py
- test/torch/mpc/test_przs.py
In the Correlated Randomness scenario, each worker will have 2 seeds (one generated locally, and one received from another worker).
For the moment this PR is WIP because I am thinking on an interface/best approach to generate random numbers remote using those generators.
Fixes #3898
- Running remote execution on the workers
- Added tests
> Add RNG for workers

- syft/frameworks/torch/tensors/interpreters/precision.py
- test/torch/tensors/test_precision.py
issue: https://github.com/OpenMined/PySyft/issues/3993
We can use reciprocal 150 times faster on average. Implementing division of AST with reciprocal can make existing very slow division much faster. In addition, many slow operations can be made very quickly.
This implementation referred to the implementation of CrypTen.
https://github.com/facebookresearch/CrypTen/blob/3c4e53aa4910117e4e136691cb09ea7a7e001029/crypten/mpc/mpc.py#L1029
```python
x = torch.tensor([1., 2., 3.]).fix_prec().share(bob, alice, crypto_provider=theo)
x.reciprocal().get().float_prec() # 27 seconds
x.reciprocal(method="nr").get().float_prec() # 0.18 seconds
x.reciprocal(method="log").get().float_prec() # 0.31 seconds
```
- Describe the tests that you ran to …
> Fast FixedPrecisonTensor Reciprocal Method (150x faster)

- syft/frameworks/torch/tensors/interpreters/precision.py
It seems that the reciprocal method using "NR" gives results that are above the threshold limits.
This PR is using the division method to compute reciprocal.
- Tests are passing
> Use division for sigmoid

- scripts/build_proto.sh
Could not find an issue to link this to.
Give a message if the ```protoc``` file is not found on the system.
No dependencies are affected
- Running ```pre_commit.sh``` without ```protoc``` installed.
> Throw error if protoc not found

- docs/conf.py
- src/syft/__init__.py
- src/syft/ast/klass.py
- src/syft/core/io/location/group/registry.py
- src/syft/core/io/route.py
- src/syft/core/node/common/node.py
- src/syft/core/node/common/service/heritage_update_service.py
- src/syft/core/node/common/service/msg_forwarding_service.py
- src/syft/core/node/device/client.py
- src/syft/decorators/typecheck.py
- src/syft/lib/generic.py
Especially, "message" had been replaced by "old_message" at different places.
> Fix some typos in docstring

- pip-dep/requirements.txt
Keep track of the syft-proto version and not the commit.
- There are no error messages when sending stuff to workers.
> Fix syft-proto version

- syft/frameworks/torch/he/fv/integer_encoder.py
Just added an error message for the case when the bfv scheme is used with non-interger values.
None
> Error message if non integer value used with BFV scheme

- syft/frameworks/torch/he/fv/encryption_params.py
Update the param id generation for generating hash ids for context object in context chain.
Using `black2b` hash from `hashlib`. 
for details: https://blake2.net/
FV module
All tests should pass
> Add black2b hash function to generate param_id for bfv scheme

- src/syft/core/common/message.py
- src/syft/lib/python/bool.py
Add docstring to `SyftMessage` and `SignedMessage`.
> Add docstring to `SyftMessage` and `SignedMessage`

- CONTRIBUTING.md
Corrects typo in section that mentions folder `pip-deps` to `pip-dep`. Would resolve Issue #4575 
None
Tested via GitHub in the browser
> fix: Corrects folder name pip-deps to pip-dep

- src/syft/ast/globals.py
- src/syft/core/node/common/action/function_or_constructor_action.py
- src/syft/lib/__init__.py
- src/syft/lib/python/__init__.py
- src/syft/lib/torch/__init__.py
- src/syft/lib/torch/allowlist.py
- tests/syft/core/node/common/action/function_or_constructor_action_test.py
In case we create a new object remotely, we set no permission for it.
This PR adds a list of default read permissions in case there is no permissions added (there is not args/kwargs).
The list might be extended.
Currently, we use only ```torch.cuda.is_available``` (for showcase).
It might impose a **security risk**. Cuda machine vs non-cuda machine, it might mean that a machine has more data?
* Added tests
> Fix get permissions

- examples/tutorials/Part 01 - The Basic Tools of Private Deep Learning.ipynb
At the end of the notebook for part 1 of the tutorial, there is a link which reads "Good first issues". This link doesn't work as it assumes that the label for a good first issue doesn't have a mortar board at the end. I have changed the URL to include the mortar board so that the link now works.
None
That the current link doesn't work can be tested by clicking it, you will find no issues with that search.
I have tested the link from inside a running notebook and it correctly showed the current good first issues.
> Corrected good first issue link in tutorial part 1.

- syft/frameworks/torch/fl/dataset.py
- syft/frameworks/torch/hook/hook_args.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/generic/frameworks/hook/hook.py
- syft/generic/object_storage.py
- syft/generic/pointers/pointer_tensor.py
- test/generic/pointers/test_pointer_tensor.py
- test/torch/federated/test_dataset.py
This provides a mechanism to set hook functions (during pytorch backprop) on remote tensors and models.
This allows to register torch hooks on remote tensors. Such operation
is tricky because you can't really send the hook function to a remote
party, as python functions are not serializable within PySyft. So you
need to keep it attached to the PointerTensor.
On the other hand, the PointerTensor cannot watch for gradient update
or be triggered natively by torch when backpropagation happens. That's
why we actually remotely set a hook that we call a callback hook whose
function is only to call back the pointer during the backpropagation
to effectively run the hook function.
So the workflow is: the remote hook is triggered by pytorch, a message
is sent back to the pointer owner which has the …
> Remote execution of torch hooks

- syft/frameworks/torch/fl/utils.py
The current version of `federated_avg()` has following issues:
- The sum of model parameters would be affected by the non zero initial model (#3863)
- Fails when aggregated models are located on GPU (#3863)
- Only includes the parameters in `named_parameters()`, whereas those of in `_buffers` and `_modules` are left.
I imported two new packages in my editing:
- copy
- functors
However, they are both native python packages.
- I passed the test cases in `test/torch/federated/test_utils.py`
- I passed the test case modified from #3863
> Fixing several issues in federated_avg()

- syft/generic/pointers/object_pointer.py
- syft/generic/pointers/pointer_tensor.py
- syft/messaging/message.py
- syft/workers/base.py
- syft/workers/message_handler.py
- test/serde/serde_helpers.py
- test/workers/test_virtual.py
Add get_copy argument in ` get ` and related methods for getting objects without removing the remote object.
This was a todo listed in get() method (https://github.com/OpenMined/PySyft/blob/1ead29ce04d6ced3e08c3bd2c48c66851ffa50cf/syft/generic/pointers/object_pointer.py#L249)
This will enable persisting remote tensors and PySyft objects.
This is required in SyferText to host permanent Pipelines and SyferText objects on Pygrid Nodes
None
No tests added
> Add get_copy argument in  get()  and related methods.

- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- test/serde/serde_helpers.py
Reduce the size of the AST message - when sending it.
Take advantage of the fact that the pointers already have the location -> no need to serialize the workers.
Also, take advantage of the fact that the garbage collect value is the same for all the shares.
How the serialization looked:
**Before**:
```
(Pdb) p tensor_tuple
(55209114651, (5, (b'18446744073709551616',)), (5, (b'snn',)), b'long', (5, (b'me',)), (0, (((5, (b'alice',)), (25, (50814691011, 47632598781, (5, (b'alice',)), None, (11, (3,)), False, None, None))), ((5, (b'  bob',)), (25, (64630107868, 8594578436, (5, (b'bob',)), None, (11, (3,)), False, None, None))), ((5, (b'charlie',)), (25, (5588846714, 53068487497, (5, (b'charlie',)), None, (11, (3,)), False, None, None))))),   {'alice': False, 'bob': False, 'charlie': False}) …
```
> Reduce length of AST message

- syft/execution/action.py
- syft/frameworks/crypten/__init__.py
- syft/frameworks/crypten/message_handler.py
- syft/frameworks/torch/dp/pate.py
- syft/frameworks/torch/he/fv/context.py
- syft/frameworks/torch/linalg/operations.py
- syft/frameworks/torch/mpc/falcon/falcon_helper.py
- syft/frameworks/torch/mpc/fss.py
- syft/frameworks/torch/mpc/primitives.py
- syft/frameworks/torch/mpc/przs.py
- syft/frameworks/torch/mpc/securenn.py
- syft/frameworks/torch/nn/conv.py
- syft/frameworks/torch/nn/functional.py
- syft/frameworks/torch/nn/pool.py
- syft/frameworks/torch/tensors/interpreters/additive_shared.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/frameworks/torch/tensors/interpreters/precision.py
- syft/generic/frameworks/hook/hook_args.py
- syft/generic/frameworks/remote.py
- syft/generic/pointers/multi_pointer.py
- syft/generic/pointers/pointer_plan.py
- syft/serde/msgpack/native_serde.py
- syft/workers/base.py
- syft/workers/message_handler.py
- test/generic/pointers/test_dataset_pointer.py
- test/generic/test_string.py
- test/torch/nn/test_nn.py
- test/workers/test_virtual.py
Changed all assert blocks to if/raise block. This is important as assert checks can be globally disabled with the -O and -OO flags, as well as the PYTHONOPTIMIZE env var. This PR is against an open issue, [Don't use `assert` for non-debugging data validation](https://github.com/OpenMined/PySyft/issues/3480) 
For now, commented out the assert blocks and wherever error statement wasn't present, added an error statement based on understanding I could make of it 
- ran the standard `python setup.py test`, which was a success
> changed all asset to if/raise to prevent disable of assert during PYTHONOPTIMISE env

- src/syft/grid/duet/__init__.py
The tests are sometimes breaking due to pytest-xdist and threaded parallel tests.
This PR is to fix the issue.
None
CI
> Fixing parallel threaded tests and nest_asyncio.apply()

- benchmarks/frameworks/torch/mpc/scripts/benchmark_ast.py
- syft/frameworks/torch/tensors/interpreters/native.py
- syft/generic/pointers/pointer_tensor.py
- test/torch/tensors/test_additive_shared.py
C408 causes the test to fail in the current CI test. I solved this problem.
> Fix Flake8 C408 Error

- src/syft/lib/python/__init__.py
There was an inconsistency between the string paths used for syft.python and the real __module__ of these types when building the ast.
I'm not sure this is the best way to do it. The other way I've thought about is to replace the paths from "syft.lib.python.Bool" to "syft.lib.python.bool.Bool" for instance.
- This fixes an issue when trying to display the duet store when in contains a Bool in the MNIST duet notebooks.
> Override __module__ for syft types

- src/syft/ast/klass.py
- src/syft/core/node/common/action/garbage_collect_object_action.py
- src/syft/core/node/common/action/get_object_action.py
- src/syft/core/node/common/action/save_object_action.py
- tests/stress/gc_test.py
- tests/syft/core/common/serializable_test.py
- tests/syft/core/common/uid_test.py
- tests/syft/grid/duet_test.py
- tests/syft/lib/torch/tensor/tensor_remote_and_serde_test.py
Currently, we use the id of the object as a way to register an object as a remote location.
This brings some advantages, but also some downsides.
The advantage is that we will record only once if we send that item multiple times.
```
ptr = x.send(alice)
ptr = x.send(alice)
```
Since we send the same object, we keep only 1 instance of that object on alice.
The problem comes (in the above example) when we delete ```ptr``` - the second assignment will generate a call to the ```__del__``` method from ```PointerTensor``` (this call can come at any time).
If we have the same id, we might execute the second statement and after that, we delete the first ```ptr``` --> in this case we will delete the underlying data, where ```ptr``` points to.
With this PR we generate another UUID  for each sent …
> Use id_at_location

- INSTALLATION.md
- examples/tutorials/advanced/Federated Recurrent Neural Network.ipynb
- Fixed Recurrent Neural Network training on local and remote websockets in response to issue #4656 
- Currently, it is impossible to install PySyft in Windows because PyTorch 1.4.0 is not available. Added a workaround to install PySyft on Windows machines in INSTALLATION.md.
No additional dependencies affected
- Working locally with websockets
- Test cases passing
- [] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
> Fix for RNN training on websockets, added instructions for Windows workaround installation

- src/syft/grid/duet/__init__.py
Don't start counter thread if stdout doesn't have parent_header
> Don't start counter thread if stdout doesn't have parent_header

- syft/generic/object_storage.py
- test/generic/pointers/test_pointer_tensor.py
Fixes #4616
When execute `pointer_tensor.svd()`, it returns 4 pointers, while what is expected is 3. And the 3rd one points to nothing. That's issue #4616.
I found that the reason is that there is bug in function `def de_register_obj()`. This function has a line `if hasattr(obj, "id")`, which is useless when `obj` is of type TorchTensor. Why it is useless is because a TorchTensor object always has `id` property, as you can see in it's definition. So I change the condition to be checking `has_attr = hasattr(obj, "_id") if isinstance(obj, torch.Tensor) else hasattr(obj, "id")`.
And why this bug is the key to #4616? Because `hasattr(obj,"id")` will run `obj.id()`. And in `obj.id()`, an `id` will be created for obj. And that `id` created is the 3rd poiner, which points to nothing.
List any …
> debug pointer.svd (OpenMined#4616)

- CONTRIBUTING.md
- setup.cfg
Makes the need for pytest-xdist package more clear to resolve the following error:
```
$ pytest -m fast -n auto
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
inifile: /mnt/d/github/PySyft/setup.cfg
rootdir: /mnt/d/github/PySyft
```
None
Locally and CI
> Added pytest-xdist to setup.cfg testing and updated CONTRIBUTING.md

- src/syft/lib/misc/union.py
- src/syft/lib/python/namedtuple.py
- src/syft/lib/torch/allowlist.py
- tests/syft/lib/allowlist_test.json
- tests/syft/lib/allowlist_test.py
- Added item, max, median, min, stride with Union types
- Added comments about List types which are really Tuples
- Added torch.return_types.* namedtuple types for max, median and min
- Fixed bug in UnionGenerator where short name was cached not fqn
None
Locally and CI
> Added Union support to allowlist_test

- examples/duet/mnist/MNIST_Syft_Data_Owner.ipynb
- examples/duet/mnist/MNIST_Syft_Data_Scientist.ipynb
- src/syft/__init__.py
- Fix issue with logging bool being backwards
- Added some comments and included in MNIST to expose to users
None
Jupyter Notebooks
> Fix issue with logging bool being backwards

- src/syft/ast/__init__.py
- src/syft/ast/module.py
- tests/syft/ast/util_test.py
- tests/syft/lib/torch/client_torch_test.py
- Fixed issue with AST Cache on python types directly using add_attr
- Added tests for torch and SyPrimitive cache types to prevent this
None
Locally and CI
> Fixed issue with AST Cache on python types directly using add_attr

- src/syft/core/node/abstract/node.py
- src/syft/core/node/common/node.py
- src/syft/core/node/common/service/auth.py
- tests/syft/core/node/common/service/auth_test.py
Extend `/syft/core/node/common/node` and `syft/core/node/common/service/auth` to include the roles of Administrator and Compliance officer. This change is needed to make available the same fine-grained access control expected in PyGrid.
- New unit tests in `tests/syft/core/node/common/service/auth_test.py`
> Add admin and compliance officer to node's auth scheme

- src/syft/core/pointer/pointer.py
**Description**
Fixes #4913 
I replaced the word 'request_queue' from sample code with 'requests'. The sample code now **does not throw** the Attribute Error:
AttributeError: 'DomainClient' object has no attribute 'request_queue'
**Affected Dependencies**
None
**How has this been tested?**
I ran the updated code on jupyter notebook
> Fixed Sample Code

- syft/frameworks/torch/hook/hook.py
This adds a new `__str__()` function to `torch.nn.Module` which adds a location printout to every shared model. In the case of an SMPC-encrypted model it outputs all the different locations. Should serve as a small convenience function.
None.
- Tested the output of normal tensors, a remote tensor, a SMPC-encrypted tensor, a normal nn.Module, a nn.Module with FixedPrecisionTensor weights, a remote nn.Module and an SMPC-encrypted nn.Module.
> added location and locations printouts to remote and SMPC-encrypted nn.Module

- .github/workflows/benchmark_actions.yml
Discontinued support for Continuous benchmark actions for pull_requests.
Currently, as the new PRs are failing this is a quick fix for #4927
None
> Quick Fix:  discontinued support for Continuous benchmark actions for pull_requests

- src/syft/core/io/address.py
- tests/syft/core/io/address_test.py
This PR adds more unit tests for `src/syft/core/io/address.py` and is related to [Issue 4805](https://github.com/OpenMined/PySyft/issues/4805) for improving test coverage.
`address.py`'s coverage improved from 64% to 96%:
```
src/syft/core/io/address.py                         164      7    96%   25, 100, 104, 108, 118, 351-352
```
`src/syft/core/io`'s coverage improved from 70% to 82.27%:
```
----------- coverage: platform linux, python 3.8.6-final-0 -----------
Name                                              Stmts   Miss  Cover   Missing
-------------------------------------------------------------------------------
src/syft/core/io/__init__.py                          0      0   100%
src/syft/core/io/address.py                         164      7    96%   25, 100, 104, 108, 118, …
```
> Test Coverage: Improve test coverage for syft.core.io.address

- .github/workflows/merge_tests.yml
Fixing issue with Windows in CI and pytest not available immediately
- See here: https://github.com/OpenMined/PySyft/runs/1603537525
None
CI
> Fixing issue with Windows in CI and pytest not available immediately

- .github/workflows/merge_tests.yml
- Benchmark plugin on the slow tests is probably causing the $? 137 OOM
> Re-enabled windows on merge test CI and added -p no:benchmark

- .github/workflows/merge_tests.yml
- tests/benchmarks/pytest_benchmarks/bench_test.py
- tests/conftest.py
- Skip benchmarks on slow and fast tests on merge
- Disabled Windows again
> Skip benchmarks on slow and fast tests on merge

- src/syft/lib/python/tuple.py
- tests/syft/lib/python/tuple/tuple_test.py
Add the possibility to have the ```hash``` code over our own designed tuples.
The ```Tuple``` class from ```Python```.
- Added a test in the Tuple test file
> Add tuple hash

- src/syft/lib/torch/module.py
- tests/syft/lib/torch/module_test.py
- syft.lib.torch.Module send was failing because load_state_dict was unable to load the result from sd_ptr.get.
- added some tests for syft.lib.torch.Module.
- the send/get flow cannot retrieve the gradients, since load_state_dict breaks the computational graph. ref: https://discuss.pytorch.org/t/loading-a-state-dict-seems-to-erase-grad/56676
- removed some duplicate code.
fixes https://github.com/OpenMined/PySyft/issues/5002
> Model get() not preserving parameters

- src/syft/ast/klass.py
- tests/syft/lib/allowlist_test.py
Preventing exception race condition on Windows CI from failing tests.
```
2021-01-20T06:18:05.0609414Z ______________ ERROR collecting tests/syft/lib/allowlist_test.py ______________
2021-01-20T06:18:05.0610098Z tests\syft\lib\allowlist_test.py:210: in <module>
2021-01-20T06:18:05.0610747Z     file_stat = os.stat(SUPPORT_FILE_PATH)
2021-01-20T06:18:05.0611766Z E   FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\a\\PySyft\\PySyft\\allowlist_test_support_3.6_1.6.0_windows.jsonl'
```
See:
https://pipelines.actions.githubusercontent.com/tPFNPqeRbvWdN0L3FU84cUvH4mGjAPQ3yYz8CFZWN08ePzUDwG/_apis/pipelines/1/runs/9698/signedlogcontent/40?urlExpires=2021-01-20T06%3A20%3A17.6176942Z&urlSigningMethod=HMACV1&urlSignature=js2f2DxdMZcCq%2FQIAt%2BeV6Wzd%2BHQLPwKm0ZB8AJZHfM …
> Allowlist Test Fix

- src/syft/ast/klass.py
- tests/syft/core/pointer/pointer_test.py
This may close #5052 .
**Features this PR fix:**
- `.tag` can be used to attach tags to object
- call `.tag("tag1")`, then `.send` without `tags` passed in: "tag1" will be used.
- call `.tag("tag1")`, then `.send` with `tags=["tag2"]` passed in: "tag2" will be used.
- similar thing happens with `.describe`
No
- test functions are added in `tests/syft/core/pointer/pointer_test.py`
- `test_tags`
- `test_description`
> fix .tag and .describe

- src/syft/ast/globals.py
- src/syft/core/node/common/client.py
- src/syft/lib/__init__.py
- src/syft/lib/opacus/__init__.py
- src/syft/lib/openmined_psi/__init__.py
- src/syft/lib/pydp/__init__.py
- src/syft/lib/sympc/__init__.py
- src/syft/lib/tenseal/__init__.py
- src/syft/lib/util.py
- tests/syft/ast/functionality_test.py
What changes this PR introduces:
* removes the ```add_attr``` from the client (I think only the things from ast should have the ```add_attr``` method)
* create a ```generic_update_ast``` and the 3rd party libraries will only partially apply that generic function -- to bind the ```lib_name``` and the ```create_as```
* AST Part of our codebase
- Library tests
> Move the generic update to util

- src/syft/core/store/__init__.py
Minor patch to ensure the Dataset class is made available once the syft package has been built.
- Built syft and made sure the class can now be imported.
> Expose dataset module within package

- CONTRIBUTING.md
While setting up PySyft for development on my Windows laptop, figured out by community help, the extra step needed in installing the package dependencies. The PR adds that information in the setup section.
None
- I followed these instructions to setup my environment.
> added windows script step in dependency installation

- src/syft/core/common/event_loop.py
When running in a Python interactive console, pressing CTRL + D should cancel the interactive console.
This was not happening because the ```run_forever``` call was never stopped.
This was happening because the ```stop``` call should be done in a threadsafe manner ([reference](https://stackoverflow.com/questions/40143289/why-do-most-asyncio-examples-use-loop-run-until-complete)
- ```python + import syft + CTRL-D``` (should close the console)
> Add threadsafe stop

- tests/syft/lib/python/dict/dict_test.py
This time I run: 
`pytest -m 'fast or slow' --no-cov -n auto`
as @madhavajay suggest, and was raised 4116 warnings, with this smalls changes that I made the warnings decreased to 24 warnings.
What I did was to change the direct …
> Issue 5075 - Investigate pytest warnings

- src/syft/grid/messages/association_messages.py
- src/syft/grid/messages/dataset_messages.py
- src/syft/grid/messages/group_messages.py
- src/syft/grid/messages/infra_messages.py
- src/syft/grid/messages/request_messages.py
- src/syft/grid/messages/role_messages.py
- src/syft/grid/messages/setup_messages.py
- src/syft/grid/messages/tensor_messages.py
- src/syft/grid/messages/user_messages.py
- tests/syft/lib/python/complex/complex_test.py
Fixing dev by removing syft_decorator from pygrid code.
None
Local and CI
> Removing @syft_decorator from pygrid code

- .github/workflows/merge_tests.yml
Using the same improved cache hash for python and torch versions in the `merge_tests.py`.
> Updated pip cache in merge_tests.yml thanks to @Borda

- src/syft/lib/python/namedtuple.py
- tests/syft/lib/python/namedtuple/namedtuple_test.py
- Fixing issue with namedtuple type resolution
- Added a test for .qr which would have failed before this fix
None
Locally and CI
> Fixing issue with namedtuple type resolution

- .github/workflows/merge_tests.yml
- .github/workflows/pr_tests.yml
- requirements.torch.txt
- requirements.txt
With 1.7.1 about to be added and the impending 1.8 release of Torch we will be dropping some older versions in our CI.
Technically they should still work but we will stop testing them on every single commit to save on some CI resources and should eventually remove them from the officially supported version matrix.
- Removing torch 1.4.0, 1.5.0 and 1.5.1 from CI
- Code is still there but we won't test these versions in CI for now
None
CI
> Removing torch 1.4.0, 1.5.0 and 1.5.1 from CI

- src/syft/core/node/domain/domain.py
- src/syft/grid/duet/__init__.py
- src/syft/logger.py
Logging was broken due to Duet print changing to log with `end` param.
None
Locally
> Fix broken logging

- src/syft/lib/sympc/session_util.py
- src/syft/lib/tenseal/context.py
When we send a session across multiple parties we should not create a new instance of the data store.
Fixes [this](https://github.com/OpenMined/SyMPC/issues/63) issue.
> CryptoStore no init in serialize function

- requirements.libs.txt
- tests/conftest.py
Moves back to main repo for the SyMPC library now that torch 1.8 and python 3.9 are working.
None
CI
> Moved sympc back to main repo

- src/syft/lib/sympc/__init__.py
Hide both eps and delta using the ```spdz_mask``` function.
Don't return the primitives anymore.
- The tests are passing in SyMPC
> Add spdz mask SyMPC

- src/syft/util.py
Fixes #5304 
Changes `get_root_data_path` in utils to use `HOME` dir that should work cross-platform.
Changed the data directory previously created as `..pysyft/data` to `~/.syft/data`
None
Ran the function independently and it accomplishes the required task. 
Tested on `Linux` and according to [this](https://docs.python.org/3/library/pathlib.html#concrete-paths) should work cross-platform.
> changed get_root_data_path to use HOME dir

- tests/syft/lib/allowlist_test.json
- Fixed issue with untested torch.Tensor ops
- __len__ added
- size and shape ignored for now as they are used remotely until serde
> Fixed issue with untested torch.Tensor ops

- src/syft/lib/python/__init__.py
- src/syft/lib/python/collections/ordered_dict.py
- src/syft/lib/python/dict.py
- tests/syft/lib/python/dict/dict_test.py
Treat the case when we have a Tensor in the Ordered Dict (is the same fix as the one with the Dict).
- Create a remote OrderedDict with a tensor as a value
> Order dict __getitem__ fix

- src/syft/core/common/environment.py
Suppress spurious warning on google colab, the warning was generated to check for notebook version being 6 or higher but is not required on google colab.
fixes #5315 
None
This has been tested on a sample google colab notebook using the following code
``` python
%%capture
import sys
if "google.colab" in sys.modules:
branch = "fix-issue-#5315"    # change to the branch you want
! git clone --single-branch --branch $branch https://github.com/ArtistBanda/PySyft.git
! cd PySyft && ./scripts/colab.sh      # fixes some colab python issues
sys.path.append("/content/PySyft/src") # prevents needing restart
! pip install syft
import syft as sy 
```
for the above code no warning will be generated but on the current dev branch it would throw the following warning 
```
Exception: Your Jupyter Notebook …
```
> Suppress spurious warning on google colab

- src/syft/lib/python/__init__.py
- src/syft/lib/python/collections/ordered_dict.py
- tests/syft/lib/python/collections/ordered_dict/ordered_dict_sanity_test.py
- tests/syft/lib/python/collections/ordered_dict/ordered_dict_serde_test.py
- tests/syft/lib/python/collections/ordered_dict/pointer_test.py
- tests/syft/lib/python/dict/dict_serde_test.py
This may close #5341 .
- dict_serde_test.py::test_iterator_methods
- ordered_dict_serde_test.py::test_iterator_methods
> fix supporting Dict/OrderedDict.items/keys/values

- src/syft/core/pointer/pointer.py
- tests/syft/core/plan/plan_test.py
- tests/syft/core/pointer/pointer_test.py
Fixes issue #5364 
Pointer is invalidated if `.get()` is called once.
None
``` python
client = sy.VirtualMachine().get_root_client()
int_ptr = client.syft.lib.python.Int(0)
result = int_ptr.get() # delete_obj = True by default
int_ptr.get()
```
Raises a reference Error in the second call and preventing a network call.
> Raise Reference error to prevent spurious network call

- tests/syft/core/fl/model-centric/mcfl_create_execute_plan_test.py
Trivial change in order of arguments in MCFL MNIST demo training plan. 
This is to make less changes in existing worker demo apps.
> Swap batch_size and lr args in MCFL MNIST demo training plan

- src/syft/core/remote_dataloader/remote_dataloader.py
- src/syft/lib/pandas/__init__.py
- Removed pandas read_csv from AST and DataLoader 
None
Locally and CI
> Removed pandas read_csv from AST and DataLoader

- src/syft/lib/sympc/session_util.py
Part of https://github.com/OpenMined/SyMPC/pull/129 for https://github.com/OpenMined/SyMPC/issues/66
SyMPC
Ran the tests for PySyft using this code on my environment (Python 3.8.5)
> Add session to globals during deserialize

- tests/syft/core/fl/model-centric/mcfl_create_execute_plan_test.py
- Updated Syft to use new GridClient endpoint for setup
- Added more print debugging for failure case
- Requires a fix on the Grid Side
This is waiting on: https://github.com/OpenMined/PyGrid/pull/852
PyGrid Integration Tests
CI
> Fixes PyGrid Integration Tests

- .github/workflows/syft-version_tests.yml
- README.md
- packages/syft/CONTRIBUTING.md
- packages/syft/docs/installing.rst
- packages/syft/examples/duet/README.md
- packages/syft/examples/private-ai-series/duet_basics/Duet_Basics_Data_Owner.ipynb
- packages/syft/examples/private-ai-series/duet_basics/Duet_Basics_Data_Scientist.ipynb
- packages/syft/examples/private-ai-series/duet_basics/exercise/Exercise_Duet_Basics_Data_Owner.ipynb
- packages/syft/examples/private-ai-series/duet_fl/Duet_FL_1_Data_Owner.ipynb
- packages/syft/examples/private-ai-series/duet_fl/Duet_FL_2_Data_Owner.ipynb
- packages/syft/examples/private-ai-series/duet_fl/Duet_FL_Data_Scientist.ipynb
- packages/syft/examples/vertical-learning/advanced/MNIST/DO.ipynb
- packages/syft/examples/vertical-learning/advanced/MNIST/DS.ipynb
- packages/syft/setup.cfg
- packages/syft/src/syft/lib/python/dict.py
- Removed references to Python 3.6, testing and support
- Removed older Torch versions from the support matrix
Python 3.6 is gone.
Locally and CI
> Removed references to Python 3.6, testing and support

- packages/syft/tests/syft/lib/pandas/categorical_test.py
- packages/syft/tests/syft/lib/pandas/pandas_test.py
Updated tests to check the behavior of ordered `pd.Categorical` object in ser/de and added test for  `sort_values`.
> Added test for ordered pd.categorical

- .github/workflows/grid-tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- packages/grid/apps/domain/Dockerfile
- packages/grid/apps/domain/poetry.lock
- packages/grid/apps/domain/pyproject.toml
- packages/grid/apps/network/Dockerfile
- packages/grid/apps/network/poetry.lock
- packages/grid/apps/network/pyproject.toml
- packages/grid/apps/worker/Dockerfile
- packages/grid/apps/worker/poetry.lock
- packages/grid/apps/worker/pyproject.toml
- packages/syft/examples/hyperledger-aries/requirements.txt
- packages/syft/src/syft/lib/pydp/__init__.py
- Updating default python version from 3.8 to 3.9 in CI, poetry and Docker
CI and Docker containers
Locally and in CI
> Updating default python version from 3.8 to 3.9 in CI, poetry and Docker

- .github/workflows/syft-security.yml
- Revert CI Action for Snyk to 3.8 since 3.9 not supported yet
> Revert CI Action for Snyk to 3.8 since 3.9 not supported yet

- packages/syft/src/syft/ast/__init__.py
- packages/syft/src/syft/ast/denylist.py
- packages/syft/src/syft/lib/pandas/__init__.py
Adding denylist for syft to explicitly deny methods and classes.
This will help us tackle security issues that may arise on moving syft libs support out of syft.
- Manually
> [Redback] Denylist for Syft

- packages/syft/src/syft/lib/sympc/rst_share.py
- packages/syft/src/syft/lib/sympc/session_util.py
- packages/syft/src/syft/lib/sympc/share.py
During de serialization of tensors, we use the session config, since we are working with multiple share values, we require the config value during deserializaiton, so the deserialization is refactored.
None
SyMPC Tests.
> Modified deserialization to use share config.

- packages/syft/src/syft/core/tensor/autograd/backward_ops/abs.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/add.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/argmax.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/argmin.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/argsort.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/clip.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/copy.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/dot.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/getitem.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/invert.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/mul.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/op.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/pow.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/repeat.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/reshape.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/resize.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/rpow.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/rshift.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/sort.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/sub.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/sum.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/transpose.py
- packages/syft/src/syft/core/tensor/autograd/backward_ops/truediv.py
- packages/syft/src/syft/core/tensor/autograd/tensor.py
Fixed 75 out of 128 initial linting errors that were found for core/tensor/autograd.
43 of the remaining 53 pertain to types that are incompatible between a class method and its corresponding method in the superclass. This is happening with 2 super classes in particular:
**1. AutogradTensor & PassthroughTensor**
`packages/syft/src/syft/core/tensor/autograd/tensor.py:83: error: Return type "AutogradTensorAncestor" of "__abs__" incompatible with return type "PassthroughTensor" in supertype "PassthroughTensor"`
**2. Many of the backward_ops and the Op superclass**
`packages/syft/src/syft/core/tensor/autograd/backward_ops/invert.py:11: error: Signature of "forward" incompatible with supertype "Op"`
No new dependencies were needed, nor old ones removed
- Describe the tests that you ran to …
> [W.I.P.] Fixing linting errors in Autograd

- .github/workflows/syft-version_tests.yml
- packages/syft/tests/syft/core/node/node_test.py
Fixed weird issue with test_known_child_nodes failing in CI
Nightly version tests
CI and Locally
> Fixed weird issue with test_known_child_nodes failing in CI

- packages/syft/proto/lib/sympc/replicatedshared_tensor.proto
- packages/syft/src/syft/lib/sympc/rst_share.py
- packages/syft/src/syft/proto/lib/sympc/replicatedshared_tensor_pb2.py
Added numpy support to ReplicatedSharedTensor, as torch does not support unsigned integers(32,64 bit).
.
Tested Locally.
> Added numpy support to ReplicatedSharedTensor

- packages/syft-libs/pyscaffoldext-syft-support/src/pyscaffoldext/syft_support/script.py
- packages/syft-libs/pyscaffoldext-syft-support/src/pyscaffoldext/syft_support/templates/update_py.template
- packages/syft-libs/pyscaffoldext-syft-support/src/pyscaffoldext/syft_support/templates/update_sh.template
If a class is imported several times, to support long/short import paths we add all these paths to the allowlist, however, it becomes more tedious if we were to add return_type for all these paths (which would be the same). To resolve this we check the base module of the class and reflect the changes to all other class references.
For instance,
```json
"classes": ["mypkg.A", "mypkg.b.A", "mypkg.b.B", "mypkg.subpkg.a.A"]
```
here, `"mypkg.A", "mypkg.b.A"` refer to the base class ` "mypkg.subpkg.a.A"` and return_type fixes for `mypkg.subpkg.a.A` can be reflected in others.
- locally on sample lib
> Redback | Support Short Long Path

- packages/grid/scripts/cron.sh
- packages/grid/scripts/redeploy.sh
- Split cron into redeploy
- Added code to check container hash as a second redeploy check
> Split cron into redeploy

- packages/grid/scripts/redeploy.sh
Make redeploy.sh only run once at a time
> Make redeploy.sh only run once at a time

- .github/workflows/stack-integration_tests.yml
Fixing docker image cache and adding stack tests to dev PRs
> Fixing docker image cache and adding stack tests to dev PRs

- packages/syft/src/syft/core/tensor/__init__.py
- packages/syft/src/syft/core/tensor/passthrough.py
- packages/syft/src/syft/core/tensor/smpc/mpc_tensor.py
- packages/syft/src/syft/core/tensor/smpc/share_tensor.py
- packages/syft/tests/syft/core/tensor/smpc/smpc_tensor_test.py
Implementation of Numpy Methods on MPCTensor which performs it on the underlying tensor
Implemented Ops:
> MPCTensor : Numpy Hook Methods

- packages/syft/src/syft/core/common/serde/serialize.py
- packages/syft/src/syft/core/node/common/action/exception_action.py
- packages/syft/src/syft/core/store/storeable_object.py
- packages/syft/src/syft/util.py
- fixing broken torch tests due to changed handling of builtins and boxes
- temporary_box now means that StorableObject can contain primitives
- StorableObject expects all storeables to have _object2proto
- fqn = obj.__module__ was technically invalid and worked via mro
> Fixing broken torch tests due to changed handling of builtins and boxes

- packages/syft/src/syft/core/tensor/autodp/row_entity_phi.py
- packages/syft/src/syft/core/tensor/autodp/single_entity_phi.py
- packages/syft/tests/syft/core/tensor/autodp/row_entity_phi_test.py
- packages/syft/tests/syft/core/tensor/autodp/single_entity_phi_test.py
Adding support and tests for the following ADP operations:
With this, all the ADP operations in Week 2 will have been implemented.
None.
Running pytest on Docker Backend Container
Pre-commit run --all-files
> Adding ALL remaining ADP Operations for week 2

- packages/syft/src/syft/core/tensor/autodp/row_entity_phi.py
- packages/syft/src/syft/core/tensor/autodp/single_entity_phi.py
- packages/syft/src/syft/core/tensor/passthrough.py
- packages/syft/tests/syft/core/tensor/autodp/row_entity_phi_test.py
Added support and tests for all transform operations for RowEntityPhiTensors:
No affected dependencies.
Added pytest tests to the `row_entity_phi_test.py` file, and used a `pre-commit run --all-files` to verify linting and other errors.
> Add support and tests for all transform operations for RowEntityPhiTensors

- packages/syft/setup.cfg
- packages/syft/src/syft/lib/numpy/array.py
> Fix issue with worker crashing with larger numpy arrays

- packages/syft/src/syft/core/node/common/client_manager/request_api.py
When results come back from the syft grid API we should upcast them
If we dont Pandas doesnt always display them correctly
> Upcast Results for Pandas

- README.md
The `notebooks` directory is in the root of the repo, not inside the `packages` directory, so I fixed the documentation to reflect that.
n/a
n/a
> docs: fix notebooks location in monorepo tree

- docs/source/install_tutorials/linux.rst
I was reading https://openmined.github.io/PySyft/install_tutorials/linux.html and saw a broken code block.
n/a
Checked edit preview on github.
> docs: fix code block format in install tutorial

- .github/workflows/hagrid-pr_tests.yml
- .github/workflows/nightlies-run.yml
- .github/workflows/stack-integration_tests.yml
- .github/workflows/syft-merge_torch_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
This fix adds a deterministic behavior for long-living branches. Dorny File path checker in the actions needs a ref for where to check file changes from if the workflow was not triggered from a pull request. |
In our case, our workflow is triggered by a scheduled call for nightlies so we need to add a `${{ github.ref }}` so even though the trigger is not from a PR, it checks for last file changes made to the branch. 
This is a gotcha for long-living branches
REF: https://github.com/dorny/paths-filter
> fixed issue with dorny file check expecting a base ref

- packages/grid/backend/backend.dockerfile
- packages/hagrid/setup.py
- packages/syft/setup.cfg
- packages/syft/tests/syft/core/common/message_test.py
- binary wheels are not available and numpy support at compile time
requires numpy to be installed first which is non-deterministic
- upgrade setup.cfg packages
> Fixed issue with Apple Silicon M1 and primesieve package

- packages/grid/scripts/cron.sh
> Fixing issue where CONTAINER_HASH fails if docker isn't running

- packages/syft/src/syft/core/tensor/autodp/row_entity_phi.py
- packages/syft/tests/syft/core/tensor/adp/row_entity_phi_test.py
- Fixed issue where __add__ on REPT with 1 row returns a SEPT
- This violates the signature and causes some tests to fail which compare the shape etc
- Added new test to check for this edge case
> Fixed issue where __add__ on REPT with 1 row returns a SEPT

- packages/grid/.env
- packages/grid/backend/backend.dockerfile
- packages/grid/vpn/requirements.txt
- packages/hagrid/hagrid.dockerfile
- packages/hagrid/hagrid/cli.py
Fixing issue that occurred on 0.6.0 with tzdata hanging docker apt-get update.
> Adding DEBIAN_FRONTEND=noninteractive to prevent tzdata from hanging

- packages/syft/setup.cfg
Dropping requirements back to python 3.7 for google colab
> python 3.7 for google colab

- .github/workflows/nightlies-run.yml
- .github/workflows/stack-integration-public_tests.yml
- .github/workflows/stack-integration_tests.yml
This PR aims to separate Stack Integration tests for public deployments to be in its own workflow and run only in nightlies as it makes sense since we do not deploy new syft & hagrid per PR or merge.
> making public test run on nightly alone

- packages/grid/ansible/roles/jupyter/tasks/main.yml
- packages/grid/ansible/site.yml
- Make jupyter cron job start sooner so that the packages can be ready
> Make it so jupyter installs regardless of install=true/false

- docs/source/install_tutorials/windows.rst
Support for user account management in Windows 10 Home Edition is not well explained on Microsoft pages too. So, adding those two lines of text (as a Note) will save time for those who are trying hagrid for the first time. 
Also, the hagrid launch error message is cryptic - just changing to 'domain' works.
Those notes will help save time for those Windows 10 users with Home edition, who are eager to get hagrid launch to happen successfully.
No dependencies
I verified the steps -
> local user group and hagrid launch message

- packages/hagrid/hagrid/cli.py
Refresh table one last time before exit in hagrid check --wait --silent
> Fix HAGrid check --silent

- packages/grid/backend/backend.dockerfile
- packages/syft/setup.cfg
- Upgrade pycapnp to 1.1.1 for binary wheels on python 3.10
> Upgrade pycapnp to 1.1.1 for binary wheels on python 3.10

- packages/syft/src/syft/core/tensor/autodp/gamma_tensor.py
- packages/syft/tests/syft/core/tensor/adp/gamma_tensor_test.py
If a data scientist tries to publish a PhiTensor, or a PhiTensor with public values added to it, the state tree will be empty when `publish` is called, resulting in failures. This PR adds a small check for this and rectifies the state tree.
Nothing new.
Re-running failed tests
> Fixing empty gamma tensor state

- packages/grid/frontend/src/components/Epsilon.tsx
- packages/grid/frontend/src/components/SidebarNav.tsx
- Sets the `Requests` to Epsilon
~- [ ] My changes are covered by tests~
> feat: #6509 Set requests sidebar icon to Epsilon

- packages/grid/backend/grid/api/syft/syft.py
- packages/grid/backend/grid/core/config.py
- packages/grid/devspace.yaml
- packages/grid/docker-compose.test.yml
- packages/syft/src/syft/core/node/abstract/node.py
- packages/syft/src/syft/core/node/common/client.py
- packages/syft/src/syft/core/node/common/client_manager/dataset_api.py
- packages/syft/src/syft/core/node/common/client_manager/domain_api.py
- packages/syft/src/syft/core/node/common/client_manager/request_api.py
- packages/syft/src/syft/core/node/common/node_service/sleep/sleep_messages.py
- packages/syft/src/syft/core/node/common/node_service/sleep/sleep_service.py
- packages/syft/src/syft/core/node/domain.py
- packages/syft/src/syft/core/node/domain_client.py
- packages/syft/src/syft/grid/client/grid_connection.py
- packages/syft/src/syft/grid/client/proxy_client.py
- packages/syft/src/syft/grid/connections/http_connection.py
- packages/syft/tests/syft/core/io/route_test.py
- packages/syft/tests/syft/core/node/common/service/simple_service_test.py
- tests/integration/network/request_load_test.py
- tox.ini
normally when we run network_client.domains it checks the health of all the domains before doing anything. as the number of domains increases (and we also discover some bugs/issues) this seems to be causing problems by default - disabling for now
> Disable checking all domain health by default

- docs/source/install_tutorials/linux.rst
As per the feedback received by @IrinaMBejan,
Download `jupyter lab` instead of `jupyter-notebook` in Linux as well and maintain consistency across all platforms
None
Verified the further commands after doing lab install instead of notebook.
> fix: install jupyer lab over notebook

- packages/syft/src/syft/core/tensor/autodp/gamma_tensor.py
We found a bug that prevented SMPC addition, it arose because of a typo in the TensorWrappedGammaTensor code (`min_val` instead of `min_vals`.
We should add tests that check the TensorPointers are working correctly.
> Fix min_val and max_val inconsistency

- .github/file-filters.yml
- Swapping "frontend" for "backend" for frontend file filters
- None
- N/A
> Fix Github File Filter filepaths

- packages/hagrid/hagrid/cli.py
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-
on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
hagrid quickstart breaks in windows due to not finding jupyter.exe.
Fixes: https://github.com/OpenMined/PySyft/issues/6764
> Fix jupyer extension disable cmd breaking in windows 

- packages/hagrid/hagrid/deps.py
- Made HAGrid binary dependency checker more defensive
> Fixed issue where running binary returns no lines for error extraction

- packages/syft/setup.cfg
Higher versions of protobuf 3.19.x seem to fail on Apple Silicon.
> Downgrading protobuf for Apple Silicon

- docs/source/index.rst
Fixes typo on the Pysyft documentation website here [here](https://openmined.github.io/PySyft/)
> fix typo on the docs index page

- packages/hagrid/hagrid/cli.py
Fix #6835
```
You appear to be using Docker Desktop but don't have enough memory allocated. It appears you've configured Memory:4 MB when 8192MB (8GB) is required. Please open Docker Desktop Preferences panel and set Memory to 8GB or higher.
OSX Help: https://docs.docker.com/desktop/mac/
Windows Help: https://docs.docker.com/desktop/windows/
Then re-run your hagrid command.
If you see this warning on Linux then something isn't right. Please file a Github Issue on PySyft's Github.
Alternatively in case no more memory could be allocated, you can run hagrid on the cloud with GitPod by visiting https://gitpod.io/#https://github.com/OpenMined/PySyft.
```
- Provide instructions so …
> Add GitPod instructions in case there's not enough memory allocated for Docker

- packages/syft/src/syft/core/adp/vectorized_publish.py
Publish breaks when there is not sufficient budget cause the comparison `value != zero_like` in `can_reduce_further` method return NotImplemented as output.
This is because zero_like is a GammaTensor tensor and JAX doesn't know how to interact with it.
- Tested locally.
> Fix publish breaking when not enough PB

- packages/hagrid/hagrid/deps.py
exec cmd "hagrid launch domain" ,ERROR log is "Error: '>' not supported between instances of 'NoneType' and 'Version'"
exec cmd "hagrid launch domain" ,check version error
after change version define value , Execute successfully！！！
no
exec cmd "hagrid launch domain"
local python and docker env version
> Modified version The default value is version object ,not None

- packages/syft/setup.cfg
This PR will fix the flakiness in **grid.test.backend** noticed with the new Pytest release `7.2.0`.
> pin pytest to 7.1.3

- packages/hagrid/hagrid/cli.py
- packages/syft/src/syft/util.py
Fixes Issue: https://github.com/OpenMined/PySyft/issues/6891
When we use multiprocessing for Event creation (it happens specifically on MacOS/Windows)  there is file not found error because the parent thread is killed while the child is starting. This is because the MacOS/Windows use `spawn` mechanism to start new Events which breaks in Python 3.8+. 
Fix: use the `fork` mechanism to start new Events.
Python Issues: …
> Fix apply_to_domain breaking due to multiprocessing lib in MacOS/Windows

- packages/syft/src/syft/grid/client/client.py
update connection error with more user action steps fix improper printing when logging in with verbose False
Update connection error and timeout error messages to more verbose and friendly.
Fixes: https://github.com/OpenMined/PySyft/issues/6888
**Connection Error**
**Timeout Error**
> Improve logging message on Connection and Timeout Errors

- .github/workflows/stack-integration_tests.yml
- scripts/container_log_collector.py
- tests/integration/network/connect_nodes_test.py
```py
"docker inspect --format '{{.Name}}' " + container, shell=True
```
would return container's name with backslash
```
like: `/canada-backend'
```
which when would appended would take it as a separate path which leads to permission error.
The PR fixes the same by removing backslash.
Example run: https://github.com/OpenMined/PySyft/actions/runs/3439644207/jobs/5737175631
Existing tests
> Modify Container name in log collector

- packages/grid/docker-compose.dev.yml
- scripts/dev_tools.sh
Improve `dev_tools.sh` support on Windows for launching specific ports in using the `start.exe` command. Script's dependency on `python3` was also causing it to fail on systems that did not have `python3` command available. Instead of fixing the python/python3 conflict, a more robust fix is to use the faster [`docker inspect --format`](https://docs.docker.com/engine/reference/commandline/inspect/#list-all-port-bindings) that uses [Go Templates](https://pkg.go.dev/text/template). The script has also been refactored in a little to support any future docker-specific additions.
- Padawan notebooks may need to be updated to reflect the new output.
- Verified by running the dev tools script on Windows, WSL2 & Linux.
> [scripts] dev_tools improve win support & performance

- .github/workflows/stack-integration_tests.yml
- scripts/container_log_collector.py
While running one of the windows integration test I got
closes: https://github.com/OpenMined/PySyft/issues/7078
```
Run python ./scripts/container_log_collector.py
Traceback (most recent call last):
File "C:\Users\azureuser\actions-runner\_work\PySyft\PySyft\scripts\container_log_collector.py", line 35, in <module>
path.write_text(container_logs)
File "C:\Users\azureuser\actions-runner\_work\_tool\Python\3.10.5\x64\lib\pathlib.py", line 1155, in write_text
return f.write(data)
File "C:\Users\azureuser\actions-runner\_work\_tool\Python\3.10.5\x64\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 14927-14928: character maps to <undefined>
Error: Process …
```
> Set docker log encoding to utf-8

- .github/workflows/hagrid-pr_tests.yml
Fixing the Hagrid PR failing due to safety warnings about `py`
> ignoring py safety warning

- packages/hagrid/hagrid/cli.py
Users had issues with clicking the hyperlink provided during the launch of hagrid that explains how to use ctop. This pull request replaces the hyperlink with the raw URL of the video.
Closes #6975 
None
None
> Replace Ctop explanation hyperlink with raw url in hagrid

- packages/syft/src/syft/core/tensor/tensor.py
> Remove redundant white spaces in tensor init message

- .bumpversion.cfg
- packages/syft/src/syft/core/tensor/autodp/gamma_tensor.py
- packages/syft/src/syft/core/tensor/autodp/phi_tensor.py
The PR aims to remove passthrough from DP tensor Pointers, 
Subclassing pointers from PassthroughTensor makes unimplemented methods available on the client side.
Fixes #6922 
Local Testing
> Removal of PassthroughTensor from DP TensorPointer

- packages/syft/src/syft/core/adp/data_subject_list.py
since we're not using it
fix #7121. also see https://github.com/OpenMined/PySyft/pull/7111#discussion_r1033150819 for more context.
> Disable __array_ufunc__ for DataSubjectArray

- packages/syft/src/syft/core/tensor/passthrough.py
- packages/syft/tests/syft/core/tensor/passthrough_test.py
FIx #7042.
Unimplemented methods on tensors now correctly raise no implementation error instead of going into an infinite loop
```py
np.full_like(sy.Tensor(np.array([1, 2, 3])).annotate_with_dp_metadata(-1, 11000, data_subjects="Bob"), 7)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [7], line 1
----> 1 np.full_like(sy.Tensor(np.array([1, 2, 3])).annotate_with_dp_metadata(-1, 11000, data_subjects="Bob"), 7)
File <__array_function__ internals>:180, in full_like(*args, **kwargs)
TypeError: no implementation found for 'numpy.full_like' on types that implement __array_function__: [<class 'syft.core.tensor.tensor.Tensor'>]
```
List any dependencies that are required for this …
> Fix __array_func__ and disable __array_ufunc__ for passthrough tensors

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/deps.py
Fix #7114
Fix #7144
Fix #7151
- Disable docker group check if inside gitpod
- Fix issue where it show `hagrid logs None` when a node name is not specified in `hagrid launch`, i.e. `hagrid launch domain to docker:8801 ...`
- Better visual for hagrid logs message (no red text, police car revolving lights)
> Miscellaneous hagrid fixes

- packages/syft/src/syft/registry.py
Should be a typo. `self.networks` is not reference anywhere
> Fix typo in attribute `networks` -> `all_networks`  in `NetworkRegistry`

- docs/source/guides/data-owner/00-deploy-domain.rst
- notebooks/Experimental/Ishan/AA/update_syft.sh
- notebooks/Experimental/Shubham/TradeDemoE2E/Trade-demo-data-owners.ipynb
- notebooks/Experimental/medical-federated-learning-program/data-owners-full/02-data-owners-setup-domain.ipynb
- notebooks/Experimental/medical-federated-learning-program/data-owners/data-owners-presentation.ipynb
- notebooks/Experimental/mflp_sessions/Project3_Hagrid_Deep_Dive/Playing with Pets - Session 3.ipynb
- notebooks/PySyTFF/DO.ipynb
- notebooks/petlab_sessions/TradeDemoE2E/Trade-demo-data-owners.ipynb
- notebooks/quickstart/01-install-wizard.ipynb
- notebooks/quickstart/data-owner/00-deploy-domain.ipynb
- packages/grid/ansible/roles/aa_demo/tasks/main.yml
- packages/grid/ansible/roles/containers/tasks/containers.yml
- packages/hagrid/hagrid/cli.py
- packages/hagrid/tests/hagrid/cli_test.py
- scripts/aa_demo/update_domain.sh
- tox.ini
Fix #7141
- Convert command line bool options to flags, *e.g.* `--cmd=True` to `--cmd`
- Bool options that were default to `True`, *e.g.* `--use_blob_storage`, `--health_checks`, `--provision` were converted to `--no_blob_storage`, `--no_health_checks`, `--no_provision`.
- Make `tail` disabled by default. To tail just specify `--tail`.
- Forcing container image rebuilding is now always enabled in `development` or `--tag=local`. Otherwise depends on whether the `--build` flag is enabled.
- Remove the `Optional: ...` prefix in some of the help texts. In the help message required arguments are tagged with `[required]` anyway.
- Use `context_settings={"show_default": True}` in `@click.command` to always show the default values for command line options.
List any dependencies that are required …
> Convert hagrid options to flags

- docs/source/deployment/index.rst
- notebooks/Experimental/medical-federated-learning-program/network-operators/00-network-operators-create-network.ipynb
- notebooks/Experimental/medical-federated-learning-program/network-operators/01-network-operators-create-empty-vm.ipynb
- packages/grid/ansible/roles/containers/tasks/containers.yml
- packages/grid/scripts/redeploy.sh
- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/lib.py
- scripts/aa_demo/update_domain.sh
- tox.ini
Fix #7140. Depends on #7168 (merge that one first).
This turns out to be a much easier fix than previously thoughts since `click` automatically assigns `@click.option(`--cli-option`)` to `kwargs["cli_option"]`.
> Make hagrid cli options `--hyphen-separated` instead of `--snake_case`

- packages/hagrid/hagrid/cli.py
- This fixes an issue where the first image you get is arm64 and then running hagrid later without --platform won't override the default
- Added ARCH to the output so its easy to see which version is running
> Default to linux/amd64 docker mode when on x86 machines

- packages/hagrid/hagrid/quickstart_ui.py
Missed this spot when converting `ArgCache` from attribute to dict-like api in #7169 and #7185.
> Fix ArgCache bug in QuickstartUI

- docs/source/install_tutorials/windows.rst
Description
The current way of installing wsl from the command line doesn't work on some machines. For the current versions of Windows 10/11, there is an alternate way to install wsl using the Microsoft store. It is more beginner friendly and clear
Affected Dependencies
No dependencies are affected since only extra documentation is added. Ideally, it should go to this page
https://openmined.github.io/PySyft/install_tutorials/windows.html
> Alternate way of installing Windows Subsystem for Linux

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/quickstart_ui.py
As title says. Also add the `hagrid dagobah [ZIPFILE]` command
Prepare a zip file containing the notebooks
```sh
git clone <repo>
cd <repo>/notebooks
zip -r padawan.zip padawan
```
Run `dagobah`
```sh
hagrid dagobah <path-to-zip-file>
```
or just `hagrid dagobah` if `padawan.zip` is in the current directory.
There are a lot of duplicated code between `fetch_notebooks_for_url` and `fetch_notebooks_from_zipfile`. I attempted to refactor earlier but it's more complicated than it looks and probably unnecessary. This works for now.
> Support extracting notebooks from a zip file for quickstart

- packages/syft/src/syft/core/node/new/api.py
The current check for empty function parameter annotation doesn't work since `param.annotation` is not a class/type and passing it to `issubclass` will throw `TypeError`. The idiomatic way to do this is to check if it is [`inspect.Parameter.empty`](https://docs.python.org/3/library/inspect.html#inspect.Parameter.empty), which is also the same as `inspect._empty` but actually documented. See https://stackoverflow.com/questions/62010367/python-check-if-signature-annotation-is-of-specific-class.
> Fix check for empty function parameter annotation

- .pre-commit-config.yaml
- packages/syft/tests/trials/skill_test.py
- Added name in padawan trial 1.
- Bumped isort to 5.12.0 based on [this issue](https://github.com/PyCQA/isort/issues/2079)
- isort
- Linting: pre-commit run --all-files
- Tests Ran: tox -e padawan.trials
> [Padawan Trial 1: Uchechukwu Emmanuel] Add name to skill_test 

- packages/grid/backend/grid/worker.py
- tests/integration/smpc/tensor/mpc_tensor_test.py
- tests/integration/smpc/tensor/tensor_abstraction_test.py
In the upcoming iteration since we plan to refactor the comparison operation of SMPC .
Currently the comparison operations are bottlenecking the CI, currently removing the redundant tests in SMPC tests
To be tested in CI
> Disabling Redundant  Tests SMPC

- packages/syft/src/syft/core/node/common/client_manager/association_api.py
- packages/syft/src/syft/core/node/common/client_manager/dataset_api.py
- packages/syft/src/syft/core/node/common/client_manager/oblv_api.py
- packages/syft/src/syft/core/node/common/client_manager/role_api.py
- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/grid/client/client.py
Added instrumentation to requests in old client and new client 
Closes https://github.com/OpenMined/Heartbeat/issues/7#issue-1548597417
However, the following part was not done: "Optionally figure out a way to enable tracing easily without having to set an environment variable, but easily leave off in production, perhaps a special import like from syft.tracing import autoenable". Perhaps we can create a separate issue and track this.
- Tested some common methods such as login, connect, create user, fetch all users, datasets, etc., in the old client, and tested new_connect in the new client.
- Tested on M1 MacBook Air
> Added instrumentation to requests in old & new client

- packages/syft/src/syft/core/node/new/user_code.py
- packages/syft/src/syft/core/node/new/user_code_parse.py
- packages/syft/src/syft/core/node/new/user_code_service.py
Modify the user code submission API following the mock notebooks.
```py
from syft.core.node.new.client import SyftClient
from syft.core.node.new.user_code import *
worker = sy.Worker()
client = sy.new_login(node=worker, email="info@openmined.org", password="changethis")
@syft_function(input_policy=ExactMatch(inputs=["x"]), output_policy=SingleExecutionExactOutput(outputs=["y"]))
def func(x):
return {"y" : x}
client.api.services.code.add(func)
uid = client.api.services.code.get_all()[0].id
client.api.services.code.call(uid, x = 7)
```
`SubmiteUserCode` now accepts a function, *e.g.*
```py
def func(x):
return {"y" : x}
```
and turns it to
```py
def func_<long-hash>(x) -> Dict[str, Any]:
def func(x):
return {"y" : x}
result = func(x=x)
return {k: result[k] for k in …
```
> Modify user code submission API following notebooks

- packages/syft/src/syft/core/node/new/user_code.py
Looks like overriding `__init__` in `ExactMatch` messes with serialization
```py
@serializable(recursive_serde=True)
class ExactMatch(SyftObject):
__canonical_name__ = "ExactMatch"
__version__ = SYFT_OBJECT_VERSION_1
id: Optional[UID]
inputs: Dict[str, Any]
def __init__(self, *args: Any, **kwargs: Any) -> None:
super().__init__(inputs=kwargs)
```
In
```py
@syft_function(input_policy=ExactMatch(x=4), output_policy=SingleExecutionExactOutput(outputs=["y"]))
def func(x):
return {"y": x}
```
`ExactMatch(x=4)` on the client works as intended
```py
class ExactMatch:
id = None
inputs = {'x': 4}
```
but on the server it deserializes into
```py
class ExactMatch:
id = None
inputs = {'inputs': {'x': 4}}
```
Comment out the overriden `__init__` for now. In the meantime use `ExactMatch(inputs={'x': …
> Deserialization bug with overriden `__init__` in `SyftObject`

- packages/syft/src/syft/capnp/iterable.capnp
- packages/syft/src/syft/capnp/kv_iterable.capnp
- packages/syft/src/syft/capnp/recursive_serde.capnp
- packages/syft/src/syft/core/common/serde/recursive.py
- packages/syft/src/syft/core/common/serde/recursive_primitives.py
- packages/syft/src/syft/core/common/serde/third_party.py
- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/worker.py
- Capnp has a max of 512mb per Data item so the outer recursive layer would hit the limit when a child is over 512mb
- Added datetime, time, date, pd.Timestamp serde types
- Changed DataFrame serde to use PyArrow
- Added root_client property to Worker
> Added support for > 512mb blobs in recursive serde

- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/core/node/new/dataset_service.py
- packages/syft/src/syft/search.py
Added a `search` endpoint to the dataset api services here so users can do
```py
client.api.services.dataset.search(name="<search-string>")
```
Currently implemented by filtering outputs of `dataset.get_all`. A better way could be through the stash api, e.g. `query_all`?
Added `sy.search` which loops through the nodes in `sy.gateways` and call their dataset search endpoints and collecting the results.
> Add dataset search

- packages/syft/src/syft/core/node/new/document_store.py
- packages/syft/src/syft/core/node/new/mongo_document_store.py
- if the searchable key is a method, call it and store its value in the mongo
- update as_mongo_dict method to use in query if the qk is of list_type
Test Notebooks: https://github.com/OpenMined/Heartbeat/pull/108
> Make input_policy.assets compatible with Mongo

- packages/grid/backend/grid/api/router.py
The recent changes moved `/new` routes definition to another source file, disabling it from the API. This PR aims to fix this by adding the router created in new.py to our API router.
> Fix /new router to work with the last changes

- packages/grid/frontend/src/lib/components/DomainOnlineIndicator.svelte
- packages/grid/frontend/src/lib/components/authentication/DomainMetadataPanel.svelte
- packages/grid/frontend/src/routes/(auth)/login/+page.svelte
- packages/grid/frontend/src/types/domain/onlineIndicator.ts
This fix created `DomainOnlineStatus` type and changes the text color for the anchor tag on the login page.
- [ x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
> Refactor domain online status icon

- packages/syft/src/syft/core/node/new/serializable.py
- packages/syft/src/syft/telemetry.py
- packages/syft/src/syft/trace_decorator.py
- packages/syft/tests/syft/messages/message_stash_test.py
- packages/syft/tests/syft/stores/base_stash_test.py
- Remove unused `**kwargs` from `@serializable` plus remove the now deprecated `recursive_serde` in tests for `BaseStash`.
- Fix `BaseStash` tests' flakiness by avoiding collision from random generators.
- Fix typing for `@serializable` and `@instrument` so that `@serializable`- and `@instrument`-ed classes and functions now offer correct typing and code completion (originally from #7475).
> Currently the `serializable` decorator has return type `Any` so when we apply it to any class the class will lose all typing. For example, currently with this
>
> ```py
> @serializable
> class PartitionKey(BaseModel):
>    ...
>
> PTKey = PartitionKey(...)
> ```
>
> we won't get any typing, completion, ... when using PTKey.
>
> This PR fixex that by using type parameter (`TypeVar`) to type …
> Misc fixes (`BaseStash` tests' flakiness, `@seriablizable` and `@instrument` typings)

- packages/syft/tests/syft/messages/message_service_test.py
Would like to see improve `test_messageservice_resolve_object_success` test to include a check for returned Messasge object.
N/A
Locally
- [X ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [X ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [X ] My changes are covered by tests
> message_service tests - 100% coverage

- packages/syft/src/syft/core/node/new/sqlite_document_store.py
Fix `SQLiteStoreClientConfig`
- Correct typing
- Fix the issue where if you initializa a `SQLiteStoreClientConfig` `x = SQLiteStoreClientConfig()` its `file_path` value will change everytime you call it.
> SQLiteStore fixes

- packages/syft/src/syft/core/node/new/serializable.py
- packages/syft/src/syft/telemetry.py
- packages/syft/src/syft/trace_decorator.py
See https://github.com/OpenMined/PySyft/pull/7476#discussion_r1154245386 for context.
> Re-add explicit typing for decorators (`@instrument`, `@serializable`)

- packages/syft/src/syft/core/node/new/request_service.py
This PR aims to fix a small bug/vulnerability by replacing the usage of `user_verify_key` which uses a hardcoded email to retrieve the root key with the `admin_verify_key` which uses the actual admin service role. This could be a problem if the admin changed his email during the onboarding process.
> Replace user_verify_key by admin_verify_key during request.submit

- packages/syft/tests/conftest.py
- packages/syft/tests/syft/messages/fixtures.py
- packages/syft/tests/syft/messages/message_serde_test.py
- packages/syft/tests/syft/messages/message_service_test.py
- packages/syft/tests/syft/messages/message_stash_test.py
Added the message serde test I could.
Added /test/messages/fixtures.py  and added to path in packages/syft/tests/conftest.py 
N/A
Locally
- [X ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [X ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [X ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [X ] My changes are covered by tests
> Added message_serde tests, cleaned up fixtures

- packages/syft/src/syft/core/node/new/policy.py
- packages/syft/src/syft/core/node/new/unparse.py
- packages/syft/tests/syft/stores/queue_stash_test.py
- https://github.com/simonpercivall/astunparse/issues/62
> Fixing issue where ast.unparse library incorrectly parses : indexing

- packages/syft/src/syft/serde/recursive_primitives.py
explicitly define serde attributes for _UnionGenericAlias which are common across versions
> fix serde for _UnionGenericAlias for backward python compatibility

- packages/syft/tests/trials/skill_test.py
Added antti to the list of R4Q2 Padawans
N/A
run `tox -e padawan.trials`
> Add antti to the skill_test

- .pre-commit-config.yaml
- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/deps.py
- packages/hagrid/hagrid/parse_template.py
- packages/hagrid/hagrid/util.py
- packages/syft/src/syft/client/api.py
- packages/syft/src/syft/external/oblv/deployment_client.py
- packages/syft/src/syft/node/routes.py
- packages/syft/src/syft/serde/recursive.py
- packages/syft/src/syft/service/action/action_graph.py
- packages/syft/src/syft/service/action/action_object.py
- packages/syft/src/syft/service/code/unparse.py
- packages/syft/src/syft/service/code/user_code.py
- packages/syft/src/syft/service/policy/policy.py
- packages/syft/src/syft/service/vpn/vpn.py
- packages/syft/src/syft/store/locks.py
- packages/syft/src/syft/store/mongo_document_store.py
- packages/syft/src/syft/store/sqlite_document_store.py
- packages/syft/src/syft/types/syft_metaclass.py
- packages/syft/src/syft/types/syft_object.py
- packages/syft/src/syft/util/trace_decorator.py
- packages/syft/tests/syft/action_graph/action_graph_test.py
- packages/syft/tests/syft/eager_test.py
- packages/syft/tests/syft/locks_test.py
- packages/syft/tests/syft/messages/message_stash_test.py
- packages/syft/tests/syft/users/user_test.py
- ruff.toml
Re-enable flake8-bugbear checks in Ruff to catch potential buggy code.
One of those is B006 `Do not use mutable data structures for argument defaults.`
for functions, instead of
```python
def f(ls=[]):
...
```
do
```python
def f(ls=None):
if ls is None:
ls = []
...
```
This is an [anti-pattern](https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html) and might lead to subtle bugs.
> Re-enable flake8-bugbear checks in Ruff

- packages/syft/src/syft/node/routes.py
to avoid B008 "Do not perform function calls in argument defaults."
https://fastapi.tiangolo.com/tutorial/dependencies/
originally part of #7677 but taken out since it fails the oblv tests. ~not sure why.~ Issue resolved. Was due to `syft-enclave` outdated test dependencies.
> Use Annotated in FastAPI routes

- notebooks/tutorials/data-owner/01-uploading-private-data.ipynb
- packages/syft/src/syft/service/action/action_object.py
- packages/syft/src/syft/service/action/action_store.py
- packages/syft/src/syft/service/dataset/dataset.py
- packages/syft/tests/syft/service/dataset/dataset_service_test.py
When users try to create a `sy.Dataset` containing `sy.Asset`'s without mock, an error will be raised. The error message lists the assets without mock and also shows instructions on how to explicitly set empty mock on an asset.
> Dataset without mock

- notebooks/api/0.8/00-load-data.ipynb
- packages/syft/src/syft/client/client.py
- packages/syft/src/syft/service/dataset/dataset.py
- packages/syft/tests/syft/service/dataset/dataset_service_test.py
As a follow up of #7676, this PR
- adds a check to disallow `dataset.add_asset` an asset with `None` mock
- adds a check to disallow `client.upload_dataset` a dataset containing assets with `None` mock. Since users can still bypass all the `Dataset` validation checks with `dataset.asset_list[0].mock = None`
See https://github.com/OpenMined/Heartbeat/issues/245#issuecomment-1583925057 for context.
> Disallow adding an asset with None mock to a dataset

- packages/hagrid/hagrid/parse_template.py
> Fixing issue where windows paths used in github url for hagrid templates

- packages/syft/src/syft/types/syft_object.py
Closes https://github.com/OpenMined/Heartbeat/issues/407
`_repr_markdown_` function
- Ran notebooks to verify if the Markdown repr in jupyter is working as expected
> Fix compound attr bug in _repr_markdown_

- packages/syft/src/syft/service/code/user_code.py
- packages/syft/src/syft/util/markdown.py
`UserCode` `.code` now shows syntax highlighted code.
> Show syntax highlighting for submitted code
