syft/__init__.py

Bugfix that was an issue in python 3.5. Fixed using this edit (and we should for other repos too)

ignored test functionality

---

Dockerfile

Thanks @TheOriginalAlex for debugging help 👍

add ca-certificates to apk add list in Dockerfile (fix for issue #115)

---

syft/tensor.py
tests/test_tensor.py

Default sum/shape Functionality for Base Tensor Type (Issues #10 and #102)

---

syft/__init__.py
syft/math.py
syft/tensor.py
tests/test_math.py
tests/test_tensor.py

Fixes #37 
Fixes #38 
Fixes #61 
Fixes #40

Implements dim, dot, matmul, equal

---

syft/tensor.py

Use in-place operators

---

syft/math.py
syft/tensor.py
tests/test_math.py
tests/test_tensor.py

I fixed few errors that @samsontmr & I discussed I also added cumulative product over axis I also noticed the test for addbm failed but since @bartimaeus12 has already noticed the last issue #142 I'll leave it to him .

Add Cumprod & erros fix

---

syft/tensor.py
tests/test_tensor.py

Please let me know if I'm on the right track here :)
Fixes #128

Implement index operator

---

syft/math.py
syft/tensor.py
tests/test_math.py
tests/test_tensor.py

fixes issues
#21
#22
#23
#25
#26
#142

Implemented addmv(),addcmul(),addcdiv(),addbmm(),baddmm() and rectified addmm()

---

README.md

That was added in https://github.com/OpenMined/PySyft/commit/29e0105969223062ca6ff010337c568e1f0d3bf1

[docs] Mention `make test` in README

---

syft/math.py

Fixes #142 

---

requirements.txt

the requirements file didn't have what it needed for the testing suite

modified req file

---

syft/math.py
syft/tensor.py
tests/test_math.py
tests/test_tensor.py

fixed pep8 errors except E501(lines too long).

Fixed pep8 issues in test_tensor.py,test_math.py, math.py, tensor.py

---

.circleci/config.yml
setup.cfg

Fixes #119
We got automatic pep8 style checks now 👍

fix-pep8-tests

---

syft/math.py
syft/tensor.py
tests/test_math.py
tests/test_tensor.py

I added the sigmoid function if it's required I can add all other activation functions as well(Tanh,ReLU,SeLU...) I also fixed few issues like one where a python keyword 'sum' is redefined and few others .

Adding sigmoid and fixing syntax issues

---

setup.cfg

fix-pytest-warning (issue #165)

---

syft/tensor.py
tests/test_tensor.py

1. Added reciprocal() and reciprocal_() in syft/tensor/py
2. Added class reciprocalTests() in tests/test_tensor.py

Implemented reciprocal functionality on BaseTensor Object#84

---

requirements.txt

Removed jupyter from requirements.txt

---

syft/tensor.py
tests/test_tensor.py

1 . added to_numpy() function in syft/tensor.py
2 . added class numpyTests() in tests/test_tensor.py

Implemented numpy functionality for BaseTensor object#79

---

syft/tensor.py
tests/test_tensor.py

implemented log(),log1p(),normal_log_()

---

syft/tensor.py
tests/test_tensor.py

I think ceil_ used to be there, but vanished somehow? Anyway, it is back with the associated test.  I took the chance to slighting enhance the test for ceil.

In-place ceiling, and associated test

---

syft/__init__.py
syft/math.py
syft/tensor.py
tests/test_math.py
tests/test_tensor.py

✨ Implemented:
1. Transpose function in math.py
2. Tranpose functions for TensorBase
3. T Functions for TensorBase
4. Respective unit tests

Implemented transpose functionality

---

syft/tensor.py
tests/test_tensor.py

This is supposed to address [https://github.com/OpenMined/PySyft/issues/109](https://github.com/OpenMined/PySyft/issues/109)

Zero_: new method for TensorBase

---

syft/tensor.py
tests/test_tensor.py

- size function
- test for size function

feat(size for tensorbase)

---

syft/tensor.py
tests/test_tensor.py

[Addressing #62 default max implementation](https://github.com/OpenMined/PySyft/issues/62)

Max method added to tensorbase

---

syft/tensor.py
tests/test_tensor.py

Hopefully takes care of this: [https://github.com/OpenMined/PySyft/issues/80](https://github.com/OpenMined/PySyft/issues/80)

Adding permute method and test, addressing issue #80

---

README.md

As requested here https://github.com/OpenMined/PySyft/issues/132

Specify Python version

---

requirements.txt
syft/tensor.py

Implemented default median,mode,inverse,minimum, histc functionality: issue #64, #67, #55, #65, #53

---

syft/tensor.py
tests/test_tensor.py

- ne function implementation
- ne_ inplace function implementation
- tests for ne and ne_

feat(ne implementation for TensorBase)

---

syft/tensor.py
tests/test_tensor.py

1. implemented mean() function in syft/tensor.py
2. implemented class meanTests() in tests/test_tensor.py

Implemented default mean functionality on BaseTensor type #63

---

Development-Dockerfile
Makefile
README.md

@iamtrask Here my adjust in DockerFile. My steps : 
1) Create a new Docker file with Jupyter;
2) Create a custom Make action to pass docker name like a parameter;
3) Include in README.md the commands for this works. 
PS: In the Dockerfile, I include this dependency : openblas-dev, gfortran . Please validate if this necessary @anoff .

Fix the Docker File and create a setup with Jupyter to study the project

---

syft/tensor.py
tests/test_tensor.py

This was way more involved than I expected. In the process of understanding PyTorch's scatter method, I discovered a bug in their implementation that is now labeled as high-priority!
closes #91

added scatter method and tests to TensorBase class

---

syft/tensor.py
tests/test_tensor.py

Feature/gather  gather method for tensor base

---

syft/tensor.py
tests/test_tensor.py

- mv implementation
- test for mv

feat(mv functionality)

---

syft/he/paillier/basic.py
syft/tensor.py
tests/test_paillier.py

This can be used to predict to predict when a number is about to become undecryptable. (#11)
@MtDersvan @iamtrask

Added additive and multiplicative depth tracking #11

---

syft/tensor.py
tests/test_tensor.py

index_select added to Tensorbase class

---

syft/tensor.py
tests/test_tensor.py

Feature/ramainder  remainder method for tensor base class

---

README.md

Adds explicitness and clarity to setup for Docker users.

Adding docker launch/run to README.md

---

syft/tensor.py
tests/test_tensor.py

masked_fill_ and tests added. Minor tweak to masked_scatter_

---

syft/tensor.py
tests/test_tensor.py

- Implemented BaseTensor.{le, ge, lt} and their inplace versions.
- Updated Basetensor.gt() and BaseTensor.gt_() to reflect the new changes.
- Tests for all four inequalities.
Closes #49, closes #56, closes #59

Implemented BaseTensor.{le,ge,lt} and inplace versions

---

syft/tensor.py
tests/test_tensor.py

Adds the final feature to issue #60 and closes it

masked_select method and tests added for the TensorBase class

---

syft/tensor.py
tests/test_tensor.py

Implemented Diag Functionality for Base Tensor Type with tests

---

syft/tensor.py
tests/test_tensor.py

Revert "Implemented Diag Functionality for Base Tensor Type with tests"

---

.gitignore

added ignores for vscode specifics

Gitingore Support for using Visual studio code IDE

---

tests/test_integrations_locally.py
tests/test_math.py
tests/test_paillier.py
tests/test_tensor.py

This PR is to change camel case function test names to use _ 
This increases readability.
Currently finished changing tests in test_math.py

Changing Test function names from camelCase to snake_case

---

syft/tensor.py
tests/test_tensor.py

Added nelement to TensorBase #74

---

syft/__init__.py
syft/math.py
syft/tensor.py
tests/test_math.py
tests/test_tensor.py

issue #28 
Features looking at:
1. if any of the tensors is encrypted return NotImplemented error.
2. Unit tests to check shape returned tensor shape.
3. Unit tests to check the tensor value returned.
4. Inline documentation should take inspiration from pytorch but not copy it (which currently i did).

BMM functionality - issue #28

---

syft/tensor.py
tests/test_tensor.py

Add cauchy_ to TensorBase

---

syft/tensor.py
tests/test_tensor.py

Fixes #50 
Please go through the PR and suggest changes if any.
Thank you.

Adds default geometric functionality

---

syft/math.py
syft/tensor.py

This is one of my first pull requests. So Please feel free to tell me where I am wrong; I would love to get some feedback
I followed the NumPy Style on inline documentation. http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html
It's a bit rough around the edges but let me know if I am on the right track

#252 Inline Documentation Consistency 

---

.travis.yml
notebooks/Syft - Paillier Encrypted Linear Classification.ipynb
syft/nn/linear.py
tests/test_integrations_locally.py

The PR attempts to add minibatch in learn API and makes use of Openmined's Capsule to allow for secure re-encryption of the weights at defined intervals.

Add minibatching in "learn" API

---

syft/tensor.py
tests/test_tensor.py

Implement new() method in TensorBase class

---

tests/test_math.py
tests/test_tensor.py

Add unit tests for neg, neg_, tanh, and tanh_

---

notebooks/Syft - Paillier Encrypted Linear Classification.ipynb

Added Capsule module link in the notebook.

Added Capsule module link in the notebook.

---

syft/tensor.py
tests/test_tensor.py

Resolve #54  
New methods:  index(), index_add_(),  index_copy_(), index_fill_()

Implementation of index methods in TensorBase #54

---

Makefile

Just a quick addition to the Makefile, so test requirements are checked before testing

Included test requirements in make test target

---

syft/tensor.py
tests/test_tensor.py

Trying new PR as I force pushed by error on #312 and couldn't push anymore. Sorry will not  force push anymore.

handle slices on 1 dim tensors, resolves #311

---

syft/tensor.py
tests/test_tensor.py

This is supposed to address #70

Implement Default narrow Functionality for Base Tensor Type #70

---

syft/tensor.py
tests/test_tensor.py

Implemented the unfold function for the `TensorBase`

Implement Tensor unfold functionality on Base Tensor type #105

---

notebooks/MPC Tensor SPDZ.ipynb
syft/mpc/__init__.py
syft/mpc/rss/repo.py
syft/mpc/spdz/__init__.py
syft/mpc/spdz/config.py
syft/mpc/spdz/repo.py
syft/mpc/spdz/scalar.py
syft/mpc/spdz/tensor.py
tests/test_integrations_locally.py

Yash implemented a new MPC tensor and it was merged, but I'd like to keep around the old MPC tensor as well. In this PR, I split them into two folders.

Side by side mpc implementations

---

README.md

Revert "add PySyft setup guide for docker windows"

---

tests/test_math.py

First pull request :P 
I changed the class name from admmTests to addmmTests, because i saw the other class names being "add", so I thought it would be nice if this was "addmm" too.

updated class name from "admmTests" -> "addmmTests" in test_math.py

---

syft/tensor.py
tests/test_math.py
tests/test_nonlin.py
tests/test_paillier.py
tests/test_tensor.py

Test files follow naming convention

Naming convention on test files solved #365

---

syft/tensor.py
tests/test_tensor.py

Implement Default multinomial Functionality for Base Tensor Type

---

syft/math.py
syft/tensor.py
tests/test_math.py
tests/test_tensor.py

Addresses the issue discussed in PR #367 comments
It changes multinomial implementation to match PyTorch's API

changes multinomial to match PyTorch's API

---

syft/math.py
syft/tensor.py
tests/test_math.py
tests/test_tensor.py

Fixes:#381
added sin, cos, tan, sinh, cosh functions along with tests

add trigonometric functions

---

syft/he/paillier/__init__.py
syft/he/paillier/basic.py
syft/he/paillier/keys.py

#393 
It removes the fixed-point implementation that was contributed by yours truly!
The implementation was not very well thought out and buggy, and should not have been merged in the first place. I decided to remove it and fall back to `phe`'s built-in floating-point implementation, until we have a better solution.

rolled back to using phe's floating point, until we have a better solution

---

notebooks/Syft - Paillier Homomorphic Encryption Example.ipynb

I thought that it would be great to have the introductory PySyft Jupyter tutorials commented for the newcomers to understand better what's happening, and since I was getting started with PySyft I decided to accept the task. It sure can be improved but I think this can be of help as a starting point.

Added comments

---

README.md
install_for_anaconda_users.bat
install_for_anaconda_users.sh
requirements.txt
syft/syft.py

- Also, wrapped no_params_func into params_func (during merge)
- Windows users often don't have ability to run .sh files without additional tweaks. Bat files should be easier?

Add scalar_multiplication, and improve windows install

---

syft/syft.py

Added floor function for issue [#481](https://github.com/OpenMined/PySyft/issues/481)

added floor_() function

---

syft/syft.py

Uses https://github.com/OpenMined/OpenMined/pull/88

Expose *, - and sigmoid_ to pysyft

---

.gitignore
install_for_anaconda.sh
install_for_anaconda_on_windows.bat

Modified the bash and batch scripts and added a folder to the .gitignore file.

Tweaked some files.

---

syft/syft.py

adds is_contiguous function to PySyft Float Tensor class

---

syft/syft.py

closes https://github.com/OpenMined/PySyft/issues/619
closes https://github.com/OpenMined/PySyft/issues/620

added trunc function

---

README.md

1. removes deprecated links & updates the installation guidelines.

chore/fix-docs: removes deprecated links

---

syft/syft.py

adds cosh & cosh_ functions

---

syft/syft.py

adds cos/cos_ functions

---

syft/syft.py

Also noticed tanh was deleted added that back

Added sinh and sinh_

---

syft/syft.py

1. adds acos/acos_ ( #409 #413)
2. adds asin/asin_ ( #428, #427)
3. adds atan/atan_ (#430, #439)

adds more math functions

---

syft/syft.py

1. adds sin/sin_ functions. (#583 #582)
2. adds tan/tan_ functions (#606 #605)

adds some math functions

---

syft/syft.py

`is_contiguous()` must return a boolean
- `return_as_tensor=False` added

bug is_contiguous

---

syft/syft.py

Addresses the following issues:
#422 
#423

added addmv and addmv_ operations

---

syft/syft.py

Also requires the pull request to OpenMined for new_feature/sign to complete issue #580.
This is my first pull request so let me know if this is not in the format you are expecting.

Added sign function as per #580.

---

syft/syft.py

Hi there, this is related to a PR in OpenMined with the same name for the same issue #581. Thanks.

Added sign_(), the inline version of sign() as per issue #581.

---

syft/syft.py

Add rsqrt op

---

syft/syft.py

As per https://github.com/OpenMined/PySyft/issues/611
Corresponds to https://github.com/OpenMined/OpenMined/pull/145

add trace()

---

syft/syft.py

Hello,
This pull request should add Exp() to FloatTensor.
Thank you!

Add Exp() to FloatTensor (#473)

---

syft/syft.py

Implementing view_as

---

syft/syft.py

sum (CPU)
OpenMined/PySyft#599
prod (CPU)
OpenMined/PySyft#556
min (CPU)
OpenMined/PySyft#528
max (CPU)
OpenMined/PySyft#525
mean (CPU)
OpenMined/PySyft#526
See https://github.com/OpenMined/OpenMined/pull/171

min, max, sum, prod, mean

---

syft/__init__.py
syft/nn.py

same place PyTorch as it.  Most users shouldn't have to define their own
loss functions!

added MSELoss to .nn package

---

syft/syft.py

This should add Round to FloatTensor.

Add Round to FloatTensor (#570)

---

syft/syft.py

Hello,
It should fixe [https://github.com/OpenMined/PySyft/issues/474](url)
Thanks,

feature: add exp_ to FloatTensor (#474)

---

syft/syft.py

Added inline neg function - issue #540. Has a related PR in Openmined.

Added inline neg function - issue #540

---

syft/syft.py

Add inline round (#571)

---

syft/syft.py

Add Log1p to FloatTensor (#513)

---

syft/syft.py

Addresses issues
OpenMined/PySyft#564
OpenMined/PySyft#563
depends on https://github.com/OpenMined/OpenMined/pull/199

Add remainder

---

syft/syft.py

Add inline log1p FloatTensor (#514)

---

syft/tensor.py

Here it is! @iamtrask  Inline Documentation was added. 
I am not done  with all of the functions in https://github.com/OpenMined/PySyft/blob/master/syft/tensor.py but I have created a pull request so you guys can give me the green light to continue, or if there are something you would like worded differently or some word spelled differently.
I followed the NumPy Style on inline documentation. http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html same as the Deprecated-PySyft. #273  
So just give a thumbs up and I will complete and polish this PR ASAP. 👍

Inline Documentation

---

syft/nn.py
syft/tensor.py

I'm working on upgrading autograd to re-use tensors from the previous dynamic graph when performing the same operations instead of always creating new tensors

started upgrading autograd

---

syft/tensor.py

Removed Duplicate Transpose Function the Original Transpose Function can be found at line 864

Removed Duplicate Transpose Function

---

syft/controller.py
syft/tensor.py

See https://github.com/OpenMined/OpenMined/pull/230

Softmax Function

---

syft/tensor.py

https://github.com/OpenMined/PySyft/issues/590

Feature: add sqrt_ (inline) to FloatTensor (#590)

---

syft/nn.py

This PR is dependent on the corresponding PR in Unity. 
Added CrossEntropyLoss and modified MSELoss to use the new Model/Layer/Loss structure in Unity. 
Please flag as WIP for now.

CrossEntropyLoss

---

syft/nn.py
syft/tensor.py

With this PR we should have a ReLU layer. 
Thanks!

Feature: add ReLU

---

syft/__init__.py
syft/controller.py
syft/functional.py
syft/tensor.py

Created functional.py to store functions such as random() which creates a FloatTensor of a given size. Dependent upon OpenMind pull request [#291
](https://github.com/OpenMined/OpenMined/pull/291)
Created a notebook Test Functional Implementations.ipynb in which new functions can be tested (will add in OpenMined pull request)

Add functions in functional.py

---

syft/tensor.py

Hello,
This PR provide CPU support for Clamp.
[https://github.com/OpenMined/PySyft/issues/443](url)
Thanks,

Add clamp to FloatTensor with CPU support (#443)

---

syft/optim.py

Adds momentum and learning rate decay to SGD

Momentum and Learning Rate Decay for SGD Optimizer

---

syft/optim.py

- Base Optimizer class to inherit from.
- Fixed momentum issue with SGD optimizer
- Added RMSProp
- Added Adam
https://github.com/OpenMined/OpenMined/pull/297

Optimizer improvements (SGD, Adam, RMSProp)

---

syft/nn.py

Add verbosity management to nn module in fit function.
User should be able to manage the verbosity. If verbosity flag on fit function set to True, Progress bar will be shown. 

Manage verbosity nn

---

syft/tensor.py

Dependent upon [https://github.com/OpenMined/OpenMined/pull/303](#303)

add uniform_() and T_() and update random_()

---

.gitignore
syft/grid/__init__.py
syft/grid/grid.py

pysyft side of the openmined -> pysyft grid communication

pysyft side of the openmined -> pysyft grid communication

---

syft/grid/grid.py

quick grid api change

---

syft/tensor.py

Added functionality for var, std, norm and split (#627, #593, #544 and #588). Have made a corresponding pull request for changes to OpenMinded.
* CPU:
* GPU:

Added var, std, norm and split to tensor.py

---

syft/nn.py
syft/tensor.py

Simple tensor ops (a-b) were broken
- [ X ] Bug fix (non-breaking change which fixes an issue)
Tested some notebooks that weren't working for me before

bugfix no-params-func

---

syft/tensor.py

__add__ method for IntTensor

---

syft/interfaces/keras/models/sequential.py

Pass the verbose variable.

---

syft/tensor.py

Implements the abs function for a IntTensor which calls into unity app
Fixes  https://github.com/OpenMined/PySyft/issues/762
OpenMined PR https://github.com/OpenMined/OpenMined/pull/326
Added CPU test in Unity
Verified in notebook (not committed)

Add abs function to IntTensor

---

install_for_anaconda.sh
install_for_anaconda_on_windows.bat
requirements.txt

The dependency `zmq` should be `pyzmq`.

Fix requirements and update conda install scripts

---

syft/tensor.py

Fixes #1246
OpenMined PR: https://github.com/OpenMined/OpenMined/pull/331

Add trace function to intTensor

---

syft/tensor.py
tests/test_inttensor.py

Added implementation of equal().
Fixes https://github.com/OpenMined/PySyft/issues/790
Since there didn't seem to be a test suite in the PySyft repository, a pytest file was added. One of the project leads will need to add a pytest runner in Travis CI though.
* CPU:
* GPU:

IntTensor.equal()

---

syft/tensor.py

Added support for `IntTensor abs_()`. 
Fixes #763 

Added IntTensor abs_

---

syft/tensor.py

Implemented IntTensor Lt and inline Lt on CPU

---

syft/tensor.py

Implemented negate in CPU and GPU for IntTensor. 
Fixes #1075, #1076, #1077, #1078
* CPU:
* GPU:

implemented negate in CPU and GPU for IntTensor (#1075, #1076, #1077, #1078)

---

syft/tensor.py

This PR is for adding Reciprocal functionality to IntTensor using CPU as stated in issue #1146 
* CPU:

Added Reciprocal Functionality

---

syft/tensor.py

This PR is adding sqrt to intTensor on CPU (#1198)
* CPU:
* GPU:
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] New and existing unit tests pass locally with my changes

Feature/intTensor sqrt on CPU (#1198)

---

syft/interfaces/keras/models/sequential.py
syft/metrics.py
syft/nn.py

To make it easier to evaluate the performance of different models, it's nice to have a model.evaluate() function that returns certain metrics and loss.
- Implemented model.evaluate() that returns metrics you provide (this can be custom metrics as well).
- Return the test loss
Dependent upon: https://github.com/OpenMined/OpenMined/pull/316 !
Tested in the Keras notebook.

implement model.evaluate() function

---

syft/tensor.py

see: https://github.com/OpenMined/OpenMined/pull/356

Set remove_after_use to True

---

syft/tensor.py

Implements the sign function for Int Tensors as stated in issue Pysyft OpenMined/PySyft#1174
Corresponding OpenMined PR:  https://github.com/OpenMined/OpenMined/pull/349
Fixes # (issue)  OpenMined/PySyft#1174
- I added a unit test and tested that the functionality of the sign function.
- I ran a jupyter notebook tests of the form, to ensure functionality is accurate.
`data = np.array([[-1,-2,3],[4,5,-6]]).astype('int')`
`m = IntTensor(data)`
`m.sign()`
* CPU: 2.7 GHz Intel Core i5
* GPU: 

added sign function for Int Tensor

---

syft/tensor.py

Inline Reciprocal CPU support functionality for Int Tensors. 
Fixes # (1147)
* CPU: Intel i5-4200 CPU 1.6GHz 2.3GHz
* GPU: AMD Radeon HD 8670M, Intel HD 4400
* Unity Version: latest

Added reciprocal inline functionality for Int Tensor: #1147

---

syft/tensor.py

Added sin functionality for Int Tensors, that accepts an Int tensor and returns a Float Tensor containing the sin of each element.
Fixes #1178, #1180 
* CPU: Windows 10 Intel(R) Core i5-4200U CPU@ 1.6GHz 2.30GHz
* GPU: AMD Radeon HD 8670M Intel(R) HD Graphics 4400
* Unity Version: latest

added sin cpu and gpu functionality for Int tensors.

---

syft/tensor.py
tests/test_inttensor.py

Added T() method to IntTensor with CPU support to calculate the transpose of an IntTensor.
Fixes # (1222)
* CPU: Windows Core-i7
* GPU: GTX 1070
* Unity Version: 2017.03.0f3

Feature/transpose  int tensor

---

syft/tensor.py

Added cos functionality for Int Tensors for CPU and GPU, accepts an Int tensor and returns a Float Tensor containing the cos of each element.
Fixes #890, #892 
* CPU: Windows 10 Intel(R) Core i5-4200U CPU@ 1.6GHz 2.30GHz
* GPU: AMD Radeon HD 8670M Intel(R) HD Graphics 4400
* Unity Version: latest

Added cos functionality for Int Tensors.

---

syft/controller.py
syft/interfaces/keras/layers/dense.py
syft/interfaces/keras/models/__init__.py
syft/interfaces/keras/models/sequential.py
syft/interfaces/keras/models/utils.py
syft/nn.py
syft/onnx/__init__.py
syft/tensor/__init__.py
syft/tensor/float_tensor.py
syft/tensor/int_tensor.py

Hi everyone,
This is PySyft part for the work in progress on serialization in OpenMined [here](https://github.com/OpenMined/OpenMined/pull/314). It's a work in progress.
Check this [OpenMined Issue](https://github.com/OpenMined/OpenMined/issues/296) for more information.
Fixes #
You can find a pseudo-test in the OpenMined repo
**Pseudo-Test Configuration:**
CPU: Ok

WIP: Add a first graph topology serialization using JSON

---

syft/tensor/int_tensor.py
tests/test_inttensor.py

Implements view feature for int tensor with -1 parameter support .
Fixes # (1298)
* CPU: i7 7700
* GPU: GTX 1070
* PySyft Version: latest
* Unity Version: latest

Feature/view  int tensor

---

syft/interfaces/keras/datasets/fashion_mnist.py

Added the function to load Fashion MNIST dataset.
Fixes # (issue):   None
Here's a link to the working code in iPython Jupyter Notebook: 
https://github.com/anujdutt9/tutorials/blob/master/beginner/Keras%20Neural%20Net%20Fashion%20MNIST.ipynb
* CPU: Intel i7
* GPU: NVIDIA Quadro M1000M
* PySyft Version:  92f8726
* Unity Version:  2017.3

Function to Load Fashion MNIST Dataset

---

syft/tensor/int_tensor.py

The bug was fixed by resolving a missing import.

Applied fix for issue #1314

---

syft/tensor/int_tensor.py

This pull request resolves issue #1182 . 
This pull request is the PySyft portion of the implementation. 
See the pull request [OpenMined/OpenMined#418](https://github.com/OpenMined/OpenMined/pull/418) for the unity portion
* CPU: 1.6 GHz Intel Core i5 (MacBook Air (13-inch, Early 2015))
* GPU: Intel HD Graphics 6000 1536 MB
* PySyft Version: 0.1.0
* Unity Version: 2017.3.0f3 Personal
* OpenMined Unity App Version: latest from repo

Implement the Sinh function for IntTensor on the CPU Issue #1182

---

syft/tensor/int_tensor.py

This pull request resolves issue #1242 . This pull request is the PySyft portion of the implementation. See the pull request OpenMined/OpenMined/pull/417 for the unity portion
Fixes #1242
* CPU: iMac (21.5-inch, Mid 2011)  2.8 GHz Intel Core i7
* GPU: AMD Radeon HD 6770M 512 MB
* PySyft Version: Latest
* Unity Version: 2017.3.0f3
* OpenMined Unity App Version: Latest

Implement the Topk function for IntTensor on the CPU #1242

---

syft/tensor/int_tensor.py
tests/test_inttensor.py

Implemented the inline max function for IntTensor on the CPU
Fixes # 795
* CPU: Intel® Core™ i3-2350M CPU @ 2.30GHz × 4
* GPU: -
* PySyft Version: Hydrogen
* Unity Version: 2017.3.0p2 (64bit)
* OpenMined Unity App Version: Hydrogen

Feature/implement the inline max function for int tensor on the cpu #795

---

syft/tensor/int_tensor.py

Adds the Exponent functionality to int tensors
Fixes # (issue) 938 in PySyft
```
I added tests in  IntTensorTest.cs
inputData = { -1, 1, 
3, 34};
expectedData = { 0, 2, 
20, 2147483647};
```

Fixes #938 add Exp to IntTensor

---

syft/tensor/float_tensor.py

New function addr(.) and addr_(.) added to the FloatTensor class.
Fixes #424 and #425 in PySyft
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Passing test in Unity Test Runner for CPU/GPU
- [ x ] Working examples in 'Test Tensor Function Implementations.ipynb' 
* CPU: 3.3GHz Intel Core i7 
* GPU: Intel Iris Graphics 550 1536 MB
* PySyft Version: current
* Unity Version: 2017.3.0f3 Personal
* OpenMined Unity App Version: current
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my …

implement addr on CPU/GPU (with inline)

---

README.md
examples/.ipynb_checkpoints/Empty Example-checkpoint.ipynb
examples/Empty Example.ipynb
examples/experimental/.ipynb_checkpoints/ExperimentalExample-checkpoint.ipynb
examples/experimental/ExperimentalExample.ipynb
setup.py
test/sample_test.py

Init structure

---

.travis.yml

[Travis CI](https://travis-ci.org) is a Continuous Integration tool for running tests which is free for open source projects like this one.  The owner of the this repo would need to go to https://travis-ci.org/profile, login with GitHub ID and flip the repository switch __on__ to enable free automated testing of each pull request.
[Flake8](http://flake8.pycqa.org) tests can help to find Python syntax errors, undefined names, and other code quality issues.
Please describe the tests that you ran to verify your changes. Provide instructions so we can …

Use Travis CI to run tests on all pull requests

---

docs/conf.py
syft/core/torch_/hook.py
syft/core/torch_/utils.py

Adds initial support for Variable operations.
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules

Grid to syft merge

---

examples/PySyft Local Worker Example.ipynb
syft/core/torch_/hook.py
syft/core/torch_/utils.py

bugfix allowing .backward() to work

---

examples/PySyft Local Worker Example.ipynb
syft/core/hooks.py
syft/core/workers.py

Fixes # (issue) NA
* CPU:
* GPU:

Hooks as context manager

---

syft/core/workers.py

renamed arg in _check_workers

---

README.md

Travis CI badge upon request from @iamtrask in slack

Updated README to include travis badge

---

.travis.yml
scripts/execute_notebooks.sh

First attempt to execute and test notebooks as part of travis testing
https://github.com/OpenMined/PySyft/issues/1355
Improved testing (didn't see a checkbox for that)

Adding notebook testing [WIP]

---

syft/core/hooks/torch/hook.py

Fixed-precision tensor added

---

syft/core/hooks/torch/hook.py
test/core/hooks_test.py
test/torch_test.py

fixed_precision updated

---

examples/Federated Learning Example.ipynb

corrected a small typing mistake

corrected typo

---

syft/core/hooks/torch/hook.py
syft/core/workers/base.py
test/torch_test.py

Adds a hook on the torch.nn.functional functions in order to perform training of neural networks.
(See an example of a FeedForward network with `F.relu` activation: [Link to Colab](https://colab.research.google.com/drive/1bqfdAbpg9nk0hIp8vlE7E11TMUQJICuD#scrollTo=ALSfsSFjeV1o))
I added a unit test on Relu
Test Configuration:
Python 3.6.4 :: Anaconda custom (64-bit)
Jupyter Notebook 5.2.2
IPython 6.2.1
PyTorch 0.3.1
(And also Colab config)

Add a hook on torch.nn.functional

---

syft/core/hooks/torch/hook.py
test/torch_test.py

Unit tests for binary methods were added.
#1385 
`python setup.py test`
* CPU:
* GPU:

Unit tests for binary methods were added

---

test/torch_test.py

Unit tests for add_ method were added.  
Fixes  #1385 
New feature (non-breaking change which adds functionality)
python setup.py test

Unit test for _add method was added

---

test/torch_test.py

added tests for iterable and tertiary methods and fixed binary method tests.
Fixes #1385 
Unnittests added
all tests run

Added tests for tertiary and iterable methods

---

test/torch_test.py

Seeded test_federated_learning and added unittest for remote optim.step()
Fixes #1398
Added unittests.
All tests pass.

Seeded test_federated_learning and added test for remote optim.step()

---

test/torch_test.py

Methods for multi-output methods were added
Issue #1385 
* CPU:
* GPU:

Unit tests for multi output methods were added

---

syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
syft/core/workers/base.py

Add basic support and send and get Variable (.grad left as a TODO)
Mainly a base for building new stuff,
in particular operations and methods are not handled (Ipython kernel dies^^)
Tested on .ipynb

[pointers_are_tensors] Add send and get on torch Variable

---

examples/experimental/Call hooked Torch functions on remote tensors.ipynb
examples/experimental/Send, get and call methods on tensors.ipynb
syft/core/frameworks/torch/__init__.py
syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
syft/core/utils.py
syft/core/workers/base.py

[pointers_are_tensors] Torch func support + send/get chain of tensors

---

.travis.yml
examples/websocket/client.py
examples/websocket/server.py
requirements.txt
syft/core/workers/__init__.py
syft/core/workers/base.py
syft/core/workers/websocket.py
test/torch_test.py

This pull request's focus is to replace the existing socket worker with Websocket workers so it can be used for syft.js.

WebSocket for workers (work in progress)

---

scripts/install.sh

Combined commands to make necessary installations a one step process

Installation Script

---

pandas_project/pandas_project.py

This tries to implement the same thing that the pytorch tensors in PySyft do but with pandas data frames. This right now is a very early example of the classes. The Pandas functions are yet to be hooked and the worker class too needs a lot of work.

Created a basic class for pandas

---

syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
syft/core/workers/base.py
test/torch_test.py

There are two cases:
- You're sending a var on a loc:id you're already pointing at -> should abort
- You're pointing at the result of an in-place remote operation like:
x = sy.Variable(torch.FloatTensor([1, 2, -3, 4, 5])).send(bob)
y = x.abs_() # in-place operation
y.get()
x.send(bob) # if x.child != y.child, x will send it's old pointer to bob->trigger an error
You want this to work, but don't want to create a new pointer, just
reuse the old one, and return the old wrapper as well
This fix was done because of the confusion that occured with many tests sending for instance some data at bob:1000
Note that this won't prevent two workers me and alice to point on the same location at Bob. This is a more difficult case to handle, because Bob doesn't know who points to his data. (Even if he …

[tensors_are_pointers] Add handling of conflicting pointers on same (location, id@loc)

---

syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
syft/core/utils.py
syft/core/workers/base.py

Tmp work on handle_call

---

syft/core/frameworks/torch/functions.py
syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
syft/core/utils.py
syft/core/workers/base.py

[pointers_are_tensors] Add support of handling_call on syft tensors

---

syft/__init__.py
syft/core/frameworks/torch/__init__.py
syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
syft/core/utils.py
syft/core/workers/base.py

[pointers_are_tensors] Add elements of PlusisMinus Tensor, calls local on method work

---

examples/experimental/Torch playground.ipynb
syft/core/frameworks/torch/tensor.py
syft/core/utils.py
syft/core/workers/base.py

[pointers are tensors] tmp work on variables

---

syft/core/frameworks/torch/tensor.py
syft/core/utils.py
syft/core/workers/base.py
test/torch_test.py

[pointers are tensors] Add support of Variable on non-trivial chains

---

syft/core/frameworks/torch/tensor.py
syft/core/utils.py
test/torch_test.py

@iamtrask left where we stopped, ie we want to create an attr grad, which for instance could be a pointer, and which will have the same chain as .data
* CPU:
* GPU:

[pointers_are_tensors] Start handling backward

---

syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
test/torch_test.py

[poitners are tensore] Put and .grad hooks and tricks in var methods, add a en/de-code unittest

---

syft/core/frameworks/torch/__init__.py
syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
syft/core/utils.py
syft/core/workers/base.py
test/torch_test.py

- Add in PlusIsMinus Tensor 3 ways of overloading (methods, functions
and attract replacement)
- Move all the non-specific logic of PlusIsMinus tensor to SyftTensor
- Fix the guard TODO and move the guard logic to torch
- Remove some useless methods of SyftTensors
- Light refactor (in utils.py) to benefit from our created functions
- Add comments on tensors.py functions
- /!\ Note that one test is failing, for other reasons
Unittests

[pointers_are_tensor] Transform PlusIsMinus in an example SyftTensor for overloading, etc.

---

syft/core/hooks/torch/hook.py

Added docstrings to hooking methods and fixed precision methods.
Fixes # 1412
No specific test run as this was simply to add in-code documentation.

Add missing docstrings in TorchHook

---

syft/core/frameworks/torch/tensor.py
syft/core/workers/base.py

Light bug fix and comment update, in phase with Issue #1447 concerns
Unittests

[pointers_are_tensors] #1447 Light bug fix and comment update

---

syft/core/frameworks/torch/tensor.py
syft/core/frameworks/torch/utils.py
syft/core/workers/base.py
test/torch_test.py

Add a light pointer referencing system to be able th check very quickly if we already have a pointer to (location, id@loc)
Add minor fixes related to executing a fed learning task, and fixing the hook on backward 
Unittest

[Pointers are tensors] Improve the get_pointer_to func: Add a pointer referencing system

---

syft/core/frameworks/torch/tensor.py
syft/core/frameworks/torch/utils.py
test/torch_test.py

Just some fix made while building notebooks of fed learning with Boston Housing and MNIST dataset
Unittests and notebook examples

[Pointers are tensors] Small fix to have a good PoC of Fed Learning on images (MNIST)

---

examples/Boston_Housing_Federated_Training.ipynb
examples/Federated_Learning_Example.ipynb
examples/SocketWorker Client.ipynb
examples/SocketWorker Server.ipynb
syft/core/frameworks/torch/utils.py
syft/core/workers/socket.py

Refresh and extend the notebooks examples. In particular SocketWorker still work!

[Pointers are tensors] Refresh and extend the notebooks examples

---

Dockerfile

- This is the first attempt to decrease the docker-image size "actually decreased by > 100 MB right now" by using an official python-alpine base image and adding needed alpine packages for the builds purposes :)

Minimizing project's docker-image

---

Dockerfile
README.md

Updating docs in README.md file to reflect the new size detail of the project's docker image.

Updating docs in README.md file

---

docs/_build/html/_autosummary/syft.core.frameworks.torch.html
docs/_build/html/_autosummary/syft.core.utils.html
docs/_build/html/_autosummary/syft.core.workers.html
docs/_build/html/_modules/index.html
docs/_build/html/_modules/syft.core.frameworks.html
docs/_build/html/_modules/syft.core.frameworks.torch.html
docs/_build/html/_modules/syft.core.html
docs/_build/html/_modules/syft.core.workers.html
docs/_build/html/_modules/syft.html
docs/_build/html/_modules/syft.mpc.html
docs/_build/html/_modules/syft.mpc.interface.html
docs/_build/html/_static/basic.css
docs/_build/html/_static/doctools.js
docs/_build/html/_static/searchtools.js
docs/_build/html/_static/websupport.js
docs/_static/css/PySyft_docs.css

Formated html, css, js files.
```
docs/_build/html/_autosummary/syft.core.frameworks.torch.html
docs/_build/html/_autosummary/syft.core.utils.html
docs/_build/html/_autosummary/syft.core.workers.html
docs/_build/html/_modules/index.html
docs/_build/html/_modules/syft.core.frameworks.html
docs/_build/html/_modules/syft.core.frameworks.torch.html
docs/_build/html/_modules/syft.core.html
docs/_build/html/_modules/syft.core.workers.html
docs/_build/html/_modules/syft.html
docs/_build/html/_modules/syft.mpc.html
docs/_build/html/_modules/syft.mpc.interface.html
docs/_build/html/_static/basic.css
docs/_build/html/_static/doctools.js
docs/_build/html/_static/searchtools.js
docs/_build/html/_static/websupport.js
docs/_static/css/PySyft_docs.css 
```
1) remove multiple empty newlines.
2) Format …

Format all html,css and js files in docs folder

---

examples/numpy/Federated Learning.ipynb

initial federated learning example in numpy

numpy federated learning example

---

syft/core/frameworks/torch/tensor/fixed_precision_tensor.py
syft/core/frameworks/torch/tensor/generalized_pointer_tensor.py
syft/core/frameworks/torch/tensor/local_tensor.py
syft/core/frameworks/torch/tensor/mpc_tensor.py
syft/core/frameworks/torch/tensor/plus_is_minus_tensor.py
syft/core/frameworks/torch/tensor/pointer_tensor.py
syft/core/frameworks/torch/tensor/syft_tensor.py
syft/core/frameworks/torch/tensor/torch_object.py
syft/core/frameworks/torch/tensor/torch_tensor.py
syft/core/frameworks/torch/tensor/torch_variable.py

Revert "added newlines"

---

examples/torch/toy/Toy MPC Example.ipynb
syft/core/frameworks/torch/tensor.py
syft/core/workers/base.py
test/torch_test.py

MPCTensor can now be wrapped by another torch object.

MPCTensor can now be wrapped by a Torch object

---

examples/torch/toy/Toy MPC Example.ipynb
syft/core/frameworks/torch/tensor.py

added sum and cumsum

---

syft/core/frameworks/torch/tensor.py
syft/mpc/spdz.py

Add matmul on MPCTensor (See Todo for neg values)

---

syft/core/frameworks/torch/tensor.py
syft/mpc/spdz.py
test/torch_test.py

Fix approx error in mpc ops due to div on integer

---

examples/other/experimental/kerasTensorflow/keras_distributed_classifier.py
examples/other/experimental/kerasTensorflow/keras_federated_classifier.py
syft/core/frameworks/tensorflow/federated_averaging_optimizer.py

Add keras tensorflow examples and correct custom optimizer to work with ResourceVariables used by keras.
Fixes [# 1521](https://github.com/OpenMined/PySyft/issues/1521)

Added keras examples and changed optimizer to work with keras

---

syft/core/frameworks/torch/tensor.py
syft/mpc/spdz.py
test/torch_test.py

solving https://github.com/OpenMined/PySyft/issues/1501 #1501

MPC Addition With Arbitrarily Large Numbers of Parties #1501

---

syft/core/frameworks/torch/tensor.py

Need to fix tripple generation to work with gpt but logic is there otherwise.

sigmoid with incorrect triple generation

---

syft/core/frameworks/torch/tensor.py

Off to class otherwise would finish this up now. Is close to working but some of the types are wrong. Is for #1514

almost working decode

---

syft/mpc/spdz.py

Fixes https://github.com/OpenMined/PySyft/issues/1526

typo in spdz.py

---

examples/other/experimental/Untitled3.ipynb
examples/torch/toy/Toy MPC Example.ipynb
test/torch_test.py

This fixed some mysteriously broken unit tests on my machine - which were only broken because some of them were getting run BEFORE the hooking process had begun (super strange). This fixed the issue for me, hopefully fixes https://github.com/OpenMined/PySyft/issues/1520 as well

fixed unit tests

---

syft/core/frameworks/torch/tensor.py
syft/mpc/spdz.py

The purpose of this Pull Request is to implement the functionality described in https://github.com/OpenMined/PySyft/issues/1510

WIP: Create a FixedPrecision Tensor

---

examples/other/experimental/new mpc demo.ipynb
examples/torch/Fixed Precision Tensor Testing.ipynb
syft/core/frameworks/torch/tensor.py

Just showed how to use fixed precision tensor on remote pointer tensor. Should also work on MPCTEnsor

Fixed Precision Tensor on Remote Pointer

---

examples/other/experimental/Untitled4.ipynb
syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
test/torch_test.py

fixes https://github.com/OpenMined/PySyft/issues/1534

got scalar mult working

---

syft/core/_types.py
syft/core/utils.py

First attempt of adding gradual typing over the source code, i started by "utils.py" file and welling to continue working from there and making types even better :)

First attempt of adding gradual typing

---

syft/mpc/securenn.py
syft/mpc/test_utils.py
test/mpc/mpc_test.py
test/mpc/secnn_test.py

This pull request is for the new SecureNN functionality which will equip our MPC system with the ability to perform private comparisons, as documented in https://github.com/OpenMined/PySyft/issues/1509

WIP - SecureNN Integration

---

syft/core/workers/base.py

added space in worker error message

---

syft/mpc/securenn.py
syft/spdz/spdz.py
test/mpc/mpc_test.py
test/mpc/secnn_test.py
test/mpc/test_utils.py

tests and fixes

---

syft/mpc/securenn.py

extensions and fixes

---

README.md

Updated ReadMe.md for PyTorch 0.3.1 installation on Windows

Update ReadMe.md for PyTorch 0.3.1 install on Windows

---

.github/ISSUE_TEMPLATE.md

Update ISSUE_TEMPLATE.md to fix issue #1549

---

examples/other/experimental/securenn/Untitled.ipynb
syft/core/frameworks/torch/__init__.py
syft/core/frameworks/torch/tensor.py
test/tensor_serde_test.py
test/torch_test.py

i'm ashamed of how inefficiently implemented this is right now - but i ran into a few bugs with more efficient implementations that i don't have time to fix before the Monday deadline. 
All that is to say- i've named it "very_slow_argmax" just to make the point that we need to fix it.

basic argmax

---

.travis.yml

Fixing indentation in .travis.yml should make TravisCL build and test PR again.

Fix indentation in .travis.yml

---

syft/core/frameworks/numpy/ndarray.py

Performance improvement changes - replaced for loop with list comprehension and map

#1605 replaced for loop with list comprehension and map

---

syft/core/workers/base.py

Raising an error (MemoryError) while trying to send a model to it's own worker.
Correcting some (2 actually) typos in `base.py`

Hargathor patch model send

---

syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
syft/core/frameworks/torch/utils.py
syft/core/workers/base.py

Optimize enforce_owner and reduce usage ; rm heavy type checks ; -13%
Fix _LocalTensor handle_call and remove useless chain fix calls

Optimize chain structure controls and add an extra 13% speed up

---

syft/core/frameworks/numpy/ndarray.py

reverting changes to #1605

---

.gitignore
examples/torch/toy/Basic Log Tensor Example.ipynb
examples/torch/toy/Federated_Learning_Example.ipynb
syft/__init__.py
syft/core/frameworks/torch/__init__.py
syft/core/frameworks/torch/constants.py
syft/core/frameworks/torch/tensor.py
syft/core/frameworks/torch/utils.py

Log tensor

---

syft/core/frameworks/__init__.py

import syft.core fails as the torch folder is in the frameworks subfolder

Wrong import path fixed.

---

.pre-commit-config.yaml
LICENSE
README.md
examples/other/experimental/kerasTensorflow/keras_distributed_classifier.py
examples/other/experimental/kerasTensorflow/keras_federated_classifier.py
syft/__init__.py
syft/core/frameworks/encode.py
syft/core/frameworks/numpy/ndarray.py
syft/core/frameworks/pandas/utils.py
syft/core/frameworks/tensorflow/federated_averaging_optimizer.py
syft/core/frameworks/torch/__init__.py
syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
syft/core/frameworks/torch/utils.py
syft/core/utils.py
syft/core/workers/base.py
syft/mpc/securenn.py
syft/spdz/interface/__init__.py
test/core/frameworks/__init__.py
test/core/frameworks/pandas/pandas_test.py
test/core/workers_test.py
test/mpc/mpc_test.py
test/mpc/secnn_test.py
test/mpc/test_utils.py
test/torch_test.py

Still needs line length and bare excepts fixed

[WIP] Fix flake 8 errors

---

test/core/frameworks/encode_test.py

This PR includes tests for `PythonEncoder` as it is in its current state

Tests for current PythonEncoder

---

syft/serde.py
test/test_serde.py

Added the logic (if necessary) for range serde.
Added a unit test
Added add docstrings for all methods describing their functionality including an example of how to serialize it

Solved: Add serde logic for range #1664

---

README.md

This should be somewhere on the README!

add arxiv abstract link to README

---

syft/serde.py
test/test_serde.py

added logic for np.ndarray serialization and deserialization
added unit test demonstrating proper serde of np.ndarray objects
added docstrings for all methods describing their functionality including an example of how to serialize/deserialize it.

Solved: Add serde logic for np.ndarray #1670

---

.flake8
.gitignore
.travis.yml
docs/conf.py
pyproject.toml
setup.py
syft/frameworks/torch/__init__.py
syft/frameworks/torch/mpc/__init__.py
syft/serde.py
syft/workers/__init__.py
syft/workers/base.py
test/test_serde.py
test/workers/test_virtual.py

Adjusted some config files and reformatted the code to pass travis

Solved: Fix travis ci build process #1685

---

setup.cfg

Revert "Using pytest to execute tests from now on."

---

.travis.yml
setup.cfg

Some unnecessary comments due to a problem after the initial PR got reverted. This one should work now

Using pytest for text execution. 

---

examples/tutorials/Part 1 - The Basic Tools of Private, Decentralized Data Science.ipynb
examples/tutorials/Part 2 - Intro to Federated Learning.ipynb
examples/tutorials/Part 4 - Federated Learning via Trusted Aggregator.ipynb
examples/tutorials/Part 5 - Intro to Encrypted Programs.ipynb

- Switched language to the more precise "model averaging"
- Added an evaluation of the resulting model
- Pointer to a future gradient averaging tutorial
- Fix a few typos
- Add a bit of code typesetting

Last minute tutorials touch-up

---

syft/serde.py
test/test_serde.py

- Solving #1637 
- Adding _compressed_ test to all serde tests

Solving #1673 - adding logic to serde python slice objects.

---

syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py
syft/core/workers/base.py
syft/core/workers/socket.py
test/torch_test.py

Fix:
https://github.com/OpenMined/PySyft/blob/master/examples/torch/toy/SocketWorker%20Server.ipynb
https://github.com/OpenMined/PySyft/blob/master/examples/torch/toy/SocketWorker%20Client.ipynb
Which underlines that worker.search(#dataset)  is broken

Fix the search function accordingly to ex/torch/toy sockets workers

---

examples/torch/Boston_Housing_Federated_Training with Diff Privacy CLIENT.ipynb
examples/torch/Boston_Housing_Federated_Training with Diff Privacy SERVER.ipynb

When effectively implementing Federated Learning in real world applications, it is important to build an architeture where data on a remote server could be accessed in order to train and test the model.
In the previous examples this is implemented using virtual clients. This example attempts to implement it over websockets.

Federated Learning with Differential Privacy on Remote Machine

---

syft/frameworks/torch/tensors/native.py
syft/frameworks/torch/tensors/pointer.py
syft/workers/base.py
test/tensors/test_native.py
test/torch/tensors/test_tensor.py

Some firsts tests added for TorchTensor and the get_method.
Some functionality is still missing to make the tests pass.

First tests added

---

test/test_serde.py

Testcases for #1665

---

test/test_serde.py

Testing serde fucntionality after hooking in regards to #1748.

---

CONTRIBUTORS.md

This was created by me and @Nivek92. We propose this as the first draft of an entry point for new contributors and defining rules for current contributors. This way we can formalize the rules for contributions and aim for a clean, readable and well-designed code base.

First Draft for a guide on how to contribute to pysyft.

---

examples/tutorials/Part 1 - The Basic Tools of Private, Decentralized Data Science.ipynb

PR created based on a thread regarding this error on the `general-discussion` Slack channel.

Add "forgot to create TorchHook object" error.

---

README.md
requirements.txt

updated requirements.txt and installation instructions 

---

.pre-commit-config.yaml
syft/frameworks/torch/hook.py
syft/frameworks/torch/tensors/__init__.py
syft/frameworks/torch/tensors/native.py
syft/frameworks/torch/torch_attributes.py

This Refactor is currently WIP. The PR includes:

Refactoring the syft hook and adding correct documentation.

---

.pre-commit-config.yaml
syft/frameworks/torch/hook.py
syft/frameworks/torch/tensors/native.py
syft/frameworks/torch/tensors/pointer.py
syft/frameworks/torch/torch_attributes.py
syft/serde.py
syft/workers/__init__.py
syft/workers/abstract.py
syft/workers/base.py
test/test_serde.py
test/torch/tensors/test_native.py
test/torch/test_hook.py
test/workers/test_base.py
test/workers/test_virtual.py

This aims at solving #1694 #1697, parts of #1695
This is still work in progress.
Simplify should work correctly.
Deserialization is not done yet.

Add pointer tensor serialization

---

syft/core/frameworks/torch/hook.py
syft/core/frameworks/torch/tensor.py

This is the first version. I will incrementally add more and then we could merge it.

Type Annotations for 0.3.1

---

syft/exceptions.py
syft/serde.py
syft/util.py
syft/workers/base.py
test/test_serde.py
test/workers/test_worker.py

* Rename utils to exceptions
* Add raise exception in `serde.py`
* Add tests for getting exceptions
* Small style fixes

Rename utils.py -> exceptions.py and add tests.

---

syft/frameworks/torch/hook.py
syft/frameworks/torch/tensors/abstract.py
syft/frameworks/torch/tensors/native.py
syft/frameworks/torch/tensors/pointer.py
syft/frameworks/torch/torch_attributes.py
syft/workers/base.py

This is my first PR to PySyft. 
In this PR, I have updated docstrings on two classes:
* frameworks/torch/tensors/abstract.py
* frameworks/torch/tensors/native.py

Add google style for docstrings #1784

---

examples/tutorials/Part 5 - Intro to Encrypted Programs.ipynb

The shell next to shell 28
input : z  = x == y + 20
z.get()
output : 1

Updated the Shell output

---

syft/frameworks/torch/hook.py
syft/frameworks/torch/hook_args.py
syft/frameworks/torch/tensors/native.py
syft/serde.py
test/test_serde.py
test/torch/tensors/test_logging.py
test/torch/tensors/test_native.py
test/torch/tensors/test_parameter.py
test/torch/test_hook.py

Change the way Parameter is hooked
and hook module,
Try to have a basic fed learnin example working
I think the PR is ok for now. We're really close to have this FL example (just try running tutorial Part2).

Remote Parameters and nn modules hooking

---

syft/__init__.py
syft/exceptions.py
syft/frameworks/torch/tensors/abstract.py
syft/frameworks/torch/tensors/native.py
syft/frameworks/torch/tensors/pointer.py
syft/serde.py
syft/workers/base.py
test/torch/tensors/test_logging.py
test/torch/tensors/test_pointer.py

Also adds automatic support for .grad pointer

adds support for pointers to attributes on remote tensors

---

examples/experimental/DP Tensor Experimentation - v1.ipynb
examples/experimental/DP Tensor Experimentation - v2.ipynb
setup.py
syft/__init__.py
syft/frameworks/torch/torch_attributes.py

needed an extra line in torch.exclude because torch.range and torch.arange were not working. Also added an additional experiment for DP

Bugfix and additional experimental notebook

---

CONTRIBUTING.md

Will replicate this functionality for a pr to master (ironic, I know)

updated contributing to say make pr's to dev

---

syft/frameworks/torch/hook.py
syft/frameworks/torch/torch_attributes.py
syft/workers/base.py
test/torch/tensors/test_gc.py

Fix remote in-place method garbage collection error

---

syft/frameworks/torch/hook_args.py
test/torch/test_hook.py

Added a typed identity function for numbers

Fix the hook args issue #1948

---

README.md

Add a link to a colab nb with a working setup

Add a TroubleShooting section in the Readme

---

syft/serde.py
test/test_serde.py

Detail id int fix

---

examples/tutorials/README.md

updated the README as secure aggregation  doesn't seem to be covered yet

fix tutorial links

---

examples/experimental/Introduction to Plan.ipynb

Add time execution log to relevant cells and clear cells outputs.

 Add time execution log to relevant cells.

---

examples/tutorials/Part 2 - Intro to Federated Learning.ipynb

The previous version was using pysyft's optimizer which does not exist. Now it is using torch's optimizer.

Fix tutorial Part 2.

---

test/workers/test_plan.py

This is the result of a [~~pair~~ triple programming section](https://github.com/OpenMined/PySyft/commit/66f5cc9688f5c74140772766420ba5d034d24c01) with @robert-wagner and @jlebensold.

Add test for plan serialization and deserialization

---

syft/__init__.py
syft/federated/__init__.py
syft/federated/train_config.py
syft/serde.py
test/federated/test_train_config.py

TrainConfig draft

---

syft/frameworks/torch/federated/dataset.py

Takes care of workers with integer ids.

Fix minor bug in class FederatedDataset

---

CONTRIBUTING.md
INSTALLATION.md
README.md

pre-commit is installed via requirements-dev.txt not requirements.txt
Markdown source formatting (based of markdownlint)

Cleanup markdown docs

---

.gitignore
examples/experimental/Sockets/Android Proxy.ipynb
examples/experimental/Sockets/Socket Bob.ipynb
examples/experimental/Sockets/socketio_server_demo.py
requirements.txt
syft/workers/__init__.py
syft/workers/socketio_client.py
syft/workers/socketio_server.py
syft/workers/websocket_client.py
test/workers/test_websocketIOClientWorker.py
test/workers/test_websocketIOServerWorker.py
test/workers/test_websocket_worker.py

A `socketio` server worker implementation to allow sync-ed communication with other systems.
The server worker is used to communicate with an Android app (see https://github.com/OpenMined/AndroidWorker)
Initially open here https://github.com/OpenMined/PySyft/pull/2013

SocketIO server that allows sync communication with Android

---

syft/federated/plan.py
test/federated/test_plan.py

Small bugfix in function Plan.replace_worker_ids to support integer ids
Added tests

added testing of plan functions, small bugfix

---

syft/codes.py
syft/frameworks/torch/tensors/interpreters/pointer.py
syft/generic/object_storage.py
syft/serde.py
syft/workers/base.py
test/federated/test_plan.py
test/torch/tensors/test_pointer.py
test/workers/test_websocket_worker.py

Fixes #2076.
Main changes are:
- tensor.garbage_collected_data is now serialized/deserialized.
- Created a force remove object operation (FORCE_RM_OBJ), the only difference from regular remove object operation is that if the tensor being removed has a child (pointer tensor) than it forces the child to be garbage collected.
- FORCE_RM_OBJ is needed to force all the chain to be removed if the "end" point tensor deleted and has garbage_collected_data attribute equals to True.
- Some test improvements :smile: !

WIP: Fix #2076

---

examples/tutorials/advanced/Federated Recurrent Neural Network.ipynb

Added Jupyter Notebook code for a Recurrent Neural Network based on two models being learned in a federated way. The RNN is used for text classification as belonging to a certain category. 
The code was also tested with Raspberry Pis using remote worker websockets. 
Federated implementation of: https://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html

Recurrent Neural Network for Text Classification - Advanced Example

---

syft/frameworks/torch/tensors/interpreters/derivatives.yaml
syft/frameworks/torch/tensors/interpreters/gradients.py
test/torch/tensors/test_autograd.py

I've commented on the test case with multiple chained operations because I think this is still work in progress, right @mcleonard ?

Fix issue from #2148

---

requirements.txt
syft/frameworks/torch/hook/hook.py
syft/frameworks/torch/hook/hook_args.py
syft/frameworks/torch/tensors/interpreters/native.py
test/conftest.py
test/torch/tensors/test_gc.py

Fix #2126 related to the new version 1.1 of Pytorch

Add support for Pytorch 1.1

---

examples/tutorials/Part 1 - The Basic Tools of Private Deep Learning.ipynb

modified the import statement for PointerTensor to syft.frameworks.torch.pointers from syft.frameworks.torch.tensors.interpreters

corrected import error for PointerTensor

---

examples/tutorials/advanced/Federated Recurrent Neural Network.ipynb

Fix for issue #2218 by moving the position of the torch.no_grad() call

Fixed predict method in RNN jupyter notebook example

---

syft/workers/tfe.py

Fix TFEWorker Windows bug

---

examples/tutorials/advanced/Federated Learning with TrainConfig/Introduction to TrainConfig.ipynb
syft/federated/federated_client.py
test/federated/test_federated_client.py
test/federated/test_train_config.py

FederatedClient was using an outdated optimizer when receiving a new TrainConfig object. 
Reset the optimizer in this case.

Correct optimizer handling in FederatedClient

---

syft/frameworks/torch/tensors/interpreters/precision.py
test/torch/tensors/test_additive_shared.py
test/torch/tensors/test_precision.py

Fix 2273 - operating Fix Prec and Additive Shared tensors with constants

---

Makefile
syft/frameworks/torch/tensors/interpreters/multi_pointer.py
test/torch/tensors/test_multi_pointer.py

fixed error in makefile and multipointer serialization

---

syft/serde/native_serde.py
syft/serde/serde.py
syft/serde/torch_serde.py
test/test_serde.py

Dinamically build simplifiers and detailers

---

syft/serde/serde.py
syft/workers/virtual.py
test/test_serde.py

Test virtual worker serialization

---

examples/tutorials/advanced/Federated Learning Reinforcement Learning Agent.ipynb

Tutorial for using pysyft to train a reinforcement learning agent in a CartPole environment

Added tutorial for using pysyft to train a reinforcement learning agent

---

syft/frameworks/torch/tensors/interpreters/precision.py
syft/serde/serde.py
test/test_serde.py

Implement simplify and detail for FixedPrecisionTensor

---

syft/federated/federated_client.py
test/federated/test_federated_client.py

Check if dataset key exists before running fit and fix epochs

---

examples/tutorials/Part 10 - Federated Learning with Secure Aggregation.ipynb
syft/frameworks/torch/pointers/pointer_tensor.py
syft/frameworks/torch/tensors/interpreters/additive_shared.py
syft/frameworks/torch/tensors/interpreters/native.py
test/torch/tensors/test_additive_shared.py

Fix operations on pointers to additive shared tensors #2352

---

syft/frameworks/torch/tensors/interpreters/additive_shared.py
syft/frameworks/torch/tensors/interpreters/precision.py
test/torch/tensors/test_additive_shared.py
test/torch/tensors/test_precision.py
test/workers/test_websocket_worker.py

Added support for torch.dot in FPT and AST
Fix #2368

Support torch dot

---

examples/tutorials/Part 9 - Intro to Encrypted Programs.ipynb

I think, there should be 'operates' instead of 'operate'

use 'operates' instead of 'operate'

---

requirements.txt

For now, we had to downgrade torch (force version 1.1) and torchvision (force version 0.3)

Fix build issues by downgrading torch

---

syft/frameworks/torch/hook/hook.py

remove TODO as flag is used

---

syft/frameworks/torch/hook/hook.py
test/torch/test_hook.py

Revert "Remote Gradient Clipping for PySyft Tensors"

---

README.md

Fix logo link in Readme

---

.gitignore
test/message/test_plan.py

Test for plans using `send`.
Closes #2539

Added test with send in plan

---

syft/frameworks/torch/tensors/interpreters/native.py
test/conftest.py
test/torch/tensors/test_autograd.py

Fix #2447 calling share(..., requires_grad=True) on pointers

---

syft/frameworks/torch/differential_privacy/pate.py
test/torch/differential_privacy/test_pate.py

Avoid calling torch.tensor() with tensor argument to remove warning

---

syft/workers/websocket_client.py

#2586 @LaRiffle _send_msg is now just a wrapper around _recv_msg and should make the lines sending messages easier to read

Use _send_msg for websocket clients instead of _recv_msg

---

syft/grid.py

I think the code looks more readable as in proposed change than before.

Fix code formatting in grid.py

---

syft/workers/base.py
test/message/test_plan.py
test/torch/tensors/test_precision.py
test/workers/test_base.py

**Changes:**
* Add decorator such that we could have a python ctx by calling a method
* Changed one of the tests that were using the *is_client_worker* member explicitly.
LE: Fixes #2689

Add python context to base worker

---

CONTRIBUTING.md

* In the new folder structure there should be ```pip install -r pip-dep/requirements.txt```.

Update documentation for installing requirements

---

syft/exceptions.py
syft/workers/base.py

Added worker arg to exceptions' `simplify`

Fix test_websocket_worker_multiple_output_response unit test

---

examples/tutorials/Part 11 - Secure Deep Learning Classification.ipynb

Fixed SMPC tutorial link

---

README.md

As more than one docker image is used, the directory structure changed a bit which needs to be reflected in the documentation.

Update docs with new directory structure of docker images

---

README.md

It's an learning resources, found it helpful @iamtrask and also you have mentioned it.PR welcome.

code base explained

---

examples/tutorials/advanced/websockets-example-MNIST-parallel/run_websocket_client.py
syft/federated/federated_client.py
syft/frameworks/torch/hook/hook.py
test/federated/test_federated_client.py
test/torch/federated/test_utils.py
test/torch/hook/test_hook.py

New default merge branch changed from dev => master. 
GPU bug fix was only merged into dev, not master.

Enable CUDA processing in PySyft (#2735)

---

examples/tutorials/advanced/Introduction to Promises and PromiseTensors.ipynb

A basic introduction to these new PySyft objects

Tutorial on Promises and PromiseTensors

---

examples/tutorials/español/Parte 01 - Herramientas básicas de aprendizaje profundo privado.ipynb

feat: Translation to spanish of the Part 01 - The Basic Tools of 
private deep learning.
This comes as a response to the initiative to translate all the 
PySyft tutorials, as it is desirable to learn PySyft in our native
language.
As requested, every part of the tutorial is done via pull request 
separately to:
- Track better the changes in every document.
- Avoid double work.
Resolves: #2775
See also: #2782

Translation to spanish of the tutorial Part 01

---

README.md

Siraj Raval has been [involved in a number of controversies](https://www.google.com/search?client=firefox-b-1-d&q=siraj+raval+fraud), and is generally considered by the wider data science community to be a known plagiarizer.
It is best to avoid association with him in this project (even if the linked content was useful).

Remove Siraj Raval from README

---

examples/tutorials/translations/español/Parte 12 - Entrenar una red neuronal encriptada con datos encriptados .ipynb

Hi. Mexican engineer based in Canada here. 
I jumped ahead to tutorial number 12 to avoid conflicts with other Spanish speaking contributors.
Please review and advise. 
Thanks

Added Spanish translation for tutorial part 12

---

examples/tutorials/translations/hindi/Part 03 - Advanced Remote Execution Tools.ipynb

Ref: #2774 
Completed the translation of Tutorial `Part 3`
fix: #2774 
See also: #2787,  #2811
Signed-off-by: Arkadip <in2arkadipb13@gmail.com>

feat: Added Part 3 of hindi translation tutorial

---

examples/tutorials/Part 08 - Introduction to Plans.ipynb

Fix typo "Part 8 bias" => "Part 8 bis"

Update Part 08 - Introduction to Plans.ipynb

---

Makefile
pip-dep/requirements.txt

when trying to run tests locally, I noticed that I kept getting errors for missing packages in the requirements files.

add missing python packages and edit makefile

---

Makefile

I do not know if this important, since things work fine on my local machine. But I feel I should have added this when I submitted #2870.
Would like some input on what does it exactly change.

add requirements_notebooks.txt to reqs

---

pip-dep/requirements.txt
syft/messaging/protocol.py
syft/serde/protobuf/proto.py
syft/serde/protobuf/serde.py
test/serde/protobuf/test_protobuf_serde_full.py
test/serde/serde_helpers.py

Adds protobuf serialization/deserialization for Protocol class.
NOTE: I didn't do anything about this: https://github.com/OpenMined/PySyft/issues/2887#issuecomment-573551054
Related syft-proto PR: https://github.com/OpenMined/syft-proto/pull/25
Please don't merge, requirements.txt must be changed first.

Add protobuf for Protocol class

---

examples/tutorials/translations/indonesian/Bagian 01 - Peralatan Dasar untuk Privasi Pembelajaran Dalam.ipynb

Translation to Indonesian Tutorial - Part 01

---

examples/tutorials/translations/español/Parte 04 - Aprendizaje Federado via un Agregador Confiable.ipynb

* Translation to Spanish of the tutorial Part 04
feat: Translation to Spanish of Part 04 - Federated Learning via Trusted Aggregator.
This comes as a response to the initiative to translate all the
PySyft tutorials, as it is desirable to learn PySyft in our native
language.
As requested, every part of the tutorial is done via pull request
separately to:
- Track better the changes in every document.
- Avoid double work.
Resolves: https://github.com/OpenMined/PySyft/issues/2775
See also: https://github.com/OpenMined/PySyft/issues/2782

Translation to Spanish of the tutorial Part 04

---

syft/frameworks/torch/nn/conv.py
syft/frameworks/torch/nn/pool.py
test/torch/nn/test_pool.py

Solves #2927, also modifies the test for handcrafted pooling layer to check for exact match

Perform direct summation in handcrafted layers

---

examples/tutorials/translations/español/Parte 08 - Introducción a los Planes.ipynb

Changes made by @socd06
This comes as a response to the initiative to translate all the
PySyft tutorials, as it is desirable to learn PySyft in our native
language.
As requested, every part of the tutorial is done via pull request
separately to:
- Track better the changes in every document.
- Avoid double work.
Resolves: #2775
See also: #2782

Translation to Spanish of Part 08 - Introduction to Plans.

---

examples/tutorials/translations/español/Parte 08 bis - Introducción a Protocolos.ipynb

This comes as a response to the initiative to translate all the
PySyft tutorials, as it is desirable to learn PySyft in our native
language.
As requested, every part of the tutorial is done via pull request
separately to:
Track better the changes in every document.
Avoid double work.
Resolves: #2775
See also: #2782

feat: Translation to Spanish of part 08 bis

---

examples/tutorials/translations/bengali/Part 13a - Secure Classification with Syft Keras and TFE - Public Training.ipynb
examples/tutorials/translations/bengali/Part 13b - Secure Classification with Syft Keras and TFE - Secure Model Serving.ipynb
examples/tutorials/translations/bengali/Part 13c - Secure Classification with Syft Keras and TFE - Private Prediction Client.ipynb

Translated Notebooks:
- Part 13a - Secure Classification with Syft Keras and TFE - Public Training.ipynb
- Part 13b - Secure Classification with Syft Keras and TFE - Secure Model Serving.ipynb
- Part 13c - Secure Classification with Syft Keras and TFE - Private Prediction Client.ipynb

Add Bengali Translated Notebooks

---

README.md

I just removed a "\n"
btw, [see](https://github.com/OpenMined/PySyft/workflows/Run%20notebook%20tests/badge.svg) :fallen_leaf:

[minor fix] fix notebooks test badge at README

---

examples/tutorials/translations/bengali/Part 12 bis - Encrypted Training on MNIST.ipynb

Translated Notebooks:
Part 12 bis - Encrypted Training on MNIST.ipynb

Add Bengali Translated Notebooks #Part 12 bis

---

examples/tutorials/translations/bengali/Part 12 - Train an Encrypted Neural Network on Encrypted Data.ipynb

Translated Notebooks:
Part 12 - Train an Encrypted Neural Network on Encrypted Data.ipynb

Add Bengali Translated Notebooks #Part 12

---

test/notebooks/test_notebooks.py

Same as #3034, but this time exclude translated titles too.

Failing tutorial translations should be ignored

---

examples/tutorials/translations/português/Parte 01 - As Ferramentas Básicas do Private Deep Learning.ipynb

Tutorial Part 1 in Portuguese

---

syft/frameworks/torch/tensors/interpreters/autograd.py
syft/frameworks/torch/tensors/interpreters/precision.py
test/torch/tensors/test_autograd.py
test/torch/tensors/test_precision.py

No need for requires_grad for input data

---

examples/tutorials/translations/bengali/Part 11 - Secure Deep Learning Classification.ipynb

Translated Notebook:
Part 11 - Secure Deep Learning Classification.ipynb

Add Bengali Translated Notebooks #Part 11

---

.github/workflows/run-tests.yml
pip-dep/requirements_dev.txt

As mentioned in #3029.
I am making the assumption that only /syft is worth working on, as I don't see the need for the test suite for example to be covered regarding this case.
Let me know if I am wrong.

CI security testing

---

.github/workflows/publish.yml
.github/workflows/update-docker-image.yml

See https://github.com/OpenMined/PySyft/pull/3030 for more details.

Correct build context for dockerhub update via GitHub Actions

---

.github/workflows/tests.yml
.github/workflows/tutorials.yml
setup.cfg
test/conftest.py

The tutorial tests take about 15 minutes to run, which is approximately
equal to the running time of all the rest of the tests. Running them in
parallel should speed up the PR checks.

Split the (English) tutorial tests into a separate Github Action

---

.github/workflows/translated-tutorials.yml
test/notebooks/test_notebooks.py

Fix git command from https://github.com/OpenMined/PySyft/pull/3064

Fix git command in translated tutorials test

---

.github/workflows/translated-tutorials.yml

Change depth to 1 during fetch in the tutorial translation builds (https://github.com/OpenMined/PySyft/pull/3085)

Change depth in fetch

---

.github/workflows/update-docker-image.yml

No need to install python to build and push the image.

Remove python installation

---

examples/tutorials/grid/Part 01 - Intro to Grid Platform.ipynb

spelling correction in grid tutorial  Part 01

---

examples/tutorials/translations/french/Part_01_The_Basic_Tools_of_Private_Deep_Learning.ipynb

Translated the first tutorial from English to the French language.
Issue #2881 #2782

Translation to french of the tutorial part 01

---

examples/tutorials/translations/chinese/Part 10 - Federated Learning with Secure Aggregation.ipynb

Update Part 10 - Federated Learning with Secure Aggregation.ipynb

---

examples/tutorials/translations/bengali/Part 08 - Introduction to Plans.ipynb
examples/tutorials/translations/bengali/Part 08 bis - Introduction to Protocols.ipynb

Translated Notebooks:
-  Part 08 - Introduction to Plans.ipynb 
-  Part 08 bis - Introduction to Protocols.ipynb

translated notebooks part 8 and part 8 bis (bengali)

---

syft/frameworks/torch/mpc/securenn.py
syft/frameworks/torch/tensors/interpreters/native.py
test/torch/crypto/test_snn.py

Float tensor additive sharing

---

syft/workers/virtual.py
test/workers/test_virtual.py

Some issues found by @LaRiffle while rebasing CrypTen.

Little fixes in the code

---

test/torch/pointers/test_callable_pointer.py

Partially solves #2510
> Added docstrings to test_callable_pointer.py

Add documentation

---

syft/federated/federated_client.py

The current version of `federated_client.py` optimizes all parameters of the model by default.
This change allows to optimize specific parameters of the model.
See https://github.com/OpenMined/PySyft/issues/3116 for more details.

Optimizer accepts which params to optimize

---

examples/experimental/FL Training Plan/Create Plan.ipynb
examples/experimental/FL Training Plan/Execute Plan.ipynb
examples/experimental/FL Training Plan/Host Plan.ipynb

Changes:
* Fix errors in experimental FL Training notebooks, due to recent Plan/etc. updates
* Add new "Host Plan" notebook that hosts training plan & model params to PyGrid
These notebooks test e2e interactions between PySyft, syft.js, PyGrid.

FL Training Plan fix & PyGrid hosting example

---

pip-dep/requirements.txt

Changed the tornado version
Closes #3019

Websocket worker start Error

---

pip-dep/requirements_notebooks.txt

Issue solution [here](https://github.com/jupyter/notebook/issues/3397#issuecomment-517546599).
Thank you @karlhigley

Install correct version of notebook and tornado

---

test/conftest.py

Changed "localhost" to "0.0.0.0" so the tests cand run inside a docker container. Tested on a container with ubuntu 18.04.

Docker test run fix

---

syft/frameworks/crypten/__init__.py
syft/frameworks/crypten/context.py
syft/workers/base.py
test/crypten/test_context.py

Fixes #3226 
Re-opened the PR from [here](https://github.com/OpenMined/PySyft/pull/3074).
It should be the same PR --- did not know what was in my head when I closed it since we want a more CrypTen like API

CrypTen Syft load based only on tag and rank

---

syft/frameworks/torch/tensors/interpreters/additive_shared.py
syft/frameworks/torch/tensors/interpreters/precision.py
test/torch/tensors/test_precision.py

fixes #2500 .
Currently using dropout function specified on ref. https://stackoverflow.com/questions/54109617/implementing-dropout-from-scratch. 
More robust implementation to be added.
This code block is yet to be tested.

Add dropout support for SMPC

---

.github/workflows/tests.yml
codecov.yml

Closes #3181 
- The Codecov pull request comment is a highly detailed overview of a pull request. It provides details on the coverage changes in the pull request that help with speeding up code review, and ensuring that pull requests are well tested. The comment is customizable to fit the desired needs.
Done!

Add codecov integration

---

.github/workflows/tests.yml
README.md

testing codecov - minor change

---

.github/workflows/tests.yml

Revert "Automatically format the code in pull requests"

---

README.md
codecov.yml

Allow range between 90 and 100

Add coverage range

---

syft/grid/grid_client.py

Created the `GridClient`  module mentioned in #3153 and implemented the `host_federated_training` method.
Related to #3153

Create host_federated_training method

---

test/generic/test_object_storage.py

Partial fix for #2510
Added docstrings to test_object_storage.py
Added inline comments

Added additional comments to test files

---

README.md

Micro-change I spotted as I was reviewing some of the docs

Patch installation link in README

---

examples/tutorials/translations/korean/Part 04 - Federated Learning via Trusted Aggregator.ipynb

I have translated part 4 of the tutorial to Korean.
Relevant issue: #2794

Translate tutorial part 4 to Korean

---

.github/workflows/tests.yml
.github/workflows/translated-tutorials.yml
.github/workflows/tutorials.yml
pip-dep/requirements_dev.txt

Hoping to shake out weird coupling between tests based on Torch hook, worker, and RNG state.

Run the tests in random orders

---

examples/tutorials/translations/japanese/Part 13a - Secure Classification with Syft Keras and TFE - Public Training.ipynb
examples/tutorials/translations/japanese/Part 13b - Secure Classification with Syft Keras and TFE - Secure Model Serving.ipynb
examples/tutorials/translations/japanese/Part 13c - Secure Classification with Syft Keras and TFE - Private Prediction Client.ipynb

I translated the tutorial from part 13 into Japanese.

Translate tutorial part 13 From English to Japanese

---

examples/experimental/FL Training Plan/Create Plan.ipynb
examples/experimental/FL Training Plan/Execute Plan.ipynb
examples/experimental/FL Training Plan/Host Plan.ipynb
syft/execution/__init__.py
syft/execution/plan.py
syft/execution/translation/torchscript.py
test/execution/test_plan.py
test/serde/serde_helpers.py

Next step for https://github.com/OpenMined/PySyft/pull/3263
Make translation on Plan build time.

Translate Plan to torchscript on build time

---

examples/tutorials/grid/Part 03 - Grid applied to Smart Cities and Smart Homes.ipynb

Changed costumer to customer

---

examples/experimental/FL Training Plan/Create Plan.ipynb
examples/experimental/FL Training Plan/Execute Plan.ipynb
examples/experimental/FL Training Plan/Host Plan.ipynb
syft/execution/__init__.py
syft/execution/plan.py
syft/execution/translation/torchscript.py
test/execution/test_plan.py
test/serde/serde_helpers.py

Reverts OpenMined/PySyft#3336
Unfortunately, this was merged when the tests weren't passing, and it breaks a few `Plan` tests that are now blocking other PRs. Reverting for now, until the `Plan` tests can be fixed.

Revert "Translate Plan to torchscript on build time"

---

examples/tutorials/grid/Part 03 - Grid applied to Smart Cities and Smart Homes.ipynb

Update the notebook code snippet connecting the remote grid nodes between each other to aggregate the energy consumption value.

Fix Part 3 - Grid applied to Smart Cities and Smart Homes

---

examples/tutorials/Part 13a - Secure Classification with Syft Keras and TFE - Public Training.ipynb

Previously all commands were gathered in one cell in notebook 13a of tutorial

separates cells from notebook

---

syft/generic/pointers/pointer_tensor.py

Minox update to PointerTensor's Docstring

Update Docstring for PointerTensor

---

pip-dep/requirements.txt
syft/frameworks/crypten/jail.py
test/crypten/test_jail.py

Class for running function in an environment with limited capabilities: can't import arbitrary module, only use available ones (default is torch, syft and crypten)

JailRunner

---

syft/frameworks/torch/tensors/interpreters/additive_shared.py
test/serde/serde_helpers.py

Fix bug with AST.dtype serde

---

pip-dep/requirements.txt
syft/frameworks/crypten/__init__.py
syft/frameworks/torch/hook/hook.py

Update CrypTen to point to the master branch from Facebook Research.

Update Crypten Head

---

.github/workflows/tests.yml
pip-dep/requirements_dev.txt

Check that docstring coverage hasn't decreased below the current level on each PR.

Add a check for docstring coverage to the Github Action tests

---

syft/execution/placeholder.py
syft/execution/plan.py
syft/execution/protocol.py
syft/execution/role.py
syft/execution/tracing.py
test/execution/test_placeholder.py
test/execution/test_protocol.py
test/serde/serde_helpers.py

Changes the syntax to build and call Protocols.

Build Roles from func2protocol decorator

---

syft/execution/placeholder.py
syft/execution/protocol.py
syft/execution/tracing.py
syft/generic/pointers/pointer_tensor.py
test/execution/test_protocol.py
test/torch/pointers/test_pointer_tensor.py

Trace `CommunicationActions` into `Roles`

---

syft/execution/plan.py
syft/execution/protocol.py
syft/execution/role.py
test/execution/test_role.py

Add reset method on Role. It's useful to build a Plan or Protocol several times.

Add reset method on Role

---

.github/workflows/tests.yml

This catches insufficient docstring issues up front instead of after 30 minutes of test execution time and cleans up a few of the build steps along the way.

Move docstring coverage check earlier in test action

---

syft/frameworks/crypten/hook/hook.py
syft/frameworks/torch/hook/hook.py
syft/grid/abstract_grid.py

Fixes #3385
Refractor (code shifted to new file)

Crypten hook logic shifted to hook_crypten.py

---

syft/messaging/message.py
test/serde/serde_helpers.py

Test if ```rank_to_worker_id``` is correctly sent in serde messages.

Correctly test simplify/detail methods

---

.github/pull_request_template.md

Updates the PR template to incorporate specific TODOs from the contribution guidelines

Incorporate specific contribution guidelines into PR template checklist

---

syft/execution/protocol.py
syft/execution/role.py
test/execution/test_protocol.py
test/serde/serde_helpers.py

Creates a `VirtualWorker` for each `Role` to use during `Protocol` tracing.
Resolves #3490

 Create a `VirtualWorker` for each `Role` and use it in the tests 

---

.github/CODEOWNERS

This will auto-request reviews from the Grid team when code in `syft/grid/` changes.

Make `@OpenMined/pygrid-team` the owners of `syft/grid/`

---

.github/workflows/stale.yml

Automate issue and PR clean-up.

Add Github action to mark and close stale issues and PR

---

syft/grid/__init__.py

Print useful information during `syft.grid.register` execution.
Resolves #3573

Print useful information on syft.grid.register()

---

syft/grid/__init__.py
syft/grid/network.py
syft/grid/nodes_manager.py

Add a proper way to handle unexpected exceptions/errors.
- Handle with unexpected exceptions during syft.grid.register function.
- Handle with unexpected behavior due to notebook async constraints.

Handle with grid unexpected errors properly

---

syft/frameworks/torch/tensors/interpreters/native.py
syft/frameworks/torch/tensors/interpreters/private.py
syft/grid/network.py

Add the ability to set up and host private datasets locally, making them searchable to other peers and managing its access level.
Resolves #3570

Host private datasets locally

---

syft/generic/pointers/pointer_tensor.py

Use serde for tags from PointerTensor

---

syft/frameworks/torch/hook/hook_args.py
syft/frameworks/torch/tensors/decorators/logging.py
syft/frameworks/torch/tensors/interpreters/autograd.py
syft/frameworks/torch/tensors/interpreters/paillier.py

Please include a summary of the change and which issue is fixed. If this closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Move torch arg hooking into the relevant classes to reduce circular imports

---

.github/CODEOWNERS

Please include a summary of the change and which issue is fixed. If this closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Update CODEOWNERS file to reflect new team names

---

syft/frameworks/crypten/jail.py
test/crypten/test_context.py

Added tests for covering implemented CrypTen context, and fixed a bug related to jail source code indent.

CrypTen test coverage

---

.github/workflows/stale.yml

Please include a summary of the change and which issue is fixed. If this closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Update the label used to mark stale issues/PRs

---

syft/serde/torch/serde.py

typo while detaching tensor in ` numpy_tensor_serializer`

serde, torch: fix typo in numpy tensor serializer.

---

syft/execution/plan.py
syft/execution/role.py
syft/execution/tracing.py

It looks like this attribute is not used anymore.

Remove owner attribute from FrameworkWrapper

---

syft/serde/msgpack/proto.py
syft/serde/syft_serializable.py
test/serde/msgpack/test_msgpack_serde.py
test/serde/msgpack/test_msgpack_serde_full.py
test/serde/serde_helpers.py

Adding support in msgpack for external libs. Solves ##3626 .

 Adding support in msgpack for external libs.

---

syft/execution/plan.py

Fix issue with wrapped frameworks from plans

Plans wrapped frameworks fix

---

syft/grid/grid_client.py

Implementing the connection speed test for fl worker
`time`, `random`
- TODO

added connection speed

---

pip-dep/requirements.txt
syft/execution/translation/threepio.py

This updates PySyft to use threepio 0.0.9. It does not yet include support for multi-command translation.
- Threepio
- Unit Tests

Update to threepio 0.0.9

---

syft/frameworks/torch/hook/hook_args.py
syft/generic/frameworks/hook/hook_args.py

Some small updates on hook_args

Update hook_args list

---

syft/frameworks/torch/tensors/interpreters/additive_shared.py

Small fixes to better use comp operators and relu with function secret sharing

Fix decorator issues for FSS in AST

---

syft/frameworks/torch/tensors/interpreters/autograd.py
syft/frameworks/torch/tensors/interpreters/gradients.py
test/execution/test_plan.py

Fix relu
Fix gradient function for sum
Add gradient function for mean and reshape

Add new gradient functions

---

syft/grid/autoscale/README.md
syft/grid/autoscale/gcloud.py
syft/grid/autoscale/test.ipynb
syft/grid/autoscale/test.py

- Added the feature to add eviction policy, which will tear-down the worker instances after `Cluster.sweep()` is called.
- Added instructions to setup budget alert on Google Cloud Platform.
**fixes** #3099 
@hericlesme 
- I have created test.py and test.ipynb for testing the functionality.
- Follow the instructions in the README.md to install the dependencies.
- Run test.py or test.ipynb to test the implemented functionality.

Added eviction policy & updated README.md with instructions to add Budget Alerts

---

examples/experimental/Length of Stay demo on MIMIC/README.md
examples/experimental/Length of Stay demo on MIMIC/__init__.py
examples/experimental/Length of Stay demo on MIMIC/example/test_trainer.py
examples/experimental/Length of Stay demo on MIMIC/metadata/config_result_paper.json
examples/experimental/Length of Stay demo on MIMIC/pytorch/__init__.py
examples/experimental/Length of Stay demo on MIMIC/pytorch/models.py
examples/experimental/Length of Stay demo on MIMIC/pytorch/trainer.py

Proposed implementation of the neural network model requested by the issue #3767
The network implemented in the [examples/experimental/Length of Stay demo on MIMIC/pytorch/models.py](https://github.com/OpenMined/PySyft/compare/differential-privacy...SaulLu:LS/baseline_pytorch_model?expand=1#diff-a46fd51a35d2f1cec144181e4a61041a) file corresponds to the network described in the paper as FFN. The dropout layers and the batchnorm have not been added for the sake of simplification for the rest of the Demo. Nevertheless, it might be interesting to add them to compare the results with the performance mentionned in the paper.
In addition, the optimal settings of the hyperparameters indicated in the paper have been collected in the [examples/experimental/Length of Stay demo on …

Add baseline pytorch model

---

.github/workflows/tests.yml
setup.cfg
src/syft/ast/__init__.py
src/syft/typecheck/typecheck.py
src/syft/worker/virtual/virtual_client.py
src/syft/worker/virtual/virtual_worker.py
src/syft/worker/worker.py
tests/syft/worker/virtual/virtual_client_test.py
tests/syft/worker/virtual/virtual_worker_test.py

Add linter/bandit and tests stubs

---

examples/experimental/CrypTen - Training an Encrypted Neural Network across Workers using Jails.ipynb

Small fix needed because of this [PR](https://github.com/facebookresearch/CrypTen/pull/121)

Quick Fix CrypTen Demo Jails

---

pip-dep/requirements.txt

Threepio 0.2.0 is identical to 0.0.1

update threepio to 0.2.0

---

examples/tutorials/static-fl/Part 02 - Execute Plan.ipynb

Fix wording in Part 2 notebook

---

examples/experimental/CrypTen - Training an Encrypted Neural Network across Workers using Jails.ipynb
examples/experimental/Training an Encrypted Neural Network across Workers using Crypten.ipynb

Demo Tutorial on Training Encrypted NN using CrypTen on Grid using Jails.

Demo Tutorial on Training Encrypted NN using CrypTen on Grid

---

syft/frameworks/crypten/context.py

Check the state of the communication before/after building the plan.

CrypTen check state

---

examples/tutorials/static-fl/Part 02a - Check Model.ipynb
syft/grid/clients/static_fl_client.py

Add notebook to show trained static FL model retrieval.
Needs https://github.com/OpenMined/PyGrid/pull/625
Ran all cells

Static fl/get model notebook

---

pip-dep/requirements.txt
syft/exceptions.py
syft/frameworks/torch/mpc/fss.py
syft/frameworks/torch/mpc/primitives.py
test/torch/mpc/test_crypto_store.py
test/torch/mpc/test_fss.py
test/torch/tensors/test_additive_shared.py

This improves on the previous implem of FSS, using numpy to have a faster runtime. The crypto store also reflects the changes. Tests are added and consolidated.
Fix: #3882

Modify the FSS scheme to use Numpy

---

examples/Syft Proto.ipynb
src/syft/core/common/uid.py
tests/syft/core/common/uid_test.py

In this pull request - I added testing coverage to the UID object - which now is at 100% coverage.

UID to 100% Test Coverage

---

docs/api/syft.core.common.rst
docs/conf.py
examples/Syft Proto.ipynb
src/syft/core/common/serializable.py
src/syft/core/common/uid.py
tests/syft/core/common/object_test.py
tests/syft/core/common/uid_test.py

In this PR, I have added documentation necessary to explain the methods in the UID class. Writing the documentation also lead to a couple small tweaks to the serializable API as explained in the commit history.

Method Documentation for UID class + Small Tweaks

---

syft/generic/pointers/multi_pointer.py

I make `for loop` simply using List Comprehenssion.
Thank You!

REFACTOR: Change For Loop to List Comprehession

---

syft/generic/frameworks/hook/string.py

Through List Comprehension and One Line If Syntax, I reduced the number of lines and deduplicated them.
Personally, I think this is better than before, but there may be opinions that it is less readable than the existing code.
So I need the opinions of reviewers.
Thank You :smile: 

REFACTOR: Line Reduce and Deduplication

---

syft/frameworks/torch/mpc/beaver.py
syft/frameworks/torch/mpc/primitives.py
syft/frameworks/torch/mpc/securenn.py
syft/frameworks/torch/mpc/spdz.py
syft/frameworks/torch/tensors/interpreters/additive_shared.py
syft/workers/base.py
test/execution/test_state.py
test/torch/mpc/test_multiparty_nn.py
test/torch/mpc/test_securenn.py
test/torch/tensors/test_additive_shared.py

This PR aligns SPDZ with the FSS protocol to use a unified way of generating crypto primitives for those protocol. This will also benefit SecureNN.
**🛑     WARNING: This PR removes support for SMPC with > 2 workers**

Refactor SPDZ to use the crypto store

---

.pre-commit-config.yaml
CONTRIBUTING.md
README.md
docs/conf.py
requirements.txt
scripts/pre_commit.sh
src/syft/__init__.py
src/syft/core/common/serde/deserialize.py
src/syft/core/common/serde/serializable.py
src/syft/core/common/serde/util.py
src/syft/core/node/common/node.py
src/syft/decorators/syft_decorator_impl.py
tests/syft/core/common/object_test.py
tests/syft/core/common/serializable_test.py
tests/syft/core/common/uid_test.py
tests/syft/decorators/typecheck_test.py

As per conversation in Slack, the pre commit hooks will prevent tests / checks in CI being easily broken.
I have tested this locally and it is all working currently as expected.
We should document the setup and encourage all developers to adopt the use of these hooks.
See: https://pre-commit.com/
I have updated my additional scripts/pre_commit.sh to use this.
There are some additional tasks that get executed in "scripts/pre_commit.sh" which we probably don't want in the actual commit hook, including running the bandit checks and the tests. If the tests are part of the commit hook one would never be able to submit a commit to fix a broken test without it being fixed first.
However, I think being able to run this command before committing manually is a good way to be sure everything should …

Updated pre-commit-config

---

README.md

I added `$` to keep format consistent.

Remove $ before command line (README.md)

---

src/syft/core/common/serde/deserialize.py
src/syft/core/common/serde/serializable.py
src/syft/core/common/uid.py
src/syft/core/io/address.py
src/syft/core/io/route.py
src/syft/core/node/common/client.py
src/syft/core/node/common/node.py
src/syft/core/node/device/device.py
src/syft/core/node/domain/domain.py
src/syft/core/node/network/network.py
tests/syft/core/common/uid_test.py

black src; black tests

---

examples/pubsub server implementation.ipynb
src/syft/core/io/address.py
src/syft/core/node/common/location_aware_object.py
src/syft/core/node/common/node.py

Bug fix. Bug causes code to fail to initialize a node as it doesn't find the "self.id" property.
Also, some address types inclusion.

quick fixes on types

---

.github/CODEOWNERS

The `torch` directory is located within the `frameworks` directory.
Thank You!

Changing the wrong file path in CODEOWNER

---

syft/generic/frameworks/hook/hook.py
syft/generic/pointers/object_pointer.py

Duplicate import syntax for same package has been removed.
No

Remove duplicated import

---

examples/experimental/CrypTen/CrypTen - Private Model Inference - Plans.ipynb
examples/experimental/CrypTen/CrypTen - Traing Encrypted Neural Network - Plans.ipynb
examples/experimental/CrypTen/CrypTen - Training an Encrypted Neural Network across Workers using Jails.ipynb
syft/frameworks/crypten/crypten_attributes.py

We deprecated PyGridNode and we need to update the CrypTen tutorials to make use of the new PyGrid repo.
Update according to the new PyGrid repo.
- The tests are passing

Fix CrypTen tutorials

---

syft/frameworks/torch/dp/pate.py

`ss_scale` is an unused local variable. I deleted it.
Thank You!

Remove unused variable `ss_scale`

---

pip-dep/requirements.txt
syft/exceptions.py
syft/serde/msgpack/serde.py
syft/workers/websocket_server.py
test/serde/msgpack/test_msgpack_serde_full.py
test/serde/serde_helpers.py

This is needed to do encrypted computation using function secret sharing with websocket workers

Make EmptyCryptoPrimitiveStoreError serializable

---

examples/tutorials/Part 02 - Intro to Federated Learning.ipynb

added the .data attribute to just print the loss tensor.
Tested by running the code on Jupyter notebook.

modification to just print the loss tensor

---

syft/frameworks/torch/tensors/interpreters/additive_shared.py
syft/frameworks/torch/tensors/interpreters/native.py

REFACTOR-3922: AST Refactor

---

.coveragerc
requirements.txt
setup.cfg
src/syft/core/common/message.py
src/syft/core/common/object.py
src/syft/core/common/serde/serializable.py
src/syft/core/common/uid.py
src/syft/core/io/address.py
src/syft/core/io/connection.py
src/syft/core/io/location/location.py
src/syft/core/io/route.py
src/syft/core/node/abstract/node.py
src/syft/core/node/common/action/save_object_action.py
src/syft/core/node/common/node.py
src/syft/core/node/domain/client.py
src/syft/core/store/storeable_object.py
src/syft/grid/client.py
src/syft/grid/duet/duet.py
src/syft/grid/duet/server.py
tests/syft/grid/duet_test.py

- Fixed small issues in Duet
- Added pycov .coveragerc to ignore generated protos
None
pre_commit script

Fixed some issues in Duet

---

proto/core/io/location/specific.proto
proto/core/store/store_object.proto
src/syft/core/store/store_disk.py
src/syft/core/store/store_interface.py
src/syft/core/store/store_memory.py
src/syft/core/store/storeable_object.py
tests/syft/core/store/memory_storage_test.py

Store cleanup

---

.pre-commit-config.yaml
src/syft/core/node/abstract/node.py
src/syft/core/node/common/client.py
src/syft/core/store/store_interface.py
src/syft/core/store/storeable_object.py
src/syft/lib/numpy/tensor.py
src/syft/lib/torch/uppercase_tensor.py
tests/syft/core/node/node_test.py

Fix More mypy and added mypy flag:
--warn-unreachable
None
CI

Fix More mypy

---

examples/tutorials/Part 09 - Intro to Encrypted Programs.ipynb
examples/tutorials/Part 11 - Secure Deep Learning Classification.ipynb
examples/tutorials/Part 12 bis - Encrypted Training on MNIST.ipynb
syft/frameworks/torch/linalg/lr.py
syft/frameworks/torch/linalg/operations.py
syft/frameworks/torch/mpc/fss.py
syft/frameworks/torch/mpc/primitives.py

This is a small update of the tutorial on Encrypted ML to improve their runtime using Function Secret Sharing

Make tutorials faster using FSS

---

src/syft/core/node/common/action/auth.py
tests/syft/core/node/common/action/auth_test.py

Add tests for the `src/syft/core/node/common/action/auth.py` file.

Add tests for auth decorator

---

syft/frameworks/torch/he/fv/context.py
syft/frameworks/torch/he/fv/encryption_params.py
syft/frameworks/torch/he/fv/key_generator.py
syft/frameworks/torch/he/fv/util/numth.py
syft/frameworks/torch/he/fv/util/operations.py
syft/frameworks/torch/he/fv/util/rlwe.py
syft/frameworks/torch/he/fv/util/rns_base.py
syft/frameworks/torch/he/fv/util/rns_tool.py
test/torch/tensors/test_fv.py

Found some typos and some outdated comments so updated it.
None
None

Minor doc updates of BFV scheme

---

.github/workflows/tests.yml
src/syft/core/node/common/action/function_or_constructor_action.py

We need to be able to test all versions of pytorch our users might already have installed. This includes all versions on the torch 1.x line which are currently available in pip.

Add tests for all versions of pytorch

---

src/syft/grid/connections/webrtc.py
src/syft/grid/duet/om_signaling_client.py
tests/syft/grid/connections/webrtc_test.py

Adding test-duet-colab changes and WebRTC fix for Python 3.6
None
On google colab and locally in python 3.6.9

Adding test-duet-colab changes and WebRTC fix for Python 3.6

---

src/syft/__init__.py
src/syft/core/node/common/action/run_class_method_action.py
src/syft/grid/duet/__init__.py
src/syft/grid/duet/duet.py
src/syft/grid/duet/om_signaling_client.py
tests/syft/lib/python/dict/userdict_test.py
tests/syft/lib/torch/nn/parameter/parameter_remote_method_api_suite_test.py
tests/syft/lib/torch/tensor/tensor_remote_method_api_suite_test.py

- Small cleanup of duet files with black, isort and some mypy
None
Locally and CI

Fix slow tests

---

src/syft/grid/network.py

ADD Try/catch scope

---

src/syft/grid/network.py

Fixes failing security check on 0.0.0.0 interface binding in demo network.py
None
Locally

Bandit fix

---

scripts/colab.sh

Improving colab script and adding docs.
On Google Colab

Colab script

---

src/syft/core/node/domain/client.py
src/syft/core/pointer/pointer.py
src/syft/grid/duet/__init__.py

Adding name param to request

---

scripts/colab.sh

- Make the branch name configurable in python and more clear
- Tested on Colab
None
On colab.

Fix colab.sh script

---

README.md

Improved changes in  README.md

---

syft/frameworks/torch/tensors/interpreters/native.py
test/generic/pointers/test_pointer_tensor.py

We need that wrapper.grad_fn refer to the ptr.grad_fn they wrap!
Implem is very close to .grad
**Is needed for the Opacus / PySyft demo**

Add support for grad_fn on pointers

---

.pre-commit-config.yaml
syft/frameworks/torch/mpc/falcon/falcon.py
syft/frameworks/torch/mpc/falcon/falcon_helper.py
syft/frameworks/torch/tensors/interpreters/native.py
syft/frameworks/torch/tensors/interpreters/precision.py
syft/frameworks/torch/tensors/interpreters/replicated_shared.py
test/torch/mpc/falcon/test_falcon_helper.py
test/torch/tensors/test_native.py
test/torch/tensors/test_precision.py
test/torch/tensors/test_replicated_shared.py

> Added support for FixedPrecisionTensor chain in ReplicatedSharingTensor (RST) 
> Modified add and sub of FPT to support FPT chain in RST
> Modified falcon files to support (Wrapper)> [ReplicatedSharingTensor]
this PR closed #3931 
None
Test cases are added for the required update

Added support for FixedPrecisionTensor chain in ReplicatedSharingTensor (RST) 

---

syft/grid/clients/data_centric_fl_client.py

Corrected DataCentricFLClient serialization. the method, the previous method has bugs and didn't serialise it correctly.
More specifically running the below code raises an error and connection breaks but the method in this PR will solves that
```
x = torch.tensor([1,2,3,4,5]) 
x = x.send(bob) 
x = x.share(bob,alice)
```
This comes after testing and discussion from @IonesioJunior and me.

Updated simplify and detail for dflclient

---

syft/frameworks/torch/mpc/fss.py

Refactoring `keygen` function and improving error message.
-

CLEAN: FSS Protocol Keygen Clean Up

---

.github/workflows/dummy.py
.github/workflows/tests.yml
docs/installing.rst
src/syft/lib/torch/__init__.py
tests/syft/grid/connections/webrtc_test.py
tests/syft/lib/allowlist_report.py
tests/syft/lib/allowlist_test.py

Resolves #4677
The tests are all passing so this also resolves: https://github.com/OpenMined/PySyft/issues/4678
n/a
- Creating PR to test :)

Testing GA with windows OS

---

src/syft/lib/__init__.py
tests/syft/core/node/common/action/function_or_constructor_action_test.py

Revert "Fix get permissions"

---

CONTRIBUTING.md

Fix from here: https://github.com/OpenMined/PySyft/pull/4712#event-3930060322
None
Docs

Removed dup section

---

syft/frameworks/torch/hook/hook.py
syft/frameworks/torch/tensors/interpreters/native.py
syft/frameworks/torch/tensors/interpreters/precision.py
syft/generic/pointers/pointer_tensor.py
test/generic/pointers/test_pointer_tensor.py
test/torch/tensors/test_precision.py

Fixes #4617 
Add .ndim and .T functionality to FixPrecisionTensor and PointerTensor.
- test units

Add .ndim and .T to Tensor (OpenMined#4617)

---

pip-dep/requirements.txt
syft/execution/placeholder.py
syft/frameworks/torch/tensors/interpreters/additive_shared.py
syft/frameworks/torch/tensors/interpreters/native.py
syft/frameworks/torch/tensors/interpreters/replicated_shared.py
syft/generic/abstract/object.py
syft/grid/clients/model_centric_fl_client.py
test/serde/msgpack/test_msgpack_serde_full.py
test/serde/serde_helpers.py
test/torch/tensors/test_replicated_shared.py

Add the possiblity to serialize/deserialize the RST
- Added a test to validate the changes

Add remote share for RST

---

README.md
examples/duet/README.md
examples/duet/mnist/MNIST_Syft_Data_Owner.ipynb
examples/duet/mnist/MNIST_Syft_Data_Scientist.ipynb
scripts/colab.sh

Updating branch refs from syft_0.3.0 to master 🚀

---

.github/workflows/tests.yml

Add the ```dev``` branch as a target branch when running the tests.
- The tests should start and finish on this PR

Add dev as target branch

---

README.md
examples/duet/README.md

Fixed PyPI README by adding the complete URL 

---

CONTRIBUTING.md

Updating the contribution guide so that the third party python package support can be worked on by other contributors.
None
None

Updating contribution guide

---

.github/workflows/merge_tests.yml
.github/workflows/pr_tests.yml

Round 2 of this: https://github.com/OpenMined/PySyft/pull/4852
Trying to get Merge Tests and workflow_dispatch working.
GitHub Actions
CI

Trying to get workflow_dispatch to work

---

.github/workflows/merge_tests.yml

Testing workflow_dispatch
None
You're looking at it.

Testing workflow_dispatch

---

src/syft/ast/klass.py
tests/syft/lib/python/list/pointer_test.py

Adding a method to customize your requests.

Adding a default request customization fix on pointers.

---

README.md
docs/FAQ_0.2.x.md

Added FAQ on 0.2.x to 0.3.x changes.
None
NA

Added some FAQs on 0.2.x to 0.3.x

---

.github/workflows/benchmark_actions.yml
requirements.txt
tests/benchmarks/pytest_benchmarks/bench_test.py
tests/benchmarks/pytest_benchmarks/benchmarks_functions_test.py

this PR fixed #4654 
pytest-benchmark
tested on local though need review for .yml :)

add github benchmark-actions support

---

tests/syft/lib/pydp/client_pydp_test.py

PyDP Integration

---

CONTRIBUTING.md

Contributing docs WSL Setup
