OpenMined/PySyft

- src/syft/__init__.py
- src/syft/grid/duet/__init__.py
> Display Open collective solicitation message on import #3724

- src/syft/lib/sympc/__init__.py
This reflects changes for https://github.com/OpenMined/SyMPC/pull/31
> Allow matmul for SyMPC

- docs/FAQ_0.2.x.md
Added a new FAQ for the module not found error, faced continuously by people pursuing the udacity course.
None
None
> Add a FAQ for Module error

- .github/workflows/merge_tests.yml
- .github/workflows/pr_tests.yml
> Upgrading pip in CI

- .github/workflows/merge_tests.yml
- .github/workflows/pr_tests.yml
> Switched to --user for windows

- .github/workflows/merge_tests.yml
- tests/syft/lib/allowlist_test.py
> Chunking slow tests into 6 parts

- .github/workflows/merge_tests.yml
- .github/workflows/pr_tests.yml
> Added pip --default-timeout=60 to fix Connection reset by peer during CI

- .github/workflows/merge_tests.yml
> Fixing very stupid mistake of passing in torch version instead of chunk

- .github/workflows/merge_tests.yml
> Added windows back to merge CI

- .github/workflows/merge_tests.yml
- .github/workflows/pr_tests.yml
- tests/conftest.py
- tests/syft/lib/allowlist_test.py
- Merge now runs torch tests only chunked
> Split slow tests into torch and slow moved slow to pr

- .github/workflows/merge_tests.yml
- .github/workflows/pr_tests.yml
> Fixed boolean logic in pytest for running fast and slow tests

- .github/workflows/merge_tests.yml
> Removed xdist on 2 core GitHub CI torch tests

- .github/workflows/merge_tests.yml
> Halving the amount of ops per run to keep memory down

- .github/workflows/merge_tests.yml
Speeding things up hopefully.
None
CI
> Forgot to re-add -n auto

- examples/duet/cli/do.py
- examples/duet/cli/do_no_threads.py
- examples/duet/cli/ds.py
- examples/duet/cli/ds_no_threads.py
- src/syft/__init__.py
- src/syft/core/common/environment.py
- src/syft/core/common/event_loop.py
- src/syft/grid/connections/webrtc.py
- src/syft/grid/duet/__init__.py
- src/syft/lib/pydp/__init__.py
- tests/syft/grid/connections/webrtc_test.py
This PR fixes the issues with the event loop in CLI mode and addresses some other related issues.
None
CLI, Jupyter and CI
> Fix asyncio CLI / Interactive issues

- src/syft/lib/python/collections/ordered_dict.py
- tests/syft/lib/python/collections/ordered_dict/ordered_dict_sanity_test.py
fixes https://github.com/OpenMined/PySyft/issues/4855
> add OrderedDict tests

- .github/workflows/merge_tests.yml
> Add an 8th Chunk for Windows OOM errors

- tests/syft/lib/allowlist_test.py
> Try catch exception tests allowlist

- src/syft/ast/attribute.py
- src/syft/ast/callable.py
- src/syft/ast/enum.py
- src/syft/ast/globals.py
- src/syft/ast/klass.py
- src/syft/ast/module.py
- src/syft/ast/property.py
- src/syft/ast/static_attr.py
> Adapting the AST error scheme to the new logging.

- docs/installing.rst
> Fixed incorrect pytest command in installing.rst docs

- tests/syft/lib/sympc/sympc_test.py
> Add Session Manager

- docs/conf.py
Noticed this while looking through the `conf.py` to set up the doclinter. Not that significant but I figured we could just update it anw
> Update year in conf.py

- .github/workflows/pr_tests.yml
it turned out that your cache file was not specific enough for it was rewritten by every Python / PyTorch version
> preserving CI cache

- LICENSE
- src/syft/core/common/environment.py
Closes: https://github.com/OpenMined/PySyft/issues/5146
Closes: https://github.com/OpenMined/PySyft/issues/4915
In Jupyter
> Fix Minimum Notebook Version and License

- .pre-commit-config.yaml
- tests/syft/lib/allowlist_test.py
Disabled unused chunking in torch tests
None
CI
> Disabled unused chunking in torch tests

- .github/workflows/merge_tests.yml
Forgot windows check on torch tests.
None
CI
> Forgot windows check on torch tests

- .gitignore
- examples/differential-privacy/opacus/Opacus_Syft_Data_Owner.ipynb
- examples/differential-privacy/opacus/Opacus_Syft_Data_Scientist.ipynb
- examples/duet/dcgan/DCGAN_Syft_Data_Owner.ipynb
- examples/duet/dcgan/DCGAN_Syft_Data_Scientist.ipynb
- examples/duet/mnist/MNIST_Syft_Data_Owner.ipynb
- scripts/nb_duet_test.py
- src/syft/util.py
- Adding workaround for MNIST dataset issues
None
CI
> Adding workaround for MNIST dataset issues

- examples/duet/README.md
> Fixing logo size

- .github/workflows/benchmark_actions.yml
Fix benchmarks by pinning torch to 1.7.0
None
CI
> Fix benchmarks by pinning torch to 1.7.0

- .github/workflows/benchmark_actions.yml
> Fix benchmarking

- .github/workflows/merge_tests.yml
- .github/workflows/pr_tests.yml
Add the ```.txt``` files as a trigger for workflows in GH.
> Add requirements files for GH actions

- requirements/supported_libs.txt
- src/syft/ast/klass.py
Make the ```args```/```kwargs```.
- Every test should pass
> Param Objs not removed

- README.md
- examples/duet/README.md
> Updated compatibility matrix

- .github/workflows/pr_tests.yml
- examples/private-ai-series/duet_basics/exercise/Exercise_Duet_Basics_Data_Scientist.ipynb
Updated the duet_basics Exercise notebook by removing the solution part.
None.
- [x ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x ] My changes are covered by tests
> updated exercise notebook

- .github/workflows/pr_tests.yml
- requirements.dev.txt
- requirements.libs.txt
The SyMPC tests are not being picked up.
> Fixing SyMPC Tests

- requirements.libs.txt
- src/syft/lib/sympc/session_util.py
I am not sure what functionality was added but it seems that it broke SyMPC
-  SyMPC Passes the tests
> Fix deserialize session

- examples/data-science/pandas/CDC_NDI_Mortality_Syft_Data_Owner.ipynb
- examples/data-science/pandas/CDC_NDI_Mortality_Syft_Data_Scientist.ipynb
Hosted CDC data on https://datahub.io/ and updated notebook to download it.
None
Jupyter
> Updated CDC notebooks to download dataset

- src/syft/grid/client/request_api/worker_api.py
Rename Worker attribute `worker.address` -> `worker.syft_address`
- `pysyft.grid.client` module
> PyGrid Client minor fixes

- proto/grid/messages/infra_messages.proto
- scripts/build_proto.sh
- src/syft/grid/client/request_api/worker_api.py
- src/syft/grid/messages/infra_messages.py
- src/syft/proto/grid/messages/infra_messages_pb2.py
- ADD `--experimental_allow_proto3_optional` flag
- Remove/Rename unused grid message CheckWorkerDeploymentStatus
- ADD new grid message GetWorkerInstanceType
- Add new method in grid client API
> Minor fixes pygrid

- requirements.dev.txt
- requirements.libs.deps.txt
- requirements.libs.txt
- requirements.txt
- scripts/colab.sh
- setup.cfg
> Revert "requirement trimming"

- README.md
- docs/installing.rst
- src/syft/grid/duet/webrtc_duet.py
> Updated README.md

- tests/syft/lib/statsmodels/statsmodels_test.py
path error occurs in https://github.com/OpenMined/PySyft/pull/5225/checks?check_run_id=2306753578
The fixed code directly loads the CSV file and convert it to pandas.dataframe ,and it doesn't create any file.
> fix path error in the statmodels test

- examples/federated-learning/model-centric/mcfl_create_plan.ipynb
- examples/federated-learning/model-centric/mcfl_create_plan_mobile.ipynb
- tests/syft/core/fl/model-centric/mcfl_create_execute_plan_test.py
* Fixes loss calculation in model w/o autograd in unit tests
* Adds intro text to MCFL notebook
* Adds MCFL for mobile notebook that can be used to seed model and plan for Kotlin/SwiftSyft workers
- Unit test
- Manually tested swiftsyft after executing notebook
> Update MCFL notebooks and test

- .pre-commit-config.yaml
> Update pre-commit hook

- .github/workflows/pr_tests.yml
- .pre-commit-config.yaml
Documentation is very important if we want to see our libraries used around the world.
To achieve this goal documentation must be improved.
In this PR I update pre-commit in order to:
* Check if docstring exists and if it follows google documentation style. pydocstyle
* Check if docstring is consistent with type annotations. darglint
I update as well GA so if the new/updated files in a PR does not follow this convention, the PR is denied.
In this way, developers must be sure that their code is documented properly.
In two ways:
* I have implemented this as well in sympc project.
* I have pushed a foo.py file with wrong documentation and I have checked that GA fails (see )
> Update pre-commit to include checks of documentation 

- .pre-commit-config.yaml
- examples/duet/dcgan/original/main.py
- examples/duet/mnist/original/main.py
- examples/duet/reinforcement_learning/original/actor_critic.py
- examples/duet/reinforcement_learning/original/reinforce.py
- examples/duet/snli/original/util.py
- examples/duet/super_resolution/original/main.py
- examples/duet/time_sequence_prediction/original/train.py
- examples/duet/vae/original/main.py
- examples/duet/word_language_model/original/generate.py
- examples/duet/word_language_model/original/main.py
- setup.cfg
- setup.py
- src/syft/core/common/message.py
- src/syft/core/node/common/action/common.py
- src/syft/core/node/domain/service/vm_service.py
- tests/syft/core/common/uid_test.py
- tests/syft/lib/torch/tensor/tensor_remote_and_serde_test.py
- Updating black in pre-commit
- Added pre-commit install to PostDevelopCommand
None
Locally and CI
> Disable breaking checks in the linting step

- examples/mock_apis/Remote Medical Data Science Grid Mock API.ipynb
This just removes an extra return within a string in a notbook JSON. The notebook file is corrupted and doesn't load without this fix.
None
- Just try to load the notebook either into a Google Colab or through `jupyter notebook`.
- [-] My changes are covered by tests
> Fix notebook Remote Medical Data Science Grid Mock

- .github/workflows/pr_tests.yml
- requirements.grid.txt
- setup.py
- tests/syft/core/fl/model-centric/mcfl_create_execute_plan_test.py
- Syncing PySyft and PyGrid
- Adding exception handling to pre-commit install which is failing
- Added lib dependencies to grid requirements file
PyGrid Tests
Locally and CI
> Syncing PySyft and PyGrid

- .github/workflows/pr_tests.yml
Fixing CI yaml file.
None
Locally and CI
> Fixing yaml to run on feature/rust

- src/syft/lib/sklearn/serializing_models.py
Adding suggested changes from this PR: https://github.com/OpenMined/PySyft/pull/5501
None: 
- By locally running the unit test
- CI
> changed to using `upcast`

- .github/workflows/merge_tests.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- README.md
- examples/duet/README.md
Renaming references to master to main.
Mostly READMEs
> master -> main

- .github/workflows/syft-publish.yml
> fix publish

- .github/workflows/syft-benchmark.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-version_tests.yml
- Ignore issues with any install-custom-dependency some failures are valid
- For example sympc has no python 3.6 so this will be skipped in tests
None
CI
> Fix nightlies

- packages/syft/src/syft/lib/__init__.py
- packages/syft/src/syft/lib/misc/__init__.py
- packages/syft/src/syft/lib/pandas/__init__.py
Closes: https://github.com/OpenMined/PySyft/issues/5323
> self-ref union types

- packages/syft/setup.cfg
> setup.cfg fix

- .github/workflows/syft-security.yml
> using secret token: snyk

- packages/syft/scripts/parse_setup.py
- packages/syft/setup.cfg
- packages/syft/src/syft/lib/gym/__init__.py
- packages/syft/tests/syft/core/remote_dataloader/remote_dataloader_test.py
- packages/syft/tests/syft/lib/gym/gym_test.py
- packages/syft/tests/syft/lib/numpy/array_test.py
- packages/syft/tests/syft/lib/sklearn/model_serialize_test.py
Fixed broken CI importing libs during conftest search
> Fixed broken CI importing libs during conftest search

- README.md
Added test and pypi badges to the main `README.md`
- Fixes #5306
- Added the sparkline
- Hello to all the first Welcome Wednesday video chat peeps 🤗
None
Manually Tested
> Added test and pypi badges to the main README.md

- .github/workflows/grid-tests.yml
- .github/workflows/syft-pr_tests.yml
- packages/grid/.pre-commit-config.yaml
- packages/grid/apps/domain/src/app.py
- packages/grid/apps/network/src/app.py
- packages/grid/apps/worker/src/app.py
- packages/syft/.pre-commit-config.yaml
- packages/syft/requirements.unstable.txt
- packages/syft/scripts/mnist.py
- packages/syft/src/syft/grid/client/grid_connection.py
- packages/syft/tests/syft/core/fl/model-centric/mcfl_create_execute_plan_test.py
- packages/syft/tests/syft/notebooks/__init__.py
- Updating GitHub CI workflow files
- grid has new working-directory change
- syft uses grid project now instead of git clone
- Isolated syft pre-commit from grid package
- Added back missing syft notebooks/__init__
- Removed continue-on-error from grid integration tests
the world
Locally and in CI
> 🚝 Fixing Monorepo CI 🎉

- packages/grid/apps/domain/src/main/core/database/bin_storage/bin_obj.py
- packages/grid/apps/domain/src/main/core/nodes/domain.py
Include Model Protobuf schema in the proto_to_bin mapping.
> Fix PyGrid's Model protobuf serialization

- VERSION
- packages/grid/apps/domain/src/__init__.py
- packages/grid/apps/network/src/__init__.py
- packages/grid/apps/worker/src/__init__.py
- packages/syft/examples/differential-privacy/pydp/PyDP_Syft_Data_Scientist.ipynb
- packages/syft/examples/hyperledger-aries/requirements.txt
- packages/syft/examples/private-set-intersection/PSI_Client_Syft_Data_Scientist.ipynb
- packages/syft/examples/private-set-intersection/PSI_Server_Syft_Data_Owner.ipynb
- packages/syft/examples/pygrid/docker-compose/Docker Compose Grid Domain and Network 🐋🎼.ipynb
- packages/syft/examples/secure-multi-party-computation/Duet/1-DS-1-DO/POC-MPCTensor-Duet-Party1-DS.ipynb
- packages/syft/src/syft/VERSION
> Bump version to 0.5.0

- .github/workflows/syft-benchmark.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- .github/workflows/syft-version_tests.yml
- packages/syft/setup.cfg
Thanks to @rasswanth-s for the fix.
None
CI
> Fixing Pillow 8.3.0 breaking CI

- packages/grid/ansible/mitogen/ansible_mitogen/compat/simplejson/decoder.py
Ran `tox -e lint` before and after changes, verified bugs were fixed
> Fixed linting errror by unpacking tuple correctly and adding type hint

- packages/hagrid/hagrid/grammar.py
Fixing small bug in logic causing validation to always fail.
> Fixed issue causing the tool to break because of MyPy change

- packages/syft/proto/core/tensor/tensor.proto
- packages/syft/proto/grid/messages/association_messages.proto
- packages/syft/src/syft/proto/core/tensor/tensor_pb2.py
- packages/syft/src/syft/proto/grid/messages/association_messages_pb2.py
- tox.ini
Updates to this PR: https://github.com/OpenMined/PySyft/pull/5844
> Updating tox fix

- packages/grid/backend/app/app/api/api_v1/endpoints/datasets.py
> Fixed issue where datasets endpoint was using old attribute name

- .github/workflows/stack-integration_tests.yml
- packages/grid/grid-ui/src/pages/_document.tsx
- packages/hagrid/hagrid/cli.py
- packages/syft/setup.cfg
- tests/integration/frontend_start_test.py
- tox.ini
This is the first stack integration test.
> First 0.6.0 Stack Integration Test

- .github/workflows/stack-integration_tests.yml
- packages/grid/.env
- packages/grid/docker-compose.override.yml
- packages/grid/docker-compose.yml
- Added tunshell to integration tests to debug docker compose v2
> Added version to stack docker images

- packages/hagrid/hagrid/cli.py
> HAGrid ssh keygen

- packages/hagrid/README.md
> Windows HAGrid README

- .github/workflows/hagrid-pr_tests.yml
- .github/workflows/stack-integration_tests.yml
- .github/workflows/syft-pr_tests.yml
- packages/grid/.env
- packages/grid/Vagrantfile
- packages/grid/ansible.cfg
- packages/grid/ansible/roles/node/tasks/main.yml
- packages/grid/backend/app/app/api/api_v1/endpoints/datasets.py
- packages/grid/backend/backend.dockerfile
- packages/grid/backend/celeryworker.dockerfile
- packages/grid/docker-compose.override.yml
- packages/grid/docker-compose.yml
- packages/grid/grid-ui/src/pages/_document.tsx
- packages/hagrid/.dockerignore
- packages/hagrid/Dockerfile
- packages/hagrid/README.md
- packages/hagrid/build_docker.ps1
- packages/hagrid/build_docker.sh
- packages/hagrid/hagrid/__init__.py
- packages/hagrid/hagrid/art.py
- packages/hagrid/hagrid/azure.py
- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/deps.py
- packages/hagrid/hagrid/land.py
- packages/hagrid/hagrid/launch.py
- packages/hagrid/hagrid/lib.py
- packages/hagrid/setup.py
- packages/syft/setup.cfg
- tests/integration/frontend_start_test.py
- tox.ini
Latest updates from 0.6.0 dev branch including new CI Integration test.
> Demo strike team branch 4

- notebooks/Experimental/Ishan/AdversarialAccountant_Domain.ipynb
- notebooks/Experimental/Ishan/Sanity_ADP.ipynb
- packages/hagrid/hagrid/cli.py
- packages/syft/src/syft/__init__.py
Uploading notebooks for ADP Demo
> [W.I.P.] Add experimental notebook for ADP Demo

- .github/workflows/hagrid-pr_tests.yml
- .github/workflows/stack-integration_tests.yml
- .github/workflows/syft-pr_tests.yml
- packages/grid/.env
- packages/grid/Vagrantfile
- packages/grid/ansible.cfg
- packages/grid/ansible/roles/node/tasks/main.yml
- packages/grid/backend/app/app/api/api_v1/endpoints/datasets.py
- packages/grid/backend/backend.dockerfile
- packages/grid/backend/celeryworker.dockerfile
- packages/grid/docker-compose.override.yml
- packages/grid/docker-compose.yml
- packages/grid/grid-ui/src/pages/_document.tsx
- packages/hagrid/.dockerignore
- packages/hagrid/Dockerfile
- packages/hagrid/README.md
- packages/hagrid/build_docker.ps1
- packages/hagrid/build_docker.sh
- packages/hagrid/hagrid/__init__.py
- packages/hagrid/hagrid/art.py
- packages/hagrid/hagrid/azure.py
- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/deps.py
- packages/hagrid/hagrid/land.py
- packages/hagrid/hagrid/launch.py
- packages/hagrid/hagrid/lib.py
- packages/hagrid/setup.py
- packages/syft/setup.cfg
- tests/integration/frontend_start_test.py
- tox.ini
> Updating 0.6.0

- .github/workflows/syft-benchmark.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- .github/workflows/syft-version_tests.yml
- packages/syft/setup.cfg
> Hotfix for Deps

- .pre-commit-config.yaml
> flynt check back

- packages/hagrid/build_wheel.sh
> HAGrid Wheel Build

- .github/workflows/syft-lib_tests.yml
- packages/syft-libs/pyscaffoldext-syft-support/setup.cfg
- packages/syft-libs/pyscaffoldext-syft-support/src/pyscaffoldext/syft_support/extension.py
- packages/syft-libs/pyscaffoldext-syft-support/src/pyscaffoldext/syft_support/script.py
- packages/syft-libs/pyscaffoldext-syft-support/tests/conftest.py
- packages/syft-libs/pyscaffoldext-syft-support/tests/test_custom_extension.py
- packages/syft-libs/pyscaffoldext-syft-support/tests/test_helpers.py
- packages/syft/setup.cfg
- packages/syft/src/syft/lib/__init__.py
- packages/syft/tests/syft/core/fl/model-centric/mcfl_create_execute_plan_test.py
- fixed broken pyscaffold extension added test
- fix -U (--update) arg in extension, i.e, -U will only update the support-package.json
- automate primitive type to syft type conversion
- support Union Type
- added unit test for extension
- union support is yet to be tested
> Redback | Union and primitive type support

- .pre-commit-config.yaml
- packages/syft/src/syft/core/common/serde/serialize.py
- packages/syft/src/syft/core/node/common/action/get_object_action.py
- packages/syft/src/syft/core/node/common/action/run_class_method_smpc_action.py
- packages/syft/src/syft/core/node/common/node_service/testing_services/smpc_executor_service.py
- packages/syft/src/syft/core/node/common/node_table/utils.py
- packages/syft/src/syft/core/node/domain/client.py
- packages/syft/src/syft/core/tensor/functions.py
- packages/syft/src/syft/grid/client/client.py
- packages/syft/src/syft/grid/duet/__init__.py
- packages/syft/src/syft/lib/python/complex.py
- packages/syft/src/syft/lib/python/primitive_factory.py
- packages/syft/src/syft/lib/python/string.py
- packages/syft/tests/syft/core/tensor/smpc/smpc_tensor_test.py
Cherry picked from: https://github.com/OpenMined/PySyft/pull/5861
> mypy fix for syft 🍒

- packages/hagrid/hagrid/cli.py
Fixing problem with hagrid and tail
> Fixing problem with hagrid and tail

- packages/grid/ansible/roles/containers/tasks/containers.yml
- packages/grid/ansible/roles/containers/tasks/hagrid.yml
- packages/grid/ansible/roles/node/tasks/main.yml
- packages/grid/backend/app/app/core/node.py
- packages/grid/backend/app/app/db/init_db.py
- packages/grid/scripts/cron.sh
- packages/hagrid/hagrid/cache.py
- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/lib.py
- Fixed issue with HAGrid detecting editable mode
- Force code clone now that we have a build dir
- Added password to hagrid auth options
- Added ansible_extras and docker_volume_destroy to ansible and cron.sh
> HAGrid Improvements

- packages/grid/ansible/roles/node/tasks/main.yml
- packages/grid/grid-ui/next-env.d.ts
- packages/grid/scripts/rotate_logs.sh
> Added log rotation cronjob

- notebooks/Experimental/Traskinator/SimpleService.ipynb
- notebooks/trade_demo/demo/Data Owner - Canada.ipynb
- packages/grid/backend/grid/api/auth/register.py
- packages/grid/backend/grid/api/router.py
- packages/grid/backend/grid/core/config.py
- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/core/node/common/node_service/object_request/object_request_service.py
- packages/syft/src/syft/core/node/common/node_service/request_receiver/request_receiver_service.py
- packages/syft/src/syft/core/node/domain/client.py
- packages/syft/src/syft/grid/client/client.py
In this pull request, I prototype two pieces of functionality which are MVP for Course 3:
- syft.register() - if the Domain is configured to allow external users to register their accounts without needing approval from the Administrator, they can do so through syft.register().
- domain_client.request_budget() - someone logged in via python can make a request for more budget which will populate into the requests queue of the Domain. If the request is approved (via either the UI or python interface), that user will have the additional budget allocated to their account.
> syft.register() and domain_client.request_budget()

- notebooks/course3/DS Search and Select a Network.ipynb
> [WIP] Mock Notebooks for course 3

- packages/grid/backend/backend.dockerfile
- packages/grid/backend/prestart.sh
- packages/grid/backend/worker-start.sh
- tests/integration/smpc_share_test.py
- Moved copy of source to after pip install layers to speed up rebuilds
- Changed to cpu version of torch libraries for smaller download
- Marked SMPC test as xfail to help CI docker cache pass
- Added buildkite to backend.dockerfile to speed up builds
> Fixing some Docker issues

- notebooks/trade_demo/demo/Data Owner - Canada.ipynb
- notebooks/trade_demo/demo/Data Owner - Italy.ipynb
- packages/grid/.env
- packages/grid/frontend/src/lib/auth.ts
- packages/syft/src/syft/core/node/common/node_manager/dataset_manager.py
- packages/syft/src/syft/core/node/common/node_service/dataset_manager/dataset_manager_service.py
- packages/syft/src/syft/core/node/common/node_service/get_all_requests/get_all_requests_messages.py
- packages/syft/src/syft/core/tensor/autodp/single_entity_phi.py
- packages/syft/src/syft/util.py
- tox.ini
Fixed stuff and added integration tests.
> SMPC + AutoDP Integration Tests

- .github/file-filters.yml
Security checks to frontend packages are not triggering integration tests which means we don't know if they will break.
> Added .lock and .json to stack tests to include frontend package updates

- README.md
- packages/hagrid/hagrid/__init__.py
- packages/syft/setup.py
- packages/syft/src/syft/core/node/common/node_service/user_manager/user_manager_service.py
- packages/syft/src/syft/core/node/network/client.py
- scripts/bootstrap.py
- Released HAGrid==0.1.6
- Updated python shebang
- Updated README.md with publish steps
> Released HAGrid==0.1.6

- .bumpversion.cfg
- .github/workflows/continuous-delivery.yml
- tox.ini
- Testing in a few days but will change to weekend releases later
> Adding bump2version and continuous delivery Github Action

- notebooks/course3/L2_Demo.ipynb
> Update Lesson 2 notebook

- packages/grid/quickstart/template.json
> Updating azure quickstart template image reference

- packages/grid/backend/grid/core/celery_config.py
- packages/syft/src/syft/core/smpc/protocol/aby3/aby3.py
- packages/syft/src/syft/core/tensor/smpc/party.py
- packages/syft/src/syft/core/tensor/smpc/share_tensor.py
> Add new spdz algo with less mul

- notebooks/trade_demo/demo/Data Owner - Canada.ipynb
- notebooks/trade_demo/demo/Data Owner - Italy.ipynb
- notebooks/trade_demo/demo/Data Scientist.ipynb
- packages/syft/src/syft/core/node/common/action/smpc_action_functions.py
- packages/syft/src/syft/core/smpc/protocol/aby3/aby3.py
- packages/syft/src/syft/core/smpc/protocol/spdz/spdz.py
> Remove one final multiplication and print statements

- packages/grid/backend/grid/core/celery_app.py
- packages/grid/backend/grid/core/celery_config.py
- packages/grid/backend/grid/core/celery_serde.py
Moved config into celery_config file and added celery_serde
> Moved config into celery_config file and added celery_serde

- README.md
- packages/hagrid/hagrid/__init__.py
> Released HAGrid 0.1.7

- docs/source/deployment/index.rst
Extended the prerequisites in the installation docs to be used in Course 3.
- Built the docs and the content is rendered fine.
FYI @yemikifouly.
> Add more explanation in the installation docs

- .github/workflows/stack-integration_tests.yml
> fixing k8s test

- docs/source/index.rst
Images were corrupted before and did not rendered correctly in the Docs.
- Renders correctly
-
> Update images for macOS tutorial

- packages/syft/src/syft/core/smpc/protocol/spdz/spdz.py
- packages/syft/src/syft/core/tensor/smpc/mpc_tensor.py
- packages/syft/src/syft/core/tensor/smpc/share_tensor.py
- tests/integration/smpc/tensor/mpc_tensor_test.py
Added tests for comparison operation.
Added unit tests.
> Added tests for comparison operation.

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/win_bootstrap.py
> Windows Bootstrap

- packages/syft/src/syft/core/tensor/smpc/mpc_tensor.py
- tests/integration/smpc/numpy/smpc_numpy_ops_test.py
Implmented numpy ops
Added unit tests for the same.
> SMPC Numpy Ops Iteration 2

- .bumpversion.cfg
- .github/workflows/continuous-delivery.yml
- packages/grid/backend/backend.dockerfile
- Install cpu wheel on x86 and auto detect on aarch64 / M1 container
> Smaller torch wheel

- packages/syft/src/syft/core/tensor/__init__.py
- packages/syft/src/syft/core/tensor/passthrough.py
- packages/syft/src/syft/core/tensor/smpc/mpc_tensor.py
- packages/syft/src/syft/core/tensor/smpc/share_tensor.py
- packages/syft/src/syft/core/tensor/tensor.py
- tests/integration/smpc/numpy/smpc_numpy_ops_test.py
Added numpy ops
Added unit tests for the same
> SMPC Numpy Iteration 3

- docs/source/install_tutorials/linux.rst
Edit install  instruction for hagrid
> hagrid install doc fix

- .bumpversion.cfg
- .github/workflows/stack-integration_tests.yml
- VERSION
- packages/grid/VERSION
- packages/grid/backend/grid/tests/conftest.py
- packages/hagrid/hagrid/art.py
- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/lib.py
- packages/hagrid/tests/hagrid/cli_test.py
- packages/syft/src/syft/VERSION
- packages/syft/tests/conftest.py
- tests/integration/conftest.py
- tests/integration/network/large_message_test.py
- tox.ini
This PR is to setup CI runners for windows testing.
> [WIP]windows Ci test runner setup

- packages/hagrid/hagrid/__init__.py
> Released HAGrid 0.1.9

- docs/source/install_tutorials/linux.rst
- docs/source/install_tutorials/osx_11_5_1.rst
> Update HAGrid version in install docs

- .github/workflows/continuous-delivery.yml
We don't want to release any alphas during the break.
> Disabling CD for the holidays 🎁🎄🎅🏽

- .github/workflows/stack-integration_tests.yml
- packages/grid/vpn/headscale.dockerfile
> debugging with tunshell

- .github/workflows/continuous-delivery.yml
- .github/workflows/stack-integration_tests.yml
> Merging in dev

- packages/hagrid/hagrid/__init__.py
> Releasing HAGrid

- .pre-commit-config.yaml
- packages/grid/vpn/tailscale.dockerfile
Changing tailscale container to use official tailscale client release.
> Changed to use official tailscale client docker container

- packages/syft/tests/syft/core/tensor/passthrough_test.py
This is a demo PR for getting started on Unit Tests.
> Added first unit test for PassthroughTensor

- packages/syft/src/syft/core/pointer/garbage_collection/gc_batched.py
- packages/syft/src/syft/core/pointer/garbage_collection/gc_simple.py
Document the `simple` and `batched` garbage collection.
- There are already tests for this functionality
> Add documentation for gc logic

- packages/grid/frontend/yarn.lock
> fix insecure nanoid library

- packages/grid/frontend/yarn.lock
> Revert "fix insecure nanoid library"

- packages/syft/proto/core/store/store_object.proto
- packages/syft/src/syft/core/store/storeable_object.py
> added write permissions to store_object.*

- .github/workflows/grid-backend_tests.yml
- .github/workflows/hagrid-pr_tests.yml
- .github/workflows/linting.yml
- .github/workflows/nightlies-run.yml
- .github/workflows/stack-integration_tests.yml
- .github/workflows/syft-merge_torch_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- .github/workflows/syft-version_tests.yml
This PR setups a nightly run of our CI tests, to run at a scheduled time. 
No dependencies were affected.
> Nightlies run setup

- packages/grid/frontend/yarn.lock
> Updated node-fetch to safer version

- packages/grid/backend/grid/api/datasets/__init__.py
- packages/grid/backend/grid/api/meta/__init__.py
- packages/grid/backend/grid/api/router.py
- packages/grid/backend/grid/api/users/__init__.py
Add documentation for some parts of the `Grid/Api` part of the source code.
Nothing is affected.
- The CI tests should pass because only documentation was added.
> Add doc for Grid API

- .github/workflows/hagrid-pr_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- packages/grid/backend/requirements.txt
- packages/syft/setup.cfg
- tox.ini
- Updating numpy to latest version which fixes other security issues
> Fixing numpy security issue

- packages/syft/setup.cfg
- packages/syft/src/syft/core/adp/vm_private_scalar_manager.py
- packages/syft/src/syft/core/common/decorators.py
- packages/syft/src/syft/core/common/uid.py
> cache prime and uuids

- .bumpversion.cfg
- .github/workflows/continuous-delivery.yml
- .github/workflows/grid-backend_tests.yml
- .github/workflows/nightlies-run.yml
- VERSION
- packages/grid/VERSION
- packages/grid/backend/pyproject.toml
- packages/grid/devspace.yaml
- packages/grid/frontend/package.json
- packages/grid/frontend/src/pages/_domain/login.tsx
- packages/syft/src/syft/VERSION
- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/core/node/common/node_table/utils.py
- packages/syft/tests/syft/core/tensor/autodp/row_entity_phi_test.py
- packages/syft/tests/syft/core/tensor/autodp/single_entity_phi_test.py
Reenabled CD for Spicy Swan🌶🦢 0.7.0
> Enable cd for 🌶🦢 (0.7.0)

- scripts/delete_old_workflows.sh
Old workflows are also cleaned up.
> Added script to cleanup old github actions workflows

- README.md
- docs/source/deployment/index.rst
- packages/grid/backend/pyproject.toml
- packages/syft/CONTRIBUTING.md
- packages/syft/README.md
- packages/syft/docs/installing.rst
- packages/syft/setup.cfg
- packages/syft/src/syft/lib/python/bool.py
- packages/syft/tests/syft/lib/python/complex/complex_test.py
- packages/syft/tests/syft/lib/python/string/string_utils_test.py
> Removed more references to python 3.7

- packages/syft/src/syft/__init__.py
> bump version syft __init__.py

- .github/workflows/continuous-delivery.yml
`packages/syft/src/syft/__init__.py` was missing in the workflow auto-commit, added it.
> added missing file to workflow commit

- .github/file-filters.yml
- .github/workflows/grid-frontend_tests.yml
- packages/grid/.env
- packages/grid/frontend/cypress/e2e/domain.spec.ts
- packages/grid/frontend/cypress/e2e/login.spec.ts
- packages/grid/frontend/cypress/e2e/network.spec.ts
- packages/grid/frontend/cypress/plugins/index.js
- packages/grid/frontend/package.json
- packages/grid/frontend/scripts/check_yarn.sh
- packages/grid/frontend/tsconfig.json
- tox.ini
- Merged Cypress tests into single test for now
- Added ability to override NEXT_PUBLIC_HOST during testing
> Added cypress front end ui tests to GitHub CI

- packages/syft/tests/syft/lib/allowlist_test.json
> Ignore mutation of torch tensor during tests changing _version attr

- packages/syft/src/syft/core/node/common/action/smpc_action_functions.py
- packages/syft/src/syft/core/smpc/protocol/spdz/spdz.py
- packages/syft/src/syft/core/tensor/smpc/mpc_tensor.py
- packages/syft/src/syft/core/tensor/smpc/utils.py
> FPT-1 SMPC code cleanup

- packages/hagrid/setup.py
> hotfix for hagrid bootstrapping

- packages/grid/scripts/cron.sh
> Fixed issue with CONTAINER_HASH and old docker compose container names

- packages/grid/scripts/cron.sh
> Fixing issue where release is not being set properly from old crontabs

- packages/grid/scripts/redeploy.sh
> Updating redeploy.sh as well

- packages/grid/scripts/cron.sh
> improved edge cases and outputted more debugging variables in cron.sh

- packages/syft/tests/syft/core/tensor/passthrough_test.py
Added missing test coverage
n/a
Locally Tested
> passthrough missing coverage fixed.

- packages/grid/scripts/cron.sh
- packages/grid/scripts/redeploy.sh
- packages/hagrid/setup.py
> Explicitly, install ansible when not on windows to fix bootstrapping

- tox.ini
> Fix stack test

- .github/workflows/doc.yml
Add doc building and deployment to CI
> setup action for docs

- .github/workflows/linting.yml
- .pre-commit-config.yaml
- docs/source/conf.py
- packages/grid/backend/backend.dockerfile
- packages/grid/backend/input.sh
- scripts/flush_queue.sh
- Fixed docs linting issues
- Refactored extra shell script into a single external script
> Remove script + Linting

- README.md
> updated readme.md with  latest documentation

- README.md
> Update Readme with latest documentation.

- .github/workflows/stack-integration_tests.yml
> Updated minikube to v1.25.2

- notebooks/Experimental/Rasswanth/blob_test.ipynb
- packages/syft/src/syft/core/node/common/client.py
- packages/syft/src/syft/core/pointer/pointer.py
> made minor changes to get

- docs/GSOD22.md
> Added GSOD 22 docs file

- README.md
> Updated README.md to add instructions for HAGrid CLI deployments

- packages/hagrid/hagrid/cli.py
Added a method  to create project  if the project ID given is not an existing project.
> added a check for project gcp

- packages/grid/.env
- packages/hagrid/hagrid/cli.py
- packages/syft/setup.cfg
> [WIP] Randomize_STACK_API_KEY

- packages/grid/backend/backend.dockerfile
- packages/grid/vpn/headscale.dockerfile
- packages/grid/vpn/requirements.txt
- packages/hagrid/hagrid.dockerfile
- packages/syft/setup.cfg
- packages/syft/tests/syft/core/common/message_test.py
- This provides prebuilt wheels for Apple Silicon M1
> hotfix updating PyNaCl==1.5.0

- .github/workflows/stack-integration_tests.yml
- .pre-commit-config.yaml
- packages/grid/ansible/group_vars/all/vars.yml
- packages/grid/ansible/roles/node/tasks/main.yml
- packages/grid/ansible/roles/node/tasks/system.yml
- packages/grid/ansible/roles/update/tasks/main.yml
- packages/grid/packer/azure.pkr.hcl
- packages/grid/scripts/containers.sh
- packages/grid/scripts/rc.local.j2
- packages/hagrid/hagrid/lib.py
hotfix to update docker compose and add container start script to vms
> hotfix to update docker compose and add container start script to vms

- .pre-commit-config.yaml
Fixing black in pre-commit
https://github.com/psf/black/issues/2964
> Fixing black in pre-commit

- packages/grid/ansible/roles/update/tasks/main.yml
- packages/grid/packer/azure.pkr.hcl
> Fixed startup script permissions and bumped image version

- packages/hagrid/hagrid/cache.py
- packages/hagrid/hagrid/cli.py
- packages/hagrid/scripts/install.sh
- Added HAGrid sh install script
- Changed default azure vm size
- Added provision=false to create VMs without provisioning for the demo
> Added HAGrid sh install script

- .github/workflows/hagrid-continuous_delivery.yml
> added checkout for the repo

- .github/workflows/syft-merge_torch_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- .github/workflows/syft-version_tests.yml
> Fixing merge tests on CI

- .github/workflows/benchmark.yml
- packages/grid/backend/requirements.txt
- packages/syft/setup.cfg
> Fix Benchmarks

- packages/syft/setup.cfg
> pin jaxlib to version 0.3.5

- .github/workflows/stack-integration_tests.yml
- tests/integration/network/connect_nodes_test.py
- tox.ini
> Force docker desktop to start on Windows runners if it hasn't already

- packages/syft/src/syft/core/tensor/autodp/ndim_entity_phi.py
- packages/syft/tests/syft/core/tensor/adp/ndim_entity_phi_test.py
Implemented the `pos` operator with @ivyclare for NDEPTs! 
None.
We added a test in the relevant NDEPT test file :)
> Implemented pos operation for NDEPT and added test

- notebooks/adastra/data-owners/01-data-owners-start.ipynb
> update working network ip

- .github/workflows/stack-integration_tests.yml
- packages/syft/MANIFEST.in
- tests/integration/e2e/trade_demo_smpc_adp_test.py
- tox.ini
This PR adds a CI test for the public deployment of Hagrid and Docker.
> added integration test for public hagrid docker

- packages/syft/src/syft/core/adp/data_subject_ledger.py
Fixing Final import for python 3.7 for google colab
> Fixing Final import for python 3.7 for google colab

- .github/workflows/benchmark.yml
> modified benchmark to nightlies

- .github/workflows/nightlies-run.yml
A PR to fix nightlies to inherit secrets for benchmark.
> inherit secrets in nightlies

- .github/workflows/benchmark.yml
Make sure Benchmark only runs in nightlies.
> making benchmark run only in nightlies

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/lib.py
- packages/hagrid/hagrid/rand_sec.py
> Fixed issue breaking hagrid in older python

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/lib.py
> save vm details to json post node launch in hagrid

- tox.ini
> Change the courses test back to the main repo

- .github/workflows/hagrid-pr_tests.yml
- packages/hagrid/hagrid/art.py
- packages/hagrid/hagrid/azure.py
- packages/hagrid/hagrid/cache.py
- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/deps.py
- packages/hagrid/hagrid/grammar.py
- packages/hagrid/hagrid/lib.py
- packages/hagrid/hagrid/mode.py
- packages/hagrid/hagrid/win_bootstrap.py
This PR aims to add previous versions of python to be tested for Hagrid to ensure compatibility.
> adding previous python versions to hagrid PR test

- notebooks/adastra/data-owners/01-data-owners-start.ipynb
> add MedNIST dataset upload details in adastra do notebook

- notebooks/adastra/network-operators/01-network-operators-create-empty-vm.ipynb
- packages/grid/docker-compose.yml
- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/lib.py
- packages/hagrid/setup.py
- packages/syft/src/syft/registry.py
- Updated network operator notebook for AdAstra
- Pinned cryptography breaking paramiko
see: https://github.com/paramiko/paramiko/pull/2039
- Added /ping endpoint so that NetworkRegistry works on --headless
> Fixed issue with tempdir and public key in HAGrid

- .github/workflows/stack-integration_tests.yml
- .pre-commit-config.yaml
- Currently the arm64 builds are setting a different buildx builder
> Reset docker buildx on self hosted runners

- packages/syft/src/syft/core/tensor/autodp/phi_tensor.py
- packages/syft/src/syft/core/tensor/fixed_precision_tensor.py
- packages/syft/src/syft/core/tensor/smpc/mpc_tensor.py
- packages/syft/src/syft/core/tensor/tensor.py
> added concat and slicing

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/lib.py
- packages/hagrid/setup.py
> Update HAGrid check --wait

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/lib.py
- packages/hagrid/setup.py
Making Hagrid more "Hagridy", with new feature checks. 🙂
> [WIP]Hagrid Check New Features

- packages/grid/vpn/tailscale.py
- packages/syft/src/syft/core/node/common/node_service/vpn/vpn_messages.py
- scripts/reset_network.sh
- Disconnect VPN before joining to prevent hangs when joining new network
> Updating reset network script

- packages/syft/src/syft/core/tensor/smpc/mpc_tensor.py
- tests/integration/smpc/tensor/tensor_abstraction_test.py
> Fixed TensorPointer concat

- packages/hagrid/hagrid/cli.py
- packages/hagrid/setup.py
> Fixing issue with hagrid kwarg name and pyOpenSSL packages

- notebooks/adastra/data-owners/02-data-owners-setup-domain.ipynb
- notebooks/adastra/data-owners/03-data-owners-join-network.ipynb
> small notebook fixes

- benchmarks/macro_executor.py
- packages/grid/docker-compose.test.yml
- packages/syft/src/syft/ast/klass.py
- packages/syft/src/syft/core/node/common/client.py
- packages/syft/src/syft/core/node/common/util.py
- packages/syft/src/syft/core/node/domain_client.py
- packages/syft/src/syft/core/pointer/pointer.py
- packages/syft/src/syft/core/tensor/ancestors.py
- packages/syft/src/syft/core/tensor/autodp/phi_tensor.py
- packages/syft/src/syft/core/tensor/smpc/mpc_tensor.py
- packages/syft/src/syft/core/tensor/tensor.py
- tests/integration/conftest.py
- tests/integration/e2e/spicy_swan_performance_test.py
> set upload blob store to True

- notebooks/adastra/data-scientists/mednist-data-scientist.ipynb
> Modified  DS Training notebook of Adastra

- packages/syft/src/syft/core/node/common/client_manager/request_api.py
- packages/syft/src/syft/core/node/common/client_manager/user_api.py
- packages/syft/src/syft/core/node/domain_client.py
fix issue on .all in user_api with new user message
> add create_user method on domain client

- packages/hagrid/hagrid/lib.py
> exit while if search is False

- packages/hagrid/.gitignore
- packages/hagrid/hagrid/cli.py
- Reading existing envs and generating a new env file
> Adding work around for broken docker compose 2.5.1

- notebooks/medical-federated-learning-program/network-operators/01-network-operators-create-empty-vm.ipynb
> added APIs to auto update data splits start,end index in a google sheet

- notebooks/medical-federated-learning-program/network-operators/01-network-operators-create-empty-vm.ipynb
> Changed email wording

- notebooks/medical-federated-learning-program/data-owners/utils.py
> added image visualization in dataset download function

- notebooks/medical-federated-learning-program/data-owners/utils.py
> Updating MFLP

- scripts/reset_network.sh
> Added association_request to reset network script

- notebooks/medical-federated-learning-program/network-operators/01-network-operators-create-empty-vm.ipynb
> add a cell to re - send email to a participant

- packages/grid/frontend/yarn.lock
> Updated json-schema to fix vulnerability

- docs/source/deployment/glossary.rst
These changes have been made as mentioned and discussed with Kyoko and Irina.
None
Compiled the docs build and verified the content as well as the addition of an external link to the Differential Privacy book.
> [Docs] Fixes the Glossary content

- benchmarks/macro_executor.py
> switching to 1M rows

- .github/workflows/nightlies-run.yml
- .github/workflows/stack-integration_tests.yml
> Reverted CI changes back

- tests/integration/network/request_load_test.py
> Extending wait time for load test during emulation of arm64

- packages/syft/setup.cfg
- tests/integration/e2e/smpc_dp_operation_test.py
- Increased timeout on smpc test
> Added ignore for new bugbear flake8 issues

- .github/workflows/hagrid-continuous_delivery.yml
> Changed hagrid CD back to weekly

- docs/source/install_tutorials/linux.rst
Simply solved a small typo.
None.
> Small typo

- packages/grid/backend/grid/tests/conftest.py
https://github.com/pytest-dev/pytest-asyncio/issues/386
> Fixed issue with strict pytest-asyncio breaking

- notebooks/Experimental/Osam/login_test.ipynb
- packages/syft/src/syft/grid/client/client.py
Fixed print statement for data scientist login with warning to change default password 
> Fixed Print Statement for DS Login

- .github/workflows/continuous-delivery.yml
> Adding linux/arm64 support to our docker build step in CD

- packages/grid/svelte/README.md
Updating README.md with additional info about starting a development server.
None
- No tests required for readme update.
> PyGrid UI - Svelte README.md Update

- .github/workflows/continuous-delivery.yml
- packages/grid/frontend/frontend.dockerfile
> arm64 docker containers

- packages/grid/backend/backend.dockerfile
> Compile ruamel.yaml on arm64 in case we later use dev mode

- .github/workflows/stack-integration_tests.yml
> Update k3s and force docker volume cleanup

- packages/hagrid/hagrid/deps.py
> Fixed words silliest bug 🙈🤦🏻‍♂️

- .github/workflows/stack-integration_tests.yml
- .github/workflows/syft-merge_torch_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-version_tests.yml
- README.md
- packages/grid/backend/backend.dockerfile
- packages/hagrid/hagrid/deps.py
- packages/syft/setup.cfg
- tox.ini
Adding custom built arm64 linux wheel
> Upgrading jaxlib to 0.3.14

- .github/workflows/nightlies-run.yml
- .github/workflows/stack-integration-public_tests.yml
- .github/workflows/stack-integration_tests.yml
- .github/workflows/syft-merge_torch_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-version_tests.yml
- README.md
- packages/grid/backend/backend.dockerfile
- packages/hagrid/hagrid/deps.py
- packages/syft/setup.cfg
- tests/integration/security/check_api_auth_test.py
- tests/integration/security/check_vpn_firewall_test.py
- tox.ini
> Fixing issue where bash if echos were not returning error codes

- notebooks/mflp_sessions/Project2_PlayingWithNetworks/DO_prepared.ipynb
- notebooks/mflp_sessions/Project2_PlayingWithNetworks/DS_prepared.ipynb
- notebooks/mflp_sessions/Project2_PlayingWithNetworks/Live_version.ipynb
- notebooks/mflp_sessions/Project2_PlayingWithNetworks/README.md
> Added notebooks from session 2 of Playing with PySyft

- packages/syft/src/syft/core/common/serde/recursive_primitives.py
- packages/syft/tests/syft/lib/python/collections/ordered_dict/ordered_dict_serde_test.py
- packages/syft/tests/syft/lib/python/complex/serde_test.py
- packages/syft/tests/syft/lib/python/dict/dict_serde_test.py
- packages/syft/tests/syft/lib/python/float/serde_test.py
- packages/syft/tests/syft/lib/python/int/int_test.py
- packages/syft/tests/syft/lib/python/int/serde_test.py
- packages/syft/tests/syft/lib/python/list/list_serde_test.py
- packages/syft/tests/syft/lib/python/range/range_serde_test.py
- packages/syft/tests/syft/lib/python/set/serde_test.py
- packages/syft/tests/syft/lib/python/slice/slice_serde_test.py
- packages/syft/tests/syft/lib/python/string/string_serde_test.py
> Serde refactoring 

- .github/workflows/stack-integration_tests.yml
- .gitignore
> Reverting and pinning devspace to v5 for now

- .github/workflows/syft-merge_torch_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- .github/workflows/syft-version_tests.yml
- packages/grid/backend/backend.dockerfile
- packages/hagrid/hagrid/deps.py
- packages/syft/setup.cfg
- Apple Silicon Wheels available
- Windows no longer needs to compile
- Updated HAGrid install wizard
> Updating pycapnp==1.2.0

- packages/hagrid/hagrid/cache.py
- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/quickstart_ui.py
- Added a/y/N options
- Cleaned up output
> Improved quickstart downloads to handle folders better

- .github/workflows/continuous-delivery.yml
> add PyYaml to setup during syft deployment

- .bumpversion.cfg
- VERSION
- packages/grid/VERSION
- packages/grid/devspace.yaml
- packages/grid/frontend/package.json
- packages/grid/frontend/src/pages/_domain/login.tsx
- packages/hagrid/hagrid/manifest_template.yml
- packages/syft/src/syft/VERSION
- packages/syft/src/syft/__init__.py
This reverts commit 0d1f4f03705fff62a80a68a5346a7d18dda6da75.
> Revert "bump version"

- packages/syft/proto/lib/numpy/array.proto
- packages/syft/src/syft/core/tensor/passthrough.py
- packages/syft/src/syft/lib/numpy/array.py
- packages/syft/src/syft/proto/lib/numpy/array_pb2.py
- Added .size to PassthroughTensor
> Added numpy scalar serde

- notebooks/quickstart/pwp_sessions/Playing with Pets Session 4.ipynb
> add pwp session 4 notebook

- .github/workflows/syft-merge_torch_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- .github/workflows/syft-version_tests.yml
- packages/grid/backend/backend.dockerfile
- packages/hagrid/hagrid/deps.py
- packages/syft/setup.cfg
This reverts commit 3ec76ac58e692848f699282a77cd0e67934907d6.
> Revert "Updating pycapnp==1.2.0"

- packages/hagrid/hagrid/cli.py
> Small hagrid fixes

- .github/workflows/syft-merge_torch_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- .github/workflows/syft-version_tests.yml
- packages/grid/backend/backend.dockerfile
- packages/hagrid/hagrid/deps.py
- packages/syft/setup.cfg
> Madhava/pycapnp 1.2.1

- README.md
- docs/source/install_tutorials/have_prerequisites.rst
- docs/source/install_tutorials/linux.rst
- docs/source/install_tutorials/osx_11_5_1.rst
- notebooks/mflp_sessions/Project3_Hagrid_Deep_Dive/Playing with Pets - Session 3.ipynb
- packages/grid/ansible/roles/aa_demo/tasks/main.yml
- packages/hagrid/hagrid/deps.py
- packages/syft/README.md
- Updated all instances of pip install syft to use -U and --pre for now 
> Updated pip install syft instructions

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/deps.py
- packages/hagrid/hagrid/lib.py
>  fixes #6736

- packages/syft/setup.cfg
> revert to older version of pyzmq

- tox.ini
> Added removal of seaweedfs data volume

- .github/workflows/stack-integration_tests.yml
- .github/workflows/syft-merge_torch_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-version_tests.yml
- README.md
- packages/grid/backend/backend.dockerfile
- packages/hagrid/hagrid/deps.py
- packages/syft/setup.cfg
- packages/syft/src/syft/core/adp/data_subject_ledger.py
- packages/syft/src/syft/core/adp/vectorized_publish.py
- tests/course/tests/lesson_5_remote_ds_test.py
- tests/integration/e2e/smpc_dp_operation_test.py
- tests/integration/e2e/spicy_swan_performance_test.py
- tests/integration/e2e/trade_demo_smpc_adp_test.py
- tox.ini
> Attempting to match jax and jaxlib with TFF

- packages/grid/backend/backend.dockerfile
- packages/grid/backend/build_tensorstore.dockerfile
> Added linux arm64 build of tensorstore==0.1.25 for python 3.10

- .github/workflows/linting.yml
- .pre-commit-config.yaml
- packages/syft/setup.cfg
- Reverted to older protoc-wheel-0 build to match TFF protobuf
- Updated pre-commit and added ignore for new bugbear rule
> Fixing Linting

- .github/workflows/hagrid-pr_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- packages/syft/setup.cfg
- tox.ini
Forcing importlib-metadata==4.13.0 to fix bandit breaking
> Fixing bandit issues

- packages/syft/tests/trials/skill_test.py
Completed as per the Notebook No. 2 of the Padawan Program
N/A
Through unit test
> [syft] add padawan program test 

- packages/syft/tests/trials/skill_test.py
First, commit under the padawan program R2Q4.
No affected dependencies
tox -e padawan.trials
> Added padawan to skill_test.py

- packages/syft/tests/trials/skill_test.py
Added my first commit under the Padawan program R2Q4.
No added dependencies.
I ran the tests from padawan.trials via tox: `tox -e padawan.trials`
> Added my name to the skill test trial

- notebooks/quickstart/data-owner/00-deploy-domain.ipynb
Adding link to install wizard in step1 of 00-deploy-domain notebook.
#6833
> Fixing broken link to Install Wizard

- packages/syft/tests/trials/skill_test.py
PR for adding name padwan skill test
> Padwan skill test -nilansh

- packages/syft/tests/trials/skill_test.py
Added my name [Zarreen] in the skill_test.py file for the Padawan trial task.
> my first trial as a padawan in skill_test.py

- notebooks/quickstart/01-install-wizard.ipynb
- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/deps.py
- packages/hagrid/hagrid/quickstart_ui.py
- packages/syft/src/syft/core/tensor/ancestors.py
- Fix spacing in quickstart install wizard text on first startup.
- fix install_wizard notebook path
- fix hagrid check to accept single str
- add timeout to docker check function
Fixes: https://github.com/OpenMined/PySyft/issues/6797
Fixes: https://github.com/OpenMined/PySyft/issues/6889
Fixes: https://github.com/OpenMined/PySyft/issues/6886
Docker services not running (Mac):
> Quickstart improvements

- tests/integration/e2e/large_message_test.py
Re-enabling Large Message Test. 
As the serialization error is fixed in this PR: https://github.com/OpenMined/PySyft/pull/6873
> enable large_message_test.py in CI

- docs/source/guides/data-owner/00-deploy-domain.rst
- docs/source/guides/data-owner/01-upload-data.rst
- notebooks/Experimental/Rasswanth/hagrid_check.ipynb
- notebooks/Experimental/Shubham/TradeDemoE2E/Trade-demo-data-owners.ipynb
- notebooks/PySyTFF/DO.ipynb
- notebooks/medical-federated-learning-program/data-owners-full/02-data-owners-setup-domain.ipynb
- notebooks/medical-federated-learning-program/data-owners/data-owners-presentation.ipynb
- notebooks/padawan/03-architecture.ipynb
- notebooks/padawan/04-rpc-and-pointers.ipynb
- notebooks/petlab_sessions/TradeDemoE2E/Trade-demo-data-owners.ipynb
- notebooks/quickstart/01-install-wizard.ipynb
- notebooks/quickstart/data-owner/00-deploy-domain.ipynb
- notebooks/quickstart/data-owner/01-upload-data.ipynb
- packages/hagrid/hagrid/cli.py
- scripts/aa_demo/update_domain.sh
Fixes #6887
The PR aims to modify the hagrid check to show progress during its execution.
The wait command is removed, instead of that, we have added the timeout command.
Currently also the silent is defaulted to True to show the rich Console UI.
Screenshots of execution attached in the PR.
> Modifying UI of hagrid check command.

- notebooks/padawan/02-dev-setup.ipynb
Since currently Docker Desktop is licensed, modified the dev setup notebook to highlight Rancher Desktop as an to Docker Desktop.
> Modified Dev Setup Notebook

- packages/hagrid/hagrid/cli.py
> Show hagrid/syft versions during hagrid launch

- docs/source/guides/data-owner/00-deploy-domain.rst
- notebooks/Experimental/Shubham/TradeDemoE2E/Trade-demo-data-owners.ipynb
- notebooks/padawan/03-architecture.ipynb
- notebooks/padawan/04-rpc-and-pointers.ipynb
- notebooks/quickstart/01-install-wizard.ipynb
- notebooks/quickstart/data-owner/00-deploy-domain.ipynb
- notebooks/quickstart/data-owner/02-create-account-configure-pb.ipynb
- packages/hagrid/hagrid/cli.py
> Removed references to hagrid launch --silent to use new progress bars

- packages/syft/src/syft/core/tensor/__init__.py
- packages/syft/src/syft/core/tensor/autodp/gamma_functions.py
- packages/syft/src/syft/core/tensor/autodp/gamma_tensor.py
- packages/syft/src/syft/core/tensor/autodp/phi_tensor.py
- packages/syft/src/syft/core/tensor/tensor.py
Fixes #6969 
The PR aims to remove  partial functioning code from the codebase
- softmax
- exp
- reciprocal
- onehot
- mpc_swap
No tests, as no new functionality has been added.
> Removal of Partial Functioning Code

- packages/syft/src/syft/core/tensor/autodp/phi_tensor.py
Fixes #6933.
Using the Twitter demo notebook.
> Wrapped data_subjects check with an numpy array to work for singular values

- packages/syft/src/syft/grid/grid_url.py
- packages/syft/tests/syft/grid/grid_url_test.py
> [FIX] Login with an URL doesn't work without specifying port

- packages/syft/src/syft/core/tensor/ancestors.py
- packages/syft/src/syft/core/tensor/tensor.py
Fixing issue #6921 by adding messages to help signpost the user(s)
co-authored by: @bitsofsteve 
N/A
> Add signposting to help users know how to annotate Tensors, upload tensors, etc

- packages/syft/src/syft/core/node/enums.py
- packages/syft/src/syft/core/pointer/pointer.py
- packages/syft/src/syft/core/tensor/autodp/gamma_tensor.py
- packages/syft/src/syft/core/tensor/autodp/phi_tensor.py
- create pointer status enums
- refactor __repr__ for pointer, GammaTensorWrappedPointer, PhiTensorWrappedPointer
- include pointer exist status in __repr__ of the respective Pointer classes
Fixes https://github.com/OpenMined/PySyft/issues/6935
- List any relevant details for your test …
> Show .exists status of pointer in its __repr__

- packages/syft/src/syft/core/tensor/autodp/gamma_tensor.py
- packages/syft/src/syft/core/tensor/autodp/phi_tensor.py
- packages/syft/src/syft/core/tensor/lazy_repeat_array.py
- packages/syft/tests/syft/core/tensor/adp/gamma_tensor_test.py
- packages/syft/tests/syft/core/tensor/adp/phi_tensor_test.py
> Fix ones_like and zeros_like on DP pointers

- packages/syft/src/syft/core/node/common/node_service/user_manager/new_user_messages.py
> fix user update API throwing error on budget update

- docs/source/guides/data-owner/02-create-account-configure-pb.rst
- notebooks/quickstart/data-owner/02-create-account-configure-pb.ipynb
> remove submit credential step from docs post user creation

- .github/workflows/nightlies-run.yml
Fix nightlies repository secrets inheritance issue.
> added secret inheritance  to nightlies

- .bumpversion.cfg
- .pre-commit-config.yaml
- packages/syft/setup.cfg
- packages/syft/src/syft/core/common/message.py
- packages/syft/src/syft/core/node/common/node.py
- packages/syft/src/syft/core/node/common/node_service/publish/publish_service.py
- packages/syft/src/syft/core/tensor/ancestors.py
- packages/syft/src/syft/lib/python/bool.py
- packages/syft/src/syft/lib/python/int.py
- packages/syft/src/syft/lib/python/primitive_factory.py
- tox.ini
> Fixing bumpversion.cfg

- .github/workflows/benchmark.yml
- .github/workflows/continuous-delivery.yml
- .github/workflows/doc.yml
- .github/workflows/grid-backend_tests.yml
- .github/workflows/grid-frontend_tests.yml
- .github/workflows/hagrid-continuous_delivery.yml
- .github/workflows/hagrid-pr_tests.yml
- .github/workflows/nightlies-run.yml
- .github/workflows/stack-integration-arm64_tests.yml
- .github/workflows/stack-integration-public_tests.yml
- .github/workflows/stack-integration_tests.yml
- .github/workflows/syft-publish.yml
- packages/grid/ansible/roles/jupyter/tasks/main.yml
- packages/hagrid/hagrid/deps.py
- tox.ini
> Pinned tox version to 3.27.1

- packages/syft/setup.cfg
> Updating pycapnp

- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- packages/grid/backend/requirements.txt
- packages/syft/setup.cfg
> Upgrading sqlalchemy and ignoring safety check

- .bumpversion.cfg
- VERSION
- packages/grid/VERSION
- packages/grid/devspace.yaml
- packages/grid/frontend/package.json
- packages/grid/frontend/src/pages/_domain/login.tsx
- packages/hagrid/hagrid/manifest_template.yml
- packages/syft/src/syft/VERSION
- packages/syft/src/syft/__init__.py
> Madhava/update 0.8

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/deps.py
- packages/hagrid/hagrid/grammar.py
We don't have a need for this anymore. Plus the code doesn't work anyway.
> Remove `vm` as hagrid target

- packages/hagrid/hagrid/wizard_ui.py
- fix getting arguments from arg_cache in complete_install_wizard
Fixes: #7184 
> Fix broken Install Wizard

- .github/workflows/stack-integration_tests.yml
- packages/syft/src/syft/core/smpc/protocol/aby3/aby3.py
> Fixed issue with deprecated numpy.bool

- tests/integration/network/make_associations_test.py
- tests/integration/network/proxy_client_test.py
- tox.ini
> Fixing flapping k8s tests

- tests/integration/e2e/client_test.py
- tests/integration/network/connect_nodes_test.py
- Increased timeout for client test
- Added some retries and timeout improvements to test_3_connect_domain1
- Split Python and REST tests into two
> Increased timeout for client test

- packages/syft/src/syft/core/adp/data_subject_ledger.py
Fixes #7197
Ran `pytest packages/syft/tests/syft/core/adp/data_subject_ledger_test.py`
> Fixed minimize scalar for newer scipy version

- .github/workflows/nightlies-run.yml
- packages/syft/src/syft/core/adp/data_subject_ledger.py
> Adding log upload to arm64 test so we can debug

- packages/grid/backend/requirements.txt
- packages/syft/src/syft/core/node/common/node_service/oblv/oblv_service.py
- packages/syft/src/syft/oblv/model.py
- packages/syft/src/syft/oblv/oblv_proxy.py
Fixed the security vulnerabilities due to `subprocess` module, and
Updated the `requests` version to `2.28.1`
`requests==2.28.1`
- tested using `tox` locally
> Fixed CI tests

- packages/syft/tests/syft/core/tensor/adp/gamma_tensor_test.py
> added some checks for the lipschitz_bound

- .github/workflows/stack-integration_tests.yml
- packages/syft/tests/syft/core/tensor/adp/gamma_tensor_test.py
> ignore git config cleanup if it fails

- 7.1
- =7.1
Probably accidentally committed in #7214?
> Remove unused files

- .github/workflows/nightlies-run.yml
- .github/workflows/stack-integration_tests.yml
- packages/syft/src/syft/core/tensor/autodp/gamma_tensor.py
- packages/syft/tests/syft/core/tensor/adp/gamma_tensor_test.py
> Remove iDP-incompatible functions

- .github/workflows/syft-merge_torch_tests.yml
- .github/workflows/syft-pr_tests.yml
- .github/workflows/syft-security.yml
- .github/workflows/syft-version_tests.yml
- packages/grid/backend/backend.dockerfile
- packages/syft/scripts/adjust_torch_versions.py
- packages/syft/setup.cfg
- packages/syft/tests/syft/lib/allowlist_test.json
> Updating torch==1.13.1

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/deps.py
This is #7150 which seems to be lost when merging 0.7 -> 0.8
> Remerge #7150

- .github/workflows/benchmark.yml
- .github/workflows/continuous-delivery.yml
- .github/workflows/doc.yml
- .github/workflows/grid-backend_tests.yml
- .github/workflows/grid-frontend_tests.yml
- .github/workflows/hagrid-continuous_delivery.yml
- .github/workflows/hagrid-pr_tests.yml
- .github/workflows/nightlies-run.yml
- .github/workflows/stack-integration-arm64_tests.yml
- .github/workflows/stack-integration-public_tests.yml
- .github/workflows/stack-integration_tests.yml
- .github/workflows/syft-publish.yml
- packages/grid/ansible/roles/jupyter/tasks/main.yml
- tox.ini
> Try upgrading tox

- .github/workflows/stack-integration_tests.yml
- packages/syft/src/syft/core/node/common/node_service/user_manager/user_manager_service.py
Fixing issue with old users api call
- Disabling courses tests while we break compatibility with nodes
> Fixing issue with old users api call

- packages/hagrid/hagrid/cli.py
> Display correct platform version on windows

- packages/syft/tests/trials/skill_test.py
No message here.
Just a PR with edited Dictionary with My Name 😂
> First commit in padawan programm. Added Name to SkillTest

- .github/workflows/stack-integration_tests.yml
> Let's see if we can reboot failed windows machines to keep them fresh

- packages/syft/tests/trials/skill_test.py
Padawan trial 1: Added my name to `skill_test.py`
No
Passed the `tox -e padawan.trials`
> [Padawan trial 1] Added my name to skill_test.py

- packages/syft/tests/trials/skill_test.py
Added name in padawan trial 1.
N/A
Linting: pre-commit run --all-files
Tests Ran: tox -e padawan.trials
> [Padawan Trial 1: Ajinkya Mulay] Add name to skill_test

- packages/syft/tests/trials/skill_test.py
Added my name to skill_test.py for padawan_trail_1
N/A
- Locally on Win10 using pre-commit  
- test: mypy-hagrid ..................... failed
> Peter Chung - added name to padawan_trial_1

- .pre-commit-config.yaml
- packages/syft/tests/trials/skill_test.py
- tox.ini
> [NEW] Add my name in R3Q1 skill_test.py

- packages/syft/tests/trials/skill_test.py
Completed Trial of Skill
None
Linting: pre-commit run --all-files
Tests Ran: tox -e padawan.trials
>  [Trial of Skill] Add my name to Padawans dict

- tests/integration/network/connect_nodes_test.py
- tests/integration/network/make_associations_test.py
- tests/integration/network/proxy_client_test.py
- tests/integration/network/request_load_test.py
- Sending old Address for 0.7.0 nodes
> Fix issue with public latest / 0.7.0 tests and older client.id

- packages/syft/tests/trials/skill_test.py
Adding my name to the padawan skill test dict to ensure i have the dev setup in order.
During local tox run some tests failed.
- Locally mypy test has failed 
- [] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
>  [Padawan Trial 1: vani] attempt skill_test 1

- packages/grid/backend/grid/core/celery_config.py
- packages/grid/backend/grid/periodic_tasks.py
- packages/grid/backend/grid/worker.py
- packages/syft/src/syft/core/node/common/node_service/object_search/obj_search_service.py
- packages/syft/src/syft/core/node/common/node_service/task_submission/task_submission.py
- packages/syft/src/syft/core/node/common/node_table/task.py
- packages/syft/src/syft/core/node/domain_client.py
Fixed  current remote code execution
> Remote code execution 2

- packages/syft/tests/trials/skill_test.py
>  added Hithem to skill_test

- packages/syft/src/syft/core/node/new/test_service.py
- packages/syft/src/syft/core/node/worker.py
- packages/syft/src/syft/oblv/deployment_client.py
Integration of worker class into syft-enclave repo
> Integration of Worker into Enclave

- packages/grid/backend/grid/core/node.py
- packages/grid/backend/grid/tests/api/users/user_routes_test.py
- packages/syft/new_tests/worker/worker_test.py
- packages/syft/src/syft/core/node/common/node_manager/user_manager.py
- packages/syft/src/syft/core/node/common/node_table/syft_object.py
- packages/syft/src/syft/core/node/new/document_store.py
- packages/syft/src/syft/core/node/new/user.py
- packages/syft/src/syft/core/node/new/user_service.py
- packages/syft/src/syft/core/node/worker.py
> Moving service to use Stash and In Memory Dict Store

- .github/workflows/syft-pr_tests.yml
- packages/syft/new_tests/worker/user_stash_test.py
- packages/syft/new_tests/worker/worker_test.py
- packages/syft/src/syft/core/common/serde/recursive_primitives.py
- packages/syft/src/syft/core/common/serde/third_party.py
- packages/syft/src/syft/core/node/new/action_service.py
- packages/syft/src/syft/core/node/new/action_store.py
- packages/syft/src/syft/core/node/new/document_store.py
- packages/syft/src/syft/core/node/new/test_service.py
- packages/syft/src/syft/core/node/new/user_service.py
- packages/syft/src/syft/core/node/new/user_stash.py
- packages/syft/src/syft/core/node/worker.py
- packages/syft/src/syft/lib/util.py
- Fixing SerDe for Worker class
- Also fixed an issue with not being able to deserialize defaultdict
Closes https://github.com/OpenMined/Heartbeat/issues/19#issue-1563772479
Tested serializing and deserializing the worker class
> Fixing SerDe for Worker class, and fixing issue with SerDe for defaultdicts

- packages/grid/backend/grid/api/new/new.py
- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/new/document_store.py
- packages/syft/src/syft/core/node/new/user_service.py
- packages/syft/src/syft/core/node/new/user_stash.py
- packages/syft/src/syft/core/node/worker.py
Added instrumentation in more places for new client/server
Closes https://github.com/OpenMined/Heartbeat/issues/7#issue-1548597417
> Added instrumentation in more places for new client/server

- packages/grid/backend/grid/api/new/new.py
- packages/grid/backend/grid/core/node.py
- packages/syft/new_tests/worker/user_stash_test.py
- packages/syft/src/syft/core/node/new/action_store.py
- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/connection.py
- packages/syft/src/syft/core/node/new/document_store.py
- packages/syft/src/syft/core/node/new/response.py
- packages/syft/src/syft/core/node/new/user_service.py
- packages/syft/src/syft/core/node/new/user_stash.py
- packages/syft/src/syft/core/node/worker.py
- Added PythonConnection
- Added SyftSuccess response / result type
- Added nice repr for response types
> Added Connection abstraction to Client

- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/new/service.py
- packages/syft/src/syft/core/node/new/signature.py
- packages/syft/src/syft/core/node/new/user.py
- packages/syft/src/syft/core/node/new/user_service.py
> Service Method Autosplat

- tox.ini
> Fixed issue with $USER env on go docker builds in tox tasks

- .github/workflows/cleanup-notebooks.yml
> Added notebook cleanup task to CI

- .github/workflows/cleanup-notebooks.yml
> Auto Cleanup Notebooks

- packages/syft/src/syft/core/node/new/client.py
> Fix typo in SyftClient connection

- packages/syft/src/syft/core/node/new/action_service.py
Remove debug statements added in #7223
> Remove debug statements added in #7223

- packages/syft/src/syft/core/node/new/mongo_document_store.py
- tests/integration/network/connect_nodes_test.py
> Fixing mongo transform

- packages/syft/src/syft/core/node/common/node_table/syft_object.py
> Fixed transform to

- packages/grid/backend/grid/api/new/new.py
- packages/syft/src/syft/core/node/common/node.py
- packages/syft/src/syft/core/node/new/mongo_document_store.py
> fixed syft new_login

- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/data_subject.py
- packages/syft/src/syft/core/node/new/data_subject_service.py
- packages/syft/src/syft/core/node/new/dataset.py
- packages/syft/src/syft/core/node/new/roles.py
- packages/syft/src/syft/core/node/worker.py
add data subject service and stash
add data_subject_registry property to syft client
> Integrate Data Subject Registry

- packages/grid/devspace.yaml
> Fixing k8s start script path change

- packages/grid/backend/grid/api/new/new.py
- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/core/common/uid.py
- packages/syft/src/syft/core/node/common/node_table/node.py
- packages/syft/src/syft/core/node/common/node_table/syft_object.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/connection.py
- packages/syft/src/syft/core/node/new/context.py
- packages/syft/src/syft/core/node/new/credentials.py
- packages/syft/src/syft/core/node/new/kv_document_store.py
- packages/syft/src/syft/core/node/new/network_service.py
- packages/syft/src/syft/core/node/new/node_metadata.py
- packages/syft/src/syft/core/node/new/response.py
- packages/syft/src/syft/core/node/new/sqlite_document_store.py
- packages/syft/src/syft/core/node/new/transforms.py
- packages/syft/src/syft/core/node/new/user_service.py
- packages/syft/src/syft/core/node/new/worker_settings.py
- packages/syft/src/syft/core/node/worker.py
- Added Python simulated networking
- Added NodePeers and NodeRoutes
- Added ability to get client in subprocess to other Python worker
- Added _repr_debug_ to sqlite
> Added NetworkService

- notebooks/Experimental/syftception.ipynb
- packages/syft/src/syft/core/node/new/action_object.py
- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/network_service.py
- packages/syft/src/syft/core/node/new/queue_stash.py
- packages/syft/src/syft/core/node/worker.py
> Added ProxyClients

- packages/syft/new_tests/worker/worker_test.py
- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/core/node/new/action_store.py
- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/dataset.py
- packages/syft/src/syft/core/node/new/dict_document_store.py
- packages/syft/src/syft/core/node/new/document_store.py
- packages/syft/src/syft/core/node/new/sqlite_document_store.py
- packages/syft/src/syft/core/node/worker.py
> Added KeyValueActionStore

- packages/grid/backend/grid/core/node.py
- packages/syft/src/syft/core/node/new/action_service.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/dataset.py
- packages/syft/src/syft/core/node/new/messages.py
- packages/syft/src/syft/core/node/new/network_service.py
- packages/syft/src/syft/core/node/new/user_code.py
- packages/syft/src/syft/core/node/new/user_code_service.py
- packages/syft/src/syft/core/node/new/worker_settings.py
- packages/syft/src/syft/core/node/worker.py
> Input and Output Policies

- notebooks/Experimental/Shubham/Messaging%20Service.ipynb
- packages/syft/src/syft/core/node/new/dataset_service.py
- packages/syft/src/syft/core/node/new/message_service.py
- packages/syft/src/syft/core/node/new/messages.py
- packages/syft/src/syft/core/node/new/request.py
> Implement Linked Document for Messages

- packages/syft/src/syft/core/node/new/action_service.py
- packages/syft/src/syft/core/node/new/data_subject_service.py
- packages/syft/src/syft/core/node/new/dataset_service.py
- packages/syft/src/syft/core/node/new/linked_obj.py
- packages/syft/src/syft/core/node/new/message_service.py
- packages/syft/src/syft/core/node/new/messages.py
- packages/syft/src/syft/core/node/new/network_service.py
- packages/syft/src/syft/core/node/new/request_service.py
- packages/syft/src/syft/core/node/new/service.py
- packages/syft/src/syft/core/node/new/user_code.py
- packages/syft/src/syft/core/node/new/user_service.py
- Added service types and lookups
> Refactored LinkedDocument to be LinkedObject

- packages/grid/backend/grid/api/new/new.py
- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/user_service.py
> User Registration

- packages/grid/backend/grid/api/new/new.py
- packages/grid/frontend/src/lib/jsserde/jsClient.svelte
- packages/syft/src/syft/core/node/new/node_metadata.py
> Added metadata fields and switched frontend to use new endpoint

- packages/syft/setup.cfg
- packages/syft/src/syft/core/common/serde/third_party.py
- packages/syft/src/syft/core/node/new/action_object.py
- packages/syft/src/syft/core/node/new/action_store.py
- packages/syft/src/syft/core/node/new/action_types.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/dataset.py
- packages/syft/src/syft/core/node/new/linked_obj.py
- packages/syft/src/syft/core/node/new/pandas.py
- packages/syft/src/syft/core/node/new/request_service.py
- packages/syft/src/syft/core/node/new/sqlite_document_store.py
- packages/syft/src/syft/core/node/new/transforms.py
- packages/syft/src/syft/core/node/new/user_service.py
> Fixed bug with Asset overwriting Dataset fields due to shared context

- packages/syft/src/syft/core/node/new/api.py
> Add node_uid to serde of SyftAPI

- packages/grid/backend/grid/api/new/new.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/data_subject_service.py
- packages/syft/src/syft/core/node/new/document_store.py
- packages/syft/src/syft/core/node/new/kv_document_store.py
- packages/syft/src/syft/core/node/new/mongo_client.py
- packages/syft/src/syft/core/node/new/mongo_codecs.py
- packages/syft/src/syft/core/node/new/mongo_document_store.py
- packages/syft/src/syft/core/node/new/user.py
Fixed: 
- add a flag to ignore duplicates and skip throwing an exception during .set
- Add custom code class for encoding/decoding any syft type object -> 
e.g. Now we don't need to take care of converting SyftVerifyKey to str or handling UID for `_id`  before querying or storing.
Mongo now knows how to handle different syft objects and does that conversion for us.
- Fix User Registration  …
> Fix Bugs - Iter1

- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/registry.py
- packages/syft/src/syft/search.py
> Changed search to use domains and more key types

- packages/syft/src/syft/core/node/new/user_code.py
> Add policy code property to output policy

- packages/grid/backend/grid/core/node.py
- packages/syft/src/syft/core/node/new/action_object.py
- packages/syft/src/syft/core/node/new/action_types.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/pandas.py
- packages/syft/src/syft/core/node/new/request.py
- packages/syft/src/syft/core/node/new/user_code_service.py
- packages/syft/src/syft/core/node/worker.py
> Modified User Flow

- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/core/node/common/node_table/syft_object.py
- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/dataset.py
- packages/syft/src/syft/core/node/new/dataset_service.py
- packages/syft/src/syft/core/node/new/dataset_stash.py
- packages/syft/src/syft/core/node/new/document_store.py
- packages/syft/src/syft/core/node/new/kv_document_store.py
- packages/syft/src/syft/core/node/new/message_service.py
- packages/syft/src/syft/core/node/new/message_stash.py
- packages/syft/src/syft/core/node/new/project.py
- packages/syft/src/syft/core/node/new/project_service.py
- packages/syft/src/syft/core/node/new/project_stash.py
- packages/syft/src/syft/core/node/new/request.py
- packages/syft/src/syft/core/node/new/request_service.py
- packages/syft/src/syft/core/node/new/user.py
- packages/syft/src/syft/core/node/new/user_code.py
- packages/syft/src/syft/core/node/new/user_code_service.py
- packages/syft/src/syft/core/node/new/user_service.py
- packages/syft/src/syft/core/node/new/user_stash.py
- packages/syft/src/syft/core/node/worker.py
> Add Projects 

- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/core/common/serde/third_party.py
- packages/syft/src/syft/core/node/new/action_service.py
- packages/syft/src/syft/core/node/new/action_store.py
- packages/syft/src/syft/core/node/new/datetime.py
- packages/syft/src/syft/core/node/new/linked_obj.py
- packages/syft/src/syft/core/node/new/request.py
- packages/syft/src/syft/core/node/new/user_code.py
- packages/syft/src/syft/core/node/new/user_code_service.py
- packages/syft/src/syft/core/node/worker.py
- Added serde for Jupyter Image and Bytes.IO
- Added is_root helper
- Fixed bug with ActionStore permissions due to dict assign
- Added OutputPolicyState StateHistory
> Added accept_by_depositing_result on Code Enum requests

- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/core/node/new/data_subject.py
- packages/syft/src/syft/core/node/new/data_subject_service.py
- packages/syft/src/syft/core/node/new/dataset.py
add a DataSubjectCreate class
update DataSubject class to store members as a dict of name and UIDs only refactor dataset upload to use the new flow
refactor data subject add method to save the data subjects and its members recursively
- List any relevant details for your test …
> [WIP] Refactor Data subject and Registry

- packages/syft/src/syft/core/node/new/action_service.py
- packages/syft/src/syft/core/node/new/action_store.py
- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/new/context.py
- packages/syft/src/syft/core/node/new/credentials.py
- packages/syft/src/syft/core/node/new/node.py
- packages/syft/src/syft/core/node/new/request.py
- packages/syft/src/syft/core/node/new/task/oblv_service.py
- packages/syft/src/syft/core/node/new/task/task.py
- packages/syft/src/syft/core/node/new/task/task_service.py
- packages/syft/src/syft/core/node/new/test_service.py
- packages/syft/src/syft/core/node/new/user_code.py
- packages/syft/src/syft/core/node/new/user_code_service.py
- packages/syft/src/syft/core/node/worker.py
- packages/syft/src/syft/oblv/constants.py
- packages/syft/src/syft/oblv/deployment_client.py
- tests/integration/oblv/enclave_manual_code_submission_test.py
- tests/integration/oblv/enclave_user_code_manual_code_submission_test.py
> [WIP]Task Service -> UserCode Service

- .github/file-filters.yml
- .github/workflows/syft-notebook-tests.yml
- .pre-commit-config.yaml
- notebooks/api/0.8/00-load-data.ipynb
- packages/syft/src/syft/core/node/worker.py
- tox.ini
- Added first Notebook test
- Added reset option to Worker
> Added notebook testing from tox and github

- notebooks/api/0.8/01-submit-code.ipynb
- packages/syft/src/syft/__init__.py
- tox.ini
> Added second notebook test

- .pre-commit-config.yaml
- notebooks/api/0.8/00-load-data.ipynb
- notebooks/api/0.8/02-review-code-and-approve.ipynb
- notebooks/api/0.8/03-data-scientist-download-result.ipynb
- packages/syft/setup.cfg
- packages/syft/src/syft/core/node/new/action_object.py
- packages/syft/src/syft/core/node/new/numpy.py
- packages/syft/src/syft/core/node/new/sqlite_document_store.py
- packages/syft/src/syft/core/node/new/user_code.py
- packages/syft/src/syft/util.py
- tox.ini
> Added more notebook tests

- packages/grid/backend/grid/api/auth/login.py
- packages/syft/src/syft/grid/client/grid_connection.py
> Fix break to old python client

- packages/grid/backend/grid/api/auth/login.py
- packages/syft/src/syft/grid/client/grid_connection.py
> Removed code which was breaking SigningKey in old login

- packages/grid/frontend/src/routes/(auth)/login/+page.svelte
Fix login page to work with the new API.
> Fix /login page

- packages/grid/frontend/src/lib/client/jsclient/jsClient.svelte
- packages/grid/frontend/src/lib/components/NavBar.svelte
- packages/grid/frontend/src/routes/(app)/+layout.svelte
Small hotfixes to fix errors caused by the latest backend changes.
> Frontend hotfixes

- packages/grid/frontend/src/lib/client/jsclient/jsClient.svelte
This PR adds two methods to get a dataset or a list of datasets using the new PySyft Dataset Service.
> ADD JSClient get Dataset API 

- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/worker.py
> Changed is_valid message signature to return SyftResponse types

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/deps.py
- packages/hagrid/hagrid/parse_template.py
- packages/hagrid/hagrid/quickstart_ui.py
> Added bandit check nosec for url timeouts to hagrid

- notebooks/api/0.8/lineage_id.ipynb
- notebooks/api/0.8/noop.ipynb
- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/core/common/uid.py
- packages/syft/src/syft/core/node/new/action_data_empty.py
- packages/syft/src/syft/core/node/new/action_object.py
- packages/syft/src/syft/core/node/new/action_types.py
- packages/syft/src/syft/core/node/new/numpy.py
- packages/syft/src/syft/core/node/new/pandas.py
> Action Hash Ideas

- packages/syft/src/syft/core/node/new/action_service.py
This endpoint was added for debugging purpose only, not meant to be committed.
> Remove debug Action Service API endpoint

- .github/workflows/pr-tests-stack-public.yml
- tox.ini
> Changing nightly public tests to use beta releases

- packages/grid/frontend/src/lib/client/jsclient/jsClient.svelte
- packages/grid/frontend/src/lib/components/AccountSettings.svelte
- packages/grid/frontend/src/lib/components/Modal.svelte
- packages/grid/frontend/src/routes/(app)/config/+page.svelte
- packages/grid/frontend/src/routes/(app)/datasets/+page.svelte
- packages/grid/frontend/src/routes/(app)/home/+page.svelte
- packages/grid/frontend/src/routes/(auth)/login/+page.svelte
- packages/grid/frontend/src/routes/(auth)/signup/+page.svelte
This PR aims to fix bugs and issues created by the last UI changes.
> Hotfixes after dataset merge

- .github/workflows/pr-tests-stack-public.yml
> Adding logging to public tests

- packages/hagrid/hagrid/lib.py
> [Hagrid] Fix metadata url for health check on api

- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/new/client.py
- packages/syft/src/syft/core/node/new/dataset_service.py
- packages/syft/tests/syft/api_test.py
Invalidate cache at plan submission and login
> Invalidate api cache at plan submission and login

- .github/workflows/pr-tests-syft.yml
- packages/syft/tests/syft/worker_test.py
> Disabled broken test on local mac (works in CI)

- packages/syft/src/syft/core/node/new/sqlite_document_store.py
> Disabled WAL on SQLite while its breaking MacOS

- packages/grid/frontend/src/lib/client/jsclient/jsClient.svelte
- packages/grid/frontend/src/lib/components/Input.svelte
- packages/grid/frontend/src/routes/(app)/config/+page.svelte
- packages/grid/frontend/src/routes/(app)/datasets/+page.svelte
- packages/grid/frontend/src/routes/(app)/datasets/datasetDetail.svelte
- packages/grid/frontend/src/routes/(app)/datasets/datasetListItem.svelte
- packages/grid/frontend/src/routes/(app)/datasets/deleteDatasetModal.svelte
- packages/grid/frontend/src/routes/(app)/home/+page.svelte
- packages/grid/frontend/src/routes/(auth)/signup/+page.svelte
- packages/syft/src/syft/core/node/new/dataset_service.py
- ADD delete dataset at the dataset page allowing the data owner to delete their own dataset by using the PyGrid UI.
> ADD Delete dataset feature at dataset page

- packages/grid/frontend/frontend.dockerfile
> Forcing rebuild of lock file because its out of sync and breaking tests

- packages/syft/src/syft/core/node/new/document_store.py
- packages/syft/tests/syft/stores/base_stash_test.py
> Add BaseStash tests

- packages/syft/src/syft/core/node/new/api.py
- packages/syft/src/syft/core/node/new/queue_stash.py
Closes https://github.com/OpenMined/Heartbeat/issues/141
None
> [syft] fix nested requests in non-blocking api calls

- packages/hagrid/hagrid/lib.py
- packages/hagrid/hagrid/orchestra.py
- add a check for node already running for given name and port
- fix check for port availability to search for new ones if current occupied
Fixes: https://github.com/OpenMined/Heartbeat/issues/144
> Fix hagrid orchestra tries to start a domain twice

- tox.ini
> Fixed issue with tailing wrong container in stack tests

- packages/syft/src/syft/core/node/worker.py
> `Worker` fixes

- packages/syft/src/syft/core/node/new/document_store.py
Some typing, bug fixes and clean up for `BaseStash`, `Partition`/`QueryKey`(`s`)
> document_store fixes

- packages/syft/src/syft/trace_decorator.py
> Fixed instrument tracing

- packages/syft/tests/syft/request/request_stash_test.py
> Marked broken windows test as xfail

- packages/hagrid/hagrid/orchestra.py
- packages/syft/src/syft/core/node/new/api.py
> Fixed bug where path to user code was overwritten

- packages/grid/traefik/docker/dynamic.yml
- packages/grid/traefik/docker/traefik.yml
> Implement IP blacklisting and rate-limiting

- packages/hagrid/.bumpversion.cfg
- packages/hagrid/hagrid/orchestra.py
- packages/hagrid/hagrid/version.py
- packages/hagrid/setup.py
- packages/syft/setup.cfg
- packages/syft/src/syft/client/deploy.py
- packages/syft/src/syft/node/run.py
- packages/syft/src/syft/node/server.py
- tox.ini
- Added host to orchestra
- bumped hagrid to 0.3.x
> Added syft launch cli tool

- README.md
- notebooks/api/0.8/00-load-data.ipynb
- notebooks/api/0.8/01-submit-code.ipynb
- notebooks/api/0.8/02-review-code-and-approve.ipynb
- notebooks/api/0.8/03-data-scientist-download-result.ipynb
- notebooks/api/0.8/04-jax-example.ipynb
- notebooks/api/0.8/05-custom-policy.ipynb
- packages/grid/backend/grid/core/node.py
- packages/grid/worker/worker.py
- packages/hagrid/hagrid/orchestra.py
- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/abstract_node.py
- packages/syft/src/syft/client/api.py
- packages/syft/src/syft/client/client.py
- packages/syft/src/syft/node/domain.py
- packages/syft/src/syft/node/gateway.py
- packages/syft/src/syft/node/node.py
- packages/syft/src/syft/node/routes.py
- packages/syft/src/syft/node/server.py
- packages/syft/src/syft/node/worker_settings.py
- packages/syft/src/syft/serde/recursive.py
- packages/syft/src/syft/service/code/user_code.py
- packages/syft/src/syft/service/context.py
- packages/syft/src/syft/service/network/network_service.py
- packages/syft/src/syft/service/policy/policy.py
- packages/syft/src/syft/service/service.py
- packages/syft/src/syft/types/transforms.py
- packages/syft/tests/syft/worker_test.py
- tox.ini
- Added Domain and Gateway stub classes
- Updated README.md
> Renamed a few things

- .pre-commit-config.yaml
- packages/syft/src/syft/serde/recursive.py
- packages/syft/src/syft/serde/recursive_primitives.py
- packages/syft/src/syft/serde/serializable.py
> Added back mypy for syft progressively

- packages/syft/src/syft/core/node/new/lib_service_registry.py
- packages/syft/src/syft/core/node/new/service.py
> rebuild function for extracting signature from docstring

- .pre-commit-config.yaml
- packages/syft/setup.cfg
- packages/syft/src/syft/core/adp/vectorized_publish.py
- packages/syft/src/syft/core/tensor/smpc/share_tensor.py
> fixed FPT error

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/lib.py
> Fixed issue where importing syft triggers git clone

- .github/workflows/cd-syft.yml
- .github/workflows/pr-tests-enclave.yml
- .github/workflows/pr-tests-hagrid.yml
- .github/workflows/pr-tests-syft.yml
- packages/syft/setup.cfg
> Release 0.8 to pypi again

- .github/workflows/pr-tests-syft.yml
> Adding python 3.9 to the container notebook tests

- README.md
- notebooks/quickstart/01-install-wizard.ipynb
- packages/grid/VERSION
- packages/grid/devspace.yaml
- packages/grid/frontend/package.json
- packages/syft/setup.cfg
- packages/syft/src/syft/VERSION
- packages/syft/src/syft/__init__.py
> 7th time lucky 🍀

- .bumpversion.cfg
- .github/workflows/cd-syft.yml
- README.md
- VERSION
- packages/grid/VERSION
- packages/grid/devspace.yaml
- packages/grid/frontend/package.json
- packages/hagrid/hagrid/manifest_template.yml
- packages/syft/setup.cfg
- packages/syft/src/syft/VERSION
- packages/syft/src/syft/__init__.py
> Bumping to 0.8.1-beta.0

- README.md
> Set README to relative again

- packages/syft/tests/trials/skill_test.py
Tested using `pre-commit run --files packages/syft/tests/trials/skill_test.py` and `tox -e padawan.trials`
> Complete trial 1

- .github/file-filters.yml
- .github/workflows/pr-tests-frontend.yml
- packages/grid/frontend/playwright.config.ts
- packages/grid/frontend/scripts/check_pnpm.sh
- tox.ini
> Updated frontend tests in tox

- packages/syft/tests/trials/skill_test.py
Added my username to the skill_test.py file to complete the first Padawan trial.
- `tox -e padawan.trials`
> Add alejandrosame to skill_test

- packages/syft/tests/trials/skill_test.py
> feat: trial of skill

- packages/syft/tests/trials/skill_test.py
Added my name to the skill_test.py file to complete the first Padawan trial.
- `tox -e padawan.trials`
> Add Osam to skill_test

- packages/syft/tests/trials/skill_test.py
Added paramm name in R4Q2 dict
- Updated length test as well
> Added paramm name in R4Q2 dict

- .github/workflows/pr-tests-stack-public.yml
- .pre-commit-config.yaml
- packages/grid/frontend/src/app.html
- adding retry to nightly public builds (windows flaps)
> Updating linting tool

- notebooks/Experimental/projects/00-projects.ipynb
- packages/syft/src/syft/node/node.py
- packages/syft/src/syft/service/metadata/node_metadata.py
- packages/syft/src/syft/service/network/network_service.py
- packages/syft/src/syft/service/project/project.py
- packages/syft/src/syft/service/project/project_service.py
- packages/syft/src/syft/service/project/project_stash.py
- packages/syft/src/syft/types/datetime.py
- packages/syft/src/syft/types/syft_object.py
- tox.ini
- Fixed issues with network APIs
- Added first 0.9 notebook
- Added 0.9 notebook tests
> Project Sync

- notebooks/api/0.9/05-eager-execution.ipynb
- packages/grid/Vagrantfile
- packages/hagrid/hagrid/cache.py
- packages/hagrid/hagrid/cli.py
- tox.ini
- Remove eager execution connect to direct port
- TODO: update gcp ubuntu image
> Changed ubuntu to 22.04 with python 3.10 as default

- packages/syft/src/syft/service/action/action_object.py
- packages/syft/src/syft/service/action/numpy.py
- packages/syft/src/syft/service/action/pandas.py
- packages/syft/tests/syft/service/action/action_object_test.py
> fix error showing for actionobjects that should not have side effects

- packages/syft/tests/trials/skill_test.py
t## Description
Add tristan to skill_test.py
> Re-ADD trial/skill_test.py

- packages/syft/src/syft/__init__.py
- packages/syft/src/syft/service/code/user_code.py
> Debox ActionObject when calling unsafe_function locally

- .pre-commit-config.yaml
- notebooks/tutorials/data-engineer/01-setting-up-dev-mode.ipynb
- notebooks/tutorials/data-engineer/02-deployment-types.ipynb
- notebooks/tutorials/data-engineer/03-hagrid.ipynb
- notebooks/tutorials/data-engineer/04-deploy-container.ipynb
- notebooks/tutorials/data-engineer/05-deploy-stack.ipynb
- notebooks/tutorials/data-engineer/06-deploy-to-azure.ipynb
- notebooks/tutorials/data-engineer/07-deploy-to-gcp.ipynb
- notebooks/tutorials/data-engineer/08-deploy-to-aws.ipynb
- notebooks/tutorials/data-engineer/09-deploying-enclave.ipynb
- notebooks/tutorials/data-engineer/10-custom-deployment.ipynb
- notebooks/tutorials/data-owner/01-uploading-private-data.ipynb
- notebooks/tutorials/data-owner/02-account-management.ipynb
- notebooks/tutorials/data-owner/03-messages-and-requests.ipynb
- notebooks/tutorials/data-owner/04-joining-a-gateway.ipynb
- notebooks/tutorials/data-owner/05-syft-services-api.ipynb
- notebooks/tutorials/data-scientist/01-installing-syft-client.ipynb
- notebooks/tutorials/data-scientist/02-finding-datasets.ipynb
- notebooks/tutorials/data-scientist/03-working-with-private-datasets.ipynb
- notebooks/tutorials/data-scientist/04-action-graph.ipynb
- notebooks/tutorials/data-scientist/05-syft-functions.ipynb
- notebooks/tutorials/data-scientist/06-messaging-and-requests.ipynb
- notebooks/tutorials/data-scientist/07-custom-policies.ipynb
- notebooks/tutorials/hello-syft/01-hello-syft.ipynb
- packages/hagrid/hagrid/manifest_template.yml
- tox.ini
- Reverted tests back to 0.8 API for now
> Added stub tutorial notebooks

- notebooks/api/0.9/09-action-graph.ipynb
test notebook for Action Graph in `notebooks/api/0.9/09-action-graph.ipynb`
> Test notebook for Action Graph Service

- packages/grid/ansible/group_vars/all/vars.yml
- packages/grid/ansible/roles/containers/tasks/containers.yml
- packages/grid/ansible/roles/update/tasks/main.yml
- packages/hagrid/hagrid/cli.py
- scripts/staging.json
- scripts/staging.py
- added staging.py script to monitor staging machines and redeploy
- disabled auto update cron and other ansible tasks
> Updated hagrid to accept all the azure cli params

- notebooks/tutorials/data-engineer/04-deploy-container.ipynb
- notebooks/tutorials/data-engineer/06-deploy-to-azure.ipynb
> Added examples of single container deployment for docker and azure

- notebooks/Experimental/projects/Messages.ipynb
- notebooks/Experimental/projects/network_routes.ipynb
- notebooks/api/0.9/projects/01-create-projects.ipynb
- notebooks/api/0.9/projects/02-multi-node-messages-sync.ipynb
- notebooks/api/0.9/projects/03-project-polls.ipynb
- packages/syft/src/syft/client/client.py
- packages/syft/src/syft/client/connection.py
- packages/syft/src/syft/service/action/action_service.py
- packages/syft/src/syft/service/action/action_store.py
- packages/syft/src/syft/service/network/network_service.py
- packages/syft/src/syft/service/network/node_peer.py
- packages/syft/src/syft/service/network/routes.py
- packages/syft/src/syft/service/policy/policy.py
- packages/syft/src/syft/service/project/project.py
- packages/syft/src/syft/service/project/project_service.py
- packages/syft/src/syft/store/kv_document_store.py
> [WIP] - Optimising Network in Multi Node Projects

- packages/hagrid/hagrid/manifest_template.yml
> fix linting

- packages/syft/setup.cfg
> bump numpy

- .github/workflows/pr-tests-frontend.yml
> Temporarily disable e2e test

- .github/workflows/pr-tests-frontend.yml
- tox.ini
Fix issue with Playwright not installing browsers on every workflow run.
> fix: fix playwright installation in tox.ini

- packages/hagrid/hagrid/cli.py
cli: fix for 0.7.0
Slack thread: https://openmined.slack.com/archives/C041XHTGE15/p1684776724090849 
> New deployment support

- packages/hagrid/hagrid/cli.py
> Fixed issue where hagrid can't deploy 0.7.0

- packages/syft/src/syft/serde/serializable.py
- packages/syft/src/syft/util/trace_decorator.py
Some fixes plus typing improvements for the decorators, discovered while working on #7395.
> Fix `@instrument` and `@serializable` (continued)

- packages/syft/src/syft/service/project/project.py
> add project events during bootstrap

- packages/grid/frontend/src/routes/(app)/datasets/+page.svelte
- packages/grid/frontend/src/routes/(app)/users/+page.svelte
Reactivate the search bar component on the `/users` page and adds a new one on the `/dataset` page.
> ADD search bars at /users and /datasets

- docs/source/guides/data-owner/01-upload-data.rst
- notebooks/api/0.8/00-load-data.ipynb
- notebooks/api/0.8/01-submit-code.ipynb
- notebooks/api/0.8/02-review-code-and-approve.ipynb
- notebooks/api/0.8/03-data-scientist-download-result.ipynb
- notebooks/api/0.8/04-jax-example.ipynb
- notebooks/api/0.8/05-custom-policy.ipynb
- notebooks/api/0.9/00-load-data.ipynb
- notebooks/api/0.9/01-submit-code.ipynb
- notebooks/api/0.9/02-review-code-and-approve.ipynb
- notebooks/api/0.9/03-data-scientist-download-result.ipynb
- notebooks/api/0.9/04-jax-example.ipynb
- notebooks/quickstart/data-owner/01-upload-data.ipynb
- notebooks/tutorials/data-owner/01-uploading-private-data.ipynb
- notebooks/tutorials/data-owner/02-account-management.ipynb
- notebooks/tutorials/data-scientist/03-working-with-private-datasets.ipynb
- notebooks/tutorials/hello-syft/01-hello-syft.ipynb
- notebooks/tutorials/pandas-cookbook/01-reading-from-a-csv.ipynb
- notebooks/tutorials/pandas-cookbook/02-selecting-data-finding-common-complain.ipynb
- notebooks/tutorials/pandas-cookbook/03-which-borough-has-the-most-noise-complaints.ipynb
- notebooks/tutorials/pandas-cookbook/04-weekday-bike-most-groupby-aggregate.ipynb
- notebooks/tutorials/pandas-cookbook/05-combining-dataframes-scraping-weather-data.ipynb
- notebooks/tutorials/pandas-cookbook/06-string-operations-which-month-was-the-snowiest.ipynb
- notebooks/tutorials/pandas-cookbook/07-cleaning-up-messy-data.ipynb
- notebooks/tutorials/pandas-cookbook/08-how-to-deal-with-timestamps.ipynb
- packages/hagrid/hagrid/manifest_template.yml
`!pip install` could install the package into the wrong (virtual) environment. See https://github.com/microsoft/vscode-jupyter/wiki/Installing-Python-packages-in-Jupyter-Notebooks
> Use %pip install instead of !pip install inside Jupyter notebooks

- packages/syft/src/syft/serde/recursive.py
Resolves https://github.com/OpenMined/Heartbeat/issues/318
> removed debug print statement

- .github/workflows/cd-hagrid.yml
- .github/workflows/cd-syft.yml
- packages/syft/src/syft/util/schema.py
> Increase CD frequency to every 2 days

- packages/syft/tests/trials/skill_test.py
Add Dave as padawan
tox -e lint
> Add Dave as padawan

- packages/grid/frontend/src/lib/api/requests.ts
- packages/grid/frontend/src/lib/components/Requests/RequestListItem.svelte
- packages/grid/frontend/src/routes/(app)/requests/+page.svelte
- packages/syft/src/syft/service/code/user_code_service.py
- packages/syft/src/syft/service/message/message_service.py
- packages/syft/src/syft/service/message/messages.py
- packages/syft/src/syft/service/request/request.py
- packages/syft/src/syft/service/request/request_service.py
- packages/syft/src/syft/service/user/user_service.py
This pull request aims to complete the API for the /requests frontend page. It introduces new services and objects to establish correlations between PySyft entities such as Users, Requests, and Messages. The result of this work can be visualized in the accompanying image.
> Requests frontend pt.2

- packages/syft/tests/syft/locks_test.py
- packages/syft/tests/syft/stores/mongo_document_store_test.py
- packages/syft/tests/syft/stores/sqlite_document_store_test.py
Placeholder issue: https://github.com/OpenMined/Heartbeat/issues/353
> Disabling Flaky tests

- .github/workflows/pr-tests-syft.yml
- packages/syft/src/syft/client/client.py
> Flipped Test Order

- .github/workflows/pr-tests-syft.yml
- notebooks/tutorials/data-engineer/01-setting-up-dev-mode.ipynb
- notebooks/tutorials/data-owner/01-uploading-private-data.ipynb
- notebooks/tutorials/data-owner/02-account-management.ipynb
- notebooks/tutorials/data-scientist/03-working-with-private-datasets.ipynb
- notebooks/tutorials/hello-syft/01-hello-syft.ipynb
- notebooks/tutorials/pandas-cookbook/01-reading-from-a-csv.ipynb
- notebooks/tutorials/pandas-cookbook/02-selecting-data-finding-common-complain.ipynb
- notebooks/tutorials/pandas-cookbook/03-which-borough-has-the-most-noise-complaints.ipynb
- notebooks/tutorials/pandas-cookbook/04-weekday-bike-most-groupby-aggregate.ipynb
- notebooks/tutorials/pandas-cookbook/05-combining-dataframes-scraping-weather-data.ipynb
- notebooks/tutorials/pandas-cookbook/06-string-operations-which-month-was-the-snowiest.ipynb
- notebooks/tutorials/pandas-cookbook/07-cleaning-up-messy-data.ipynb
- notebooks/tutorials/pandas-cookbook/08-how-to-deal-with-timestamps.ipynb
- packages/syft/src/syft/client/client.py
- tox.ini
> Parallelising CI based tests

- .github/workflows/pr-tests-hagrid.yml
- .github/workflows/pr-tests-syft.yml
- notebooks/api/0.8/01-submit-code.ipynb
- notebooks/api/0.9/projects/01-create-projects.ipynb
- packages/syft/src/syft/client/api.py
- packages/syft/src/syft/client/client.py
- packages/syft/src/syft/node/node.py
- packages/syft/src/syft/service/project/project.py
- packages/syft/src/syft/service/project/project_service.py
- packages/syft/src/syft/service/project/project_stash.py
Closes https://github.com/OpenMined/Heartbeat/issues/332
Adds new helper methods/attributes for projects...
```python
client.get_project(name="Project Name")   # Returns project by name
client.get_project(uid=sy.UID(hex))       # Returns project by its UID
client.get_project()                      # returns list of all projects
```
... which use these new project APIs
```python
client.api.services.project.get_by_uid(uid: UID)
client.api.services.project.get_by_name(name: str)
```
- `ProjectSubmit` and `Project` now have unique names.
- Notebook based tests
- TODO: Unit tests
> Add project helper attr/functions to SyftClient

- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/parse_template.py
Fixes : https://github.com/OpenMined/Heartbeat/issues/323
> use dev for manifest branch when tag points to a beta 

- notebooks/api/0.8/01-submit-code.ipynb
- packages/syft/src/syft/service/message/message_service.py
Fixes: https://github.com/OpenMined/Heartbeat/issues/365
- enable resolve_object service for GUEST USER ROLE LEVEL
> Enable resolve_object for GUEST ROLE LEVEL

- packages/syft/src/syft/service/code/user_code.py
- packages/syft/src/syft/service/request/request.py
- packages/syft/src/syft/types/syft_object.py
> fix request.changes and user code repr

- notebooks/api/0.8/01-submit-code.ipynb
- notebooks/api/0.8/05-custom-policy.ipynb
- notebooks/api/0.8/06-multiple-code-requests.ipynb
- notebooks/api/0.9/01-submit-code.ipynb
- notebooks/api/0.9/projects/01-create-projects.ipynb
- notebooks/api/0.9/projects/02-multi-node-messages-sync.ipynb
- notebooks/api/0.9/projects/03-project-polls.ipynb
- notebooks/tutorials/pandas-cookbook/01-reading-from-a-csv.ipynb
- notebooks/tutorials/pandas-cookbook/02-selecting-data-finding-common-complain.ipynb
- notebooks/tutorials/pandas-cookbook/03-which-borough-has-the-most-noise-complaints.ipynb
- notebooks/tutorials/pandas-cookbook/04-weekday-bike-most-groupby-aggregate.ipynb
- notebooks/tutorials/pandas-cookbook/05-combining-dataframes-scraping-weather-data.ipynb
- notebooks/tutorials/pandas-cookbook/06-string-operations-which-month-was-the-snowiest.ipynb
- notebooks/tutorials/pandas-cookbook/07-cleaning-up-messy-data.ipynb
- notebooks/tutorials/pandas-cookbook/08-how-to-deal-with-timestamps.ipynb
- packages/syft/src/syft/client/client.py
- packages/syft/src/syft/node/worker_settings.py
- packages/syft/src/syft/serde/recursive.py
- packages/syft/src/syft/service/project/project.py
- packages/syft/src/syft/service/project/project_service.py
- packages/syft/src/syft/service/user/user.py
- packages/syft/src/syft/service/user/user_roles.py
- packages/syft/src/syft/store/document_store.py
- packages/syft/src/syft/types/uid.py
- packages/syft/tests/syft/api_test.py
- packages/syft/tests/syft/client_test.py
- packages/syft/tests/syft/project/project_test.py
Closes https://github.com/OpenMined/Heartbeat/issues/324
> [syft] Revamp ProjectSubmit UX

- .github/file-filters.yml
- .github/workflows/pr-tests-syft.yml
- tox.ini
Switching Windows Notebooks tests to self hosted runners
CI tests.
> Some More CI Speedup

- notebooks/api/0.8/02-review-code-and-approve.ipynb
- packages/syft/src/syft/service/project/project.py
- packages/syft/src/syft/service/project/project_service.py
Some small changes for projects and notifications:
* added `project.requests` that resolves the requests from project requests
Resolves:
- https://github.com/OpenMined/Heartbeat/issues/325
- https://github.com/OpenMined/Heartbeat/issues/350
- https://github.com/OpenMined/Heartbeat/issues/345
> Projects and Notifications UX changes

- .github/workflows/cd-hagrid.yml
- .github/workflows/cd-syft.yml
Switching to releasing beta's every day.
> Switching to releasing beta's every day until release

- .github/workflows/pr-tests-syft.yml
> Added retry for notebook tests

- .github/workflows/nightlies.yml
> Disable VM test

- .github/workflows/pr-tests-stack-public.yml
- notebooks/api/0.8/07-domain-register-control-flow.ipynb
- packages/syft/setup.cfg
- packages/syft/src/syft/service/code/unparse.py
- packages/syft/src/syft/store/mongo_client.py
- packages/syft/src/syft/util/filterwarnings.py
- Upgrade pyzmq
- Ignore time resolution warnings on windows
- Added sleep to metadata notebook test
> Upgrade FastAPI and Starlette due to security fix

- notebooks/tutorials/pandas-cookbook/03-which-borough-has-the-most-noise-complaints.ipynb
> add assert for pandas file len check

- notebooks/api/0.8/05-custom-policy.ipynb
- notebooks/api/0.8/06-multiple-code-requests.ipynb
- notebooks/api/0.8/07-domain-register-control-flow.ipynb
- notebooks/tutorials/pandas-cookbook/00_cache_test.py
- notebooks/tutorials/pandas-cookbook/01-reading-from-a-csv.ipynb
- notebooks/tutorials/pandas-cookbook/04-weekday-bike-most-groupby-aggregate.ipynb
- notebooks/tutorials/pandas-cookbook/05-combining-dataframes-scraping-weather-data.ipynb
- notebooks/tutorials/pandas-cookbook/06-string-operations-which-month-was-the-snowiest.ipynb
- notebooks/tutorials/pandas-cookbook/07-cleaning-up-messy-data.ipynb
- notebooks/tutorials/pandas-cookbook/08-how-to-deal-with-timestamps.ipynb
> Adding a file cache test to warm the cache and check df sizes

- packages/grid/devspace.yaml
- tox.ini
> Add Frontend to devspace

- .pre-commit-config.yaml
- packages/grid/devspace.yaml
- packages/grid/helm/component-chart/templates/backend-headless.yaml
- packages/grid/helm/component-chart/templates/backend.yaml
- packages/grid/helm/component-chart/templates/frontend.yaml
- packages/grid/helm/component-chart/templates/grid-stack-ingress.yaml
- packages/grid/helm/component-chart/templates/mongo-headless.yaml
- packages/grid/helm/component-chart/templates/mongo.yaml
- packages/grid/helm/component-chart/templates/proxy-headless.yaml
- packages/grid/helm/component-chart/templates/proxy.yaml
- packages/grid/helm/component-chart/templates/traefik-main-config.yaml
- packages/grid/helm/helm.py
- packages/grid/helm/manifests.yaml
- tox.ini
> Added syft.build.helm and syft.test.helm tasks to tox

- packages/syft/src/syft/__init__.py
> commenting out for the blog post as per Andrews suggestion

- packages/syft/src/syft/types/syft_object.py
Fix the bug in [this ticket](https://github.com/OpenMined/Heartbeat/issues/443)
> fixed SyftObject repr only shows the first element

- README.md
> Added links to PySyft API notebooks

- notebooks/tutorials/model-auditing/colab/01-user-log.ipynb
> Updated colab tutorial notebook

- notebooks/tutorials/model-auditing/colab/01-user-log.ipynb
> Make sure notebook register line works with older api just in case

- .github/workflows/pr-tests-stack-public.yml
- .github/workflows/pr-tests-syft.yml
- Continue on error for public tests
> Fix retry on pandas notebook tests

- packages/syft/tests/syft/stores/mongo_document_store_test.py
> Marking mongo thread test as xfail because it flaps even with retry

- .github/workflows/cd-syft.yml
> Revert CD checks

- packages/grid/backend/grid/start.sh
- packages/grid/worker/start.sh
- packages/hagrid/hagrid/cli.py
- packages/hagrid/hagrid/deps.py
- packages/hagrid/hagrid/manifest_template.yml
- packages/hagrid/hagrid/mode.py
- packages/hagrid/hagrid/orchestra.py
- packages/syft/src/syft/util/telemetry.py
- Improved HAGrid handling of beta and latest tags
- Added --render mode
> Fixed bug with telemetry in dev mode

- .github/workflows/pr-tests-syft.yml
> disabled windows tests

- .github/workflows/cd-syft.yml
> Add skip tests to syft CD

- .github/workflows/cd-syft.yml
- packages/grid/helm/syft/Chart.yaml
> Forgot to commit bumped Chart.yaml

- notebooks/tutorials/model-auditing/colab/01-user-log.ipynb
- packages/hagrid/hagrid/manifest_template.yml
> add note for light theme

- packages/syft/src/syft/service/dataset/dataset.py
- packages/syft/src/syft/service/request/request.py
> Small bugs

- packages/grid/frontend/src/lib/components/Navigation/SideNavItems.svelte
> Hide requests from UI until finished

- notebooks/tutorials/model-auditing/colab/01-user-log.ipynb
- packages/syft/src/syft/service/project/project.py
> Updated user log notebook

- .github/workflows/new-cd-syft.yml
> added new syft cd with test pypi functionality

- .github/workflows/new-cd-syft.yml
> modified test pypi secret name

- .github/workflows/cd-syft.yml
> commenting out publish

- .github/workflows/cd-syft.yml
> commented bump version

- .github/workflows/cd-syft.yml
> Revert "commented bump version"

- .github/workflows/cd-syft.yml
> change secret name

- helm/index.yaml
> Busting cache

- packages/syft/src/syft/client/client.py
- packages/syft/src/syft/service/dataset/dataset.py
- packages/syft/src/syft/util/util.py
fix bug where dataset size is not being set
> add asset size check

- packages/syft/src/syft/service/request/request.py
- packages/syft/src/syft/service/settings/settings.py
> Small fixes

- packages/hagrid/hagrid/cli.py
> Fix Hagrid Tag

- notebooks/tutorials/data-engineer/08-deploy-to-aws.ipynb
> [WIP] Deploy to AWS tutorial
